### ISSUE TITLE
Could not load file or assembly 'Microsoft.Azure.Amqp.resources, Version=2.1.0.0

### ISSUE THREAD

**Issue by AbhishekTripathi** [Azure/azure-functions-host#3205] opened 2018-07-30 13:56 UTC
#### Investigative information

Please provide the following:

- Timestamp: 30/07/2018
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region: local development
- Azure Functions Core Tools Version: 2.0.1-beta.33
- Function Runtime Version: 2.0.11933.0
- Microsoft.NET.Sdk.Functions: 1.0.14

#### Repro steps

Provide the steps required to reproduce the problem:

A simple Function with inbound service bus trigger. I was earlier getting AppDomain related issue #2854. I upgraded my Function Host which broke VS integration. However, I tried debugging from the CLI using ``func host start --debug VS --debugLevel verbose --build``. I get a different error now. I am using VS 2017 Enterprise (Version 15.7.5)

![image](https://user-images.githubusercontent.com/1847545/43401258-f823b9e2-940f-11e8-9387-f7470259b28f.png)

![image](https://user-images.githubusercontent.com/1847545/43401664-0c2156e2-9411-11e8-9eb4-d8e0e5188b64.png)

![image](https://user-images.githubusercontent.com/1847545/43401192-c90e1724-940f-11e8-8024-2d02fb9dd79b.png)

![image](https://user-images.githubusercontent.com/1847545/43401595-dc7cd86c-9410-11e8-8b9f-eed67abdb823.png)

*StackTrace*

   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoadContext.TryLoadRuntimeAssembly(AssemblyName assemblyName, Assembly& assembly) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\FunctionAssemblyLoadContext.cs:line 163

#### Expected behavior

Provide a description of the expected behavior.
Function should run with trigger invoked when message is put in the subscription

#### Actual behavior

Provide a description of the actual behavior observed.
Error with FileNotFoundException

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used C#
* Links to source
* Bindings used

**Comment by fabiocav** [comment] 2018-12-06 19:56
A number of changes happened in this area since this beta. Closing this as we believe the issue is resolved, but please let us know if you continue to have problems.

**Closed by fabiocav** 2018-12-06 19:56 UTC
