### ISSUE TITLE
error output table binding with pre-compiled C# function

### ISSUE THREAD

**Issue by step5** [Azure/azure-functions-host#2169] opened 2017-11-29 04:51 UTC
So I'm having a problem basically the same as #2027. Trying to run my C# pre-compiled Azure Function Visual Studio 2017 is giving a runtime error of `Microsoft.Azure.WebJobs.Host: Error indexing method 'TestFunction.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'outputTable' to type CloudTable. Make sure the parameter Type is supported by the binding.`

My function.json has the binding as:
`{
        "type": "table",
        "name": "outputTable", 
        "direction": "out", etc...
`

and the function is defined as:
`public static void Run(TimerInfo myTimer, CloudTable outputTable, TraceWriter log)`

My current nuget packages in the visual studio project are Microsoft.NET.Sdk.Functions (1.0.6) and WindowsAzure.Storage (7.2.1) which I read from a couple places would solve this issue, but it's not currently working for me. Is there anything I'm missing here? It seems to work if I just make a .csx function in the azure portal with the same binding and CloudTable parameter but that's not really an option for production since we need unit tests and to be able to use visual studio.

**Comment by paulbatum** [comment] 2017-11-29 19:51
Most likely explanation for that error message is a mismatch in storage versions. But 7.2.1 is the right version of storage if you're making a v1 function app. 

Are you getting this error when you test locally or only when you deploy to Azure?

If you run locally and then open the modules window in VS, select all and copy and then paste into a github gist and link it here, we can try to eyeball the version mismatch...

**Comment by paulbatum** [comment] 2018-02-08 17:08
@MrMikeFloyd Since you're creating a v2 functions project, storage 8.x is the right major version to be on (so don't attempt to downgrade to 7.x).

I can't reproduce. Lets try to reduce this to the simplest set of steps. My environment looks like this:
Win 10
VS 15.5.6
.NET Framework 4.7.02556
Azure Functions and Web Jobs Tools 15.0.40108.0

Then here is what I do:
1. Create a new functions V2 project, select queue trigger
2. Start the azure storage emulator
3. Hit F5 and confirm that everything starts up OK
4. Go into the code and change `string myQueueItem` to be `CloudQueueMessage myQueueItem` and add the appropriate using statement.
5. Clean, rebuild, hit F5 and confirm that everything still loads OK.

If those steps fail for you, I think it has to be an environmental issue. If these steps pass, then let me know how your repro is different from the above.

**Comment by MrMikeFloyd** [comment] 2018-02-10 09:45
@paulbatum cheers for the quick response Paul! I tried to narrow things down to a simple example that you can find [in this gist](https://gist.github.com/MrMikeFloyd/16d93f0bace0bd1229f6b7767c96569c). I added build and runtime output in the comments.
My dev environment differs quite a bit from yours. I'm running Visual Studio Code on macOS and used the Azure Functions extension to create the project and add a HTTP-triggered function. Apart from setting the `AzureWebJobsStorage` in `local.settings.json` and throwing in a minimal example in `read_from_tabstorage.cs` I sticked to the project structure and code generated by the functions extension. What's particularly interesting is that the build system comes up with a few warnings on the very first build, i.e. even before I added my custom code. I can access the table storage just fine using the connection string in Azure Storage Explorer.
I hope this helps! Please let me know if there's anything else that I can do.

**Comment by MrMikeFloyd** [comment] 2018-02-20 14:36
@paulbatum Any updates on this Paul? Any help would be highly appreciated. Cheers.

**Comment by MrMikeFloyd** [comment] 2018-02-21 15:25
So upon further digging I discovered that this issue apparently occurs _"by design"_ and `IQueryable` can't be used in .NET Core (which would explain why this only fails for v2 Azure Functions 😞) - see [here](https://github.com/Azure/azure-webjobs-sdk/issues/1566) and [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table#input---usage). So, at least in the context of v2 functions, this issue could be closed.

**Comment by paulbatum** [comment] 2018-02-21 17:05
@MrMikeFloyd happy to close this but I must admit I'm a bit confused - your repro said your function signature was `public static void Run(TimerInfo myTimer, CloudTable outputTable, TraceWriter log)` - so I'm not sure how IQueryable is in play?

**Comment by MrMikeFloyd** [comment] 2018-02-21 20:30
@paulbatum I understand your confusion, but the repro you're referring to seems to be the one provided by @step5 - if you look at [the gist I provided](https://gist.github.com/MrMikeFloyd/16d93f0bace0bd1229f6b7767c96569c) you will see that my function signature looks like this: 
```
public static HttpResponseMessage Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = null)]HttpRequest req,
            [Table("tabstoragetbl1", "")] IQueryable<TableRow> tRows,
            TraceWriter log)
```
So you see the `IQueryable` clearly is in play here. This could therefore be a different issue altogether. The issue I am experiencing looks pretty much [like this one here](https://github.com/Azure/azure-webjobs-sdk/issues/1548), but I only found out later. Sorry for the confusion.

**Comment by paulbatum** [comment] 2018-02-21 22:54
Ohh got it, thanks for clearing things up for me. I'm going to close this issue since I can no longer repro the  issue reported by @step5, and you're correct that your issue is about how Azure Storage SDK changed their IQueryable support and the impact that had on functions.

**Closed by paulbatum** 2018-02-21 22:54 UTC
