### ISSUE TITLE
[Custom Handlers - Go] - List in HTTP Body As System.Collections.Generic.List`1[System.Object]

### ISSUE THREAD

**Issue by mikaelweave** [Azure/azure-functions-host#6575] opened 2020-08-31 21:10 UTC
**Overview**
I currently have a sample Go function ([link to code here](http://github.com/mikaelweave/go-azfunc-sample/)) where I have 4 simple functions that perform actions on resource groups (create, read, list, delete). I was able to get all operations to work, except for the `List` operation which should return an array of objects. The function returns "System.Collections.Generic.List`1[System.Object]" instead of the object. It seems that a conversion of this type in the .NET code isn't converting to JSON correctly.

**Background**
I have made some choices about how my function app is structured because it was the only way I could get the behavior I needed. These seem ambitious to me, but could be important to debugging the issue. If any of these seem like bugs, please let me know and I can file a new issue. 

- My function.json files have two HTTP outputs defined. I have the below `function.json` defined. If I do not define both the `res` and `$return` outputs, I get the entire InvokeResponse output object instead of the body or `res`. This is important, as I want my API to return different status codes.
```json
{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get"
      ],
      "route": "playground"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    }
  ]
}
```
- I don't define a `ReturnValue` without Outputs as when I do this, I am unable to specify an HTTP Code on the return. If I return a 404 from my Go server, the function call returns a 500 since the Go server did not return a successful status code. So using the "Output" of "res" seems to be my only option.
- If I return both Outputs and ReturnValue, I lose the ability to return a HTTP Status Code and the Content-Type is text though I am returning JSON.

My code building the InvokeResponse looks like this:
```go
        outputs := make(map[string]interface{})
	headers := make(map[string]interface{})
	headers["System"] = "Azure Playground Generator"
	headers["Content-Type"] = "application/json"

	res := make(map[string]interface{})
	res["statusCode"] = status
	res["headers"] = headers
	res["body"] = body
	outputs["res"] = res
	invokeResponse := InvokeResponse{Outputs: outputs}

	c.JSON(http.StatusOK, invokeResponse)
```

**Bug Details**
When using the above code to construct a HTTP Output of "Res", I get "System.Collections.Generic.List`1[System.Object]" when I execute a function that returns a list. When executing the request against the Go server directly, I'm seeing the below response. <ins>I would expect the call against the function to return the JSON from body, instead of the .NET type</ins>
```json
{
    "Outputs": {
        "res": {
            "body": [
                {
                    "id": "/subscriptions/<omitted>/resourceGroups/mik-test-pg-1",
                    "name": "mik-test-pg-1",
                    "location": "westus2",
                    "ownerId": "<omitted>",
                    "tags": {
                        "OwnerId": "<omitted>",
                        "System": "Playground"
                    }
                }
            ],
            "headers": {
                "Content-Type": "application/json",
                "System": "Azure Playground Generator"
            },
            "statusCode": 200
        }
    },
    "Logs": null,
    "ReturnValue": null
}
```

Thanks for looking into this, let me know it you need any other details! 

**Execution Information**
- Timestamp: 2020-08-31T20:33:31.8707331Z
- Function App version: 3.0.14287.0
- Function App name: mikaelw-go-func-test-fa
- Function name(s) (as appropriate): playground-list
- Invocation ID: 97b4abe2-f0d0-4433-922a-a686392d8424
- Region: westus2

**Comment by anthonychu** [comment] 2020-08-31 22:19
We're going to deprecate the `httpWorker` section in host.json in favor of `customHandler`. The new config addresses the problem you're running into, where a pure HTTP function has different payloads than other functions. Try changing your host.json to this:

```json
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
  "customHandler": {
    "description": {
      "defaultExecutablePath": "./azure-playground-generator"
    },
    "enableForwardingHttpRequest":false
  }
}
```

I think instead of setting the body to lists and objects, can you marshal the data to JSON string?

**Comment by anthonychu** [comment] 2020-08-31 22:20
We're waiting for the next Core Tools release before publishing the docs. /cc @pragnagopa

**Comment by mikaelweave** [comment] 2020-09-01 03:38
Thanks for the response! A couple updates:

- Assuming I'm only the Custom Handler for HTTP requests, I am able to set `enableForwardingHttpRequest` to `true` and get my desired functionality! As advertised, the function just forwards my HTTP response, easy as that. 

- Changing to the above posted config (with `enableForwardingHttpRequest` to `false`) I get the same behavior as above (list return value is ```System.Collections.Generic.List`1[System.Object]```) but every other endpoint is working fine. The Function App is acting strange when returning a JSON list of objects. I was able to get my use case working completely by using Marshal to set the body as a string.

**More Details**

Taking @anthonychu's advice, I switched out  the above logic which sets the `body` to an `interface{}` (basically whichever object is passed to the Go Code) with logic that sets it as a string. This fixed my issue while allowing me to use a HTTP output!

```go
         outputs := make(map[string]interface{})
	headers := make(map[string]interface{})
	headers["System"] = "Azure Playground Generator"
	headers["Content-Type"] = "application/json"

	jsonData, err := json.Marshal(body)
	if err != nil {
		WriteGinErrorResponse(c, errors.NewInternalServer("error serializing body"))
	}

	res := make(map[string]interface{})
	res["statusCode"] = status
	res["headers"] = headers
	res["body"] = string(jsonData)
	outputs["res"] = res
	invokeResponse := InvokeResponse{Outputs: outputs}

	c.JSON(http.StatusOK, invokeResponse)
```

I am still seeing weird behavior when returning objects as the body. It works great if the body contains a single object like this:
```json
{
    "Outputs": {
        "res": {
            "body": {
                "id": "/subscriptions/<omitted>/resourceGroups/mik-test-pg-1",
                "name": "mik-test-pg-1",
                "location": "westus2",
                "ownerId": "<omitted>",
                "tags": {
                    "OwnerId": "<omitted>",
                    "System": "Playground"
                }
            },
            "headers": {
                "Content-Type": "application/json",
                "System": "Azure Playground Generator"
            },
            "statusCode": 200
        }
    },
    "Logs": null,
    "ReturnValue": null
}
```

But breaks down when returning a list:
```json
{
    "Outputs": {
        "res": {
            "body": [
                {
                    "id": "/subscriptions/<omitted>/resourceGroups/mik-test-pg-1",
                    "name": "mik-test-pg-1",
                    "location": "westus2",
                    "ownerId": "<omitted>",
                    "tags": {
                        "OwnerId": "<omitted>",
                        "System": "Playground"
                    }
                }
            ],
            "headers": {
                "Content-Type": "application/json",
                "System": "Azure Playground Generator"
            },
            "statusCode": 200
        }
    },
    "Logs": null,
    "ReturnValue": null
}
```

If the body should always be JSON as a string I understand that. Definitely caused some confusion, though, since it's behaving differently for different payload types.

**Comment by pragnagopa** [comment] 2020-09-01 15:35
cc @yojagad 
Thanks for reporting the issue. As long as response is valid JSON content it should work.

Needs further investigation.

**Comment by WillAbides** [comment] 2020-09-01 16:43
@anthonychu 
> We're waiting for the next Core Tools release before publishing the docs

Are the unpublished docs in a PR somewhere I could look at?

**Comment by anthonychu** [comment] 2020-09-01 21:45
@WillAbides The PR is staged on a private fork. However, it's been signed off on and will hopefully be live in a few hours here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers

**Comment by anthonychu** [comment] 2020-09-23 00:30
@yojagad Is this resolved with the PR above?

**Comment by pragnagopa** [comment] 2020-09-23 01:29
Yes, the issue is addressed in the referenced PR. Will be closing this issue. We opened a issue #6644 to track details of the root cause.

**Closed as completed by pragnagopa** 2020-09-23 01:29 UTC
Labels: httpWorker
