### ISSUE TITLE
Local Function Runtime Version: 4.834.3.22875 break the compatability with Identity Server 4 

### ISSUE THREAD

**Issue by adrianog91** [Azure/azure-functions-host#10248] opened 2024-06-25 13:44 UTC
#### Investigative information

Please provide the following:

- Timestamp: 2024-06-24T20:20:00.000Z
- Function App version: 4
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region: Multiple local environments

#### Repro steps

Provide the steps required to reproduce the problem:

1. Update the Function Runtime Version from previous to: 4.834.3.22875

#### Expected behavior

Everything should work properly

#### Actual behavior

I get the following exception:
```csharp
System.InvalidOperationException
  HResult=0x80131509
  Message=IDX20803: Unable to obtain configuration from: '[https://localhost/myauth/.well-known/openid-configuration'.](https://localhost/myauth/.well-known/openid-configuration%27.) Will retry at '25/06/2024 13:32:40 +00:00'. Exception: 'System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)'.
  Source=Microsoft.IdentityModel.Protocols
  StackTrace:
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__17.MoveNext()
   at DP.Functions.Security.<ValidateTokenAsync>d__2.MoveNext() in C:\Users\Oigres\source\repos\DP\DP.Functions\Security.cs:line 39
 
  This exception was originally thrown at this call stack:
    [External Code]
 
Inner Exception 1:
TypeLoadException: Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.```


#### Known workarounds
Set manualy the previous version of the runtime: 4.34.1.22669

#### Related information 

Provide any related information 

* Programming language used: C#

**Comment by neghev** [comment] 2024-06-25 14:22
same issue for me..

**Comment by janharders** [comment] 2024-06-26 07:52
Same here. Raised an issue with [azure-functions-core-tools](https://github.com/Azure/azure-functions-core-tools/issues/3715).

**Comment by patrick-elmore** [comment] 2024-06-26 15:05
We are seeing the same.  Not sure if it is related, but when looking at the runtime version in the azure portal on all of our non-prod function apps, it says "Error".  
![image](https://github.com/Azure/azure-functions-host/assets/9022601/da9aab38-dae6-4a3f-b7eb-a9d2fbafb023)

Functions in our prod subscription show the runtime version as suspected.
![image](https://github.com/Azure/azure-functions-host/assets/9022601/a53ac3cb-0d2c-48ff-b3d9-007465a7e562)

**Comment by fabiocav** [comment] 2024-06-26 20:58
@adrianog91 can you confirm you're only seeing that locally? If so, can you please follow this issue instead? https://github.com/Azure/azure-functions-core-tools/issues/3715

**Comment by josbol** [comment] 2024-06-27 17:25
Same here. When deployed on Azure, everything works fine. When running remote, we receive the same error. 

C#, V4 in-process, .NET 6

**Comment by adrianog91** [comment] 2024-06-27 19:35
Yes @fabiocav I confirm. Thanks for your support!

**Comment by mattchenderson** [comment] 2024-06-28 16:05
Given that confirmation, we'll treat this as a dupe of https://github.com/Azure/azure-functions-core-tools/issues/3715

**Closed as not planned by mattchenderson** 2024-06-28 16:05 UTC
