### ISSUE TITLE
Support function to returns a byte stream rather than fixed content

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-functions-host#5731] opened 2020-02-19 20:27 UTC
An HttpTriggered Java function app is trying to stream file down to the caller without having to load it all in memory. In returning the stream, functions hangs the socket forever - same behavior locally and in Azure.

**Comment by mhoeger** [comment] 2020-06-01 21:55
Closing as dupe of https://github.com/Azure/azure-functions-host/issues/1361

**Closed by mhoeger** 2020-06-01 21:55 UTC
Labels: Needs: Triage (Functions)
