### ISSUE TITLE
Azure Functions - .NET 5 - Did not find any initialized language workers

### ISSUE THREAD

**Issue by richsage** [Azure/azure-functions-host#7843] opened 2021-11-09 08:57 UTC
Linked to #7618 - we are seeing "Did not find any initialized language workers" when our .NET 5 (dotnet-isolated) function is triggered. Trigger is on blob creation in Azure Storage, which in our setup is a nightly occurrence. This failure started on 1 Nov 21 without any code or infrastructure changes - worked fine on 31 Oct 21. We saw a brief resolution without any intervention on 6-8 Nov 21 and then failures resumed as of 9 Nov 21, again without any intervention.

#### Investigative information

Please provide the following:

- Timestamp (UTC): `2021-11-09 00:56:32.114`
- Function App version: `~3` (presuming this is runtime version)
- Function App name: `<redacted>`
- Function name(s) (as appropriate): `<redacted>`
- Invocation ID: `28b8bcda-0aa7-4c28-a563-acc4bcc42b4d`
- Region: `North Europe`

#### Expected behavior

Function app triggers and completes successfully.

#### Actual behavior

Function app is triggered but host fails to start within c.50 seconds; log shows "Did not find any initialized language workers"

#### Known workarounds

None

#### Related information 

* .NET 5 function app; single function within.
* Running as dotnet-isolated

**Comment by kristan66** [comment] 2021-11-10 15:00
Same behaviour for me (error "Did not find any initialized language workers").  .net 6, isolated, linux, app service plan

**Comment by craigomatic** [comment] 2021-11-10 22:43
Seeing this show up on dotnet 6.0, isolated, windows, consumption also.

_Edit: In my case this may have been due to a reference to a dependent library which was targeting .net 5 and function v3 instead of .net 6 and function v4_

**Comment by liliankasem** [comment] 2021-11-15 11:54
Yeah, unfortunately this error shows up for a wide variety of reasons, we are working to improve the logging so that we can better display the real error instead of letting them all bubble up to "failed to init worker". 

@craigomatic did fixing that reference remove the error? Or is it still happening after the reference fix?

@kristan66 please share a timestamp, region and invocation Id so I can take a look

**Comment by craigomatic** [comment] 2021-11-15 23:39
Yes, fixing the bad targeting in the dependent library did resolve this for me. I'm not sure which of the net 5 or function v3 was the culprit as I changed them both at the same time.

**Comment by DryJhin** [comment] 2021-11-24 21:36
Hello Guys,

Same behaviour for me also, the same configuration, just it is windows service plan, region Germany West Central, trying for more than one day to find a fix for this... 

I wanted to migrate the Azure Storage Event Grid to isolated mode...

**Comment by wurzingerringana** [comment] 2021-11-26 08:28
Hi there,

We had the same Issue 4 weeks ago and couldn't fix it on our own.
Azure support came back with the advice from the product team to upgrade to the newest packages. We did so, deployed the application and since then (~3 weeks ago already) we couldn't observe any downtimes and every health check completed successfully.

The upgraded packages are
`Microsoft.Azure.Functions.Worker 1.6.0`  (from 1.2.0)
`Microsoft.Azure.Functions.Worker.Sdk 1.3.0` (from 1.0.3)

We are running a .NET 5 application on `dotnet-isolated` hosted as Azure Functions v3 with a Linux consumption plan.


(Azure support ticket id 2111010050001764)

**Comment by DryJhin** [comment] 2021-11-26 17:57
Hi @wurzingerringana ,

I have also the latest packages, what type of function do you use?

Could you provide a git sample that is working?

Thanks in advance

**Comment by DryJhin** [comment] 2021-11-26 21:15
UPDATE

I made it work finally... after a lot of struggles, I started to build from these examples:

[https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/Extensions](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/Extensions)

But adjusted with these things

- Latest versions of Worker
- on worker SDK add OutputItemType="Analyzer"
- for the EventGridTrigger used a string, not a custom class
- delete the function from azure and readded it
- do not try to build your configuration, in Program.cs use the extension method ConfigureAppConfiguration when you create the host builder, and you will have access to IConfiguration everywhere as a DI or via HostBuilderContext

Hope will help someone.

Cheers

**Comment by dawwa** [comment] 2021-12-02 04:25
Could this be some regression recently rolled out? Our function hits this issue as well, nothing changed, just idled for a few weeks and we observed timeout due to this error.

What is the way to figure out the actual issue under the error?

**Comment by DryJhin** [comment] 2021-12-02 14:56
There is no way at the moment to find why it's not working... Microsoft is working on improving the error... I was just removing/adding code and deploying again... Probably Microsoft made an update that affected the OS/runtime.... so basically you have to upgrade nugget packages as in the following  [comment](https://github.com/Azure/azure-functions-host/issues/7843#issuecomment-979781725)

**Comment by venkatsm** [comment] 2021-12-14 16:48
We are also having the same issue occurring intermittently, below are the details

Timestamp (UTC): 2021-12-14T15:42:49.385Z
Function App version: ~3 (presuming this is runtime version)
Invocation ID: f0b4788f-b57c-47ef-92a6-9bf893efeda6
Region: East US

**Comment by liliankasem** [comment] 2021-12-14 17:50
> We are also having the same issue occurring intermittently, below are the details
> 
> Timestamp (UTC): 2021-12-14T15:42:49.385Z Function App version: ~3 (presuming this is runtime version) Invocation ID: f0b4788f-b57c-47ef-92a6-9bf893efeda6 Region: East US

I feel like this case is a little different to the rest. Here it seems like something is causing the worker to crash, potentially something in your code related to Cosmos? So you might want to look into those errors.

`"Summary": Worker '66ab62b0-6b5a-450c-88f8-f858d3cd77ff' encountered a fatal error. Failing invocation id: **8145ba4e-4c88-40f1-bda3-e5845df9524a**`

And when we look up that invocation Id:

```
"Summary": Executed 'Functions.<yourfuncname>' (Failed, Id=**8145ba4e-4c88-40f1-bda3-e5845df9524a**, Duration=119633ms),
"Details": Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.<yourfuncname> ---> Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException : C:\Program Files (x86)\dotnet\dotnet.exe exited with code -532462766
 Unhandled exception. Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: ServiceUnavailable (503)
 Reason: (The request failed because the client was unable to establish connections to 0 endpoints across 1 regions. The client CPU has thread starvation
```

In the other cases that we're trying to investigate, there aren't really any errors or other indicators of the problem - to address this, we're currently working on reliability and logging so we can try and surface the root cause.

**Comment by venkatsm** [comment] 2021-12-15 20:24
> 

The issue which you stated is a different one and it is something within my code, but if you look up the invocation id(f0b4788f-b57c-47ef-92a6-9bf893efeda6) I shared, it says "Did not find any initialized language workers"
Transaction id - 322f76bce637054a9d55472423c975d9

![image](https://user-images.githubusercontent.com/15385074/146259366-04c1baae-5492-41b4-adff-7e496b093c2f.png)


Other issue which you quoted is for invocation id "8145ba4e-4c88-40f1-bda3-e5845df9524a" is cosmos specific
Transaction id - 06d0645f63196948b27d0542a791f8e3

![image](https://user-images.githubusercontent.com/15385074/146259559-9e0e62ba-b78f-4bef-b856-05186bbf7738.png)

**Comment by ursaciuc-adrian** [comment] 2022-12-06 08:16
We are still seeing this issue one year later. (.net 6, isolated, windows).
Has the logging improved in any way that could help us identify the cause?

**Comment by fabiocav** [comment] 2023-02-08 21:45
@ursaciuc-adrian we've been making frequent improvements as we identify scenarios that lead to this error state (which is, unfortunately, quite generic). The best approach here is to have a new issue opened any time you run into this message so we can take a closer look at the specific case. 

Closing this issue to promote that approach, but please let us know if you have any additional questions.

**Closed as completed by fabiocav** 2023-02-08 21:45 UTC
Labels: Needs: Attention :wave:
