### ISSUE TITLE
[QUERY] Token acquisition fails for ManagedIdentity in an Azure Function

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-functions-host#9884] opened 2024-02-16 22:09 UTC
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#42038](https://github.com/Azure/azure-sdk-for-net/issues/42038).

### Please be aware that @jaxidian is the author of the original issue and include them for any questions or replies.

**Azure Functions Team:** The response in the problem statement below indicates that the managed identity endpoint on the host is returning a 500 when invoked. 

## Details

# The Problem
I am attempting to have one Azure Function call another Azure Function with Azure API Management in the middle. I'm getting an exception on the `GetTokenAsync` call:

> Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
> Status: 500 (Internal Server Error)
> 
> Content:
> {\"statusCode\":500,\"message\":\"An unexpected error occured while fetching the AAD Token.\",\"correlationId\":\"guid-snipped\"}

The call to APIM is protected via OAuth and we've had this functional for some months with various clients (who were not me). My call to try to consume this is pretty simple:

```
    public async Task<string> MakeCall()
    {
        var targetFunctionAppAppRegistrationApplicationId = $"{redactedClientIdGuid}/.default";
        var uri = "https://redacted";
        var creds = new DefaultAzureCredential();

        // THIS IS THE LINE THAT FAILS!
        var token = await creds.GetTokenAsync(new Azure.Core.TokenRequestContext([targetFunctionAppAppRegistrationApplicationId]));

        using var client = new HttpClient(); // fix this to use a factory and dependency injection to avoid port exhaustion!
        client.DefaultRequestHeaders.CacheControl = CacheControlHeaderValue.Parse("no-cache");
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.Token);

        HttpResponseMessage response;

        using (var content = new StringContent("redacted"))
        {
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            response = await client.PostAsync(uri, content);
        }
        return await response.Content.ReadAsStringAsync();
    }
```

# Additional Information

1. This is .NET 8. As such, this is an isolated function, not in-proc.
2. Locally, I set `AZURE_TENANT_ID`, `AZURE_CLIENT_ID`, and `AZURE_CLIENT_SECRET` to trigger the `DefaultAzureCredential`'s functionality to pull environment variables for authentication. This works.
3. In Azure, I don't set any of those three variables. As such, it [falls down to the internal Managed Identity functionality][1], which is what I want. Unfortunately, it throws this exception. (And yes, there really is a Managed Identity enabled for the Azure Function. We have to have permissions setup for the Managed Identity for it to access Key Vault and other resources.).
4. If I add those 3 env vars to Azure (no new code), it works again! However, that's not what I want. I have requirements to use the Managed Identity for this. Which brings me back to the error.

What's causing this? I expected this to "just work", or at least give me a permissions error. I think I've eliminated networking errors and other tangential problems that I'm aware of. Am I missing something?

All of my Nuget packages are as updated as I can have them be (to stable versions, anyway):

```
  <ItemGroup>
	  <PackageReference Include="Azure.Identity" Version="1.10.4" />
	  <PackageReference Include="ClosedXML" Version="0.102.2" />
	  <PackageReference Include="EfCore.SchemaCompare" Version="8.0.1" />
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.2" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.16.0" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.0" />
	  <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.5.1" />
	  <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi.Configuration.AppSettings" Version="1.5.1" />
	  <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.8.0" />
	  <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" />
	  <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.8.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.2" />
  </ItemGroup>
```

The stack trace looks like this:

```
   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToAppTokenProviderAsync(ILoggerAdapter logger, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientCoreAsync(String[] scopes, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientAsync(String[] scopes, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
```

Note: I've also posted this on [StackOverflow](https://stackoverflow.com/questions/78009034/defaultazurecredential-fails-to-get-token-for-managedidentity-for-azure-function).

  [1]: https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#defaultazurecredential

### Environment

Azure Functions, v4, isolated, Premium V2

**Comment by jaxidian** [comment] 2024-02-18 04:33
Please let me know if you have any questions. :-)

**Comment by kiwipiet** [comment] 2024-02-22 03:49
Hi, we are experiencing the exact same issue as well.

**Comment by mattchenderson** [comment] 2024-02-22 19:13
Hi - If this is believed to be platform rather than SDK, it may be good to create a support ticket if you haven't already.

We can try to look at platform logs associated with this, but we'll need some app information. See [Sharing your function app name privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) for how to provide that here.

I see from the StackOverflow that you changed it to ManagedIdentityCredential and got the same thing. It might also be good to try a [direct request to the token endpoint](https://learn.microsoft.com/azure/app-service/overview-managed-identity?toc=%2Fazure%2Fazure-functions%2Ftoc.json#rest-endpoint-reference) to see if any more detail is returned.

Has that specific code snippet been working previously? I'm guessing here based on the code snippet, but seeing the input as `targetFunctionAppAppRegistrationApplicationId` made me pause. There were changes in the identity libraries that remove the ability to just use the client ID. The Entra ID V2 endpoints that the newer SDKs target require scopes rather than resource identifiers (which the client ID is), and while in many cases a resource identifier can be turned into a scope using `/.default`, that's not guaranteed to be true for a client ID. I wonder if some part of the system (SDK or platform) could be getting caught on that. That said, I'd expect a 4xx error code to be returned then, not a 500.

**Comment by mattchenderson** [comment] 2024-02-23 00:08
Small update here: I was able to have the provided method working if targeting the Microsoft Graph at least. It wasn't a full repro in terms of the provided dependency set, or using a target API that could have different handling around its scopes. However, I was using that version (latest) of `Azure.Identity`, and it was good to confirm a baseline working state.

In trying it out, I did also set some extra [Azure SDK logging](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/TROUBLESHOOTING.md#enable-and-configure-logging) just in case. That may be helpful in understanding what behavior you're running into in general. :
```csharp
            // Setup a listener to monitor logged events.
            using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
            var creds = new DefaultAzureCredential( new DefaultAzureCredentialOptions()
            {
                Diagnostics =
                {
                    LoggedHeaderNames = { "x-ms-request-id" },
                    LoggedQueryParameters = { "api-version" },
                    IsLoggingContentEnabled = true
                }
            });
```

Given I could not reproduce the issue myself, I think we'd need information about impacted apps so that we can investigate from the platform side. Again, a support ticket is probably a good idea.

**Comment by mattchenderson** [comment] 2024-02-27 23:52
(Just explaining previous action: I removed the `Needs: Author Feedback` label as I don't want the automation to catch there - it would be looking for a response from Jesse as defined.)

@jaxidian would you be able to try getting those logs and/or providing us the information to check behavior of the platform? Thanks!

**Comment by jaxidian** [comment] 2024-02-28 02:28
Sorry, I had a plumbing emergency that has had me stretched too thin.

I'll see what I can get tomorrow. This is a client's environment that I have limited access to, so I can't promise success. But I'll try. I've tried to suggest a support ticket but the client seems resistant to creating one.

**Comment by jaxidian** [comment] 2024-02-28 02:37
To answer some questions:

1. That referenced variable is effectively a GUID (App ID) with the `/.default` at the end.
2. This uses v1 AAD endpoints, not V2.
3. I'm curious if perhaps the clients custom networking setup could be interfering with the host's ability to communicate with AAD in some way. (They keep that abstracted away from my view, unfortunately.)

I'll post back tomorrow with some more hands-on info, including trying to get logs from comms with the 127.0.0.1 MSI endpoint.

**Comment by jaxidian** [comment] 2024-02-28 12:24
@mattchenderson I believe this is everything that you asked for.

## Direct request to the token endpoint
To do this, I'm attempting to run the following PowerShell command from a Kudu PowerShell prompt:
```
$resourceURI = "https://MY-APP-ID-GUID/.default"
$tokenAuthURI = $env:IDENTITY_ENDPOINT + "?resource=$resourceURI&api-version=2019-08-01"
$tokenResponse = Invoke-RestMethod -Method Get -Headers @{"X-IDENTITY-HEADER"="$env:IDENTITY_HEADER"} -Uri $tokenAuthURI
$accessToken = $tokenResponse.access_token
```

The `Invoke-RestMethod` line triggers the same 500 error with no additional information. I've played around with that `$resourceURI` value and have tried changing it to Mickey Mouse data as well as `https://vault.azure.net` (this MSI does have access to some KV resources to use the pass-through KV injection into Configuration variables) and I see the same result.

One thing I'm seeing in hitting the endpoint this way is that, after a while, I see "Unable to connect to the remote server" errors on that `Invoke-RestMethod` command instead of a 500. I'm not sure if that's interesting or not, but I have not seen that from my API's errors.

## Logging Details from the provided Listener
I adjusted your example such that I think it's the same thing (I have another repro case for somebody else using `DefaultAzureCredential` with the well-known envvars, so I'm going direct to `ManagedIdentityCredential` for your tests):
```
                    using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
                    var creds = new ManagedIdentityCredential(options: new TokenCredentialOptions
                    {
                        Diagnostics =
                        {
                            LoggedHeaderNames = { "x-ms-request-id" },
                            LoggedQueryParameters = { "api-version" },
                            IsLoggingContentEnabled = true
                        }
                    });
```

With this, I believe the relevant logs you want are here. I did sanitize the scope a little by replacing an App ID with `REDACTED_GUID`.
```
2024-02-28T12:08:41Z   [Information]   [Warning] Azure-Core: Error response [e4249b85-d102-4393-8fed-97562fd0b82a] 500 Internal Server Error (00.8s)
2024-02-28T12:08:41Z   [Information]   Date:Wed, 28 Feb 2024 12:08:38 GMT
2024-02-28T12:08:41Z   [Information]   Server:Kestrel
2024-02-28T12:08:41Z   [Information]   Transfer-Encoding:chunked
2024-02-28T12:08:41Z   [Information]   X-CORRELATION-ID:REDACTED
2024-02-28T12:08:41Z   [Information]   Content-Type:application/json; charset=utf-8
2024-02-28T12:08:41Z   [Information]   [Informational] Azure-Core: Error response [e4249b85-d102-4393-8fed-97562fd0b82a] content: {"statusCode":500,"message":"An unexpected error occured while fetching the AAD Token.","correlationId":"a06b11fb-39de-4016-9f2c-5698077cf92b"}
2024-02-28T12:08:41Z   [Information]   [Error] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.1 Microsoft Windows 10.0.20348 [2024-02-28 12:08:39Z - 0606626b-235c-459b-8fcf-d102c4dbe705] Exception type: Azure.RequestFailedException
2024-02-28T12:08:41Z   [Information]      at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
2024-02-28T12:08:41Z   [Information]      at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
2024-02-28T12:08:41Z   [Information]      at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
2024-02-28T12:08:41Z   [Information]      at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
2024-02-28T12:08:41Z   [Information]      at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToAppTokenProviderAsync(ILoggerAdapter logger, CancellationToken cancellationToken)
2024-02-28T12:08:41Z   [Information]      at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
2024-02-28T12:08:41Z   [Information]      at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
2024-02-28T12:08:41Z   [Information]      at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
2024-02-28T12:08:41Z   [Information]   [Informational] Azure-Identity: ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ REDACTED_GUID/.default ] ParentRequestId:  Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ManagedIdentityCredential authentication failed: Service request failed.
2024-02-28T12:08:41Z   [Information]   Status: 500 (Internal Server Error)
2024-02-28T12:08:41Z   [Information]   Content:
2024-02-28T12:08:41Z   [Information]   {"statusCode":500,"message":"An unexpected error occured while fetching the AAD Token.","correlationId":"a06b11fb-39de-4016-9f2c-5698077cf92b"}
2024-02-28T12:08:41Z   [Information]   Headers:
2024-02-28T12:08:41Z   [Information]   Date: Wed, 28 Feb 2024 12:08:38 GMT
2024-02-28T12:08:41Z   [Information]   Server: Kestrel
2024-02-28T12:08:41Z   [Information]   Transfer-Encoding: chunked
2024-02-28T12:08:41Z   [Information]   X-CORRELATION-ID: REDACTED
2024-02-28T12:08:41Z   [Information]   Content-Type: application/json; charset=utf-8
2024-02-28T12:08:41Z   [Information]   See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
2024-02-28T12:08:41Z   [Information]    ---> Azure.RequestFailedException (0x80131500): Service request failed.
2024-02-28T12:08:41Z   [Information]   Status: 500 (Internal Server Error)
2024-02-28T12:08:41Z   [Information]   Content:
2024-02-28T12:08:41Z   [Information]   {"statusCode":500,"message":"An unexpected error occured while fetching the AAD Token.","correlationId":"a06b11fb-39de-4016-9f2c-5698077cf92b"}
2024-02-28T12:08:41Z   [Information]   Headers:
2024-02-28T12:08:41Z   [Information]   Date: Wed, 28 Feb 2024 12:08:38 GMT
2024-02-28T12:08:41Z   [Information]   Server: Kestrel
2024-02-28T12:08:41Z   [Information]   Transfer-Encoding: chunked
2024-02-28T12:08:41Z   [Information]   X-CORRELATION-ID: REDACTED
2024-02-28T12:08:41Z   [Information]   Content-Type: application/json; charset=utf-8
```

## Anonymous Function ID
`b7973cb9-443c-4c1a-b9b4-e0079befcba4` is an invocation where I triggered the error. I think another one is in the logs above. This `b79` invocation was before I added the add'l logging options.

## Some add'l details
Our architectural setup is such that we have two Azure Functions running on ASPs (I can see they're Premium V2 but I don't have permissions to dig deeper). Both Functions are .NET REST APIs. The "Server" Function is .NET 6 and is behind Azure API Management. We have a JavaScript app hitting that APIM API and successfully authenticating/consuming it via OAuth (AAD v1 endpoints). This second .NET REST API is .NET 8 and is where our problem is. This API is trying to consume the other API though APIM, ideally using the MSI's token for authentication.

I know there are a ton of configuration issues that can creep up with this configuration, but I feel like we can work through those just fine, if only we could get the MSI's token itself. Hence our problem and this GitHub Issue. :-)

## Thank You
Thank you so much for your help with this! We are planning to fall back to `ClientSecretCredential` so our team isn't blocked by this. That said, I'd like to try to help see this through, if that's at all possible.

**Comment by mattchenderson** [comment] 2024-02-29 00:05
@jaxidian Thanks a ton for the detailed response. In our logs, I am seeing an AAD error returned: AADSTS501051. This isn't an exact match string match for that, but this reference article seems to cover the same thing: https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50105-user-not-assigned-role. The error itself also included a link to a hand y page that shows the string template of the error message I'm seeing: https://login.microsoftonline.com/error?code=501051. Repasted to save a click:
> Application '{appId}'({appName}) is not assigned to a role for the application '{resourceId}'({resourceName}).

The following substitutions are made for that:
|error message parameter | value description |
|-|-|
| `appId`| The application ID for the system-assigned managed identity for your app |
| `appName` | The name of your function app (which is what gets used for system-assigned identities) |
| `resourceId` | The application ID of `targetFunctionAppAppRegistrationApplicationId`. I correlated that with the token request itself to confirm.|
| `resourceName`| the friendly name associated with the above. |

To me, that error looks like the consent errors you can see for some delegated access flows or even before users can even log in for the first time with interactive apps (depending on tenant configuration). Basically, AAD is being defensive and asserting that someone needs to confirm that app A is allowed to access app B. An admin consent interaction is needed, and there are instructions for that in the reference guide. The other way to handle that would be to configure the app registration of the resource to mark the managed identity client ID as a [known client application](https://learn.microsoft.com/en-us/entra/identity-platform/reference-app-manifest#knownclientapplications-attribute), assuming that they are in the same tenant, which is a general requirement of Managed Identities. That will probably still require an admin consent to the application in the tenant, but I suspect that already happened, because otherwise we would have seen a different error.

In theory, per your original assertion, that error should be flowed back to you in the token service response. It seems to be caught in a stack trace on the platform side, nothing to do with Functions specifically. But I happen to work on that, too, and we'll get it so that error is properly returned going forward. There's also some work in parallel to provide some additional information through "Diagnose and solve" in the portal, and I'll make sure this type of thing can be surfaced there as well.

**Comment by mattchenderson** [comment] 2024-02-29 00:19
Ah you know what, I conflated the scopes errors with the app role errors. The error here is specifically asking about an app role being assigned. Best instructions for that are actually going to be https://learn.microsoft.com/en-us/entra/identity-platform/howto-add-app-roles-in-apps. That a role assignment is required here implies that one has probably been defined at least.

**Comment by mattchenderson** [comment] 2024-03-06 20:04
I'm going to go ahead and close this issue since there's no action planned on this repo. Hopefully the above helps with the specific configuration issues impacting the app in question. I am also pursuing platform fixes to ensure the error is returned as part of the token service response.

For anyone encountering the generic 500 error response from the token service (on Functions or web apps), if you have a support plan, please open a ticket - our support team should be able to help find the underlying error that should have been returned. That a 500 is being returned without any error information represents a platform managed identity concern, but that could be hiding a variety of different issues which could hopefully be resolved quickly for a given app.

**Closed as completed** 2024-03-06 20:04 UTC
Labels: feature: identity
