### ISSUE TITLE
Functions Keys stale after rotating storage account until startup cache invalidated.

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-host#7698] opened 2021-09-24 21:46 UTC
#### Investigative information

In an internal investigation of a customer reported incident, we found that after the customer had changed their storage account, there were several hours where the sync triggers operation was still using the stale keys from the old storage account.

This is because the SecretsManager was loading the secrets from the functions startup cache, so it didn't poll the new storage account to see that no keys existed and update with the new keys.

Only when the app went through a code path where the startup cache was not used were the new keys finally populated and used by the Functions Host.

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a new storage account and query for the keys.
2. Change the storage connection string to a new storage account.

Note that this will only reproduce in the case where the Functions startup

#### Expected behavior

The keys should change, as the keys are stored in the storage account that the app is no longer referencing.

#### Actual behavior

If the startup cache was used, the keys will remain the same.

#### Known workarounds

Unsure if there is a manual way to bypass the startup cache.

#### Proposed Fix

In the sync triggers code path, bypass the startup cache values and go directly to storage so we catch the invalid cache scenario earlier.

**Comment by mathewc** [comment] 2021-10-05 22:31
Here's the exact steps I had to follow to get a repro:

1) Ensure app is configured to use blob storage for keys (the default)
2) Make sure a SyncTriggers has been performed for the app, so that keys are initialized from StartupContext (code [here](https://github.com/Azure/azure-functions-host/blob/852eed9ceef6ef56b431428a8eb31f1bd9c97f3b/src/WebJobs.Script.WebHost/Security/KeyManagement/SecretManager.cs#L708)). You can verify this by ensuring you're seeing the logs showing keys were loaded from StartupContext.
3) Take note of the keys shown in the portal
4) Now stop the app, and ensure 0 workers are allocated to it
5) Update AzureWebJobsStorage to point to a new storage account. With app still stopped, portal will still show old cached values (served from ARM cache).
6) Start the app and verify in logs that keys are still being loaded from StartupContext
7) Verify keys shown in the portal are incorrect (old keys)
8) Even if you initiate an explicit SyncTriggers via portal Refresh button it won't fix it

**Comment by mathewc** [comment] 2021-11-30 20:41
Reactivating this because we had to revert in https://github.com/Azure/azure-functions-host/pull/7915/files due to an unforeseen regression.

**Closed as completed** 2021-12-02 22:24 UTC
Labels: bug
