### ISSUE TITLE
.Net unhandled exception causes Host Restart

### ISSUE THREAD

**Issue by sadgit** [Azure/azure-functions-host#3945] opened 2019-01-13 15:47 UTC
I have a timer trigger function that raises an exception if some action fails. The exception is unhandled by the environment and causes a restart of the host.

#### Investigative information

Please provide the following:

- Timestamp: 2019-01-09T10:45:00.01949Z
- Function App version (1.0 or 2.0): 2.0
- Function App name: <withheld>
- Function name(s) (as appropriate): aa_00_PingManager
- Invocation ID: 2O2m18MRt7Y=
- Region: UK South

#### Repro steps

Every run of previous code edition - code now changed to avoid throwing exception

#### Expected behavior

1. Expected failure result code e.g. 500 - internal Server Error
1. Telemetry logging as exception - to be tracked through AppInsights Failures page
1. No forced restart of host

#### Actual behavior

1. Host restarts
1. Telemetry not logged
1. No record or exception in AppInsights

#### Known workarounds

Ensure that all exceptions handled in function code - however that swallows any errors and therefore does not permit log analysis.

**Comment by paulbatum** [comment] 2019-01-18 01:02
@sadgit I would be very interested to get my hands on a repro for this behavior. I know it requires additional work, but have you attempted to put together a standalone repro that you can share?

My attempts to repro have not been successful. If I make a V2 app in visual studio with a C# timer trigger and have it throw an exception and run locally, I get output that looks like this:

```
Function Runtime Version: 2.0.12246.0

[1/18/2019 12:55:00 AM] Executing 'Function1' (Reason='Timer fired at 2019-01-17T16:55:00.0094961-08:00', Id=6d11d9f0-acac-436d-9889-113c60af3842)
[1/18/2019 12:55:00 AM] C# Timer trigger function executed in process: 12620
[1/18/2019 12:55:00 AM] Executed 'Function1' (Failed, Id=6d11d9f0-acac-436d-9889-113c60af3842)
[1/18/2019 12:55:00 AM] System.Private.CoreLib: Exception while executing function: Function1. FunctionApp11: deliberate exception.
[1/18/2019 12:55:05 AM] Executing 'Function1' (Reason='Timer fired at 2019-01-17T16:55:05.0093095-08:00', Id=dc79f459-d499-4e1e-9a1a-21ebbdbf3431)
[1/18/2019 12:55:05 AM] C# Timer trigger function executed in process: 12620
[1/18/2019 12:55:05 AM] Executed 'Function1' (Failed, Id=dc79f459-d499-4e1e-9a1a-21ebbdbf3431)
[1/18/2019 12:55:05 AM] System.Private.CoreLib: Exception while executing function: Function1. FunctionApp11: deliberate exception.
[1/18/2019 12:55:10 AM] Executing 'Function1' (Reason='Timer fired at 2019-01-17T16:55:10.0093276-08:00', Id=f5f58742-620e-40cb-8924-81a804f2d22a)
[1/18/2019 12:55:10 AM] C# Timer trigger function executed in process: 12620
[1/18/2019 12:55:10 AM] Executed 'Function1' (Failed, Id=f5f58742-620e-40cb-8924-81a804f2d22a)
[1/18/2019 12:55:10 AM] System.Private.CoreLib: Exception while executing function: Function1. FunctionApp11: deliberate exception.
```

I deploy the same app to Azure and get the same behavior:

```
2019-01-18T00:59:19  Welcome, you are now connected to log-streaming service.
2019-01-18T00:59:25.005 [Information] Executing 'Function1' (Reason='Timer fired at 2019-01-18T00:59:25.0035720+00:00', Id=814900bf-88af-4ef7-b17e-1106b6291bb5)
2019-01-18T00:59:25.013 [Information] C# Timer trigger function executed in process: 10700
2019-01-18T00:59:25.269 [Error] Executed 'Function1' (Failed, Id=814900bf-88af-4ef7-b17e-1106b6291bb5)
deliberate exception
2019-01-18T00:59:30.007 [Information] Executing 'Function1' (Reason='Timer fired at 2019-01-18T00:59:30.0073226+00:00', Id=65ac9737-bbcc-426c-a88e-e70dabbbab35)
2019-01-18T00:59:30.008 [Information] C# Timer trigger function executed in process: 10700
2019-01-18T00:59:30.037 [Error] Executed 'Function1' (Failed, Id=65ac9737-bbcc-426c-a88e-e70dabbbab35)
deliberate exception
```

The exceptions appear in the app insights live trace:
![image](https://user-images.githubusercontent.com/10663/51358737-705cb680-1a79-11e9-9db1-7cc241f58b59.png)

And in the failure view of app insights:
![image](https://user-images.githubusercontent.com/10663/51358765-971aed00-1a79-11e9-8725-6e310d27ef5b.png)

**Comment by paulbatum** [comment] 2019-01-18 01:12
I just remembered from the other issue you filed that you are using F#. I have not tried this. I would be surprised if it makes a difference, but thought I should mention this anyway. If you can reproduce this with some simple F# functions that would make life much easier!

**Comment by sadgit** [comment] 2019-01-18 16:37
@paulbatum - I have experienced this under two circumstances.

1. Timer trigger with failing HTTP request - deliberate exception raised in order to indicate host is down. This caused a Host restart. The Host restart is not visible in the AppInsights so difficult to spot and/or troubleshoot.
1. ServiceBus trigger with failing MySql sproc - deiliberate exception raised in order to attempt message retry. Also caused Host restart.

I will create a mock function in order to simulate the condition. Functions to look at are FS01 - ping_manager and FS02 - relay.

**Comment by sadgit** [comment] 2019-03-07 14:30
@paulbatum - Just realised this also will happen under v1 too. If a message persistently causes an unhandled exception then you can easily cause a meltdown in a service. 
Process message > Fall-over > Restart all functions > Re-process message > Fall-over > Restart... until the bad messages are expunged from the queue.
Also there is no telemetry warning of the cause

`
let Run2 (message : string, executionContext : ExecutionContext, log : TraceWriter) = 
    let logInfo = log.Info

    executionContext |> PrintAndGetFunctionGuid logInfo |> ignore

    message |> AcceptMessage logInfo

    raise (System.Exception ("My Fail"))

let ExceptionWrapper (log : TraceWriter) run args =
    try
        run args
    with
    | ex ->
        log.Error ("Execution Failed", ex, "message")

let Run(message : string, executionContext : ExecutionContext, log : TraceWriter) =
    (message, executionContext, log)
    |> ExceptionWrapper log Run2 

`

**Comment by paulbatum** [comment] 2019-03-07 18:07
Is the above code a repro? Sorry my F# is really bad. 

I was still looking for a V2 repro of this behavior. That would let us move this issue forward. The simpler the repro the better.

**Comment by sadgit** [comment] 2019-03-08 18:12
@paulbatum 

#### Investigative information

- Timestamp: 2019-03-08T16:01:33.5712015Z
- Function App version (1.0 or 2.0): 2.0
- Function App name: <withheld>
- Function name(s) (as appropriate): v2_exception_throw_without_catch
- Operation ID: f95a75a5811b8f4a890d6d23817ab89d
- Region: UK South

Also in V1
- Timestamp: 2019-03-08T16:01:33.428643Z
- Function App version (1.0 or 2.0): 1.0
- Function App name: <withheld>
- Function name(s) (as appropriate): v1_exception_throw_without_catch
- Operation ID: 6b50f47a-e70d-43b8-b63b-be522292504c
- Region: UK South

#### Repro Steps

Enqueue message with body = reboot
message = catch  -> applies a try-catch wrapper to the same function.

#### Some changes may have been made to mitigate this error.

#### Code
https://github.com/sadgit/AzureFunctionFailureModes

**Comment by paulbatum** [comment] 2019-03-15 00:26
OK, first thing I did was look at our logs for the executions you listed above.

For the V2 invocation, I was not able to find execution f95a75a5811b8f4a890d6d23817ab89d. Notice that this does not have dashes like your V1 ID. Maybe you pasted the wrong value? Anyway, I found two invocations at the time you specified: `53ff884c-bb7e-47a3-949a-033034cf7b65` and `ecdf1c92-8ce4-4357-becd-9d6d9eb492bd`. Both of these executions were for function `Function.v2_exception_throw_without_catch`. Both of these executions failed with the following stack trace:

```
Newtonsoft.Json.JsonReaderException : Unexpected end while parsing unquoted property name. Path '', line 1, position 10.
   at Newtonsoft.Json.JsonTextReader.ParseUnquotedProperty()
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonTextReader.ParseObject()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader,Type objectType,JsonContract contract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerMember,Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader,Type objectType,JsonContract contract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerMember,Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader,Type objectType,Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader,Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value,Type type,JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value,JsonSerializerSettings settings)
   at Samples.Debug.v2.CrashSimulation.Simulate.v2_exception_throw_no_catch(String message,ExecutionContext executionContext,ILogger log) at Simulate.fs : 25
   at lambda_method(Closure ,Simulate ,Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidMethodInvoker.cs : 20
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 63
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 556
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 503
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 439
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 249
```

I think you must have been running different code to what you linked me, because the code I just grabbed does not do a JSON convert, but it has commented out code that does. Also I will note that there is no sign of a process crash, the process ID (3568) remained. So these executions don't really tell me anything.

Next I looked at V1, execution 6b50f47a. It failed with this stack trace:

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.v1_exception_throw_without_catch ---> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException : The constructor method 'get_Ok' for the union case could not be found
   at Microsoft.FSharp.Reflection.Impl.getUnionCaseConstructorMethod(Type typ,Int32 tag,BindingFlags bindingFlags)
   at Microsoft.FSharp.Reflection.Impl.getUnionCaseConstructor(Type typ,Int32 tag,BindingFlags bindingFlags)
   at Microsoft.FSharp.Reflection.FSharpValue.PreComputeUnionConstructor(UnionCaseInfo unionCase,FSharpOption`1 bindingFlags)
   at Microsoft.FSharp.Core.FSharpFunc`2[System.Object[],System.Object] PreComputeUnionConstructor(Microsoft.FSharp.Reflection.UnionCaseInfo, Microsoft.FSharp.Core.FSharpOption`1[System.Reflection.BindingFlags])(Object ,Object[] )
   at Newtonsoft.Json.Utilities.FSharpUtils.<>c__DisplayClass49_0.<CreateFSharpFuncCall>b__0(Object target,Object[] args)
   at Newtonsoft.Json.Converters.DiscriminatedUnionConverter.CreateUnion(Type t)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.AddValue(TKey key)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Converters.DiscriminatedUnionConverter.WriteJson(JsonWriter writer,Object value,JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer,JsonConverter converter,Object value,JsonContract contract,JsonContainerContract collectionContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer,Object value,JsonContract valueContract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter,Object value,Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter,Object value,Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value,Type type,JsonSerializer jsonSerializer)
   at Run.Run(String message,ExecutionContext executionContext,TraceWriter log) 
   End of inner exception
   at System.RuntimeMethodHandle.InvokeMethod(Object target,Object[] arguments,Signature sig,Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj,Object[] parameters,Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj,BindingFlags invokeAttr,Binder binder,Object[] parameters,CultureInfo culture)
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 278
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionInvokerBase.cs : 90
   at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception
```

I don't know what this error means, but from the stack it looks like JSON.NET calling into F#. Again I'm going to guess that you had JSON deserialization code active, not `failwith "Manual Error"` like the code you sent me.  Like the first case, PID (6320) did not change. I see no sign of a process crash.

You should see all these errors yourself in App Insights. Check the exceptions table.

Lastly, I took the code you linked and tried to run it locally. I had problems, because it seemed to need a SB topic set up, with some specific subscriptions. I couldn't make sense of that, so I changed the functions to just use a SB queue. e.g.

```fsharp 
    [<FunctionName("v2_message_emitter_http")>]
    let v2_message_emitter_http 
        ( [<HttpTrigger(
            AuthorizationLevel.Function,
            "get",
            Route = "trigger/{message}")>]
          req : HttpRequestMessage, 
          message : string,
          [<ServiceBus ("queue1", ServiceBus.EntityType.Queue, Connection = "debug.bus.pub")>]
          output : ICollector<string>,
          executionContext : ExecutionContext, log : ILogger) =
```
and
```fsharp
    [<FunctionName("v2_exception_throw_without_catch")>]
    let v2_exception_throw_no_catch 
        ( [<ServiceBusTrigger ("queue1", Connection = "debug.bus.sub")>]
         message : string, 
         executionContext : ExecutionContext, log : ILogger) =
        let logInfo = log.LogInformation
```

I ran this locally and saw no sign of a process crash. I then took this app and deployed it to azure. I invoked v2_message_emitter_http with "hello", confirmed that the v2_exception_throw_without_catch function ran without issue, then ran it with "reboot". I see a string of errors as the function throws the exception as expected by with `failwith` call. I did this with process explorer open and I confirmed that there was no process crash, and that when I sent another "hello" message, the system continued to work, and the message was processed by the same process.

All of this is to say, between the logs of the executions you shared and my experiences running this code locally and in Azure, it does not seem like any of this repro's what you've been describing. 

Let me know what I'm missing.

**Comment by paulbatum** [comment] 2019-03-15 00:34
Forgot to mention, I also checked the logs for when I ran this in Azure, and the ScriptHostId (i.e. the unique identifier assigned to our internal host object) stayed consistent throughout the test i.e. not only was there no process crash, but there was also no ScriptHost restart.

**Comment by sadgit** [comment] 2019-03-15 16:44
I have updated the function with an http trigger to permit you to send to tests - can I DM you?

You are correct - the exception does not have the same effect in this context as it does in my full app. I have tried to replicate the actual exception, however, the simplified structure means we are missing some significant factor.

I'm very busy ATM so can't give this a huge amount of time but I am hoping that we can use this as a basis to build up the test cases until we hit the Jackpot. 

What happens if an exception is thrown in an async thread (say a plinq iterator). One of our functions is a fan out to several MySQL DBs and if one were to throw - then how should that be caught. C# examples should be basically the same.

It is made more difficult because the spontaneous restart doesn't show in the AppInsights.

**Comment by paulbatum** [comment] 2019-03-15 17:28
If you need to send me something privately, just email me at pbatum@microsoft.com.

To be able to see these restarts in app insights, you might want to add some log entries that log the process ID. If you see the process ID change on a given cloud_RoleInstance then you'll know a process restart occurred.

**Comment by paulbatum** [comment] 2019-07-16 01:00
I'm currently closing this issue as no-repro. I am happy to reopen if someone manages to repro this behavior.

**Closed by paulbatum** 2019-07-16 01:00 UTC
