### ISSUE TITLE
Update Stacks API to include .NET 9

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#10243] opened 2024-06-24 10:08 UTC
Include .NET 9 in https://github.com/Azure/azure-functions-ux/blob/dev/server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts

cc @fabiocav @nzthiago

**Comment by pragnagopa** [comment] 2024-06-27 05:52
P0; Required for GA

**Comment by mattchenderson** [comment] 2024-07-02 23:48
Duplicate of https://github.com/Azure/azure-functions-dotnet-worker/issues/2562

**Closed as not planned by mattchenderson** 2024-07-02 23:48 UTC
