### ISSUE TITLE
[Bug] IDX10503: Signature validation failed. Token does not have a kid.

### ISSUE THREAD

**Issue by mkeinemans** [Azure/azure-functions-host#10621] opened 2024-11-12 15:39 UTC
Since the 23th of October at around 01:22 AM UTC our Azure Functions East US that use the Isolated hosting model started logging `Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException` exceptions.

Those exceptions don't seem to impact the performance or end result of the invocation. 

On the 29th of October at around 10:00 PM the same services in South East Asia and West Europe also started showing the same behavior. Since our services do not reference any of the Assemblies mentioned in the StackTrace, I suspect that the issue lies in the host itself.

Forcing the runtime to the previous version 4.36.0.23246 by setting FUNCTIONS_EXTENSION_VERSION makes those errors disappear again.

#### Investigative information

Please provide the following:

South East Asia

- Timestamp: 23th of October at around 01:22 AM UTC
- Function App version: 4.1036.3.23284
- Invocation ID: afd29f6f-d0af-44a9-9eda-3d2b711fb668
- Region: East US

#### Exception Message:
```
IDX10503: Signature validation failed. Token does not have a kid. Keys tried: '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Number of keys in TokenValidationParameters: '2'. 
Number of keys in Configuration: '0'. 
Exceptions caught:
 '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. See https://aka.ms/IDX10503 for details. 
```

 #### Stack Trace
```
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException:
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature (System.IdentityModel.Tokens.Jwt, Version=6.35.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignatureAndIssuerSecurityKey (System.IdentityModel.Tokens.Jwt, Version=6.35.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateJWS (System.IdentityModel.Tokens.Jwt, Version=6.35.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken (System.IdentityModel.Tokens.Jwt, Version=6.35.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken (System.IdentityModel.Tokens.Jwt, Version=6.35.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler+<HandleAuthenticateAsync>d__6.MoveNext (Microsoft.AspNetCore.Authentication.JwtBearer, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```

#### Packages
```
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.23.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.4.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.2" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.18.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
	</ItemGroup>
```

**Comment by satvu** [comment] 2024-11-12 17:41
It is likely that this has a similar root cause to https://github.com/Azure/azure-functions-host/issues/10532 and can be mitigated the same way (instructions [here](https://github.com/Azure/azure-functions-host/issues/10532#issuecomment-2460815735)).

Thank you for the investigative information, we will take a look.

**Comment by satvu** [comment] 2024-11-13 21:20
Closing as duplicate - please track #10532 for updates and fixes.

**Closed as completed by satvu** 2024-11-13 21:20 UTC
