### ISSUE TITLE
Function not allowing HTTP request body size more than 30MB after upgrading to .NET core 3.1

### ISSUE THREAD

**Issue by skyovi** [Azure/azure-functions-host#5540] opened 2020-01-25 10:03 UTC
Upgraded HTTP Function app framework to .NET core 3.1 and run time version to v3, and throwing the below error if the request body size is more than 30MB.  

Error:
**Exception while executing function: Upload Exception binding parameter 'req' Request body too large**.
Microsoft.AspNetCore.Server.IIS.BadHttpRequestException
--

It was allowing up to 100MB when I was using .NET core 2.1 and v2 runtime. 

#### Investigative information

- Timestamp: 1/24/2020, 6:01:35 PM (Local time)
- Function App version (1.0 or 2.0): azurefunctions: 3.0.13107
- Invocation ID: 72f9e662-75ca-45d7-bc7f-73c72bf66ca0
- Region: South Central

#### Repro steps

Provide the steps required to reproduce the problem:

- Create HTTP Azure function with (Extensions,AzureKeyVault,DependencyInjection, HTTP, ActiveDirectory and SqlClient libraries)
- Use .NET Core 3.1
- Azure run time v3
- Upload request more than 30MB 

Project file:
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.1" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.2.6" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.2" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

#### Expected behavior

throws error

#### Known workarounds

downgraded to .NET core 2.1, run time version to v2 and function libraries:
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="2.2.0" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.2.6" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.29" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

**Comment by dalibor-sanzeru** [comment] 2020-04-29 12:44
Isnt this the same thing?

https://github.com/Azure/azure-functions-host/issues/5548

**Comment by yepeekai** [comment] 2020-05-20 18:04
looking at the code, the default value for IISServerOptions.MaxRequestBodySize has been set to match the default value of IIS.  The problem is that you now have to change this value at 2 places: 
web.config (configuration/system.webServer/requestFiltering/requestLimits: attribute maxAllowedContentLength) and the IISServerOptions in startup.cs: services.Configure<IISServerOptions>(options => { options.MaxRequestBodySize = null; });

This is counter intuitive...  If we override the default value at one place, it should follow at the other...

**Comment by gzuber** [comment] 2020-05-21 20:07
Yes, thank you @dalibor-sanzeru I believe this is the same issue. Looks like is was resolved and the fix should be deployed soon. Closing as duplicate of #5548

**Closed by gzuber** 2020-05-21 20:07 UTC
Labels: 3.x, bug, needs-investigation

**Comment by karpikpl** [comment] 2020-06-14 04:31
Hey,
is that issue is still open?
I'm running into this when running function locally. 
```
Azure Functions Core Tools (3.0.2534 Commit hash: bc1e9efa8fa78dd1a138dd1ac1ebef97aac8d78e)
Function Runtime Version: 3.0.13353.0
```
.Net Core 3.1, functions V~3
Microsoft.NET.Sdk.Functions 3.0.7

```
[6/14/2020 4:22:14 AM] Executed 'RecordDocument' (Failed, Id=8353b29f-597e-4ecc-a050-ff6da4a5382b)
[6/14/2020 4:22:14 AM] System.Private.CoreLib: Exception while executing function: RecordDocument. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'req'. Microsoft.AspNetCore.Server.Kestrel.Core: Request body too large.
```

**Comment by weischermanuel** [comment] 2020-06-29 14:25
> Hey,
> is that issue is still open?
> I'm running into this when running function locally.
> 
> ```
> Azure Functions Core Tools (3.0.2534 Commit hash: bc1e9efa8fa78dd1a138dd1ac1ebef97aac8d78e)
> Function Runtime Version: 3.0.13353.0
> ```
> 
> .Net Core 3.1, functions V~3
> Microsoft.NET.Sdk.Functions 3.0.7
> 
> ```
> [6/14/2020 4:22:14 AM] Executed 'RecordDocument' (Failed, Id=8353b29f-597e-4ecc-a050-ff6da4a5382b)
> [6/14/2020 4:22:14 AM] System.Private.CoreLib: Exception while executing function: RecordDocument. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'req'. Microsoft.AspNetCore.Server.Kestrel.Core: Request body too large.
> ```

Hi,

for me i've this error aswell while trying to upload a file above 100mb in debug mode.

same configuration
