### ISSUE TITLE
[Bug] Missing dependencies when adding FrameworkReference to .csproj

### ISSUE THREAD

**Issue by david-peden-q2** [Azure/azure-functions-host#5174] opened 2019-10-30 19:18 UTC
1. Right click solution -> Add New Project -> Azure Functions -> Empty

This produces the following project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AzureFunctionsVersion>v3-preview</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.30-beta2" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

The project compiles successfully.

2. Update the `TargetFramework` to `netcoreapp3.0`

The project compiles successfully.

3. Add the `FrameworkReference`:

```xml
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

The project compiles successfully.

4. Right click project -> Add -> New Azure Function...
4a. Add
4b. Choose Http trigger
4c. Choose Anonymous authorization level

That produces the following Azure function:

```csharp
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            return name != null
                ? (ActionResult)new OkObjectResult($"Hello, {name}")
                : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
        }
    }
```

Attempt to compile the solution.

#### Expected behavior

The project compiles successfully.

#### Actual behavior

The project now fails to compile with the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Mvc.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at MakeFunctionJson.MethodInfoExtensions.GetDisabled(MethodInfo method)
   at MakeFunctionJson.MethodInfoExtensions.HasUnsuportedAttributes(MethodInfo method, String& error)
   at MakeFunctionJson.FunctionJsonConverter.GenerateFunctions(IEnumerable`1 types)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
   at MakeFunctionJson.FunctionJsonConverter.TryRun()
```

#### Related information 

If the `FrameworkReference` is removed, the solution _will_ compile successfully. However, you now no longer have access to any of the packages contained in the `FrameworkReference`.

I also tried copying the missing assembly to the output folder (sourced from `C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.0.0\ref\netcoreapp3.0`) and that changes the exception type from `FileNotFoundException` to `BadImageFormatException`.

**Comment by david-peden-q2** [comment] 2019-10-30 19:26
This is the same symptom as https://github.com/Azure/azure-functions-host/issues/5154 but with a clean repro case. Not sure if they are actually related since no code was supplied in the other issue.

**Comment by david-peden-q2** [comment] 2019-10-30 19:29
https://github.com/Azure/azure-functions-host/issues/5136 may be suffering from the same underlying cause as well.

**Comment by brettsam** [comment] 2019-11-15 16:03
I'm resolving this issue as a dupe of the first one created (https://github.com/Azure/azure-functions-vs-build-sdk/issues/349). Please follow that issue for the PR and resolution.

**Closed by brettsam** 2019-11-15 16:03 UTC
Labels: 3.x
