### ISSUE TITLE
Function host is not running. Host Job Stop after Timeout or Function Error

### ISSUE THREAD

**Issue by alohaninja** [Azure/azure-functions-host#2243] opened 2017-12-20 17:59 UTC
#### Investigative information

Please provide the following:

- Timestamp: [20/12/2017 16:09:19.661]
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Invocation ID: ddcceb06-d3f0-42e6-aae4-6ee4a0e50404'
- Region: East US 2
- Language: Javascript

### Captured the following error output....

  ```
Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is 'ddcceb06-d3f0-42e6-aae4-6ee4a0e50404'
Microsoft.Azure.WebJobs.Host.FunctionTimeoutException : Timeout value of 00:30:00 was exceeded by function: <MyFunctionName>
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryHandleTimeoutAsync(Task invokeTask,CancellationToken shutdownToken,Boolean throwOnTimeout,CancellationToken timeoutToken,TimeSpan timeoutInterval,IFunctionInstance instance,Action onTimeout) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 658
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 580
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 534
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 477
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 264
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 320
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 96
Job host stopped
info: Host.Startup[0]
      => RequestId:0HLA78K6RN59G:0000000F RequestPath: => Microsoft.Azure.WebJobs.Script.WebHost.Controllers.AdminController.Invoke (Microsoft.Azure.WebJobs.Script.WebHost)
      Job host stopped
```

After the timeout or function failure the host stops and doesn't return until we kill `w3wp.exe` via kudu console. The function app is not accessible via the portal blades - just spinning wheel. Navigating to website shows `Function host is not running.`, and all functions stop running.

**Comment by amitxagarwal** [comment] 2018-01-07 16:15
If there are issues with any of the functions under the function app this is the expected behaviour.
we should try to fix the issues which will allow the host remain healthy.
Here is an article which you may find interesting and can be helpful in future as well.
https://blogs.msdn.microsoft.com/amitagarwal/2017/11/20/we-are-unable-to-retrieve-the-master-runtime-keys-for-azure-function-app/

**Comment by christopheranderson** [comment] 2018-01-16 18:46
We should expect the host to restart the worker after a timeout. We should improve this behavior.

**Comment by marconline** [comment] 2018-01-19 16:01
Hello there, I'm experiencing a same issue, but I do not have a log like alohaninja's.
What I notice is that only one WebJob out of 10 inside my App randomly stops and stops processing messages from Service Bus. It starts processing again as soon as I kill it and restart.
The only difference from the other WebJobs in the same app is that this one execute functions that can take minutes or more than one hour. What I noticed today is that in the dashboard the webjob had a yellow exclamation mark with a tooltip "Job Host not Running". In the Azure Portal WebJob section, it was in "Running" status.
I don't know if this will help, but, after reading this issue, I decorated my function with a Timeout attribute, with 4 hours timeout and ThrowOnTimeout = false. Will it help in some way?

Thanks!
Marco

**Comment by paulbatum** [comment] 2018-01-20 02:40
@marconline That does not sound related to this issue.

**Comment by paulbatum** [comment] 2018-03-13 01:14
I'll note that this can completely hose a V2 application running in a dedicated app service plan as it puts the app into a state of permanently returning 503s, so even functionality like Always On will not return the app to a healthy state.

**Comment by pragnagopa** [comment] 2018-08-01 18:14
I cannot repro this in production today with runtime version: 2.0.11933 
Repro:
- set function time to 10secs in host.json
```
"functionTimeout": "00:0:10"
```
- Create HttpTrigger JS function and add delay of 15secs to trigger timeout exception
```
   var start = new Date().getTime();
   while (new Date().getTime() < start + 15000)
```
@mhoeger - Can you please help verify if this is still an issue?

**Comment by mhoeger** [comment] 2018-08-01 21:36
Confirmed that for both C# and Javascript, the behavior on timeout is to kill the host _and restart._
Closing issue

**Closed by mhoeger** 2018-08-01 21:36 UTC
Labels: 2.0, bug, functions-v2-GA-musthave, lang-js, out-of-proc

**Comment by TurtleBeach** [comment] 2018-08-01 22:03
What is the expected behavior for Java functions? I have noticed:
Wrap a function call with a code to get the elapsed (wall clock) time
  start = ZonedDateTime.now(Clock.systemUTC())
  // trigger function within try / catch
  eplapsed = start.until(ZonedDateTime.now(Clock.system.UTC));
If the function runtime times out, elapsed time is NOT the functionTimeout value set in host.json - not even close (typically on the order of 3:57.xxx). It suggests to me that some timer other than one based on the last function execution is governing timeout behavior. Over the last several days I have been running a utility to trigger all functions every 4 1/2 minutes, and generally that has kept functions responsive. However one timeout did occur, with the utility indicating the function call took 3.5x.xxx. More to the point of this thread, once the timeout occurred, the function returned HTTP 502 errors. I had to manually restart the function. Which suggests that the Java runtime is NOT automatically restarting.

**Comment by TurtleBeach** [comment] 2018-08-01 23:07
@mhoeger I actually have functions set for a what I think is the maximum timeout "functionTimeout":"00:10:00 in host.json. The function is in a consumption plan.

My utility is designed to prevent a function ever having to start from "cold" by providing a regular "heartbeat" execution. I can tolerate a second or two of delay with a "real" execution, but not 10's of seconds. So that's what I mean - if the function is called with a special payload (minimal processing) the function returns "immediately" with an HTTP 202 (which is by design and only seen by other internal code). These heartbeat executions typically take ~300 ms to execute (round trip from Cayman Islands to EAST US). A "real" execution actually typically takes less time, because the function is called by other code that resides in EAST US, where the function is deployed.
When my utility reports that the function returned an HTTP 500 (not 502), the round-trip time is around 4 minutes. But I look at the APP INSIGHT log and it reflects a 10 minute timeout. So some other timer (not the fact that my utility tried to execute the function) started well before my utility issued a call to the function - and in any case the function never takes more than a few hundred milliseconds to execute.
With all that said, what is not immediately clear to me is what the effect of intermixing "real" function calls at random times with the regularly spaced utility heartbeat calls. I have not been able yet to isolate whether the reported timeout was because the runtime was trying to scale out to process a request while one instance was already running (due to the heartbeat). I am of course hoping that when the Java runtime is updated in the next release, the function execution from "cold" will be improved and I won't have to employ the heartbeat hack.
To answer your final question - not really certain. I'd say several minutes - but probably less than 10. I messed around with Postman trying to see what was going on (Postman reported the return as 502), but eventually decided just to restart the function.

**Comment by mhoeger** [comment] 2018-08-02 00:41
@TurtleBeach
First point to clarify: is your function app running multiple functions? (See docs [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#function-code) on a "function" vs. a "function app").

If any single function execution of any function (if you have multiple) in the function app runs for >10 minutes, then you will see a timeout error and potentially other 5xx errors, because your function app is temporarily shutting down and restarting.

Have you checked that the timeout error is coming from the heartbeat execution, as you expect? Is there a chance that a bad payload could be causing the >10 minute timeout?

It would also be helpful if you could share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) to help us investigate!

**Comment by TurtleBeach** [comment] 2018-08-02 01:36
I have one function per Function App. So the particular function that timed out was (is) the only one in the App.
As I tried to explain, my heartbeat utility got an HTTP 500 code (via standard Java 8 HttpURLConnection methods). As I said - a hack (a Java application running on a local machine, calling the function in EAST US). After I noticed the problem, when I called the function using Postman, the return was HTTP 502 and an HTML page generated somewhere by Azure. When I looked at APP INSIGHT logs I saw the standard verbiage about the function timing out.
Here is information from APP INSIGHTS - I believe you can identify the function App from the ID here:
2018-08-01 19:24:08.416	0	600269.4168	fd316eeb-4e76-497a-9040-796b6a9bf330
Microsoft.Azure.WebJobs.Host.FunctionTimeoutException:
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryHandleTimeoutAsync>d__25.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 607)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<InvokeAsync>d__23.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 523)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__22.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 483)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__21.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 426)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__15.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 231)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__15.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 275)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsync>d__12.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 75)

**Comment by pragnagopa** [comment] 2018-08-02 15:50
@TurtleBeach - Azure AppService ends a request after around 4 minutes and returns 500 errors. This is the expected behavior and explains the errors you are seeing after 3:57.xxx

This issue is closed. Please open a separate issue on https://github.com/Azure/azure-functions-java-worker and fill all the details in the issue template if you need further assistance.

**Comment by EricDahlvang** [comment] 2018-09-01 18:33
@mhoeger 

> Confirmed that for both C# and Javascript, the behavior on timeout is to kill the host and restart.
> Closing issue

I'm seeing a consistent four minute gap between a function timeout, and the function host restart:

![image](https://user-images.githubusercontent.com/11055362/44948774-8de5f800-add8-11e8-84d3-79b2b5cdb444.png)

@christopheranderson  @paulbatum  Is there something we can do to decrease this time period between host tear down and restart?  (Node functions sometimes require a long load period, and this host re-load is causing timeouts on function consumers.... better yet, don't reload the process for a timeout.)

**Comment by paulbatum** [comment] 2018-09-07 18:53
@EricDahlvang Can you file a new issue about this delay? Include the details requested in the issue template so that we can identify your app and look at the relevant logs.

Just as background - we cannot follow your suggestion of not shutting down the process on a timeout, because shutting down the process is the only mechanism we have to force user code to stop running.
