### ISSUE TITLE
Configured environment is not respected when functions host thinks it is in debug mode

### ISSUE THREAD

**Issue by DavidZidar** [Azure/azure-functions-host#6085] opened 2020-05-24 18:51 UTC
#### Investigative information

- Timestamp: 2020-05-24
- Function App version: 3.x
- Region: North Europe
- .NET Version: .NET Core 3.1
- Deployment method: `az functionapp deployment source config-zip`

#### Repro steps

Read `IHostEnvironment.EnvironmentName`

#### Expected behavior

I expect `EnvironmentName` to match what I have configured using `AZURE_FUNCTIONS_ENVIRONMENT`, in this case `Production`

#### Actual behavior

`EnvironmentName` is always `Development` regardless of what is configured.

#### Related information 

My functions always start as `Development` environment when deployed to Azure even though I have correctly configured `AZURE_FUNCTIONS_ENVIRONMENT` to `Production`.

From what I can tell this seems to be because it is hard coded to be set to `Development` during startup if Azure Functions Host thinks it is in debug mode.

https://github.com/Azure/azure-functions-host/blob/fc6a5f49717ce69367842e9ce47e4877283fc517/src/WebJobs.Script.WebHost/WebScriptHostBuilderExtension.cs#L97-L101

I have not enabled any debugging features as far as I know and have not been able to figure out why Azure Functions Host thinks it is in debug mode, it should not be. It seems debug mode is set via `EnableDebugModeFilter` when host status is queried, this seems weird to me, could this be why?

https://github.com/Azure/azure-functions-host/blob/fc6a5f49717ce69367842e9ce47e4877283fc517/src/WebJobs.Script.WebHost/Controllers/HostController.cs#L70-L71

Regardless, I would not expect environment name to ever be anything other than what I have configured so I hope you would consider this a bug.

Regarding debug mode, I deploy my function applications using ZIP deploy, so I am wondering if status is queried during the deployment somehow and thus always enabling debug mode? Though, I have tried stopping and restarting my applications manually in the Azure Portal and they start in debug mode anyway.

**Comment by ankitkumarr** [comment] 2020-08-26 05:44
@DavidZidar, I was able to repro the issue. Can you try stopping your function app, waiting for a couple of seconds and then starting it to see if that mitigates the problem? For me it did. Ideally after this "hard restart", you should see `AZURE_FUNCTIONS_ENVIRONMENT` being honored.

I looked at https://github.com/Azure/azure-functions-host/issues/6239 with @madelinegordon, and I think this is a duplicate of that.

**Comment by DavidZidar** [comment] 2020-08-26 08:36
@ankitkumarr Hi, my function applications seems to have switched to `Production` like they should have been all along. They seem to have switched when I redeployed them all two weeks ago, I have no idea why but I guess the deployment flow can't be the issue.

Issue #6239 says the value switches when disabling a function, I have never disabled any functions in the portal. The only other things I have done in the portal is connecting to the log stream and sometimes perform a test execution a function to make sure it works as expected.

**Comment by ankitkumarr** [comment] 2020-08-26 09:35
@DavidZidar, even though the issue linked has a repro with disabling functions, it actually seems to occur with any action that causes a soft restart. If you update any Application Setting or click restart, I think you will see the issue again.
The workaround for now is to manually stop the function app, and after a few seconds, start it back up.
This is a bug for sure.

**Comment by DavidZidar** [comment] 2020-08-26 09:44
Thank you for the update, I would rather not stop running applications in production but this is good to know.

**Comment by v-anvari** [comment] 2020-08-27 15:40
Hi @DavidZidar, we are closing the issue hoping that your queries have been answered, please feel free to reopen this issue for any queries related to this issue

**Closed as completed by v-anvari** 2020-08-27 15:40 UTC

**Comment by DavidZidar** [comment] 2020-08-27 15:47
@v-anvari The issue is not resolved though, there is a workaround but the issue is still very much present. Is #6239 the main issue for this now?

**Comment by v-anvari** [comment] 2020-08-27 16:48
@DavidZidar, yes [#6239](https://github.com/Azure/azure-functions-host/issues/6239) looks like a duplicate of this issue, which is already being investigated.
