### ISSUE TITLE
Unauthorized error when acquiring token using Managed Service Identity

### ISSUE THREAD

**Issue by beaubgosse** [Azure/azure-functions-host#7273] opened 2021-04-05 22:26 UTC
When trying to acquire a token using an AAD Managed Service Identity, we received a (401) Unauthorized error.

#### Investigative information

Please provide the following:

- Timestamp: 2021-02-28 18:33:12.684 +00:00   (one of many)
- Function App version: 3
- Function App name: gcm-pvm-transactionintegrationservice-prd
- Function name(s) (as appropriate): Transactions
- Invocation ID: 2274bdc2-33a3-458a-a5d4-66685f3841c5
- Region: East US

#### Repro steps

Can't reproduce reliably, but this happened in our production environment and restarting the function fixed the issue.

#### Expected behavior

Able to acquire token 

#### Actual behavior

401 error

#### Known workarounds

Restarting the Azure Function fixed the issue

#### Related information 
* Programming language used: C#
Exception Log:
Host: pd1sdwk00000Y   
Name: pvm-transactionintegrationservice   
Category: Http Input 
date: 2021-02-28 18:33:12.684 +00:00   
exception: System.AggregateException: One or more errors occurred. (Parameters: Connection String: [No connection string specified], Resource: https://database.windows.net/, Authority: . Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Failed after 5 retries. MSI ResponseCode: InternalServerError, Response: {"ExceptionMessage":"System.Net.WebException: The remote server returned an error: (401) Unauthorized.\r\n at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpHelper.<SendPostRequestAndDeserializeJsonResponseAsync>d__0`1.MoveNext()","ErrorCode":"invalid_client","ServiceErrorCodes":["700027"],"InnerException":null,"StatusCode":401,"Message":null,"CorrelationId":"084da99a-92f5-491a-add5-5324bf441d9d"}) 
---> Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://database.windows.net/, Authority: . Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Failed after 5 retries. MSI ResponseCode: InternalServerError, Response: {"ExceptionMessage":"System.Net.WebException: The remote server returned an error: (401) Unauthorized.\r\n at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpHelper.<SendPostRequestAndDeserializeJsonResponseAsync>d__0`1.MoveNext()","ErrorCode":"invalid_client","ServiceErrorCodes":["700027"],"InnerException":null,"StatusCode":401,"Message":null,"CorrelationId":"084da99a-92f5-491a-add5-5324bf441d9d"} 
at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthResultAsyncImpl(String resource, String authority, CancellationToken cancellationToken) 
at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsync(String resource, String tenantId, CancellationToken cancellationToken) 
--- End of inner exception stack trace --- 
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) 
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) 
at System.Threading.Tasks.Task`1.get_Result() 
at Gcm.Pvm.TransactionIntegrationService.Infrastructure.IoC.Services.<>c.<Configure>b__3_6(IServiceProvider c) in D:\a\1\s\Source\Infrastructure\Infrastructure\IoC\Services.cs:line 80 
at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\DryIocAdapter.cs:line 156 
at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 4550 
at lambda_method(Closure ) 
at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7849 
at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7834 
at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 309 
at lambda_method(Closure , IResolverContext ) 
at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 225 
at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 196 
at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedServiceProvider.GetService(Type serviceType) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\ScopedServiceProvider.cs:line 25 
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired) 
at lambda_method(Closure , IServiceProvider , Object[] ) 
at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IServiceProvider serviceProvider) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 37 
at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 32 
at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 20 
at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 26 
at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.CreateInstance(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 44 
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.Initialize() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 762 
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 91   
host: pd1sdwk00000Y   
level: Error   
lifecycle: prd   
logger: Function.Transactions   
message: Executed 'Transactions' (Failed, Id=2274bdc2-33a3-458a-a5d4-66685f3841c5, Duration=54692ms)   
ms_event: FunctionStart   
ms_functioninvocationid: 2274bdc2-33a3-458a-a5d4-66685f3841c5   
ms_functionname: Transactions   
ms_hostinstanceid: 00000000-0000-0000-0000-000000000000   
ms_httprequest: Microsoft.AspNetCore.Http.DefaultHttpRequest

**Comment by v-anvari** [comment] 2021-04-07 08:28
Hi @beaubgosse , We will be checking the backend logs to try and find any errors and update you with the findings shortly. Meanwhile can you tell us if you could [diagnose any other failures or exceptions in your application insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-exceptions)? Also, Can you give us more insights on your project scenario, any repro steps and how are you running the function

**Comment by v-anvari** [comment] 2021-04-07 08:41
I do see the exception : System.AggregateException : One or more errors occurred. (Parameters: Connection String: [No connection string specified], Resource: https://database.windows.net/, Authority: . Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Failed after 5 retries. MSI ResponseCode: InternalServerError, Response: {"ExceptionMessage":"System.Net.WebException: The remote server returned an error: (401) Unauthorized.\r\n

I see the Function has completed, but I don't see the Function has started anywhere. Also, Can you tell me if you have seen these in recent times, it would be ideal to find the logs for recent invocation id. Also, running a production application on a Standard, Premium, or Isolated App Service Plan for better performance and isolation. What are the others specs of your Function App.

We will further try to investigate on the reason for the cause of error

**Comment by beaubgosse** [comment] 2021-04-13 19:43
@v-anvari The function had been previously deployed November 24th 2020 and presumably running since then. Do you mean to say that you don't see the start of that invocation of the endpoint? We haven't seen this error in recent times, only the one time. But we're worried that it will come back in a month or so and cause another production outage for us. I'm not sure what other specs of the Function App you're looking for. It has 6 HTTP triggers and 1 Service Bus trigger. 

The general scenario of this function is that it is basically an API wrapper around a SQL Azure DB. Other applications hit this API to get data and this API merges data from SQL Azure and from another API to produce the returned data.

**Comment by v-anvari** [comment] 2021-04-14 08:12
Hi @beaubgosse , Yes we do not see the start of the invocation id. We will further investigate on the instances running during that time to understand the error. Also, Do let us know if you see this error again.

**Comment by v-anvari** [comment] 2021-04-15 18:44
Hi @beaubgosse, We checked the backend logs from the functions host perspective and looks like there was some outage during that point of time. Also, the error is coming from the managed Service Identity and not functions host. Since, this is 2 months old error, the log retention is not more than 60 days, which makes it difficult to understand the cause of the error. 

This is more of an outage issue, hence request you to raise a support ticket in the help and support section of your portal, when you see the same error again in the future.

**Comment by v-anvari** [comment] 2021-04-15 18:46
Closing this issue as the error hasn't re-occurred. Feel free to re-open the issue with the latest invocation id, if at all you come across the issue in future

**Closed as completed by v-anvari** 2021-04-15 18:46 UTC
