### ISSUE TITLE
Throw an error if a binding is attempted to be used with wrong type or w/out extension

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-host#2992] opened 2018-06-13 12:26 UTC
A number of people end up writing a function.json like this for the v2 runtime:

```json
{
    "name": "employeeDocument",
    "type": "documentDB",
    "databaseName": "MyDatabase",
    "collectionName": "MyCollection",
    "createIfNotExists": true,
    "connection": "MyAccount_COSMOSDB",     
    "direction": "out"
}
```

Which is invalid for a few reasons (`type` in v2 is now `cosmosDB`, and `connection` in v2 is now `connectionStringSetting`).  Even though [we have this documented](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2), people who don't realize they have done something wrong have a very hard time debugging. Specifically javascript users.

One problem is when trying to run code like:

```javascript
context.bindings.employeeDocument = JSON.stringify({ 
        id: context.bindings.myQueueItem.name + "-" + context.bindings.myQueueItem.employeeId,
        name: context.bindings.myQueueItem.name,
        employeeId: context.bindings.myQueueItem.employeeId,
        address: context.bindings.myQueueItem.address
      });
```

The code will run and execute without exception. However it doesn't result in the expected side-effects (of a document in Cosmos DB).

**Comment by paulbatum** [comment] 2018-06-13 20:49
Dupe of https://github.com/Azure/azure-functions-host/issues/2895

**Closed by paulbatum** 2018-06-13 20:49 UTC
Labels: 2.0, functions-v2-GA-shouldhave, improvement
