### ISSUE TITLE
 Azure Function app seems to stop queue processing, and only restart after I visit the Azure portal

### ISSUE THREAD

**Issue by jaltin** [Azure/azure-functions-host#7498] opened 2021-06-24 14:44 UTC
I have a problem with our Azure function project on a consumption plan stopping for (to us) no obvious reason. 

This has happened 2 days in a row now. I will give you the background and the information for the first occurrence in this post and hopefully this will give you enough information to investigate this.

We have a data flow where we do an export of data, and in this flow a number of functions are executed sequentially (using queue triggered functions among others).

By analysing Application Insights logs, we see the following information (all times in GMT)

- On 21/6 @ 14:51:08, the job host was shut down, and no processing of queue messages occurred after that

- We detected that our export flow had stopped on 22/6 around 06:50 (unsure of exact timing). At that point we openend the Azure portal to try and investigate.

- In application insights we then see that the functions are running, processing messages from our queue(s), picking up where it had stopped the flow the day before.

- From the stop log on 21/6 @ 14:51:08, there were no more logs at all in Application Insights until 22/6 @ 06:53:42, and after that the processing ran as expected.

- This start seems to have been triggered by us opening the Azure portal. No other action from our side was done.

I prefer to not share function app name, but hopefully this info from an Application Insights trace can help you find the app. If not let me know.

Time: 6/22/2021, 6:53:52 AM
Trace message: Initializing Host. OperationId: '33f2d796-fa69-4923-bea3-062f1c0e8350'.
Function app region: North Europe

**Comment by v-anvari** [comment] 2021-06-25 14:10
Hi @jaltin , Thank for providing the details, we would require any invocation id from the functions to find the Function App. Could you please provide the invocation Id.

**Comment by jaltin** [comment] 2021-06-25 14:14
Hi @v-anvari,

I just triggered one of our http functions, and this is the log output. Is that enough info?

2021-06-25T14:13:17.617 [Information] Executed 'Xml_ExportStatus' (Succeeded, Id=8932ae2d-1d3a-46e5-9066-961e59f13b87, Duration=5714ms)

**Comment by v-anvari** [comment] 2021-06-25 16:24
Thank you for the information, I shall try to pull the logs with the provided details.

**Comment by jaltin** [comment] 2021-06-28 10:12
Hi again @v-anvari,

Did you manage to pull the logs or do I need to give you further information?

**Comment by v-anvari** [comment] 2021-06-28 11:02
Hi @jaltin , Yes, I was able to pull the logs and I see that the function did not run in the time you have specified. I see the below logs:

2021-06-22 06:53:51.9686083	4	Starting language worker channel specialization
2021-06-22 06:53:51.9688990	5	Completed language worker channel specialization
2021-06-22 06:53:51.9689580	5	Restart requested.

We need to understand why was a restart requested. Checking this issue further, will update you with our findings

**Comment by v-anvari** [comment] 2021-06-28 11:05
I see the same case on the next day:

TIMESTAMP	Level	Summary
2021-06-22 16:53:17.7508898	5	Disposing MetricsEventManager
2021-06-23 08:45:42.9002401	4	Starting language worker channel specialization
2021-06-23 08:45:42.9071815	5	Completed language worker channel specialization
2021-06-23 08:45:42.9072785	5	Restart requested.

**Comment by jaltin** [comment] 2021-06-28 11:10
> I see the same case on the next day:
> 
> TIMESTAMP Level Summary
> 2021-06-22 16:53:17.7508898 5 Disposing MetricsEventManager
> 2021-06-23 08:45:42.9002401 4 Starting language worker channel specialization
> 2021-06-23 08:45:42.9071815 5 Completed language worker channel specialization
> 2021-06-23 08:45:42.9072785 5 Restart requested.

Yes exactly, this is the problem we have experienced.

We have no idea why it stopped, and it happened 2 days in a row.

I am really curious if you can find the issue for this. 

I found this old similar issue, could it perhaps be related? https://github.com/Azure/azure-functions-host/issues/1858

**Comment by v-anvari** [comment] 2021-06-28 16:06
Hi @jaltin , I see the worker events shutting down at the time the host instance was not available, I am checking with the concerned team for more understanding

**Comment by v-anvari** [comment] 2021-06-29 10:30
Triaging this issue for further investigation, I am following up with the team to look into this issue

**Comment by v-anvari** [comment] 2021-07-01 16:46
Hi @jaltin , We went through the logs again and we see that there are no messages throughout the logs, which is letting the App to scale out and requiring a function restart. This is an expected behavior in consumption plan to shut down the host if there are no messages.  It is running for certain time period, because it is scale up. Later in the day, it scales down because there are no messages. It is important to understand if you see that the messages are being sent.

Poll for function 'Xml_**********s' on queue 'exp****************tus' with ClientRequestId '29cb7820-daab-4966-9778-176084a69708' found 0 messages in 5 ms.

**Comment by jaltin** [comment] 2021-07-02 08:48
Hi @v-anvari,

We have a queue triggered function named 'Xml_CreatePdfFinished', and this is listening to a queue named 'export-*******-pdf-finished' (***'s to protect sensitive data). 

At the time the function app shut down on 21/6 @ 14:51:08, there was around 81 messages in this queue, and they should have been processed by the function.

However, it seems that there is a bug in the function host, and that the queue was not polled until the morning after, a shutdown/delay that should not happen. And it happened again the day after as you also pointed out in an earlier post.

It seems similar to this issue from a few years back: https://github.com/Azure/azure-functions-host/issues/1858

Is this enough information for you to continue your investigation?

**Comment by v-anvari** [comment] 2021-07-05 10:46
Hi @jaltin , Thank you for the details, I could find 16 messages in the queue at this time stamp 2021-06-21 14:28:49.7724262. I couldn't find many messages there after. We are further investigating to understand why were there no messages even after being processed, We shall update you the findings as appropriate.

**Comment by janwalczynski-intive** [comment] 2021-07-09 06:54
Hi @v-anvari, 

We are experiencing a very similar problem, the only difference being that we have to manually restart functionapp to get the messages in the queue to start processing again. So far our application has not caused this problem, the first time it happened was on July 2, so we suspect it may have something to do with the Azure functions host update.

Since yesterday, we have enabled Debug-level logging of entries from the `Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener` category hoping to see something interesting there when the problem recurs.

We have also reported the problem through Azure Support Plan - ProDirect, but so far the experts there have not been able to find anything concrete.

Please let us know if we can provide any additional information that would help you track down the problem.

**Region:** West Europe
**Number of messages on the queue before restart:** over 170
**Last function call before the problem occurred (UTC time):** `8/07/2021, 11:13:43.776: Executed 'ProcessEmail' (Succeeded, Id=bda64724-7005-49cc-9bbd-ce6513c3240c, Duration=1169ms)`
**First call after restart (UTC time):** `8/07/2021, 11:29:59.335: Executing 'ProcessEmail' (Reason='New queue message detected on 'process-email'.', Id=50f72102-690d-448b-ac94-205e3fc48051)`

**Comment by v-anvari** [comment] 2021-07-09 09:57
Hi @janwalczynski-intive , Thank you for the details, The investigation is in progress. We will check the backend logs

**Comment by janwalczynski-intive** [comment] 2021-07-12 06:44
As for the logs from the `Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener` category, unfortunately they don't show too much. We encountered this problem again today and the only thing you can see in these logs is that the function has stopped polling the queue completely:

```
12.07.2021, 06:16:57.782	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId 'ffcb0941-380b-4d1d-b8dd-3b5904766503' found 0 messages in 8 ms.	
12.07.2021, 06:16:53.542	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId '54c08c8b-7911-4449-a0a9-07041aa6e652' found 16 messages in 73 ms.	
12.07.2021, 06:16:50.207	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId 'b293c3d7-7e0a-4d28-af4f-6222dc98bd18' found 16 messages in 173 ms.	
12.07.2021, 06:16:45.389	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId 'ede0d402-6502-4a24-af46-59c3c15cfd2e' found 16 messages in 289 ms.	
12.07.2021, 06:16:39.984	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId 'b29b0c8c-ba13-4b56-980e-fbcfae3a85aa' found 16 messages in 31 ms.	
12.07.2021, 06:16:20.337	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId '8eaa7485-7a62-4d55-a344-8023f334779f' found 16 messages in 472 ms.	
12.07.2021, 05:55:51.854	Function 'ProcessEmail' will wait 11354.6208 ms before polling queue 'process-email'.	
12.07.2021, 05:55:51.853	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId '9e8a4c06-551b-4661-b091-ae9596e07fe7' found 0 messages in 3 ms.	
12.07.2021, 05:55:46.185	Function 'ProcessEmail' will wait 5656.8362 ms before polling queue 'process-email'.	
12.07.2021, 05:55:46.185	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId '2c62f5d6-3da7-4728-801b-fcefbc13e4c6' found 0 messages in 5 ms.	
12.07.2021, 05:55:42.624	Function 'ProcessEmail' will wait 3550.8191 ms before polling queue 'process-email'.	
12.07.2021, 05:55:42.624	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId '6cb8607c-05e4-4c43-b8bb-2acf166665fd' found 0 messages in 3 ms.	
12.07.2021, 05:55:40.889	Function 'ProcessEmail' will wait 1728.0617 ms before polling queue 'process-email'.	
12.07.2021, 05:55:40.889	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId '63247d4a-7e4b-4cf5-9f42-3bd65f722491' found 0 messages in 3 ms.	
12.07.2021, 05:55:40.085	Function 'ProcessEmail' will wait 795.4153 ms before polling queue 'process-email'.	
12.07.2021, 05:55:40.085	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId 'f685d4c4-2fb2-4af2-8db4-8b064ba3389c' found 0 messages in 11 ms.	
12.07.2021, 05:55:39.537	Function 'ProcessEmail' will wait 538.5123 ms before polling queue 'process-email'.	
12.07.2021, 05:55:39.537	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId '16cbd6c0-1e40-4454-9306-fa41195cad55' found 0 messages in 3 ms.	
12.07.2021, 05:55:39.270	Function 'ProcessEmail' will wait 260.5204 ms before polling queue 'process-email'.	
12.07.2021, 05:55:39.270	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId '9ea17e3b-5356-4175-a2a1-e2d5b87d66cf' found 0 messages in 38 ms.	
12.07.2021, 05:55:39.013	Function 'ProcessEmail' will wait 207.3322 ms before polling queue 'process-email'.	
12.07.2021, 05:55:39.013	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId 'edf9e4ce-bc89-4c34-baa7-593bfe6cb5fe' found 0 messages in 349 ms.	
12.07.2021, 05:55:38.471	Function 'ProcessEmail' will wait 100 ms before polling queue 'process-email'.	
12.07.2021, 05:55:38.471	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId '042a6868-7a43-4fe9-ba47-74e4d5a526e1' found 0 messages in 3 ms.	
12.07.2021, 05:55:38.459	Poll for function 'ProcessEmail' on queue 'process-email' with ClientRequestId 'c43915f7-8565-4cca-a214-271429c839f1' found 2 messages in 6 ms.	
```

A more interesting seems to be the memory-related metric - at the time of the problem, all but one instance was shut down, and the memory of the only remaining instance at some point began to grow noticeably, even though theoretically none of the functions had yet been executed:

![image](https://user-images.githubusercontent.com/53433721/125242585-2f158c80-e2ed-11eb-9d6b-72c71fde1aa5.png)

**Comment by ZachTB123** [comment] 2021-07-12 21:05
I don't know if this is related, but the problems described here sound very similar to what I've experienced. In my case I have Function Apps on the consumption plan that have an Event Hub trigger. These occasionally stop triggering and only start triggering again when I view the Function App in the portal, restart the Function App, or sync triggers (though these don't always work). I originally [reported](https://github.com/Azure/azure-functions-host/issues/6790) this in October and eventually opened a support case. I was told a fix was identified and was rolled out. I again encountered this in ~March and was told another fix was deployed. Then I got this again in April and had a ticket that lasted 60+ days in which I was told they've identified an "issue with a deadlock in the storage plane that affects our scale controllers" and there was no eta on when a fix would be deployed. I was told to add a timer trigger function to my Function Apps that would run every 15 minutes and sync triggers to essentially keep the Function App awake. I have already built out a similar solution to what was suggested but instead of having the timer trigger inside the Function Apps that stop triggering, I have a separate Function App that runs on a timer and restarts ones that stop triggering. This doesn't always seem to work because today, for example, I have many Function Apps in eastus that are still not processing data after restarts and sync triggers.

**Comment by v-anvari** [comment] 2021-07-13 15:38
Hi @ZachTB123 , Thank you for the information, when we run through the logs, we see Site's DynamicScalingEnabled is false. We are yet to identify what is turning off DynamicScaling for the app. Queue is idle for a longer time which is causing the app to scale out. But, queue is idle even when the messages are expected.

**Comment by v-anvari** [comment] 2021-07-14 12:21
Hi @jaltin , The team ran through the logs again to check if there are errors coming from the host, but there were no such. The queue was idle for a very long period of time and there were no messages. According to scale controller there was no need to add workers since the queues were empty. Since you were expecting messages during this time, we suggest
enabling scale controller logs so that you will have visibility into how scaling decisions are made.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#scale-controller-logs

**Comment by jaltin** [comment] 2021-07-20 11:06
> Hi @jaltin , The team ran through the logs again to check if there are errors coming from the host, but there were no such. The queue was idle for a very long period of time and there were no messages. According to scale controller there was no need to add workers since the queues were empty. Since you were expecting messages during this time, we suggest
> enabling scale controller logs so that you will have visibility into how scaling decisions are made.
> 
> https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#scale-controller-logs

Hi again @v-anvari.

I will try to enable the logs as you suggest.

However, as I pointed out in a previous message in this thread, I am almost 100% sure that there were 81 messages in one of our queues that were not detected and processed until we visited the Azure portal the day after, indicating a bug. For clarification, this is my previous comment:

> We have a queue triggered function named 'Xml_CreatePdfFinished', and this is listening to a queue named 'export-****-pdf-finished' ('s to protect sensitive data).

> At the time the function app shut down on 21/6 @ 14:51:08, there was around 81 messages in this queue, and they should have been processed by the function.

> However, it seems that there is a bug in the function host, and that the queue was not polled until the morning after, a shutdown/delay that should not happen. And it happened again the day after as you also pointed out in an earlier post.

**Comment by v-anvari** [comment] 2021-07-20 17:05
Hi @jaltin , Thank you for the update. Please let us know your analysis after enabling the logs. 

Because if you see the screenshot below, somehow these messages did not reach the queue.

![image](https://user-images.githubusercontent.com/66122429/126365706-e81fc05d-3a13-412d-a51a-5eb67d2d091a.png)

**Comment by janwalczynski-intive** [comment] 2021-07-22 07:50
Our team received the following response from the experts at Azure Support:

> The Microsoft Azure Functions Team has investigated the issue you reported on the lack of executions by your Function app. 
>
> We determined that the proper monitoring of incoming events, which is responsible for triggering executions, was suspended by a deadlock on  the Azure Storage SDK. 
>
> Restarting the related monitoring service recycled the stuck operation and resumed the monitoring. We have identified a fix for this issue.

Which means that the problem should no longer occur.

**Comment by v-anvari** [comment] 2021-07-22 08:57
Thank you for the update. We could only access the logs on the host and scale controller. Closing this issue as the problem is resolved, feel free to re-open the issue if you have any queries related to this issue

**Closed as completed by v-anvari** 2021-07-22 08:57 UTC
Labels: Needs: Attention :wave:

**Comment by jaltin** [comment] 2021-07-22 11:25
> Hi @jaltin , Thank you for the update. Please let us know your analysis after enabling the logs.
> 
> Because if you see the screenshot below, somehow these messages did not reach the queue.
> 
> ![image](https://user-images.githubusercontent.com/66122429/126365706-e81fc05d-3a13-412d-a51a-5eb67d2d091a.png)

Hi @v-anvari ,

I enabled the logs, but since the issues only occured over 2 days back in June, I am not able to analyse. If the issue occurs again then I will look at the logs as you suggest.

**Comment by jaltin** [comment] 2021-07-22 11:29
> Our team received the following response from the experts at Azure Support:
> 
> > The Microsoft Azure Functions Team has investigated the issue you reported on the lack of executions by your Function app.
> > We determined that the proper monitoring of incoming events, which is responsible for triggering executions, was suspended by a deadlock on  the Azure Storage SDK.
> > Restarting the related monitoring service recycled the stuck operation and resumed the monitoring. We have identified a fix for this issue.
> 
> Which means that the problem should no longer occur.

Thanks for the update on this @janwalczynski-intive! Hopefully we will no longer see any more of this problem now then.

Did they provide info on if the fix is already applied or will be in a future update/release?

And thanks to you @v-anvari for your help in looking into this!

**Comment by janwalczynski-intive** [comment] 2021-07-22 11:47
> Thanks for the update on this @janwalczynski-intive! Hopefully we will no longer see any more of this problem now then.
> 
> Did they provide info on if the fix is already applied or will be in a future update/release?

The fix is supposedly already in place.

**Comment by ZachTB123** [comment] 2021-07-22 13:05
The "deadlock on the Azure Storage SDK" issue sounds like the same canned response I've been getting from support on my similar problem. My original ticket I had opened with this said a fix was deployed earlier this year yet I still run into this today. Assuming my issue and the issue in this thread are due to the same underlying cause, I'm not convinced it is fixed.

> The fix is supposedly already in place.

Can we get confirmation on this - I assume the engineering team would be aware of what support is saying is already deployed?

**Comment by v-anvari** [comment] 2021-07-27 10:27
@ZachTB123 , Apologies, we do not have access to the support case.
