### ISSUE TITLE
Rename or wrap RpcException to make it clear error is from code and not platform

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#6284] opened 2020-06-29 19:39 UTC
When a function execution fails and the exception starts with `Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: Failure`, it looks like this should be a platform error when in almost every case, it is a failure with exception stack from user code. We should make this more clear from the name.

**Comment by mhoeger** [comment] 2020-06-29 19:41
cc: @pragnagopa @yojagad @ahmelsayed @AnatoliB @Hazhzeng - let me know your thoughts, I just had a CRI (and it feels like there are often CRI's) that ask questions about customer code errors and perhaps the "RpcException" bit is what makes them think it's platform related

**Comment by mhoeger** [comment] 2020-06-29 19:48
Would also be great to get rid of the stack exception portion that points to our code:
```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at D:\a\1\s\src\WebJobs.Script\Description\Workers\WorkerFunctionInvoker.cs : 85
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at D:\a\1\s\src\WebJobs.Script\Description\FunctionInvokerBase.cs : 85
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) at D:\a\1\s\src\WebJobs.Script\Description\FunctionGenerator.cs : 225
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 585
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 532
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 468
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 278
```

**Comment by pragnagopa** [comment] 2020-06-29 19:50
Related issue https://github.com/Azure/azure-functions-host/issues/4296, possibly a dup?

**Comment by liliankasem** [comment] 2022-02-23 23:15
Also related: https://github.com/Azure/azure-functions-dotnet-worker/issues/370

**Comment by liliankasem** [comment] 2022-04-01 16:11
Duplicate of #4296

**Closed as completed by liliankasem** 2022-04-01 16:11 UTC
Labels: feature:language-extensibility, enhancement, supportability: error-message-improvement
