### ISSUE TITLE
Function host stopping in the middle of function execution

### ISSUE THREAD

**Issue by joshlrogers** [Azure/azure-functions-host#7182] opened 2021-02-23 17:31 UTC
#### Description

We are encountering an issue where the function host stops in the middle of execution not allowing the function to continue.  We have a timer triggered function that downloads 1 or more files from an FTP location, saves them to blob storage, then notifies an API endpoint of the files.  Our function was able to achieve the first two things then the function host stopped without executing the third even though the function did not timeout, it had only been executing for 12 seconds.  There was no error/exception just a log that `Hosting Stopping`.  This may be related, though the function didn't timeout in our case, to the issue encountered here: https://github.com/Azure/azure-functions-host/issues/6202

#### Investigative information

Please provide the following:

- Timestamp: 2021-02-12T16:20:12.156 -0600
- Function App version: 3
- Invocation ID: 53783998-6c5b-4386-988c-2d3bd38bf26e
- Region: Central US

#### Repro steps

Unknown, this function works the vast majority of times

#### Expected behavior

This function should be allowed to finish or shouldn't have been scheduled on a host that was about to be shutdown in the first place.

#### Actual behavior

Function host shut down in the middle of execution leaving the process incomplete and us unaware as no error/exception was thrown.

#### Known workarounds

None

**Comment by elbarto-ptv** [comment] 2021-03-04 14:44
I also had exactly the same problem with a python azure function running within a docker container. 
The reason was the "pycache" Folder within the function folder. The host is stopping after ~ 10 seconds because the content of the function folder was changed and this leads the function to restart!

For details see here: https://github.com/Azure/azure-functions-python-worker/issues/366

The solution in my case was to compile all python files before running the azure function.
`pipenv run python -m compileall JobFolder  `

**Comment by joshlrogers** [comment] 2021-03-04 15:12
Thank you.  In our case, our application is a .Net Core 3.1 app and we aren't changing any underlying files in the function.  This has only happened once so far, so it seems rare, which is good, but it shouldn't happen at all. We need some kind of insight that it has happened since we can't rely on logs within our app given the host is just turned off and the host itself doesn't log it as an exception either.  Barring that we need a way to guarantee this won't happen at all.

**Comment by v-bbalaiagar** [comment] 2021-03-15 11:46
Hi @joshlrogers, Let us know if you are still facing the issues, if yes could you please provide us the function app name and recent time stamp to get the logs and check the cause.

**Comment by joshlrogers** [comment] 2021-03-15 14:35
No, thankfully, it hasn't happened in the 3 weeks it has taken to get a response to this.  I expect this issue is rare, but it shouldn't have happened at all and we still need to know what happened and/or how to prevent it from happening in the future.  Are you unable to use the timestamp already provided?  The function app name is: `SaddleCreek-Monitors-prod-func`

**Comment by v-bbalaiagar** [comment] 2021-03-18 16:57
Hi @joshlrogers, I went through the logs for the time stamp - 2021-02-12 00:00:00 to 2021-02-12 23:59:00. I see the error "Singleton lock renewal failed for blob 'saddlecreek-monitors-prod-func/host' with error code 409: LeaseIdMismatchWithLeaseOperation".  Here is how you can troubleshoot the issue.
https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger#troubleshooting
Related information:
[azure-functions-host/issues/7025](https://github.com/Azure/azure-functions-host/issues/7025)
Azure/azure-webjobs-sdk-extensions#249
[azure-functions-host/issues/1864](https://github.com/Azure/azure-functions-host/issues/1864)

**Comment by joshlrogers** [comment] 2021-03-18 17:11
I truly do not believe the singleton lock error had anything to do with it and even if it did the function that was killed was an HTTP triggered function, not a timer-triggered one.  Should a timer-triggered function have caused this issue it should not be acceptable that it killed the entire host, particularly so in the middle of execution. We are not anywhere close to stressing the host, we only have at most 2-3 functions executing on a host at any given time with at most a 120MB working memory set.  I/O operations are all async and properly awaited.

Also, per this guidance, https://github.com/Azure/azure-functions-host/issues/1864#issuecomment-556016881, we can pretty safely ignore these renewal warnings, which we get at least once or twice per day without issue such as the host going down.

Again, I feel quite confident in saying that a singleton lock error is not what caused this issue.  There weren't even any errors thrown around this timeframe when the host just died nor was there any thrown when the host died which caused a few days delay in us realizing there had been a problem.

**Comment by v-bbalaiagar** [comment] 2021-03-26 14:06
Hi @joshlrogers, For invocation id- **53783998-6c5b-4386-988c-2d3bd38bf26e**, function has started but it shutdown before it completed as shown below:

 

**2021-02-12 22:20:00.1157745- dw0SmallDedicatedWebWorkerRole_IN_hr0HostRole-392-VM-9 - function started- 53783998-6c5b-4386-988c-2d3bd38bf26e
2021-02-12 22:20:10.9209114- dw0SmallDedicatedWebWorkerRole_IN_hr0HostRole-392-VM-9 - ShutDownCompleted- 53783998-6c5b-4386-988c-2d3bd38bf26e**

 

Logs:Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'NotifyReefHttp'

 

Meanwhile, Next invocation has started and completed.

**2021-02-12 22:20:00.1213536-dw0SmallDedicatedWebWorkerRole_IN_hr0HostRole-392-VM-9-function started -4ddd033f-3cfe-4b2b-86fc-73c49c3f6647**

 

We need to further investigate to understand the cause of the "stopped the listener" . Meanwhile can you let us know if you are still seeing these failures. If yes, can you check the [failures and exceptions](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-exceptions#diagnosing-exceptions-using-visual-studio) in your application insight logs and let us know if you find something.

 

If you find any errors, please provide the latest error invocation id to investigate further and to check the timer trigger analysis.

**Comment by joshlrogers** [comment] 2021-03-26 14:09
@v-bbalaiagar we have not experienced this error since this time.  We had been running the function app for quite some time before we experienced it the first time, so we believe it to be quite rare.  If it should happen again I'll update with any information.

**Comment by v-bbalaiagar** [comment] 2021-04-20 05:46
Hi @joshlrogers, Closing this issue as the error hasn't re-occurred. Feel free to re-open the issue with the latest invocation id, if at all you come across the issue in future

**Closed as completed by v-bbalaiagar** 2021-04-20 05:46 UTC
