### ISSUE TITLE
Azure Function with Service Bus Trigger stops processing messages when not explicitly abandoning or completing messages unless the Function App is restarted

### ISSUE THREAD

**Issue by pacodelacruz** [Azure/azure-functions-host#6788] opened 2020-10-14 00:29 UTC
#### Check for a solution in the Azure portal

_Not available_

#### Investigative information

Please provide the following:

- Timestamp: `2020-10-13T22:59:36.378`
- Function App version: `v3`
- Function name(s) (as appropriate): `Receive01`
- Invocation ID: `f96bec1c-3eb8-4b90-9e16-3f3adca9c812`
- Region: `Australia East`

#### Repro steps

1. Create a Service Bus Topic and Subscription, with a High `maxDeliveryCount` e.g. `100` and short lock duration, e.g. `5 seconds`. (The same behaviour is observed with a lock duration of 5 mins)
2. Drop `1000` messages in the topic.
3. Deploy a basic Service Bus Triggered Azure Function with `autocomplete` set to `false` and without explicitly abandoning the message. 
4. Let the function run

#### Expected behavior

The Azure Function will keep the lock on the messages until they expire and while keeps picking up all active messages in the topic subscription until they are either consumed or dead-lettered. 

According to the [documentation]( 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-output?tabs=csharp#hostjson-settings):
> If an exception is thrown (and none of the MessageReceiver methods are called), then the lock remains. Once the lock expires, the message is re-queued with the DeliveryCount incremented and the lock is automatically renewed.

It is not clear what's the expected behaviour if there is no exception, but none of the `MessageReceiver` methods are called. However, I'd expect that the lock expires/is released and the message is available again for consumption with the `DeliveryCount` incremented. 

I'd expect that the Azure Functions runtime followed what's documented [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-transfers-locks-settlement): 

>When the receiving client fails to process a message but wants the message to be redelivered, it can explicitly ask for the message to be released and unlocked instantly by calling Abandon or it can do nothing and let the lock elapse.

#### Actual behavior

After 5K to 6K executions, the function stops processing messages, while messages are still active in the topic subscription and without being locked; messages can be consumed by other clients. After that, no activity is shown in the Azure Functions logs or Service Bus. 

So it seems that the function is actually allowing the lock to expire, but not picking the message after x retries. 

Without calling the `AbandonAsync` method, messages are being picked up multiple times (after their locks expire and their deliverycount increased) by the function without requiring restart. But after some retries, the function stops picking up messages. However, we can test that messages are not locked, as they can be consumed by other clients. 

Considering the [documentation]( 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-output?tabs=csharp#hostjson-settings):
> If an exception is thrown (and none of the MessageReceiver methods are called), then the lock remains. Once the lock expires, the message is re-queued with the DeliveryCount incremented and the lock is automatically renewed.

We can confirm that 
- Message locks expire as per the topic subscription configuration
- DeliveryCount is incremented

However, locks are not automatically renewed, as they are picked up multiple times by the same function and can be consumed by other clients even when the function stops picking them up. 

_A similar behaviour can be seen when running the Azure Function locally._ 

So the questions are: 

1. What's the expected behaviour when none of the MessageReceiver methods are called? 
2. Why does the Function stops picking up messages? 

#### Known workarounds

* Restart the Function App. This triggers the Function App again, but it eventually stops picking up messages. 
* Explicitly calling the `AbandonAsync` method. However, we want to let the lock expire by itself, regardless of the execution time of the function. 

#### Related information 

* Plan: App Service Plan (S1) with Always on turned on. Also happened on an Isolated (App Service Environment).
* Service Bus tier: The same behaviour is observed in Premium and Standard tiers.
* Connection String to Service Bus using `RootManage` access level. 
* There are no other apps deployed on the App Service Plan.
* CPU and Memory are quite healthy.
* No errors logged on Application Insights, Log Stream (verbose), Kudu (host or functions).
* Availability and Performance shows no issues.
  - TCP connections look healthy.
* Host keeps sending a `Running` status to App Insights.
* Function name well under 32 characters (originally suggested this as an issue by the support team).
* Storage account not shared with any other functions. 
* Deployment slots not in use.
* We are deliberately not calling the `AbandonAsync` method to let the lock expire by itself. 

Project Info: 
```XML
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
```

Host File
```JSON
{
  "version": "2.0",
  "extensions": {
    "serviceBus": {
      "prefetchCount": 0,
      "messageHandlerOptions": {
        "maxConcurrentCalls": 16,
        "autoComplete": false
      }
    }
  }
}
```

Packages
```XML
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
  </ItemGroup>
```

Function Code

```csharp
    public static class Receive01
    {
        [FunctionName(nameof(Receive01))]
        public static void Run(
            [ServiceBusTrigger("topic01", "sub01",
                Connection = "ServiceBus:ConnectionString")]
            Message message,
            MessageReceiver messageReceiver,
            ILogger logger)
        {
            logger.LogInformation($"Sequence: {message.SystemProperties.SequenceNumber} - DeliveryCount: {message.SystemProperties.DeliveryCount.ToString()}");
            return;
        }
    }
```

we know that if we add the code below (before returning the function) this behaviour does not happen. However, we want to let the lock to expire by itself. 

```csharp
await messageReceiver.AbandonAsync(message.SystemProperties.LockToken);
```

Topic / Subscription description
```JSON
    {
      "id": "/.../topic01/subscriptions/sub01",
      "name": "sub01",
      "type": "Microsoft.ServiceBus/TopicSubscriptions",
      "location": "Australia East",
      "properties": {
        "topicPath": "topic01",
        "subscriptionName": "sub01",
        "lockDuration": "00:00:05",
        "requiresSession": false,
        "defaultMessageTimeToLive": "14.00:00:00",
        "deadLetteringOnMessageExpiration": true,
        "deadLetteringOnFilterEvaluationExceptions": false,
        "messageCount": 2001,
        "maxDeliveryCount": 300,
        "enableBatchedOperations": true,
        "status": "Active",
        "countDetails": {
          "activeMessageCount": 2001,
          "deadLetterMessageCount": 0,
          "scheduledMessageCount": 0,
          "transferMessageCount": 0,
          "transferDeadLetterMessageCount": 0
        },
        "autoDeleteOnIdle": "10675198.02:48:05.4770000",
        "entityAvailabilityStatus": "Available"
      }
    }
```

Last Log Events

Not sure if relevant, but these events `Last analysis flag value` and `Skipping breaking change analysis` are always logged after the last execution. When are these events meant to be executed? See below. 

```text
2020-10-14T01:14:33.701 [Information] Executed 'Receive01' (Succeeded, Id=ef463d25-337b-4fc6-9d83-ec1fc1b0b995, Duration=1ms)
2020-10-14T01:14:55.508 [Information] Last analysis flag value '2020-10-13T21:41:28.9326466+00:00'.
2020-10-14T01:14:55.511 [Information] Skipping breaking change analysis.
2020-10-14T01:15:10.531 [Information] Host Status: {"id": "***","state": "Running","version": "3.0.14492.0","versionDetails": "3.0.14492 Commit hash: b088b9dad1238cef70931c608f16c5c315d328fb","processUptime": 95019}
```I

**Comment by Camios** [comment] 2020-10-14 01:53
+1

**Comment by hybridtechie** [comment] 2020-10-14 04:54
+1

**Comment by smairo** [comment] 2020-10-15 05:56
+1

**Comment by pacodelacruz** [comment] 2020-10-21 03:09
Microsoft have confirmed that the root cause of this issue is not on the the Azure Functions host. It's a limitation on the AMQP implementation on the Service Bus backend side as explained here. 
https://github.com/Azure/azure-sdk-for-net/issues/6450#issuecomment-595926541.

**Comment by shankarsama** [comment] 2020-11-10 01:03
We fixed the issue with the Service Bus SDK, refer to this PR  https://github.com/Azure/azure-sdk-for-net/pull/16163

**Comment by pacodelacruz** [comment] 2020-11-12 06:55
Hi @shankarsama, could you please confirm if this issue is fixed by updating the client SDK? 
It's not very clear from the PR. 
What's the nuget package required on the client to avoid this from happening? 
Thanks!

**Comment by v-bbalaiagar** [comment] 2021-08-06 14:17
Hi @pacodelacruz, Apologies for the delayed response, the issue was somehow lost in the trace. Could you please confirm if the issue is not on the azure functions host, can we close this issue here.

**Closed as completed** 2021-08-13 22:00 UTC
Labels: Needs: Author Feedback, no-recent-activity
