### ISSUE TITLE
Functions CLI stops writing output and failing to let Functions to trigger/run successfully

### ISSUE THREAD

**Issue by bzhu94** [Azure/azure-functions-host#2595] opened 2018-03-28 17:54 UTC
INSTALL STEPS

1. Clean machine: Win 7 SP1 x86 DEU

2. Run preinstall.cmd: \\vspreinstall\preinstall\preinstall.cmd 

3. Install Dev15.6 Val (pre-release-build) VSE from \\cpvsbuild\drops\VS-Val\d15.6\products\27427.9000.pehuene.180227.152046\bootstrappers  

4. Select Web + NetCore + Azure workload

REPRO STEPS

1. File > New Project > Azure Functions > Azure Functions v2 (.Net Core) with the Empty template + Storage Emulator option selected.

2. Right click project -> Add New Item-> New Azure Function (name Foo.cs) > Blob trigger function and set the connection to "AzureWebJobsStorage".

3. Right click project -> Add New Item-> New Azure Function > HttpTrigger function with the Access rights set to "Function".

4. Run the command "C:\Program Files\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start  

5. Hit F5

ACTUAL

![actualbehaviorclifail](https://user-images.githubusercontent.com/8541576/38047026-09440674-3276-11e8-8c78-c63689c8eccd.png)

The runtime stops writing new output and is essentially "stuck". Attempting to run and trigger any Functions (Http and BlobTriggers used in this case) fail and also don't display new output. 

EXPECTED

![expectedbehaviorclifail](https://user-images.githubusercontent.com/8541576/38047022-02e1a214-3276-11e8-8923-f175beb0b0fa.png)

The runtime should show this output and write new output as Functions get triggered. The Functions should work without issue.

**Note: this seems related to https://github.com/Azure/azure-functions-host/issues/2125, but creating this issue anyways in case the root cause for the two issues are different**

**Comment by mathewc** [comment] 2018-03-28 18:06
Does this repro if you point to a non emulator storage account? You say this seems related to #2125 - are you seeing AccessViolation errors in the log like in that issue?

**Comment by pragnagopa** [comment] 2018-05-04 21:05
Root cause identified. Issue #2525. Closing this as Dup.

**Closed by pragnagopa** 2018-05-04 21:05 UTC
