### ISSUE TITLE
Switch from IApplicationLifetime(deprecated) to IHostApplicationLifetime

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-host#8866] opened 2022-10-26 17:07 UTC
https://github.com/dotnet/aspnetcore/issues/7749
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iapplicationlifetime?view=aspnetcore-6.0

Usage of the deprecated type in host: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/WebScriptHostExceptionHandler.cs#L17

**Comment by jviau** [comment] 2023-07-26 22:09
Duplicate of #8508

**Closed as not planned by jviau** 2023-07-26 22:09 UTC
