### ISSUE TITLE
Python Function app process events in sequence, not in parallel (Event Hub trigger, Consumption plan)

### ISSUE THREAD

**Issue by artsheiko** [Azure/azure-functions-host#6310] opened 2020-07-06 20:05 UTC
We have the next chain : event producer -> input Event Hub -> Azure Function [Python] -> output Event Hub -> consumer.
Function app process events in sequence, not in parallel.

**Repro steps**
1. Create a function app 

> Python, 3.7
> North Europe
> Consumption plan

2. Create an Event Hub

> Pricing tier : Basic 
> Throughput units : 20

3. Use an Event Hub Trigger for function
4. Deploy a Function with a not CPU-bound processing logic
5. Send 1000 messages in a Event Hub

**Expected behavior**
Knowing that we can have up to 1000 messages sent in EventHub almost simultaneously, we need a workaround to reduce overall time of execution (process Python Azure Function in parallel)

**Actual behavior**
Not taking into account a cold start if it happens : 
- one message is processed during 8 secs (OK)
- 1000 messages are processed during 2 hours (KO)

**Related information**
Based on the trigger description (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=python) the new instance is added when the hub has more messages than function can proceed. But it seems that 1000 events is not enough to scale up a function app to start a parallel processing.
Tested using the next configurations : 

- Event Hub throughput units : 20
- input Event Hub partitions quantity :  20
- input Event Hub consumer group : $Default
- output Event Hub partitions quantity : 20
- output Event Hub consumer group : $Default

host.json : 
`
{
    "version": "2.0",
    "extensions": {
        "eventHubs": {
            "batchCheckpointFrequency": 1,
            "eventProcessorOptions": {
                "maxBatchSize": 200,
                "prefetchCount": 400
            }
        }
    }
}
`

function.json : 
`{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "event",
      "direction": "in",
      "eventHubName": "event-hub-20-read",
      "connection": "receiverConnectionString",
      "cardinality": "one",
      "consumerGroup": "$Default",
      "dataType": "binary"
    },
    {
      "type": "eventHub",
      "name": "$return",
      "eventHubName": "event-hub-20-write",
      "connection": "receiverConnectionString",
      "direction": "out"
    }
  ]
}`

Application settings
FUNCTIONS_EXTENSION_VERSION : ~3
FUNCTIONS_WORKER_PROCESS_COUNT : 10

**Comment by balag0** [comment] 2020-07-07 00:19
Thanks for the detailed description of the issue, could you also share the name of the function app (and approx time range ) which you used to test this configuration. Would like to check if the scaling logic worked as expected. 

You can also share the function app name privately using
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by paulbatum** [comment] 2020-07-07 01:03
So the main thing to focus on first is scaling, so please share the details Bala requested so we can look at that. I do have a few other suggestions, though these are mostly things that might help once scaling is solved:

Are you setting a partition key when you write the data? If you are using a partition key and you are using the same partition key for all 1000 messages, then they will land on the same partition and be processed sequentially.

It sounds like the amount of work per message is quite high (you mentioned it takes 8 seconds). Is this a CPU bound workload, or is it an IO bound workload? If the 8 seconds is mostly spent on IO, then you will likely get better throughput if you write your python function to be async. See [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#scaling-and-concurrency) for some documentation.

I also noticed that you have your cardinality set to one, i.e. your function is being passed just one message at a time. Please be aware that if you need in-order processing of a given partition (but with parallel processing across multiple partitions), once you change your function to be async, you'll need to also change your function to be passed a batch of messages (with cardinality many). If you have no ordering requirements, then you don't need to worry about this.

Also I think you'll want a smaller batchsize since the messages require a long time to be processed. I would suggest altering maxBatchSize to something like 20, and I would leave prefetch count at the default. This will mean that each instance will pull fewer messages at a time.

**Comment by pragnagopa** [comment] 2020-07-07 03:10
Assigning to @balag0 for Triage. @balag0 - Please do reassign as needed.

**Comment by artsheiko** [comment] 2020-07-07 10:25
@paulbatum and @balag0, thank for your reply. 

UTC execution time : 2020-07-07T10:10:14Z
Function GUID : 5c1d4eeb-448f-4a9b-9f83-e5417d14e878
Region : North Europe 

Last test using 200 messages (approx time range) : 
2020-07-07 09:20
2020-07-07 09:50

The two files below was used to send and receive messages.

send.py :
```
async def send_event_data_batch(producer):
    event_data_batch = await producer.create_batch()
	data = ...
    event_data_batch.add(EventData(json.dumps(data)))

    await producer.send_batch(event_data_batch)

async def run(nbr_messages):
    producer = EventHubProducerClient.from_connection_string(conn_str=cnx, eventhub_name=eh_name)
    async with producer:
        for i in range(int(nbr_messages)):
            await send_event_data_batch(producer)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run(200))
```

receive.py :
```
async def on_event(partition_context, event):
    data = json.loads(event.body_as_str(encoding='UTF-8'))
    print(f'Message Id : {data.get("id")} , received at {datetime.now()}')
    await partition_context.update_checkpoint(event)

async def main():
    client = EventHubConsumerClient.from_connection_string(cnx, consumer_group='$Default', eventhub_name=eh_name) 
    async with client:
        await client.receive(on_event=on_event)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

Partition key is not set while batch is created => default None is used => round-robin expected.
I'd like to say that it is CPU bound, but we see that CPU Total metric value is rarely more than 5%.

We will try to test using the next : cardinality = "many" ; maxBatchSize = 20 ; prefetchCount = 300.

**Comment by artsheiko** [comment] 2020-07-07 15:17
UTC execution time : 2020-07-07T12:35:35.3978485Z
Function GUID : 6ed7760a-ee3c-4e2f-a2e3-bcfbfc3c6835
Region : North Europe

Last test using 200 messages (10 batches , 1 batch = 20 messages, approx time range) :
2020-07-07 12:35
2020-07-07 13:14
 
function.json :
```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "events",
      "direction": "in",
      "eventHubName": "event-hub-20-read",
      "connection": "receiverConnectionString",
      "cardinality": "many",
      "consumerGroup": "$Default",
      "dataType": "binary"
    },
    {
      "type": "eventHub",
      "name": "$return",
      "eventHubName": "event-hub-20-write",
      "connection": "receiverConnectionString",
      "direction": "out"
    }
  ]
}
```


The file below was used to send messages as batches.
send_w_batch.py :
```
async def send_event_data_batch(producer,batchSize):
    event_data_batch = await producer.create_batch()
    for i in range(batchSize):
        data = ...
        event_data_batch.add(EventData(json.dumps(data)))

    await producer.send_batch(event_data_batch)
```

**Comment by balag0** [comment] 2020-07-07 23:49
The app scaled to 1 instance. But this is by design with just 200 messages and non-increasing queue length. 

@alrod @pragnagopa I shared the kusto query with the app details by email. Please update here if you have anything else to add.

**Comment by paulbatum** [comment] 2020-07-07 23:58
Its not quite as simple as that. For other trigger types like service bus, we also use queue time as a metric to drive scale, and this helps for cases where the messages require heavy processing. I think perhaps the problem here is that we don't have such a metric available for the eventhub case, and typically customers use eventhub for lightweight/realtime event processing and so the lack of something like queue time based scaling has not been as much of an issue so far.

But its unreasonable to say that this is "by design" and leave it at that. The idea is the platform should be smart enough to scale out the workload for a variety of workload types.

To get this particular pattern (small, short burst of heavyweight eventhub messages) to scale well, perhaps we need to take the change in unprocessed messages over time into account. Bala I will catch up with you offline so you can show me more of the scale controller telemetry we captured for these runs.

**Comment by artsheiko** [comment] 2020-07-08 05:43
@balag0, will it be useful if we send 200 / 1000 messages and then 1/2/5/10 others each 5/10/N seconds to simulate new incoming events to force function to scale up ?

For our purposes, we are not limited to the pattern event hub -> function -> event hub. The main objectif is to process events quickly as possible. Execution must be parallelized. It is unacceptable for the producer to send the 1000th message and wait 2 hours while other 999 existing messages in the queue are processed.

**Comment by paulbatum** [comment] 2020-07-08 21:29
Oh yes, service bus is much more appropriate for your workload (based on the details you've shared so far). 

If you want maximum parallelism and there are no ordering requirements at all, then eventhub is a poor choice because each partition is ordered. This means that the maximum amount of parallel VMs you can have running processing your workload is equal to your partition count. Also any messages that are "slow" to process will block the processing of other messages on the same partition.

In comparison, messages written to service bus will be processed with the competing consumer pattern, with basically no upper limit on the number of consumers. Your app could theoretically be running on 100s of VMs, all competing for messages, and processing of one message would not block any others.

Also, our scaling logic for service bus takes queue time into account, so your load pattern of dropping a large batch of messages in one go would scale better.

Yes its possible that changing your write pattern to simulate an increasing workload would be a reasonable workaround to force the eventhub scenario to scale better, but I would look at this as only a method of last resort.

**Comment by fabiocav** [comment] 2020-07-29 16:08
Closing this as answered based on the information above, but please let us know if you have additional questions.

**Closed as completed by fabiocav** 2020-07-29 16:08 UTC
