### ISSUE TITLE
Azure Function is retriggered by a successful/completed Service Bus Queue message

### ISSUE THREAD

**Issue by jhoerr** [Azure/azure-functions-host#2309] opened 2018-01-12 02:17 UTC
I have a function with a service bus queue trigger. The queue is configured with the default 30 second lock duration. Within the last hour, I've seen at two instances of the function successfully processing a message, and then that same message being processed again 30 seconds later. The behavior is inconsistent: only 2 of ~20 successful function invocations have exhibited this behavior. App Insights indicates that all completed successfully ("_Function Completed (Success,...)_").

#### Investigative information

Please provide the following:

- Timestamp: 
    + _initial invocation: 19:30:06 EST (00:30:06 UTC)_
    + _duplicate followup invocation: 19:30:36 EST (00:30:36 UTC)_
- Function App version (1.0 or 2.0-beta): _1.0_
- Function App name: _ptp-functions-prod_
- Function name(s) (as appropriate): _Workflow_
- Invocation ID: 
   1. _First case:_ 
       + _initial invocation ID: 51ba3755-27ee-4b93-a85e-44f7c71a366a_
       + _duplicate followup invocation ID: f2bef441-5245-480e-bad1-1442e76ec4a7_
   2. _Second case:_
       + _initial invocation ID: 1e679d20-1be8-472c-b811-fc9b6a8e6ebd_
       + _duplicate followup invocation ID: 7e267b4c-f3a1-41c8-a0c7-23d60b99c567_
- Region: _US North Central_

I do not think duplicate messages were being enqueued because in each case the second invocation occurred exactly 30 seconds after the first invocation. I would expect that duplicate messages would have been executed at close to the same time. There were also other messages enqueued in the same batch that were not executed twice.

I have no reason to believe this duplicate processing is limited to this particular function. I just happened to get alerted in this case because the function generates email and the recipient mentioned they got duplicate emails.

#### Repro steps

Unknown, unfortunately. The behavior is inconsistent.

#### Expected behavior

Upon success the service bus message is automatically completed and is not reprocessed.

#### Actual behavior

Though the function succeeds the message appears to not get completed. After 30 seconds the lock expires and the message is erroneously reprocessed.

#### Known workarounds

None.

#### Related information 

Provide any related information 

* Programming language used: _F#_
* Links to source:
  + function code: _https://github.com/pingthepeople/ptp-functions/blob/master/src/Functions/Workflow/Workflow.fs_
  + function.json: _https://github.com/pingthepeople/ptp-functions/blob/master/src/Functions/Workflow/function.json_
* Bindings used: _Service bus queue_

**Comment by mathewc** [comment] 2018-01-16 19:02
The invocations you mentioned take under a second, so it doesn't appear that the issue is an expired lock. Our logic for completing a function invocation is [here](https://github.com/Azure/azure-webjobs-sdk/blob/ff08a455d838829c9c57cf68ac8679ba1cb5996e/src/Microsoft.Azure.WebJobs.ServiceBus/MessageProcessor.cs#L59) - if the function returns success (i.e. doesn't throw an exception) the message is completed, otherwise it is abandoned.

**Comment by NichUK** [comment] 2018-01-20 00:05
I'm seeing something very very similar. One message got put onto the service bus topic and it seems to have been duplicated and played many times all exactly the same, but with a different context id in the logs.

The invocations start with this context ID at around 2018-01-19T23:29Z
3d04eb75-988a-4ac0-9a2a-2563effeae93

Service bus topic: https://giftie-production.servicebus.windows.net/renderer-razor
Service bus subscription: razor-renderer

I don't think it's a lock problem because the invocations are very quick to process, and they all succeed, but there are an accumulating number of messages in the subscription, so nothing seems to be getting deleted, even though the functions are succeeding.

I'm running with a "Listen" access policy. I'm assuming that has sufficient rights to delete after processing?

**Comment by paulbatum** [comment] 2018-03-01 19:48
We have a few different service bus bugs that all appear to be related to completion behavior. @mathewc will look at this and see if its related to the others.

https://github.com/Azure/azure-webjobs-sdk/issues/1573

**Comment by mathewc** [comment] 2018-03-02 19:15
Guys - we have a fix for https://github.com/Azure/azure-webjobs-sdk/issues/1605 going out in the next release. This might fix your issues. When the new release is out, please let us know if you're still having problems.

**Comment by krislw** [comment] 2018-03-06 11:01
Hi, I believe I am experiencing the same bug using c#. I am using a singleton Listener Mode, and successful messages are being re-sent to the queue with different IDs. This makes the Function essentially unusable for our use case. 

@mathewc which release do you expect your mentioned fix to go out in?

Many thanks

**Comment by graemeenglish** [comment] 2018-03-16 14:47
I am also seeing this behaviour. In my case I believe it is related to the webjob restarting. I'm using a custom MessageProcessor which logs and calls message.CompleteAsync() in CompleteProcessingMessageAsync if result.Succeeded. I'm also logging the start/end of function execution. What I see on occasion is something like the following:

`Processing message, deliveryCount:1, id:eb0ddce9-64de-476c-a940-c30c1686c56f`
`Beginning message id:eb0ddce9-64de-476c-a940-c30c1686c56f `
`Finished message id:eb0ddce9-64de-476c-a940-c30c1686c56f`
`Job host stopped`
`Job host started`
`Processing auto requeued message, deliveryCount:2, id:eb0ddce9-64de-476c-a940-c30c1686c56f`
`Beginning message id:eb0ddce9-64de-476c-a940-c30c1686c56f `
`Finished message id:eb0ddce9-64de-476c-a940-c30c1686c56f`
`Completed message, deliveryCount:2, id:eb0ddce9-64de-476c-a940-c30c1686c56f`

So it looks like because the CompleteProcessingMessageAsync is not being called, ServiceBus requeues the message. Message all have a message id so I'm sure it is the same message.

**Comment by mathewc** [comment] 2018-03-16 16:48
@graemeenglish You can get a version of the ServiceBus package from our myget feed - version 2.2.0 has the fix. Instructions here: https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds. Because you're using a custom MessageProcessor, I take it you're not using Azure Functions and are just using the WebJobs SDK. You could try the fixed build and see if it addresses your issue.

@krislw You're using Azure Functions? The release with the fix is already rolling out. It's in some regions but not all yet.

**Comment by krislw** [comment] 2018-03-16 17:28
@mathewc  thanks for getting back to me. yes I am using Azure Functions. Is there a page where I can view what fixes are applied to which regions?

**Comment by graemeenglish** [comment] 2018-03-16 18:01
@mathewc Thanks for your response, yes using webjobs but I saw you mention the webjobs sdk above so thought it might apply, it will be next week before I get the chance to check it out.

**Comment by mathewc** [comment] 2018-03-16 18:12
@krislw No, our staged release progression isn't public. We do post when we start/complete releases however on our announcements page, e.g. https://github.com/Azure/app-service-announcements/issues/91

**Comment by krislw** [comment] 2018-03-16 18:15
@mathewc ok, I guess I'll just monitor that page for when 2.2.0 has been release. Thank you

**Comment by graemeenglish** [comment] 2018-03-20 08:54
@mathewc No difference with 2.2.0 I'm afraid. I think I might be running into https://github.com/Azure/azure-webjobs-sdk/issues/1064
If I add a delay after RunAndBlock my function completes, however CompleteProcessingMessageAsync does not seem to be called so servicebus will requeue the message
One thing I noticed is that I see an exception (I registered for the ExceptionReceived event in ServiceBus config) and 'Job Host stopped' almost immediately after I touch the shutdown file. I've included the logs in case it helps.
```
warn: Host.Startup[0]
      ServicePointManager.DefaultConnectionLimit is set to the default value of 2. This can limit the connection throughput to services like Azure Storage. For more information, see https://aka.ms/webjobs-connections.
warn: xxx.CustomMessagingProvider.CustomMessageProcessor[0]
      Processing auto requeued message, path:test, deliveryCount:10, id:37baf528-3c00-437f-8c64-f42cbdd77fa3
info: Host.Startup[0]
      Job host started
function started
warn: xxx.WebJob[0]
      Message pump exception processing Receive
System.OperationCanceledException: The operation cannot be performed because the entity has been closed or aborted. ---> System.ServiceModel.CommunicationObjectAbortedException: Internal Server Error: The server did not provide a meaningful reply; this might be caused by a premature session shutdown. TrackingId:83ca24db-81f4-47f4-815d-4a4b89840228, Timestamp:20/03/2018 08:33:33
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass8_1.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndReceiveCommand(IAsyncResult result, IEnumerable`1& messages)
   --- End of inner exception stack trace ---
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndReceiveCommand(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.ReceiveAsyncResult.<>c.<GetAsyncSteps>b__12_5(ReceiveAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.OnEndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.<>c.<GetAsyncSteps>b__15_3(RetryReceiveAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.TryReceiveEnd(IAsyncResult r, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndReceive(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceivePump.PumpAsyncResult.<>c.<GetAsyncSteps>b__7_3(PumpAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
info: Host.Startup[0]
      Job host stopped
function complete
fail: Host.Results[0]
      Executed 'Functions.DummyFunction' (Failed, Id=cf6f3d89-a965-42d0-b92b-b1b594dcda7c)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Loggers.UpdateOutputLogCommand.<UpdateOutputBlob>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Loggers.UpdateOutputLogCommand.<SaveAndCloseAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__13.MoveNext()
```

**Comment by graemeenglish** [comment] 2018-03-21 08:43
@mathewc Is it worth me creating a new issue in the azure-webjobs-sdk project or do you think it is the same issue as 1064?

**Comment by mathewc** [comment] 2018-03-21 17:09
I commented on https://github.com/Azure/azure-webjobs-sdk/issues/1064, explaining how the shutdown process works. During shutdown, if for whatever reason your functions don't complete before the grace period (before the WebJob process is stopped) there indeed may be some messages that started processing but haven't completed. That is normal, and can also happen in cases where the process crashes for whatever reason - messages will be reprocessed until they complete. Your code needs to be prepared for that possibility.

I suspect that there isn't an issue here, but if you feel there is, then you can create an issue in the SDK reop with a full repro so we can investigate further to see if the behavior you're experiencing is expected.

**Comment by mathewc** [comment] 2018-03-21 17:11
The Azure Functions release with the referenced fix has been released. I'm closing this issue as resolved. The WebJobs SDK issue discussed above should be handled separately in the referenced SDK issue threads.

**Closed by mathewc** 2018-03-21 17:11 UTC
Labels: bug
