### ISSUE TITLE
Successful and Failed Execution metric

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-host#3943] opened 2019-01-11 21:33 UTC
The metric we're planning to move to for executions aggregation, function.invoke.latency, regresses a part of our pipeline, since it doesn't tell us whether the execution was successful. We should either add to this metric a field for whether the execution was successful, or add a new metric to give us this information.

**Comment by paulbatum** [comment] 2019-01-12 01:04
Yes, I need this for some detectors (otherwise have to parse strings in the functions logs table).

**Comment by ColbyTresness** [comment] 2019-02-27 01:02
@jeffhollan

**Comment by fabiocav** [comment] 2019-04-09 20:08
Adding this to sprint 47 for scoping/investigation. May not be completed until 48.

**Comment by fabiocav** [comment] 2019-04-12 19:51
This is done.

Duplicate of #3640

**Closed by fabiocav** 2019-04-12 19:51 UTC
Labels: P1, Supportability
