### ISSUE TITLE
Error during generation of extensions.json - broken dependency injection

### ISSUE THREAD

**Issue by michalkadlubowski** [Azure/azure-functions-host#5741] opened 2020-03-04 14:18 UTC
When using Microsoft.NET.Sdk.Functions 1.0.33 and dependency injection as described in [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection) generated extensions.json file is not populated.

This results in exceptions during runtime of any functions relaying on dependency injection.

When using Microsoft.NET.Sdk.Functions 1.0.31 everything works fine.

Detailed build log reveals problem during **GenerateFunctionsExtensionsMetadata task**:

`Cannot load 'Microsoft.Azure.WebJobs.Host'. Aborting assembly resolution.`

Microsoft.Azure.Functions.Extensions depends on Microsoft.Azure.WebJobs.Host and it seems that this dll is being deleted during **RemoveRuntimeDependencies task** that is run before **GenerateFunctionsExtensionsMetadata task**

**Repro steps**
In visual studio create new Azure Functions project and setup dependency injection as described in official [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection) using Microsoft.NET.Sdk.Functions 1.0.33.
Run or debug functions project on your machine.

**Expected behavior**
Function runs with dependencies injected

**Actual behavior**
Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type...

**Known workarounds**
Downgrade Microsoft.NET.Sdk.Functions to version 1.0.31

**Related information**
Language: C#
Function App version: **2.0**
Azure Functions Core Tools (3.0.2245 Commit hash: 1d094e2f3ef79b9a478a1621ea7ec3f93ac1910d)
Function Runtime Version: 3.0.13139.0

**Comment by michalkadlubowski** [comment] 2020-03-05 19:52
I think this is same as  #5747 and should be closed

**Comment by brettsam** [comment] 2020-03-05 20:25
Thanks @michalkadlubowski -- closing as dupe of https://github.com/Azure/azure-functions-host/issues/5747.

**Closed as completed by brettsam** 2020-03-05 20:25 UTC
