### ISSUE TITLE
Azure function time trigger not resuming unless I visit the azure portal 

### ISSUE THREAD

**Issue by tberst** [Azure/azure-functions-host#2421] opened 2018-02-14 10:12 UTC
#### Investigative information

- Timestamp: 2018-02-13T15:35:00.0076347+00:00 (successfull run) / 2018-02-14T08:02:05.0220800+00:00 (next successfull run ... no activity in between, this is supposed to be an every  5 mins trigger)
- Function App version (1.0 or 2.0-beta): Runtime version: 1.0.11535.0 (~1)
- Function App name: FdriverFunctionsDemo
- Function name(s) (as appropriate): PullXmlFilesTimer
- Invocation ID: 5a170853-ea00-456f-9ae0-b151454f2048 / c16cf1c2-cdf2-49b1-92ee-209806694ce1
- Region: West-Europe

#### Repro steps

I have a timer triggered azure function with schedule =  "0 */5 * * * *", the function is supposed to run every 5 minutes. It stops after a few invocations...
I don't see any error in the various available logs. ..

#### Expected behavior

The function should run every 5 minutes

#### Actual behavior

The function runs a few times and then stops. There are no new invocations unless I manually go the azure portal website and look at the azure function..... then it starts for a few rounds and stops again.

![image](https://user-images.githubusercontent.com/11627752/36198642-6ebaa7b2-1177-11e8-97b2-4a67778b8e6d.png)

#### Known workarounds

N/A

#### Related information 

* Programming language used : C# 
* Links to source : Not publically available
* Bindings used
``` "bindings": [
    {
      "type": "timerTrigger",
      "schedule": "0 */5 * * * *",
      "useMonitor": true,
      "runOnStartup": false,
      "name": "myTimer"
    }
  ]
```

**Comment by mdelgadodiaz83** [comment] 2018-02-16 07:52
Hi , 

We have the same scenario, and we are experimenting the same behavior, but for us, visit the portal wasn't enough, we had to change something about web app, concretely we activated the streaming log and immediately all function started to work again. 

We have Azure functions on Production and we have a big impact on this issue. 

Thanks for investigating it !!!!

**Comment by alrod** [comment] 2018-02-17 04:16
@ConnorMcMahon, is it duplicate https://social.msdn.microsoft.com/Forums/en-US/07b7cab1-09e2-4c6e-9fd1-3561ae0c6ca4/azure-timer-function-not-firing?forum=AzureFunctions ?

**Comment by mdelgadodiaz83** [comment] 2018-02-21 18:51
something else about that ?????

**Comment by kastwey** [comment] 2018-02-22 08:56
Hi,

I have the same behavior. We have a lot of azure functions in production, and sometimes (I cannot determine the pre-conditions), the functions stop working and we need to Access portal to resume them.

**Comment by tberst** [comment] 2018-02-22 11:15
I tried the **WEBSITE_USE_PLACEHOLDER = 0** trick. It seems to work (at least for the past 3 hours).

**Comment by mdelgadodiaz83** [comment] 2018-02-22 16:01
WE have tested the workaround and the problem persist . Please, could someone say something !!!!!!

**Comment by ConnorMcMahon** [comment] 2018-02-23 00:57
@tberst, @kastwey, @mdelgadodiaz83, how did you initially deploy your functions?

**Comment by ConnorMcMahon** [comment] 2018-02-23 01:02
One way to potentially alleviate this in the short term is to manually sync your triggers. The easiest way to do this is  to go to the portal, then click the refresh button next to your function app name in the tree. However, knowing what way you deployed will help us to fix this issue for future deployments.

**Comment by kastwey** [comment] 2018-02-23 01:15
Hi,

I'm deploying my functions by using the kudu functions api. I create,
delete and update functions dynamically.

Thanks!

Regards,

Juanjo..


2018-02-23 2:02 GMT+01:00, ConnorMcMahon <notifications@github.com>:

**Comment by mdelgadodiaz83** [comment] 2018-02-23 07:01
@connorMcMahon we are using service plan instesd to consumption plan . For our production product is not possible to do refresh every time one function is created. We are so stuck with that 😥

**Comment by tberst** [comment] 2018-02-23 08:48
@ConnorMcMahon : we use an ARM template. The deploy task looks like that.

`    "resources": [
                {
                    "name": "MSDeploy",
                    "type": "extensions",
                    "location": "[resourceGroup().location]",
                    "apiVersion": "2015-08-01",
                    "dependsOn": [
                        "[resourceId('Microsoft.Web/sites', variables('azureFunctionName'))]"
                    ],
                    "tags": {
                        "displayName": "AzureFunction"
                    },
                    "properties": {
                        "packageUri": "[concat(parameters('_artifactsLocation'), '/', parameters('SyncEnginePackageFolder'), '/', parameters('SyncEnginePackageFileName'), parameters('_artifactsLocationSasToken'))]",
                        "dbType": "None",
                        "connectionString": "",
                        "setParameters": {
                            "IIS Web Application Name": "[variables('azureFunctionName')]"
                        }
                    }
                }
            ],`

If there is another way of deploying it by script, I'd be happy to try :)

**Comment by kastwey** [comment] 2018-02-23 11:00
Hi,

I'm using app service mode. Does that link information  affect also the functions in app service mode?
Anyway, I'm not changing the "function.json" trigger time span expression on an existing function. I create new functions or update existing csx functions code but without changing its interval.
Normally, when I create a new function with Kudu, this function is integrated an executed a lot of times without errors. The problem is that over time, the functions stop running for no apparent reason, or at least I have not been able to detect reproducible behavior.
I imagine that executing SyncTriggers (because the host is restarted), everything will come back to work correctly, but making that call in a recurring way does not seem to me the most appropriate in production environment :)
In addition, the call to SyncTriggers, when restarting the host, takes up to one minute (with fifty functions). I imagine the more functions there are, the longer this operation takes.

Thanks!

Regards.

**Comment by ConnorMcMahon** [comment] 2018-02-23 19:47
@tberst, ARM deployments should synchronize the triggers. We saw that your other two triggers were synchronized on deployment, just not your timer trigger. Was the timertrigger function deployed at the same time as your other functions?

**Comment by ConnorMcMahon** [comment] 2018-02-23 19:51
@kastwey and @mdelgadodiaz83, as stated in the above link, currently Kudu does not synchronize triggers from functions added there. The easiest options would be to switch to a deployment method that does handle this, such as Visual Studio deployment or the Azure Functions CLI. If for some reason you really need to stick to Kudu deployments, there is an issue logged [here ](https://github.com/serverless/serverless-azure-functions/issues/4) that you could express your interest in having fixed.

**Comment by tberst** [comment] 2018-02-27 13:59
@ConnorMcMahon, actually this instance was deployed using visual studio. They're all part of the same project and deployed at the same time.

How can I check this 'synchronization' thing ?

Btw, I deployed again the same azure functions on a new instance (in another ressource group, using another app plan) and this time it seems to work without the WEBSITE_USE_PLACEHOLDER  trick.

**Comment by ConnorMcMahon** [comment] 2018-02-27 19:16
@tberst The issue with the place holders was actually fixed, so that should no longer affect functions triggering or not.

In general, I do not know of a particularly clean way of figuring out whether all of your functions are synchronized, as it is meant to occur automatically for most of our deployment methods. If you believe that your functions are not being synchronized on deployment, then you can manually trigger it by hitting the refresh button in the portal or by using the PowerShell API described [here](https://github.com/Azure/Azure-Functions/issues/210).

If you are seeing a function not execute after deploying using one of the supported methods in the above link, and synchronizing fixes it, please report that either here or as a separate issue, with information such as how you deployed, when you deployed, and when you synchronized so we can investigate why the functions didn't synchronize properly.

**Comment by vludax** [comment] 2018-03-04 21:32
Timer-triggered functions not firing seems to be a recurring issue for over a year already, based on bug reports here. Just a few days ago we deployed a timer-triggered function via an ARM template. It was the only timer-triggered function in a Function App, which existed previously hosting a number of queue-triggered functions, which have been working without issues for months. The timer-triggered function was supposed to run every 5 minutes (0 */5 * * * *), which it did for a few hours. When we checked a couple of day later, the function wasn't running anymore. The fact of checking seemed to have made the function run again, but only for a about half an hour. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/5164413/36950781-0976bee0-204f-11e8-929c-362ab2b4a563.png)

We'll likely implement this functionality using an Azure Scheduler now, which appears to fire more reliably. Quantum functions don't exactly fit our needs just yet.

**Comment by mdelgadodiaz83** [comment] 2018-03-04 21:36
A los of us are experimenting this issue but they saying that it's only related with method deploy, and the issue happens over and over again...

**Comment by ConnorMcMahon** [comment] 2018-03-05 19:18
@vludax Can you [share your function app privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) so that we can help investigate your issue?

@mdelgadodiaz83 There does seem to be this issue reported across different deployment methods. If we find a bug here, we will fix it, but even then, it will not be fixed in Kudu, as that is not a deployment method that supports trigger synchronization. I have added a comment to another issue which would add that functionality to the Kudu workflow.

**Comment by vludax** [comment] 2018-03-05 20:59
@ConnorMcMahon The **name** of our Function App is 2e07f25e-308b-504a-950d-8b35f1a55136 (it's used for testing purposes). We have already changed the timer trigger to an HTTP trigger and made an Azure Scheduler call that function, which has been working reliably so far.

**Comment by ConnorMcMahon** [comment] 2018-03-05 21:15
@vludax, Thank you for sharing your function name despite this issue no longer affecting you. This will help us debug.

**Comment by ConnorMcMahon** [comment] 2018-03-05 23:31
@vludax, having looked into your function app, it looks like the last time your function triggers were synchronized was at the end of January (all that is present there is QueueTriggers). Even your most recent HTTP trigger is not present. You may be seeing success with your new approach if you are logged into the portal, which keeps alive your function app, even if the trigger has not been synchronized.

What looks to be your actual problem is your host.json. It has comments in it, which means that although your code was successfully deployed, our backend was not sent information about the new triggers. If you remove the comments from your host.json file and redeploy, then that should fix your problem with your new triggers not firing (whether the triggers are TimerTriggers or HttpTriggers).

**Comment by vludax** [comment] 2018-03-05 23:56
@ConnorMcMahon Oh, thank you for investigating! We'll remove the comments, but will keep the function triggered via HTTP for now. We'll give timer-triggered functions another go the next time we need such functionality.

It's interesting though that the HTTP function does get triggered, despite the comments in host.json. We don't keep the portal open, and only peeked at the function and scheduler logs a couple of times during the past two days -- both logs appear to be consistently successful.

**Comment by ConnorMcMahon** [comment] 2018-03-06 00:38
I have filed an issue [here](https://github.com/projectkudu/kudu/issues/2712) to make it so we are a little more lenient with that host.json file.

@vludax I suspect that our internal keep-alive logic for HttpTriggers is a little bit different than our keep-alive logic for TimerTriggers. At an HTTP request every 5 minutes, you function application was always kept alive, so even though the trigger was never synchronized, since your application was never recycled, that worked out fine. I recommend manually synchronizing once you remove the comments from host.json, because until your http trigger is synchronized, if your application is ever recycled, it may stop triggering on HTTP requests until the application is loaded up again.

I am going to close this issue for now, as the original post has been addressed, and we seem to have resolved the other issues that have come up here. If anyone has any issues with triggers not firing, your host.json is valid and the function was deployed using one of the supported methods detailed in this thread, please open up a new issue and we will investigate it there.

**Closed by ConnorMcMahon** 2018-03-06 00:38 UTC
Labels: needs-investigation

**Comment by jwisener** [comment] 2019-07-15 19:15
I don't understand why this was closed, as the original issue remains.

**Comment by ConnorMcMahon** [comment] 2019-07-15 19:27
@jwisener, I had diagnosed all of the failed synchronizations that occurred in this thread, and we filed various issues to make these failed synchronizations less likely, most of which have already been implemented. 

I have noticed you have recently been commenting on various issues related to trigger synchronization saying that you are having issues with it. Can you open a new ticket with explicit information so that we can investigate your specific case?

When you do so, please provide an application name (on the post or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), your deployment methods, and a timestamp (or multiple timestamps) of when the function failed to trigger properly.

That is the best way to get traction on the issue you are currently experiencing, as it may have a different root cause of these closed issues, and we can look at your specific case and determine if there are fixes to be made on our end.

**Comment by jwisener** [comment] 2019-07-15 19:56
Thank @ConnorMcMahon, 

My apologies, and thank you for the response. I was just a little frustrated trying to find what could be causing this. Seeing tickets open for since 2017 with similar issues, doesn't inspire much hope.

I guess being unable to view the logs in the scale controller, make it a bit difficult to trouble-shoot what is happening. I have been going thru all the various checks/logs, digging thru appinsight/logs and other github posts, and could not find anything. The automated azure function **"troubleshoot problems** reports everything is okay (#fail). So it's not easy find issues, especially if there is a "hidden" log that only microsoft can see. If ms could add the "scale controller failures" to the azure function app "logging" for me to see, it would probably allow me to discover what the issue is, without having to comment and ask on so many similar issues.

**Comment by ConnorMcMahon** [comment] 2019-07-15 21:21
No worries Jason, the frustration is understandable. We have made some improvements in these areas, but clearly there is still some customer pain we need to address.

We should definitely add some customer-facing detectors to detect when the scale controller fails to synchronize triggers. However, it is a bit tricky for us to detect when the user deployed a new trigger that hasn't synced yet if the deployment method does not support synchronization, as it's difficult to detect the _absence_ of a call to the SyncTriggers() API.

There are still a couple of options I see that could potentially improve user detection of these issues.

1. Expose a list of synched triggers to end-users in some way, shape or form, be that an API on the function application or a pane in the **troubleshoot problems** window. This way, developers can at least see if any of their triggers are missing.
2. Provide a best effort attempt to detect when the Functions runtime sees a function without a sync trigger, and expose that information in the **troubleshoot problems** pane.

I'll file an `improvement` issue against the Azure Functions repo.

**Comment by jwisener** [comment] 2019-07-15 21:53
Thank you @ConnorMcMahon  greatly appreciated. I think I have a theory what maybe happening.  We come from background of writing alot of .net core applications, and we have standardized the way we do our configuration settings for all our connections strings (blob, azure service, sql server, table storage, etc...) So, as we have ventured in to replacing our current webjobs, with azure functions. I used our standardized appsettings.json format. So I was able to put on the in the ServiceBusTrigger attribute something like ["ConnectionString:AzureServiceBus"].  And it works (at least initially). I guess I did not think about the other side what you refer to as the "scale controller", it is probably looking for an exact key name of "AzureWebJobsServiceBus" (which in my case I removed).

**Comment by ConnorMcMahon** [comment] 2019-07-16 18:27
@jwisener, That is good to know. I took a look at our Scale Controller logic for Service Bus and it LOOKS like it should be able to handle that scenario, though it is difficult to tell without testing it out myself with a real world example.

Thankfully, it turns out that we have recently exposed a way to view at least some of our Scale Controller logs to customers. It may not be a perfect solution, but it should reduce some of the opacity of our scale decisions.

Here is how it works:
Set SCALE_CONTROLLER_LOGGING_ENABLED to a string of the form <Type>:<Level>, where Type is either Blob or AppInsights (if app insights, AppInsights_INSTRUMENTATIONKEY should be set). Level is Verbose, Warning, or None (default is warning).

This will right to blobs on your default storage account or to your default App insights location. I don't know the exact paths of where they will right to, as this is an undocumented feature, but it should be something along the lines of `azure-functions-scale-controller`. Note that since this feature is undocumented, it may be rough around the edges, but it should help you debug some of your issues.

If you are still unable to diagnose your issue with these logs, I would recommend opening up a separate issue, with as much detail as you can provide, and we will help you diagnose the problem.

If you find this feature helpful (or unhelpful), please provide feedback, so we can improve it before we expose this more widely. Thanks for your patience, and I hope this helps.

**Comment by jwisener** [comment] 2019-07-16 19:09
@ConnorMcMahon  when you say of the form **:,**  what does that mean? do you Mean like this: 

SCALE_CONTROLLER_LOGGING_ENABLED:Blob ?

**Comment by ConnorMcMahon** [comment] 2019-07-16 19:16
Sorry, markdown formatting ruined that line. It should have said "a string of the form < Type >:< Level >". The app setting name will be SCALE_CONTROLLER_LOGGING_ENABLED, and the  value will look something like "Blob:Verbose".

**Comment by jwisener** [comment] 2019-07-16 19:21
Okay, let me try that.

**Comment by jwisener** [comment] 2019-07-16 20:04
when you say default storage account, is that the one defined in
the AzureWebJobsStorage appsetting?

**Comment by jwisener** [comment] 2019-07-16 21:24
I couldn’t get it to log anything. I think i am just going to have to open
a support ticket.

**Comment by ConnorMcMahon** [comment] 2019-07-17 00:01
Yes!

**Comment by rhichajambhale** [comment] 2019-08-14 10:46
### **Error for a time trigger azure function**
I have written a function to generate a pdf report using iTextSharp which uses system.drawing .

In this i am getting following prominent error:

[Error] : The type 'Matrix' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

I have included the same library also but the error persists. Please help. Please suggest.

**Comment by alrod** [comment] 2019-08-20 22:11
@rhichaj please create a separate issue in https://github.com/Azure/azure-functions-host/issues
