### ISSUE TITLE
Function Runtime tries to execute function that has compilation errors 

### ISSUE THREAD

**Issue by pratapprashant** [Azure/azure-functions-host#2439] opened 2018-02-21 08:21 UTC
I have an EventHub trigger function app. Everything works fine. But due to environment issue or deployment issues, my function app fails to compile. 
When my function code is failing to run, Function Runtime still reads messages from the EventHub, tries to execute my function and mark these messages from EventHub as processed (via checkpoint api). 

#### Investigative information

2018-02-21T06:40:55.148 [Info] Function started (Id=a2ea1702-3bf9-4351-9348-1fa662ac295b)
2018-02-21T06:40:55.164 [Error] Function compilation error
2018-02-21T06:40:55.164 [Error] run.csx(25,26): error CS0103: The name 'NLog' does not exist in the current context

#### Expected behavior 

If there are any compilation errors in function code, Function Runtime shouldn’t read messages from EventHub nor mark them as processed.

#### Repro steps

1. Create an EventHub trigger function app
2. Add NLog NuGet package
3. Add this line : var logger = NLog.LogManager.GetCurrentClassLogger();
4. Now push a message to EventHub (working condition)
5. Get the sequence number from the checkpoint data (from the storage blob)
6. Failing condition : in the project.json file change the NLog version to an unknown version. 
7. Change the version from  "NLog":"4.4.12" to  "NLog":"44.12"
8. Now push another message to EventHub
9. If you check the sequence number again, it will increase. But message from the EventHub didn’t get processed. 

#### Repro code

run.csx
`
public static void Run(string myEventHubMessage, TraceWriter log)
{
	var logger = NLog.LogManager.GetCurrentClassLogger();
}
`

working project.json
`
{
    "frameworks": {
        "net46": {
            "dependencies": {
                "NLog":"4.4.12"
            }
        }
    }
}
`
failing project.json
`
{
    "frameworks": {
        "net46": {
            "dependencies": {
                "NLog":"44.12"
            }
        }
    }
}
`

**Comment by paulbatum** [comment] 2018-02-21 19:30
We recognize that its easy to lose data due to this behavior but our recommendation is to separate dev/test/prod environments so that its impossible for you to deploy code that does not compile into production. That way you won't lose data.

**Comment by tobiasb** [comment] 2018-02-21 19:33
I'm disappointed that this got dismissed so quickly. The problem is not that their app didn't compile. That just serves as an easy to verify example of how the Azure Function event hub binding checkpoints too optimistically. I'm having the same issue where a bug in the Function runtime caused the function to not even be called and the message was lost. No try/catch or dev/test/prod environment can prevent that, only the way the event hub binding is developed can. This is a fundamental flaw in the event hub binding and disqualifies Functions for reliable event hub messaging scenarios.

**Comment by paulbatum** [comment] 2018-02-22 02:12
Apologies for being abrupt. Its a constant challenge to keep up with the volume filed against our repos and I have been trying to err on the side of short, fast responses rather than having issues sit for weeks with no response at all.

This bug as written is about the behavior when the function does not compile. Thats the main reason I closed it - I'm not convinced yet that it makes sense to implement special behavior around failed compilation. I'll reopen while we discuss.

We absolutely care about being able to implement reliable event hub processing workloads on functions. If you are encountering behavior where your function is not even executed and yet the checkpoint still occurs then please file an issue with the appropriate details as it needs to be investigated.

When it comes to error handling and event hubs, the main challenge is that the system always has to move forward. We deliberately avoided a design where one bad message that the function code is unable to process would halt all processing. Do you agree that this behavior would be seriously problematic for production systems? Perhaps you could clarify what you want the behavior to be.

**Comment by paulbatum** [comment] 2018-02-22 17:52
@tobiasb Retention policy doesn't help here, since its typically on the order of days. A significant proportion of Event Hubs workloads work in near real-time. Once there is a bad message on the event hub, you have to checkpoint past it or your real-time system sits idle for several days while you wait for the retention policy to delete the bad message. Even worse is the case when you have a single misbehaving client that is writing messages that your backend logic is failing to process successfully that are distributed throughout the event stream.  The answer for this is to let the error handling logic in your function put the bad message somewhere else and then continue execution.

That all said, the case that impacted you is relevant - if your function wasn't executed then any error handling logic you have didn't even run. Talking this through I do see that the same is true for a function that fails to compile.

Just thinking out loud right now - if the functions event hub processing logic only checkpointed if there was at least one successful execution within the batch, I think that would address the case that @pratapprashant ran into aswell as your case.. what do you think?

**Comment by tobiasb** [comment] 2018-02-26 20:33
What do you mean by "bad message".

It just feels wrong to put the responsibility of "checkpointing past it" on the Function runtime. Whatever a "bad message" is, it should not make the Function runtime fail. Why not let the Function determine if the message is "bad" and try/catch and successfully return the Function call?

**Comment by paulbatum** [comment] 2018-02-27 01:56
Some clarifications:
- By "bad message" I mean a message that is on the event hub that your function code deterministically fails to process successfully. For example, perhaps your function code throws a deserialization exception because the message was not written correctly.
- I agree, no message should make the function runtime itself fail

Regarding this:
> Why not let the Function determine if the message is "bad" and try/catch and successfully return the Function call?

Are you proposing that the runtime would only checkpoint a batch if every function execution for that batch completed successfully? If so, I have major issues with this along the lines of what I've explained above. If a customer forgets the try/catch, then their function will be "stuck" on that bad message, retrying it over and over. New messages on the event hub won't be processed until the bad message drops of the event hub due to the retention policy. In the meantime, customers in the consumption plan will be billed for all these failed executions. The bill will likely be very large. If we had this behavior, customers would ask us "why can't you implement the try/catch for us", and thats what functions does today. Please let me know if this does not make sense to you as its the key point underlying this conversation.

Thinking about what I proposed in my last reply:
> If the functions event hub processing logic only checkpointed if there was at least one successful execution within the batch....

Unfortunately this would have a similar problem in that if we don't checkpoint, then we'll retry with the same messages over and over and it will generate a huge amount of usage.

It could make sense to implement a feature where you configure an Event Hub triggered function with an "error event hub" that it writes the messages to when it fails. That would allow checkpointing to occur but the message that hit an error would still be waiting somewhere else to be processed. All messages would be automatically dumped to the "error event hub" in the case where the function does not compile. 

I am unable to think of a useful change we can make here that does not involve a second event hub.

**Comment by tobiasb** [comment] 2018-02-27 02:35
I'll see if I can escalate this because it would be extremely unfortunate if that would prevent us from using the Function event hub binding for reliable messaging.

> If a customer forgets the try/catch, then their function will be "stuck" on that bad message, retrying it over and over

That's how the `EventProcessorHost` works as well. 

I see where you're coming from but if the customer forgets a `try/catch` and is on a consumption plan and doesn't realize they aren't successfully processing messages, maybe they shouldn't be using Azure at all ;-)

**Comment by paulbatum** [comment] 2018-02-27 02:59
I am sorry but I can't find the humor in that. The consumption plan has significant adoption amongst cost conscious users and we generally regard any behavior that allows "runaway" billing as a bug. 

Perhaps we cannot reach agreement on what the default behavior should be, and we should be instead focusing on giving you the right settings so you can implement your scenario in the desired manner. 

Would a feature where you can specify a maximum number of retries of a function execution before it is abandoned address your need, if there is an ability to set that number to "infinite"?

**Comment by tobiasb** [comment] 2018-02-27 16:00
That might work, yes.

**Comment by paulbatum** [comment] 2018-02-27 17:41
I filed https://github.com/Azure/azure-webjobs-sdk/issues/1597 as thats where the eventhub binding currently lives, lets continue the discussion there.

As for this particular issue - I do not think we have any workable proposals around what behavior should occur for a function that does not compile that do not lead to infinite billing problems, so I'm closing it again.

**Closed by paulbatum** 2018-02-27 17:41 UTC
