### ISSUE TITLE
Support Slack (and other) WebHooks that use Content-Types other than application/json 

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#317] opened 2016-04-30 04:35 UTC
See SO post [here](https://stackoverflow.com/questions/36949436/handling-application-x-www-form-urlencoded-posts).

We need to finish the ASP.NET WebHooks Receiver support across the various Receivers to ensure all the permutations are supported. We need to generalize and robustify the Content-Type handling accross the Receivers.

**Comment by fabiocav** [comment] 2016-04-30 19:59
👍  The core work to make this happen is already in place. We need to make sure we have an issue open in the Portal repo since much of the work left is UI related. I have some samples using Kudu, Azure and a couple other WebHook receivers I can add to the templates repo as well.

**Comment by christopheranderson** [comment] 2016-05-02 17:18
Largely, I think the work to be done is to:

0. Confirm which Content-types we handle (application/json, x-www-form-urlencoded?, ...)
0. Create Portal UX (issue here is that we need to track which WebHooks need to be given a secret (ie. GitHub) and which ones we need to accept from the WebHook provider(Slack))
0. Make sure we build working examples for each WebHook we light up to test that we've got the right configuration - Slack is currently busted so I've filed an issue here to remove it from the portal: https://github.com/Azure/azure-webjobs-sdk-templates/issues/175

**Comment by christopheranderson** [comment] 2016-06-21 18:41
I think this likely meets the rc bar because it's a giant quality issue with our WebHooks. It might fall under should have because we've blocked the broken scenarios, but it's relatively low hanging fruit if we just do the investigation. I might be able to own this until the engineering work is documented (which recievers need which things - similar to the slack issue - https://github.com/Azure/azure-webjobs-sdk-script/issues/318)

**Comment by kfrancis** [comment] 2016-09-23 14:33
Really looking forward to this. Seems like a giant hole to not support other content types.

**Comment by kfrancis** [comment] 2016-12-15 14:38
Now that V1 has been announced, any idea when this might get discussed and/or implemented?

**Comment by simonaco** [comment] 2017-12-04 11:02
Is there any update on this issue? I can reproduce it in the latest version, javascript HttpTrigger functions.

**Comment by fabiocav** [comment] 2019-07-17 03:52
This work is not planned. Closing issue.

**Closed by fabiocav** 2019-07-17 03:52 UTC
Labels: improvement, needs-discussion
