### ISSUE TITLE
Cannot add 'function.proj' file/nuget packages to azure-functions

### ISSUE THREAD

**Issue by abinayasekar93** [Azure/azure-functions-host#4665] opened 2019-07-12 08:17 UTC
I need to add some nuget packages to the azure function. While trying to add a 'function.proj' file, getting an error as follows,

```
2019-07-12T07:52:13.177 [Information] System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
2019-07-12T07:52:13.177 [Information] at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
2019-07-12T07:52:13.903 [Information] at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
2019-07-12T07:52:13.904 [Information] at System.Environment.SetEnvironmentVariableCore(String variable, String value, EnvironmentVariableTarget target)
2019-07-12T07:52:13.904 [Information] at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-12T07:52:13.905 [Information] at Internal.Runtime.Augments.EnvironmentAugments.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-12T07:52:13.905 [Information] at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-12T07:52:13.905 [Information] at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-12T07:52:13.906 [Information] at Microsoft.DotNet.ShellShim.WindowsEnvironmentPath.AddPackageExecutablePathToUserPath()
2019-07-12T07:52:13.906 [Information] at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
2019-07-12T07:52:13.906 [Information] at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel, IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean hasSuperUserAccess, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider)
2019-07-12T07:52:13.907 [Information] at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
2019-07-12T07:52:13.907 [Information] at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
#### Investigative information

- Timestamp: 2019-07-12T07:52:48.560
- Function App version : 2.0
- Invocation ID: 0a370ad8-efcc-4e9a-8463-3041941b2877
- Region: West US
- Programming Language used: C#

#### Repro steps

Try to create a 'function.proj' file and add some nuget packages to it.

#### Expected behavior

After adding the above, nuget packages should get installed and show compilation succeeded message in the log.

#### Actual behavior

Throwing a "System.UnauthorizedAccessException: Attempted to perform an unauthorized operation." exception in the log.

**Comment by feresg** [comment] 2019-07-15 13:01
any solution?

**Comment by feresg** [comment] 2019-07-15 15:36
@abinayasekar93 I was able to solve this by, instead of writing the Azure function in the portal directly, creating it in Visual Studio, adding the NuGet package like any usual local project and publishing the function to Azure.

**Comment by ethanbayliss** [comment] 2019-07-16 03:43
@feresg Was there any additional files that Visual Studio uploaded in addition to the function.proj file that was already created?

**Comment by feresg** [comment] 2019-07-16 08:16
@ethanbayliss when writing the function inside Visual Studio then publishing to Azure instead of the portal, I can only access the function in read-only mode and the only visible file is function.json

**Comment by ethanbayliss** [comment] 2019-07-17 01:48
I've replicated this error on a new function and an existing function that was previously relying on nuget packages to work. Both functions were in different azure tenancies as well.

**Comment by abinayasekar93** [comment] 2019-07-17 05:48
> @abinayasekar93 I was able to solve this by, instead of writing the Azure function in the portal directly, creating it in Visual Studio, adding the NuGet package like any usual local project and publishing the function to Azure.

@feresg I am able to solve this by using Visual studio instead of Azure portal.

**Comment by hameno** [comment] 2019-07-17 09:27
Same problem here, trying to follow https://dotnetthoughts.net/resizing-images-using-azure-functions/ ans it fails with the same error

**Comment by mhoeger** [comment] 2019-07-17 22:45
@fabiocav and @brettsam - This issue is easy to reproduce, it feels like a regression?

```
2019-07-17T22:39:51.432 [Information] Restoring packages.
2019-07-17T22:39:51.451 [Information] Starting packages restore
2019-07-17T22:39:52.073 [Information] System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
2019-07-17T22:39:52.073 [Information] at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
2019-07-17T22:39:52.074 [Information] at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
2019-07-17T22:39:52.074 [Information] at System.Environment.SetEnvironmentVariableCore(String variable, String value, EnvironmentVariableTarget target)
2019-07-17T22:39:52.074 [Information] at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-17T22:39:52.075 [Information] at Internal.Runtime.Augments.EnvironmentAugments.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-17T22:39:52.075 [Information] at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-17T22:39:52.075 [Information] at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-17T22:39:52.075 [Information] at Microsoft.DotNet.ShellShim.WindowsEnvironmentPath.AddPackageExecutablePathToUserPath()
2019-07-17T22:39:52.076 [Information] at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
2019-07-17T22:39:52.076 [Information] at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel, IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean hasSuperUserAccess, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider)
2019-07-17T22:39:52.077 [Information] at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
2019-07-17T22:39:52.081 [Information] at Microsoft.DotNet.Cli.Program.Main(String[] args)
2019-07-17T22:39:52.124 [Information] Packages restored.
```

**Comment by fabiocav** [comment] 2019-07-17 22:58
If the steps on the docs are failing as described, yes, looks like a regression. Did you happen to see the specific operation that was restricted in the logs?

**Comment by abinayasekar93** [comment] 2019-07-18 13:46
> If the steps on the docs are failing as described, yes, looks like a regression. Did you happen to see the specific operation that was restricted in the logs?

@fabiocav There are no other specific information available in the logs except the above mentioned one.

**Comment by fabiocav** [comment] 2019-07-18 15:12
Sorry if that wasn’t clear, but that was a question for @mhoeger . E identified the issue yesterday and we’re investigating a solution. Will keep this issue open to track. Thanks again for reporting!

**Comment by mhoeger** [comment] 2019-07-18 15:52
@fabiocav - The message that popped up was "rejected file path access" for dotnet.exe, but it's not more specific beyond that!

**Comment by fabiocav** [comment] 2019-07-18 17:19
That, with the other details you've found, tells us what is happening. The .NET CLI is attempting to write to a read only location in recent releases, and that is causing the issue. We're working to get a fix out ASAP.

**Comment by fabiocav** [comment] 2019-07-18 17:54
While we work on a permanent fix, a known mitigation is to set the following app setting in your Function App:

Name: `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` 
Value: 1

Again, apologies for the issue. We'll have a permanent fix in place as soon as possible.

**Comment by soninaren** [comment] 2019-07-23 23:24
Fix has been checked-in and is being deployed as part of this release
https://github.com/Azure/app-service-announcements/issues/188

Please use https://github.com/Azure/app-service-announcements-discussions/issues/105 for discussions related to the release.

**Closed by soninaren** 2019-07-23 23:24 UTC
Labels: regression

**Comment by bombshot** [comment] 2019-09-30 13:26
I am trying to create azure function in Portal and even adding the project.json file with all the dependencies i am getting error : "the type or namespace name azure does not exist in the namespace microsoft". Anything i am missing??

**Comment by mhoeger** [comment] 2019-09-30 14:54
@bombshot - project.json is for V1 apps, is this a V2 app (if it's newly created, it will be)?
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#using-nuget-packages

**Comment by bombshot** [comment] 2019-10-04 17:00
@mhoeger - Yes, It's a V2 app. 
Issue is resolved, Thanks a lot 😊
