### ISSUE TITLE
Get Message Details with Python

### ISSUE THREAD

**Issue by HyP3r-** [Azure/azure-functions-host#2422] opened 2018-02-14 18:45 UTC
I'm working on a Azure Function which is triggered by the **Azure Event Hubs trigger**. As programming language I'm using Python 3.6. The problem is now that only the body of the message is passed to the python script by setting the envirorment variable to the path of the file which contains the message. But I need more information to process the message. Like they are displayed here:

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-query-language#routing-on-message-headers

#### Investigative information

Please provide the following:

- Timestamp: **2018-02-14**
- Function App version (1.0 or 2.0-beta): **1.0.11535.0**
- Function App name: **ds-bms-hub-gw** 
- Function name(s) (as appropriate): **gw-testing**

#### Repro steps

Provide the steps required to reproduce the problem:

I tried to follow this manual: https://github.com/yokawasa/azure-functions-python-samples/tree/master/eventhub-trigger-table-out-bindings

I thought I'm also able to access the **deviceId** like in the example. But the Client has to send this field as element in the body message. But the Azure IoT Hub and the Event Hub knows where the message came from. I don't have to send it inside the body.

#### Expected behavior

Provide a description of the expected behavior.

I thought I'm able to access the whole message, when I read the message file. But there is only the body.

**Comment by christopheranderson** [comment] 2018-02-15 20:02
This is not possible in Python v1, but will be possible in Python v2, which is currently in development. Closing this as "by design" for v1, and already addressed in v2 design.

**Closed by christopheranderson** 2018-02-15 20:02 UTC

**Comment by HyP3r-** [comment] 2018-02-16 12:02
Thank you for this information. Do you know the Release Date for the Version 2?
