### ISSUE TITLE
Can't use Task<unit> anymore

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-host#3171] opened 2018-07-24 07:41 UTC
The following F# code doesn't work anymore with latest 2.0.11933.0 (beta) runtime:

    module SendEMail
    
    open Microsoft.Azure.WebJobs
    open FSharp.Control.Tasks.ContextInsensitive
    open System.IO
    
    [<FunctionName("SendEMail")>]
    let Run([<QueueTrigger("sendmail")>] content:string, log: Host.TraceWriter) = task {
        log.Info(sprintf "Got message %A" mail)        
    }

This is basically returning a `System.Threading.Tasks.Task<unit>` to the runtime. This used to work in older runtime versions. Now we need to explicitly await this task.

    Function (SendEMail) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.SendEMail'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter '$return' to type Unit&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
Session Id: dd084db993414b2ba3d9e7eea6e73848

Timestamp: 2018-07-24T07:34:08.549Z
Region: Europe West
FunctionApp: ecarjobs

**Comment by forki** [comment] 2018-07-26 12:38
@fabiocav any info about this?

**Comment by forki** [comment] 2018-08-08 08:55
I think this is rather important since newcomers will run into this a lot.

**Comment by tforkmann** [comment] 2018-08-08 09:12
Hey there. Run into the same issue today. Any updates on that?

**Comment by forki** [comment] 2018-08-08 09:14
Just for documentation, the workaround is:

    [<FunctionName("SendEMail")>]
    let Run([<QueueTrigger("sendmail")>] content:string, log: Host.TraceWriter) = 
    let t = task {
        log.Info(sprintf "Got message %A" mail)        
    }
    t.Wait()

**Comment by isaacabraham** [comment] 2018-08-08 09:17
@forki why even bother with `task { }` if you're just going to synchronously `.Wait()` at the end :-)

**Comment by fabiocav** [comment] 2018-08-08 18:05
Sorry, we're in the middle of handling a large set of changes and have been heads down landing that, so I haven't had a chance to look at this yet, but I have a pretty good idea of what's causing it. Need to validate and address. Will update this with more information when I have it.

**Comment by forki** [comment] 2018-08-08 18:31
thanks!

Am Mi., 8. Aug. 2018 um 20:05 Uhr schrieb Fabio Cavalcante <
notifications@github.com>:

**Comment by tforkmann** [comment] 2018-09-04 13:53
Hi there, any updates on that?

**Comment by fabiocav** [comment] 2018-09-14 20:12
@tforkmann @forki this should now be fixed on the release we're rolling out (2.0.12095) . Validated this based on the provided code, but if you have a repro you want to share I'll run that as well.

**Comment by forki** [comment] 2018-09-15 06:36
Thanks. I will test it out.

Fabio Cavalcante <notifications@github.com> schrieb am Fr., 14. Sep. 2018,
22:12:

**Comment by forki** [comment] 2018-09-17 14:18
ok. it did not work. ;-(

**Comment by fabiocav** [comment] 2018-09-17 15:56
Can you share more details on your setup? The assumption here is that you are using the earlier pre-compiled model, with an entrypoint reference to your function method (as opposed to the model used by the VS tooling that provides the metadata generation based on the attributes). Is that the case? A simple repro (or at least a sample of your function.json file) would answer those questions.

**Comment by forki** [comment] 2018-09-17 16:19
No I'm using attribute based like in the sample code above

**Comment by fabiocav** [comment] 2018-09-17 16:34
With the code generator, correct? In other words, you have a reference to the functions SDK and your function.json has the `configurationSource` property set to `attributes`, right? If so, that would explain the disconnect

**Comment by fabiocav** [comment] 2018-09-17 16:39
Ok... that was helpful. I have a good repro now.

**Comment by fabiocav** [comment] 2018-09-17 16:44
And just to make sure, you've had this working before, with the same model? This logic is all down in the WebJobs SDK's function indexer, so I'm curious to understand whether this is a regression or just a difference scenario.

**Comment by forki** [comment] 2018-09-17 16:48
IIRC I had it working in old precompiled style. The one with explicit
functions.json

Fabio Cavalcante <notifications@github.com> schrieb am Mo., 17. Sep. 2018,
18:44:

**Comment by fabiocav** [comment] 2018-09-17 17:00
Yeah, that makes sense. That's the distinction. I see the issue in the core SDK, but that code has been like that for a while. At least the problem is now well understood. Will work on a fix.

**Comment by forki** [comment] 2018-11-15 08:51
ping

**Comment by fabiocav** [comment] 2018-11-16 00:59
Apologies for the delay on this! This is on my radar, but it has unfortunately been slipping. I'm bumping the priority on this to have it dona ASAP.

**Comment by fabiocav** [comment] 2019-02-04 19:52
@forki just realized this hadn't been updated, but the core fix for this was pulled into the runtime a couple of releases ago, so this should be resolved. Please let me know if you still have problems with this.

**Closed by fabiocav** 2019-02-04 19:52 UTC
