### ISSUE TITLE
fix worker indexing for dotnet-isolated scenarios

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#9178] opened 2023-03-23 19:58 UTC
It seems that this PR (#8900) broke dotnet-isolated with worker indexing (I ran into this while testing dotnet-isolated placeholders, which are relying on worker indexing to be fast)

It seems to boil down to this PR using the IWebHostRpcWorkerChannelManager (vs the IJobHost...) -- which means that when dotnet-isolated overwrites the worker config upon loading, it's not found -- that only happens in the JobHost

**Comment by fabiocav** [comment] 2023-04-26 20:13
@soninaren just went through a round of validation with the changes in 4.19 and that seems to be working as expected.

@soninaren can you please confirm and close if that is the case?

**Comment by fabiocav** [comment] 2023-04-26 20:34
Closing this as resolved. (Confirmed with @soninaren )

**Closed as completed by fabiocav** 2023-04-26 20:34 UTC
Labels: bug
