### ISSUE TITLE
Function app not triggered by blob

### ISSUE THREAD

**Issue by BKB503** [Azure/azure-functions-host#4500] opened 2019-05-28 12:53 UTC
#### Investigative information

Please provide the following:

- Timestamp:2019-05-25T01:29:20.935 (Last run)
- Function App version (1.0 or 2.0):V2
- Function App name:
- Function name(s) (as appropriate):TransferFile
- Invocation ID:931945c7-7059-45ac-a187-f2386f2c25f4 (After restarting) 
- Region:North Europe
I have provided the invocation Id after restarting the app it might be different before it is stalling 

#### Repro steps
Blog Trigger  for function app is queued but function app not picking up (in Production envt)

#### Expected behavior

Function app should trigger when new file is added in blob storage

#### Actual behavior

Function app is running but not able to trigger the blob events

#### Known workarounds

Restarting the function app it's picking all the queued events

#### Related information 

Provide any related information 

* Programming language used : C#

**Comment by ankitkumarr** [comment] 2019-06-21 02:16
@BKB503, I believe this might have been caused by a race condition we recently fixed -- https://github.com/Azure/azure-webjobs-sdk/issues/2194

The last Functions runtime update should have included the fix. I think it is rolling out this week. Closing the issue, please feel free to re-open if you continue to see any such issue.

**Closed by ankitkumarr** 2019-06-21 02:16 UTC
Labels: Needs: Triage :mag:
