### ISSUE TITLE
Investigate Functions Host test failures in V4 for 6/13/22 

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-host#8466] opened 2022-06-13 23:31 UTC
Investigate Functions Host test failures in V4 for 6/13/22 

For integration testing, we build the language workers, the Functions Host, and Core Tools. However, the Functions Host pipeline failed after 4 retries. Could you please take a look and let us know if this is regression? Thanks.

Here is the link to the pipeline executions with the test failures:

https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=75300&view=ms.vss-test-web.build-test-results-tab

![image](https://user-images.githubusercontent.com/12720858/173463847-b0d299c6-4191-4aa7-a6b1-afd2e4ac5d21.png)

**Comment by kshyju** [comment] 2022-06-13 23:43
Dupe of #8444

**Comment by Francisco-Gamino** [comment] 2022-06-13 23:50
Hi @kshyju -- Are there any plans to fix this test soon? Currently this is blocking integration testing. 

I can try to rerun the pipeline to see if passes the next time.

**Comment by RohitRanjanMS** [comment] 2022-06-14 04:04
https://github.com/Azure/azure-functions-host/pull/8468

**Closed as completed** 2022-06-14 04:04 UTC
