### ISSUE TITLE
Azure function V2 is not triggering on scheduled time with App service Plan

### ISSUE THREAD

**Issue by kinjalpgor** [Azure/azure-functions-host#4831] opened 2019-08-22 04:48 UTC
*Description*
Azure function  V2 is not triggering on scheduled time unless triggered manually or opened from the portal. and with App Service plan 

*C# language is used *

*Related information*
App Service plan: South Central US (App Service plan)

**Comment by AartBluestoke** [comment] 2019-08-23 02:38
@kinjalpgor is always on turned on?

**Comment by kinjalpgor** [comment] 2019-08-23 05:41
**Yes Always ON is turned on.**
Just to update, we discovered that the timer trigger is not triggering on scheduled time only if the Run method is synchronous. When I changed it to Asynchronous, the timer trigger is perfectly triggering.
If it is by design, then please update your official documentation.

**Comment by brettsam** [comment] 2019-08-23 14:42
That is not by design. Can you share what it looked like before/after your change? If you switch it back to synchronous, does it fail again?

Is it possible that your synchronous version was locking up and never completing? That would prevent subsequent invocations.

**Comment by kinjalpgor** [comment] 2019-08-26 10:08
Actually, due to internal commitments, I can't change that back as the code has been started to be used for the live environment. 

To answer your second question, the synchronous version was not getting triggered, so it never executed. Therefore, it never locked up.  And if I am not wrong, the trigger is independent of invocation right? How can an invocation affect other invocations? Isn't a new scope/instance of the azure function executed every time it triggers? (And if not, does it mean that one failed/locked-up invocation would result in non-triggering of consecutive ones?)

**Comment by brettsam** [comment] 2019-08-26 13:07
Timers are slightly different than other triggers. They will not run until the previous one is complete. Say you have a 1-second timer but the invocation takes 10 seconds -- we won't start the next invocation until the first one is done, even though it's off-schedule now.

Back to your original issue -- if you could share your Function App name (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), we can see if we find anything from the backend logs. Sharing the rough timeframe when you saw this would help as well.

**Comment by ThejaChoudary** [comment] 2020-08-03 13:46
@kinjalpgor closing this as answered based on the information above ,but please let us know if you have any additional questions.

**Closed by ThejaChoudary** 2020-08-03 13:46 UTC
Labels: Needs: Attention :wave:
