### ISSUE TITLE
Function returning an ActionResult not consistent with ASP.NET controller

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#4396] opened 2019-05-08 01:02 UTC
The HTTP response received from a function that returns an `ActionResult<string>` does not look correct. Specifically it looks like functions is treating the ActionResult like a poco. The same is probably true for other cases of `ActionResult<T>`.

#### Repro steps

Create and run the following function in a V2 function app:

```csharp
    public static class Function1
    {
        [FunctionName("Function1")]
        public static string Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "values")] HttpRequest req,
            ILogger log)
        {
            return "value1";
        }
    }
```

#### Expected behavior

Assuming the function was executed with no accept header, the response should look like this:

```
HTTP/1.1 200 OK
Date: Wed, 08 May 2019 00:52:23 GMT
Content-Type: text/plain; charset=utf-8
Server: Kestrel
Content-Length: 6

value1
```

#### Actual behavior

The response is as follows:

```
HTTP/1.1 200 OK
Date: Wed, 08 May 2019 01:00:10 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Content-Length: 32

{"result":null,"value":"value1"}
```

**Comment by fernandreu** [comment] 2019-05-28 22:45
I just had this same issue and, just in case it helps somebody else, I made my own workaround by implementing my own class with the exact same contents of `ActionResult<T>` but implementing `IActionResult` as well. The idea is to replace every occurrence of the standard `ActionResult<T>` class with the new one and, once this issue gets fixed, revert back the changes.

I could have simply derived it from `ActionResult<T>`, but unfortunately the latter is a sealed class. Instead, I took the official implementation from [here](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ActionResultOfT.cs) as reference.

The resulting class looks like this (relevant changes highlighted in **bold**):

<pre>
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace MyProject
{
    public sealed class MyActionResult&lt;TValue&gt; : IConvertToActionResult<b>, IActionResult</b>
    {
        public MyActionResult(TValue value)
        {
            if (typeof(IActionResult).IsAssignableFrom(typeof(TValue)))
            {
                var error = $"Invalid type parameter '{typeof(TValue)}' specified for ActionResult&lt;T&gt;";
                throw new ArgumentException(error);
            }

            this.Value = value;
        }

        public MyActionResult(ActionResult result)
        {
            if (typeof(IActionResult).IsAssignableFrom(typeof(TValue)))
            {
                var error = $"Invalid type parameter '{typeof(TValue)}' specified for ActionResult&lt;T&gt;";
                throw new ArgumentException(error);
            }

            this.Result = result ?? throw new ArgumentNullException(nameof(result));
        }

        public ActionResult Result { get; }

        public TValue Value { get; }

        public static implicit operator MyActionResult&lt;TValue&gt(TValue value)
        {
            return new MyActionResult&lt;TValue&gt(value);
        }

        public static implicit operator MyActionResult&lt;TValue&gt(ActionResult result)
        {
            return new MyActionResult&lt;TValue&gt(result);
        }

        IActionResult IConvertToActionResult.Convert()
        {
            return this.Result ?? new ObjectResult(this.Value)
            {
                DeclaredType = typeof(TValue),
            };
        }

        <b>public async Task ExecuteResultAsync(ActionContext context)
        {
            await ((IConvertToActionResult) this).Convert().ExecuteResultAsync(context);
        }</b>
    }
}
</pre>

**Comment by alrod** [comment] 2019-06-26 20:15
PR is merged

**Closed by alrod** 2019-06-26 20:15 UTC
Labels: bug, needs-investigation

**Comment by asasine** [comment] 2019-09-09 03:55
I am also facing this issue with a new project created today. How can I update my project to get the expected behavior above?

**Comment by paulbatum** [comment] 2019-09-09 17:42
@fabiocav Was this implemented as a featureflag for compat concerns? Should we be considering a change in the default behavior in the next major version?

**Comment by fabiocav** [comment] 2019-09-09 18:00
Yes, this was put behind a flag as this would be a potential breaking change to customers in production.

I've created https://github.com/Azure/azure-functions-host/issues/4907 to track the work to make this the default behavior in 3.0

**Comment by asasine** [comment] 2019-09-09 18:01
Jumping back in to confirm that adding the application setting `AzureWebJobsFeatureFlags` with value `EnableActionResultHandling` to your remote Azure Functions Application Settings, it will enable the new behavior while running remotely.
