### ISSUE TITLE
Add support for AzureWebJobsSecretStorageType=none

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#5922] opened 2020-04-28 02:51 UTC
For customers not using AzureWebjobsStorage / AzureWebJobsSecretStorageSas there is no where to store function/host keys. This causes failures anytime an attempt is made to access secrets, e.g., during synctriggers, secrets management admin APIs, etc.

Proposal is to support AzureWebJobsSecretStorageType=none, For apps using this configuration we will not generate or persist any keys.

Instead all authentication will be based on jwt tokens based on AzureWebEncryptionKey.

@mathewc / @balag0 for additional details.

**Comment by fabiocav** [comment] 2021-02-17 21:42
Work currently in progress. Moving to sprint 96

**Comment by mathewc** [comment] 2021-02-17 21:51
@balag0  - can you remind me what the source of this work item was? Are customers running into this? Definitely if we have codepaths that are accessing secrets (e.g. admin keys APIs, synctriggers) and not failing gracefully in absence of a secrets repository we should address that.

**Comment by fabiocav** [comment] 2021-02-17 22:35
@mathewc I believe this is for static web apps.

**Comment by balag0** [comment] 2021-02-18 07:40
Correct. It is for SWA. + @anthonychu as well who is tracking other related requirements around this scenario.

**Comment by anthonychu** [comment] 2021-02-19 01:54
Yes this is the issue: https://github.com/Azure/static-web-apps/issues/165

It’s because BlueRidge apps don’t have storage accounts. @annaji-msft can provide more details.

This is quite common because folks are using a function as the callback for external auth providers and they pass a token in the query string with the name `code`.

**Comment by anthonychu** [comment] 2021-02-19 01:58
The desired outcome is if no AzureWebJobsStorage and the http function has authLevel anonymous, requests with `code=` in the query string should work, and the parameter value is accessible in the function.

**Comment by fabiocav** [comment] 2021-04-14 20:31
Moving to next sprint as this work has not started yet.

FYI @anthonychu

**Comment by fabiocav** [comment] 2021-06-09 20:36
@anthonychu an update on this issue; @kashimiz has the initial set of changes and is iterating with additional people prior to opening a PR. We expect this to be done at the beginning of 104.

**Comment by fabiocav** [comment] 2021-07-07 20:25
@kashimiz should this be moved to 106?

**Comment by kashimiz** [comment] 2021-07-12 22:25
@fabiocav Yes, we should move this to 106.

**Comment by fabiocav** [comment] 2021-08-04 20:37
@kashimiz leaving this in 106 pending an update. Let me know if this needs to move.

**Comment by fabiocav** [comment] 2022-01-05 21:38
Moving this to sprint 116 as we still have open discussions on this.

/cc @mathewc @kashimiz

**Comment by fabiocav** [comment] 2022-01-20 21:34
@kashimiz has opened a PR that leverages some work done by @mathewc and reduces the priority of this issue. We'll still track this as a future enhancement, which will be addressed in the current sprint, but with the approach in the linked PR, the issue is addressed for SWA.

**Comment by fabiocav** [comment] 2022-03-02 21:24
PR for this is out and being iterated on. Moving to 118.

**Closed as completed** 2022-03-25 17:53 UTC
