### ISSUE TITLE
"Value cannot be null" error when AzureWebJobsStorage is missing for output binding

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-functions-host#4810] opened 2019-07-29 16:21 UTC
```
func --version
2.7.1480
```

### Repro steps:
1. Create a new project (language shouldn't matter, but I did JS)
1. Add an http trigger
1. Add a Cosmos DB output binding to that trigger
1. Make sure extension bundle is set in host.json
1. Make sure AzureWebJobsStorage is _not_ set in local.settings.json

### Expected:
A readable error message saying `AzureWebJobsStorage` needs to be set. Honestly I would expect this to be the same error message that occurs if you have a Cosmos DB trigger (instead of output binding) without `AzureWebJobsStorage` set. That error is much better.

### Actual:
Error message:
```
Value cannot be null.
Parameter name: provider
```

_originally brought up by @askpatrickw in https://github.com/microsoft/vscode-azurefunctions/issues/1403#issuecomment-515238736_

**Comment by FinVamp1** [comment] 2019-08-20 10:58
Related User Feedback here. https://feedback.azure.com/forums/355860/suggestions/38202586

**Comment by mhoeger** [comment] 2020-06-23 01:24
I can't repro this in later versions of the core tools and I'm not sure if this is actually related to the missing AzureWebJobsStorage setting.

Here is the behavior in core tools version 2.7.1480:
```
[6/23/2020 1:04:49 AM] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at C:\Users\mahoeger\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle
[6/23/2020 1:04:49 AM] Found a matching extension bundle at C:\Users\mahoeger\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
Value cannot be null.
Parameter name: provider
Application is shutting down...
```

Behavior in core tools version 2.7.2508:
```
[6/23/2020 1:03:24 AM] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at C:\Users\mahoeger\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle
[6/23/2020 1:03:24 AM] Found a matching extension bundle at C:\Users\mahoeger\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
[6/23/2020 1:03:24 AM] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[6/23/2020 1:03:24 AM] Skipping bundle download since it already exists at path C:\Users\mahoeger\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
[6/23/2020 1:03:24 AM] Loading Extention bundle from C:\Users\mahoeger\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
[6/23/2020 1:03:24 AM] Loading startup extension 'CosmosDB'
```

Again, hard to know because it's a generic error message, but I think we can close this as resolved. At the very least, I am unable to repro with the repro steps given and should close this until we reproduce on the latest versions

**Comment by mhoeger** [comment] 2020-06-23 01:28
@soninaren - I'm wondering if you might have been the one to fix this issue? it seems like the error might have been related to the bundles path

**Comment by mhoeger** [comment] 2020-06-23 18:56
Closing as resolved in latest versions. Please re-open with updated repro steps if this happens again!!

**Closed by mhoeger** 2020-06-23 18:56 UTC
Labels: P1, Supportability, error-message-improvement
