### ISSUE TITLE
[HttpWorker]Unable to connect to GO HttpWorker on linux consumption

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5696] opened 2020-02-24 17:13 UTC
@asw101 reported issue with Go HttpWorker on linux consumption.

Repro: https://github.com/Azure-Samples/functions-custom-handlers/tree/master/go

**Comment by pragnagopa** [comment] 2020-02-24 17:14
tagging @anthonychu in case he tried httpWorker on linux consumption.

**Comment by pragnagopa** [comment] 2020-02-27 19:19
cc @divyagandhii 
Verified on linux dedicated. It works as expected. The issue is scoped to linux consumption. Needs more investigation

Note: Built go binary for linux amd64 : https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04 using command
```
set GOOS=linux
set GOARCH=amd64
go build <gofile>.go
```

**Comment by divyagandhii** [comment] 2020-02-28 22:40
```
 MS_FUNCTION_LOGS 5,divya_sub,httpworkergotest2,,,Worker.HttpWorkerChannel.0f3dccc3-5430-4b5c-8398-40966eecb85b,"","Initiating Worker Process start up",2.0.12969.0,02/28/2020 10:17:45.856 PM,,"",,78b99ab3-8c6f-4d87-b548-3fdbc4f6e759,,7017E215-637185248327495453,divyameshrptest,ee591b04a6464cf1ba52b94b8c683a6f
2020-02-28T22:17:45.8745231Z stdout F [40m[32minfo[39m[22m[49m: Worker.HttpWorkerProcess.0f3dccc3-5430-4b5c-8398-40966eecb85b[0]
2020-02-28T22:17:45.8745231Z stdout F       Starting worker process:/home/site/wwwroot/helloworldServer  --workerId 0f3dccc3-5430-4b5c-8398-40966eecb85b --port 43997
2020-02-28T22:17:45.8745231Z stdout F MS_FUNCTION_LOGS 4,divya_sub,httpworkergotest2,,,Worker.HttpWorkerProcess.0f3dccc3-5430-4b5c-8398-40966eecb85b,"","Starting worker process:/home/site/wwwroot/helloworldServer  --workerId 0f3dccc3-5430-4b5c-8398-40966eecb85b --port 43997",2.0.12969.0,02/28/2020 10:17:45.859 PM,,"",,78b99ab3-8c6f-4d87-b548-3fdbc4f6e759,,7017E215-637185248327495453,divyameshrptest,ee591b04a6464cf1ba52b94b8c683a6f
2020-02-28T22:17:45.875513Z stdout F MS_FUNCTION_AZURE_MONITOR_EVENT 4,httpworkergotest2.divyameshrptest.antares-test.windows-int.net,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'message':'Starting worker process:/home/site/wwwroot/helloworldServer  --workerId 0f3dccc3-5430-4b5c-8398-40966eecb85b --port 43997','category':'Worker.HttpWorkerProcess.0f3dccc3-5430-4b5c-8398-40966eecb85b','hostVersion':'2.0.12969.0','hostInstanceId':'78b99ab3-8c6f-4d87-b548-3fdbc4f6e759','level':'Information'}",7017E215-637185248327495453,ee591b04a6464cf1ba52b94b8c683a6f,2/28/20 10:17:45 PM
2020-02-28T22:17:45.9490764Z stdout F [41m[30mfail[39m[22m[49m: Worker.HttpWorkerProcess.0f3dccc3-5430-4b5c-8398-40966eecb85b[0]
2020-02-28T22:17:45.9490764Z stdout F       Failed to start Worker Channel
2020-02-28T22:17:45.9490764Z stdout F System.ComponentModel.Win32Exception (13): Permission denied
2020-02-28T22:17:45.9490764Z stdout F    at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
2020-02-28T22:17:45.9490764Z stdout F    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
2020-02-28T22:17:45.9490764Z stdout F    at System.Diagnostics.Process.Start()
2020-02-28T22:17:45.9490764Z stdout F    at Microsoft.Azure.WebJobs.Script.Workers.WorkerProcess.StartProcessAsync() in /src/azure-functions-host/src/WebJobs.Script/Workers/ProcessManagement/WorkerProcess.cs:line 51
```

**Comment by divyagandhii** [comment] 2020-02-28 22:40
The functions host is not able to connect to a random port on linux consumption due to insufficient permissions.

**Comment by craigshoemaker** [comment] 2020-03-17 11:47
We need to make sure to update [the doc](https://docs.microsoft.com/azure/azure-functions/functions-custom-handlers) once this bug is fixed.

**Comment by fabiocav** [comment] 2020-03-18 20:23
Moving this to sprint 72 to continue investigation.

**Comment by bketelsen** [comment] 2020-03-19 14:51
subscribing, this is important.

**Comment by pragnagopa** [comment] 2020-03-20 17:50
Similar issue reported here: https://stackoverflow.com/questions/58698095/how-to-launch-puppeteersharp-on-server-ubuntu-18-04-3-lts-system-componentmodel

**Comment by pragnagopa** [comment] 2020-03-20 20:32
@fabiocav - Leaving this issue in the current sprint as this is an investigation.

**Comment by pragnagopa** [comment] 2020-03-25 19:10
Thanks @ahmelsayed for helping with identifying the root cause. 
Executable/binary provided by the user does not have "executable" permission when running in linux consumption as these permissions are removed when extracting and assigning user content to a function app.

Workaround:
- Build binary on linux and ensure right permissions are assigned to the http worker binary
- On linux consumtion function app, set app setting: `WEBSITE_MOUNT_ENABLED` to `1`.

@craigshoemaker  - can you please update the docs to reflect the work around?

Proposed fix:
- Run command to give all the files in users app content  folder 'executable' permissions during specialization. Similar approach to: https://github.com/Azure/azure-functions-host/blob/20bb9149954eed2e6428f47ecc33867df8683a19/src/WebJobs.Script.WebHost/Management/InstanceManager.cs#L487

This will unblock other scenarios apart from http worker where users need to launch executables from function app.

**Comment by anthonychu** [comment] 2020-03-28 23:51
Confirmed that workaround is working. Thanks.

**Closed** 2020-03-31 00:28 UTC
Labels: httpWorker

**Comment by anthonychu** [comment] 2020-04-06 20:24
@pragnagopa @divyagandhii Do we have any documentation on `WEBSITE_MOUNT_ENABLED`, like when is it typically used (outside of the context of this workaround)? @asw101 and I are trying to understand what it's doing.

**Comment by balag0** [comment] 2020-04-06 22:07
If the file pointed to by WEBSITE_RUN_FROM_PACKAGE is a squashfs file, it will be mounted to the container by default. Setting WEBSITE_MOUNT_ENABLED = 0 will extract the file instead of mounting it.

If the file pointed to by WEBSITE_RUN_FROM_PACKAGE is a zip file, it will be extracted inside the container by default. Setting WEBSITE_MOUNT_ENABLED = 1 will force mount the file instead of extracting it.

The appsetting is only applicable in Linux consumption.
