### ISSUE TITLE
x64 V3 - Sporadic OutOfMemoryException when publishing to Azure

### ISSUE THREAD

**Issue by hallidev** [Azure/azure-functions-host#5349] opened 2019-12-07 18:59 UTC
Most times (but not every time), publishing my functions to Azure leaves every function throwing an OutOfMemoryException. After extensive troubleshooting a few days back, I called it a night. When I took a lot in the morning, everything was running fine. It essentially fixed itself at some point.

After some more testing, my "regular" experience is that after publishing from Visual Studio 2019 (Version 16.4, Zip Deploy), I have to wait up to 30 minutes before the functions all suddenly spring to life after throwing OutOfMemoryExceptions.

I have the same set of functions running in a production environment (different resource group), and although it doesn't happen nearly as frequently in production, I have had it happen several times. The main difference is that in production, I'm deploying to a deployment slot and swapping to production. This seems to be more reliable.

#### Investigative information

Please provide the following:

- Timestamp: 2019-12-07T18:46:09.494Z
- Function App version (1.0 or 2.0): 3.0 (Preview)
- Function App name: CavFunctions-Dev
- Function name(s) (as appropriate): CalculateUserContributorPointsFunction
- Invocation ID:
- Region: East US

#### Repro steps

Provide the steps required to reproduce the problem:

1: From Visual Studio 2019 (16.4), perform Azure Zip Deploy publish

#### Expected behavior

Functions run in Azure

#### Actual behavior

Functions throw OutOfMemoryException for up to 30 minutes

#### Known workarounds

Wait for functions to start working

#### Related information 

Provide any related information 

* Programming language used: C#

**Comment by hallidev** [comment] 2019-12-10 14:57
This appears to be fixed when switching from AzureFunctionsVersion v3-preview to v3

**Comment by FabienLavocat** [comment] 2019-12-23 19:02
I'm still seeing that problem on v3.0 functions. 
Runtime version: 3.0.12939.0
Region West US 2
App written in .net core 3.1 with a ServiceBusTrigger

This is the stack I receive from ApplicationInsights:

```
System.OutOfMemoryException:
   at System.String.CreateStringFromEncoding (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Text.UTF8Encoding.GetString (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at ProtoBuf.ProtoReader+StreamProtoReader.ImplReadString (protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net.Core\ProtoReader.Stream.csprotobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 337)
   at ProtoBuf.ProtoReader+State.ReadString (protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net.Core\ProtoReader.State.ReadMethods.csprotobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 550)
   at proto_2 (DotNetTI.BreakingChangeAnalysis, Version=1.0.5.0, Culture=neutral, PublicKeyToken=null)
   at ProtoBuf.Internal.Serializers.SimpleCompiledSerializer`1.ProtoBuf.Serializers.ISerializer<T>.Read (protobuf-net, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net\Internal\Serializers\CompiledSerializer.csprotobuf-net, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 91)
   at ProtoBuf.ProtoReader+State.ReadMessage (protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net.Core\ProtoReader.State.ReadMethods.csprotobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 938)
   at ProtoBuf.ProtoReader+State.ReadRepeatedCore (protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net.Core\ProtoReader.State.ReadMethods.csprotobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 215)
   at ProtoBuf.ProtoReader+State.FillBuffer (protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net.Core\ProtoReader.State.ReadMethods.csprotobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 281)
   at ProtoBuf.Serializers.RepeatedSerializer`2.ReadRepeated (protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net.Core\Serializers\RepeatedSerializer.csprotobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 265)
   at ProtoBuf.Serializers.RepeatedSerializer`2.ProtoBuf.Serializers.IRepeatedSerializer<TCollection>.ReadRepeated (protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net.Core\Serializers\RepeatedSerializer.csprotobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 251)
   at ProtoBuf.ProtoReader+State.ReadAny (protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net.Core\ProtoReader.State.ReadMethods.csprotobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 978)
   at ProtoBuf.ProtoReader+State.<ReadAsRoot>g__ReadFieldOne|100_0 (protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net.Core\ProtoReader.State.ReadMethods.csprotobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 1044)
   at ProtoBuf.ProtoReader+State.ReadAsRoot (protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net.Core\ProtoReader.State.ReadMethods.csprotobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 1032)
   at ProtoBuf.ProtoReader+State.DeserializeRoot (protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net.Core\ProtoReader.State.ReadMethods.csprotobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 1006)
   at ProtoBuf.Serializer.Deserialize (protobuf-net, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67protobuf-net, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: C:\projects\protobuf-net\src\protobuf-net\Serializer.Deserialize.csprotobuf-net, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67: 19)
   at DotNetTI.BreakingChangeAnalysis.BreakingChangeReportGenerator..ctor (DotNetTI.BreakingChangeAnalysis, Version=1.0.5.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService.LogBreakingChangeReport (Microsoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-functions-host\src\WebJobs.Script.WebHost\BreakingChangeAnalysis\ChangeAnalysisService.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 132)
   at Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService+<TryLogBreakingChangeReportAsync>d__12.MoveNext (Microsoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-functions-host\src\WebJobs.Script.WebHost\BreakingChangeAnalysis\ChangeAnalysisService.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 105)

```

**Comment by hallidev** [comment] 2019-12-23 20:23
I closed this prematurely it turns out. I’m still seeing it on 3.1 and just this morning deleted my Consumption function app and just redeployed as a regular app service. The regular app service seems to be running reliably

**Comment by Smoovsky** [comment] 2020-01-19 03:01
> I closed this prematurely it turns out. I’m still seeing it on 3.1 and just this morning deleted my Consumption plan and redeployed as a regular app service plan. The regular app service plan seems to be running reliably.

Same behavior here, spent a lot of time to debug as well.
However, the metric of app service indicates memory consumption is all good,

**Comment by pragnagopa** [comment] 2020-01-28 23:05
Root cause issue tracked here: https://github.com/Azure/azure-functions-host/issues/5430
Closing this issue as dup,

**Closed by pragnagopa** 2020-01-28 23:05 UTC
