### ISSUE TITLE
Runtime error on Azure portal: Could not load file or assembly 'Microsoft.Azure.WebJobs.ServiceBus, version =4.1.0.0

### ISSUE THREAD

**Issue by nishantsny** [Azure/azure-functions-host#5537] opened 2020-01-24 22:53 UTC
I created a new `ServiceBusTrigger` functions and deployed it to the portal. The function works perfectly fine locally, but does not start in the portal with this error:

```
2020-01-24T22:38:54.416 [Error] A host error has occurred during startup operation '66d7c4aa-4a16-434e-abf7-3a07e9ce03b9'.
System.IO.FileLoadException : Could not load file or assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) ---> System.IO.FileLoadException : Could not load file or assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

There are the Micrsoft.azure.* packages in my csproj file.
```
    <PackageReference Include="Microsoft.Azure.KeyVault" Version="3.0.3" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.2.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.1.3" />
```

Any help is appreciated.

**Comment by mhoeger** [comment] 2020-01-24 23:37
@nishantsny - What version are you using (V1/V2/V3) and how are you deploying?
Could you also share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by mhoeger** [comment] 2020-01-25 00:46
Adding details - this app does not have a host.json file. Sometimes, the app runs correctly with:
```
Empty host configuration file found. Creating a default host.json file.
```
Other times, we see: 
```
Host configuration file read:
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}
```

**Comment by nishantsny** [comment] 2020-01-25 00:47
The mitigation was to have a non-empty `hosts.json` file

```
{ 
   "version": "2.0"
}
```

**Comment by mhoeger** [comment] 2020-01-28 00:51
In this case in particular, a host.json existed with 
```
{}
```

An empty or non-existent host.json can be problematic because referencing extensionBundles in a pre-compiled (.dll) .NET project can be problematic. cc: @soninaren to investigate this issue.

Another issue is why the customer sometimes saw their function app working. I think it's because in InitializeHostConfig, we [GetDefaultHostConfigObject here](https://github.com/Azure/azure-functions-host/blob/8a2368ff36c3831079f236d37879761da08ed29c/src/WebJobs.Script/Config/HostJsonFileConfigurationSource.cs#L167) if the found host config object has no values. The problem is the default host config is only assigned in the wrong scope, although it is written (for future invocations). I think that's why it would work once on the dedicated machine, but then future instances (with the file written) would fail. cc: @brettsam in case I'm misunderstanding something about the GetDefaultHostConfigObject code I linked to

**Comment by soninaren** [comment] 2020-02-03 19:55
part of the fix has been checked in this PR https://github.com/Azure/azure-functions-host/pull/5580
@mhoeger let me know if we need any thing else to close this issue.

**Closed** 2020-02-03 22:33 UTC
Labels: Needs: Attention :wave:
