### ISSUE TITLE
EntryPointNotFoundException with Autofac

### ISSUE THREAD

**Issue by Inspyro** [Azure/azure-functions-host#2979] opened 2018-06-11 07:25 UTC
Describe the bug
When referencing Autofac in an old version in a referenced project of the function app, and referecing a newer version of Autofac in the function app via nuget we get an EntryPointNotFoundException that is rather strange.

To Reproduce
Use the attached repro sample, Press F5 to debug the function app -> see the EntryPointNotFoundException
[FunctionApp1_Repro.zip](https://github.com/Azure/azure-functions-host/files/2089009/FunctionApp1_Repro.zip)

Expected behavior
No Exception is thrown and the function succeeds

Environment summary
Visual Studio 2017 (15.7.3), Windows 10 1703, .NET 47, Azure CLI Tools 1.0.12.1

Additional context
The error seems to be related to using multiple versions of a nuget package in different projects.

**Comment by LeastOne** [comment] 2018-06-12 01:15
Confirmed. Encountering the same problem attempting to integrate Autofac 4.8.1 in a Azure Function v2 project targeting netstandard2.0.

**Comment by paulbatum** [comment] 2018-06-13 18:27
Can you give us a repro against V2? We probably won't be able to address for V1.

**Comment by fabiocav** [comment] 2018-07-10 22:15
@LeastOne do you still have issues with V2? Can you please share a repro or more details so we can investigate? The original issue here is with a V1 app.

@Inspyro, as Paul mentioned, it is unlikely this would be addressed in V1, but the root of the problem is within your reference mismatches. You also have dependencies on two different major versions. Aligning those references should address the issue.

**Closed by fabiocav** 2018-07-10 22:15 UTC
Labels: assembly-load
