### ISSUE TITLE
System.IO.FileLoadException when running function ("Microsoft.IdentityModel.Tokens")

### ISSUE THREAD

**Issue by craig006** [Azure/azure-functions-host#2440] opened 2018-02-21 16:47 UTC
Invocation ID: 4a8b83e2-2ad0-4f70-a13b-c41295cf6f17
Timestamp: 2018-02-21T16:25:54.224
Function App version (1.0 or 2.0-beta): 2.0-beta

#### Repro steps

Create a .net core project that contains the function to run.

Add package reference to project like below:
`<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="5.2.1" />`

Call a method that uses the above package and its dependancies. 

<details>
<summary>Example method</summary>

```csharp
public string CreateJWTToken(ClaimsIdentity identity)
{
    string _algorithm = "http://www.w3.org/2001/04/xmldsig-more#hmac-sha256";
    string _digest = "http://www.w3.org/2001/04/xmlenc#sha256";
    var symmetricKey = Encoding.UTF8.GetBytes("<somekey>");
    var securityKey = new SymmetricSecurityKey(symmetricKey);
    var credentials = new SigningCredentials(securityKey, _algorithm, _digest);

    var tokenDescriptor = new SecurityTokenDescriptor();
    tokenDescriptor.Subject = identity;
    tokenDescriptor.Issuer = "";
    tokenDescriptor.Audience = "";
    tokenDescriptor.SigningCredentials = credentials;

    var tokenHandler = new JwtSecurityTokenHandler();
    var token = tokenHandler.CreateToken(tokenDescriptor);
    return tokenHandler.WriteToken(token);
}
```
</details>

#### Expected behavior

Assembly resolved and jwt token created successfully

#### Actual behavior

Exception is thrown:
System.IO.FileLoadException

Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)

#### Known workarounds
None

#### Related information 

1. This fails both on my local functions host and when running in Azure. 
2. I have inspected the bin folder in both cases and the assembly exists there right along side my application dll.
3. I have tried to recreate in a .net core console app and all work well there.

Provide any related information 

* Programming language used 
C#

<details>
<summary>Binding</summary>

```json
{
  "generatedBy": "Microsoft.NET.Sdk.Functions.Generator-1.0.8",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "httpTrigger",
      "route": "Authenticate",
      "methods": [
        "post"
      ],
      "authLevel": "anonymous",
      "name": "request"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/MyProject.dll",
  "entryPoint": "MyProject.Functions.AuthenticateFunction.Run"
}
```
</details>

**Comment by craig006** [comment] 2018-03-04 11:43
Does anyone know if this is perhaps something I could fix on my side? Or is it something that will just not work until the next release?

**Comment by fabiocav** [comment] 2018-03-05 19:18
@craig006 I'll provide an update once I take a look at this. The issue is assigned to the current sprint.

**Comment by craig006** [comment] 2018-03-07 06:56
@fabiocav Thanks a million man. That would be awesome!

**Comment by paulbatum** [comment] 2018-04-04 20:15
@fabiocav hi ;)

**Comment by kaushik-hemant** [comment] 2018-04-30 10:56
@paulbatum Any update on that?

**Comment by pizerg** [comment] 2018-05-11 10:25
I'm running into the same issue with Microsoft.IdentityModel.Tokens Version="5.2.2"

**Comment by anthonychu** [comment] 2018-05-14 05:08
Having the same issue while writing a binding extension. Also had to downgrade to 5.1.4. Thanks @pizerg for the workaround. Any updates, @fabiocav? Thanks.

**Comment by fabiocav** [comment] 2018-05-22 03:01
Sorry about the delay on this. 

There has been progress on the issue with the latest set of assembly loading and binding enhancements, but we are currently treating this particular assembly as a runtime _restricted_ assembly. I'll be sharing some more details on this in documentation soon, but essentially, assemblies in that category (by GA, we'll have a very small number of them) are required to match within a minor version.

With the last release (2.0.11776), we were, intentionally, overly aggressive with that assembly list, but this assembly will likely be removed, allowing you to bind to any version you reference.

That, combined with additional enhancements in unification logic and dependency updates in the runtime (we'll automatically unify if the runtime dependency minor version is higher), will address this issue.

For now, the current version still requires to use 5.1.x, but I just wanted to give an update as the issue is understood and mitigation will be coming, ideally with the next release.

I'm leaving this issue open and assigned to the current sprint so I can post updates once the changes are made.

**Comment by fabiocav** [comment] 2018-05-30 17:57
As mentioned. Work is in progress and fixes will be deployed with the next release. Leaving this open and moving to Sprint 25 for validation

**Closed by fabiocav** 2018-05-30 17:57 UTC
