### ISSUE TITLE
Emit metric for language worker after jobhost initializes

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-host#3826] opened 2018-11-28 04:59 UTC
We need to emit a log to FunctionsMetrics when the host starts up any language worker.

**Comment by ColbyTresness** [comment] 2018-11-29 01:07
@maiqbal11 chat with me when you're ready to give this a go, would love to talk about naming and such so we can instruct analytics on how to consume

**Comment by maiqbal11** [comment] 2018-11-29 21:36
Created a PR for this #3837. I'll deploy a private site extension to test it. @ColbyTresness could you check to see if the name formatting seems fine?

**Comment by mhoeger** [comment] 2019-01-11 21:48
I think what we found was that the metric being logged by https://github.com/Azure/azure-functions-host/pull/3837 is the worker runtime from app setting. The problem is that not all workers have an app setting containing the runtime stack (it's not a hard requirement for function apps that have functions in only one language). The logic goes: 

if app setting is set:
only run functions that are written in that language (so your function app could have a mix of languages, but we will only honor the ones that you explicitly set your function app to run, via `FUNCTIONS_WORKER_RUNTIME`

else if function app only has functions written in one language (and app setting is not set):
assume that this is the language you want to run in and carry on

else (function app has functions in multiple languages and app setting is not set):
throw an error and ask user to set `FUNCTIONS_WORKER_RUNTIME` in app settings to choose one runtime stack. 

Although this is likely out of the scope of this issue, whenever we use the worker runtime App Setting in code, we should probably be more explicit that this is a worker runtime *setting* that may be null. The best way to know for sure what language we're using is: https://github.com/Azure/azure-functions-host/commit/a5be3f1867d5f8339b8b591deed3219d345799e5

Here's an example of where we pass in "workerRuntime" that comes from the app setting value, and if that value does not exist, we get it from the language of the functions: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/FunctionRegistration/FunctionDispatcher.cs#L98

Here's another example of a metrics change, where we use `workerConfig.Language`, which comes from indexing a user's functions, to know the runtime stack: https://github.com/Azure/azure-functions-host/commit/a5be3f1867d5f8339b8b591deed3219d345799e5

**Comment by ColbyTresness** [comment] 2019-01-26 01:53
@fabiocav @maiqbal11 Can we prioritize this for next sprint? I'd also like to emit a metric if no language worker startup was necessary, to indicate that Stack is .NET.

**Comment by ColbyTresness** [comment] 2019-02-13 07:34
Any word on this work item @fabiocav @maiqbal11? Don't think it'll be too crazy to get this change in based on what @mhoeger provided above. Doing it this way is far better than our workaround, detecting language worker from the invocation latency metric.

Also, it would be really nice to emit a metric when no worker was started because stack is .NET, since we're special casing on the analytics side for that case.

**Comment by fabiocav** [comment] 2019-02-13 18:52
That makes sense. We should really be logging/tracking the resolved stack.

@maiqbal11 do you have clarity on this issue? If so, we can assign this to the next sprint.

**Comment by fabiocav** [comment] 2019-02-13 18:52
@ColbyTresness FYI, this wasn't triaged last time because it was still assigned to Sprint 38 after it was reopened.

**Comment by maiqbal11** [comment] 2019-02-13 19:13
@ColbyTresness  @fabiocav, should be good to assign to the next sprint

**Comment by ColbyTresness** [comment] 2019-02-13 21:37
Got it, next time I reopen an issue I'll reassign to Triaged. Thanks!

**Comment by ColbyTresness** [comment] 2019-02-27 01:02
@jeffhollan

**Closed** 2019-03-01 01:00 UTC
Labels: P0, improvement
