### ISSUE TITLE
[RPC]Implement InvocationCancel

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4027] opened 2019-01-29 23:01 UTC
Need to implement [InvocationCancel ](https://github.com/Azure/azure-functions-language-worker-protobuf/blob/ed55563d9d83ca78c1d268aaf9e8deda1ee51cd2/src/proto/FunctionRpc.proto#L64
)
This specifically impacts language workers that start in placeholder mode as language worker process will not restart as part of jobhost restarts.

From issue #1319, 
TIMEOUT
A language worker should handle Function timeout/cancelation messages
A language worker should ACK if the Function gracefully timed out based on a configurable grace period
A language worker should provide a means for a Function to be notified of graceful shutdown
The host should send the timeout/cancelation message for a given Function execution to the language worker processing it
A language worker should wait for an ACK for a configurable grace period
The grace period should be configurable via the host.json (timeoutGracePeriod)
The grace period can be overridden per Function via function.json (timeoutGracePeriod)
The default grace period should be 1 second

**Comment by pragnagopa** [comment] 2020-03-18 18:31
@yojagad - this is related to issue #5391 . Please take a quick look if this message can be useful to send to worker process to indicate invocation is timeout.

**Comment by fabiocav** [comment] 2020-03-18 20:43
Moving to 72 for investigation as this may no longer be needed.

**Comment by liliankasem** [comment] 2022-02-23 23:47
@yojagad @fabiocav was this investigated at all? Do we still need this?

**Comment by pragnagopa** [comment] 2022-02-24 05:19
Tagging @soninaren - as he was looking to extend the support for CancellationToken to out-of-proc languages

**Comment by soninaren** [comment] 2022-02-24 19:32
I believe this is still relevant. It may not be a cancellation token the functionality is still needed. It would need some design work to start with.

**Comment by fabiocav** [comment] 2022-03-09 21:28
Duplicate of #2152

**Closed by fabiocav** 2022-03-09 21:28 UTC
Labels: feature:language-extensibility, design
