### ISSUE TITLE
Cannot access a disposed object. Object name: 'System.Net.Http.HttpClient'.	

### ISSUE THREAD

**Issue by codermrrob** [Azure/azure-functions-host#4520] opened 2019-06-03 12:38 UTC
I have same tried this with and without a typed client as suggested in https://github.com/Azure/azure-functions-host/issues/4344 but with the same result.

The HttpClient is always disposed of between runs resulting in 
Cannot access a disposed object. Object name: 'System.Net.Http.HttpClient'.	

```
[assembly: FunctionsStartup(typeof(Orders.Collector.Startup))]
namespace Orders.Collector
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddHttpClient<OrdersCollector>();
        }
    }
}
```
```
{
    public class OrdersCollector
    {

        private readonly HttpClient _client;

        public OrdersCollector(HttpClient client)
        {
            _client= client;
        }


        [FunctionName("OrdersCollector")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequest req,
            ILogger log)
        {
        //Do some processing
         return (ActionResult)new OkObjectResult("Data collection completed");
        }
}
```
it is the same result with the emulator & Function App, runs fine first time but not subsequently.

Predictably restarting the Function App resets everything and it will run one time again.

Azure Functions Core Tools (2.7.1158 Commit hash: f2d2a2816e038165826c7409c6d10c0527e8955b)
Function Runtime Version: 2.0.12438.0

**Comment by brettsam** [comment] 2019-06-03 12:55
Are you using an HttpClient anywhere? Can you share the callstack of the exception?

**Comment by codermrrob** [comment] 2019-06-04 02:59
For some reason the catch block of the try catch around the
 `response = await httpClient.SendAsync(request);`
doesn't catch the exception in the emulator but this is the error exported from Application Insights in the attached file.
[query_data.xlsx](https://github.com/Azure/azure-functions-host/files/3250310/query_data.xlsx)

**Comment by codermrrob** [comment] 2019-06-04 06:55
And also just to mention that it all works fine if I inject my own services.

**Comment by brettsam** [comment] 2019-06-04 13:04
HttpClient is injected as Transient. It seems like you're holding onto it past its lifetime, which means that it gets disposed and you continue to use it.

Can you share the entire class (or at least the signature and usage) that this is being used in? Is it a singleton or static class? How does it get the HttpClient?

**Comment by ThomasVandenbon** [comment] 2019-06-04 15:04
I have the same issue when reading a Cosmos DB change feed.
The very first time the function is executed it works correctly.
On every following run the HttpClient has been disposed.

The project only contains this Cosmos-triggered function and the Startup class (that inherits from FunctionsStartup).

My code is identical to the example: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#use-injected-dependencies

**Comment by brettsam** [comment] 2019-06-04 17:38
There's some issues here, but luckily they're doc/pattern issues and we can get you unblocked quickly. All of the [documented patterns](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#consumption-patterns) for `IHttpClientFactory` (and `HttpClient`) apply to Functions -- however, the [documented example](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#use-injected-dependencies) in our Dependency Injection docs is not correct.

For example, you can:
- Use an `IHttpClientFactory` directly in your Function constructor. Then use this to create your `HttpClient`.
- Use a [Typed client](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#typed-clients), where you inject an `HttpClient` into a service, which is then injected into your Function class. Note that the `HttpClient` is not directly injected to your Function class like in our sample doc -- it goes to this "middle" class first.

But you *cannot*:
- Inject an HttpClient directly to a Function class (as mentioned above). The reason is that your Function class is not instantiated in the same way as other DI services. Even though it looks very similar to the "typed client" samples in the `IHttpClientFactory` docs, it doesn't work (as you've seen).

An example of using the "typed client approach":

```csharp
public class Startup : FunctionsStartup
{
    public override void Configure(IFunctionsHostBuilder builder)
    {
        builder.Services.AddHttpClient<MyTypedClient>();
    }
}

public class MyTypedClient
{
    // This sample just exposes the HttpClient as a property, but this typed client can hide it, configure it, etc.
    public HttpClient Client { get; private set; }

    public MyTypedClient(HttpClient client)
    {
        Client = client;
    }
}
```
```csharp
public class HttpFunction
{
    private readonly MyTypedClient _typedClient;

    public Function1(MyTypedClient typedClient)
    {
        _typedClient = typedClient;
    }

    [FunctionName("HttpFunction")]
    public async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
        ILogger log)
    {
        await _typedClient.Client.GetAsync("http://some-url");
        return new OkObjectResult($"Hello");
    }
}
```

I'm jumping over to the docs right now to correct this -- I'm going to change that sample to use an `IHttpClientFactory` instead.

**Comment by brettsam** [comment] 2019-06-04 20:25
I'm going to go ahead and close this since there's nothing for us to handle here -- the doc PR is linked above. Let me know if you have any further questions. Thank you for the report and for helping out!

**Closed by brettsam** 2019-06-04 20:25 UTC
Labels: Needs: Attention :wave:

**Comment by codermrrob** [comment] 2019-06-05 05:14
Brilliant thanks for your timely response and the docs update...saved much head scratching :)

**Comment by andyblack19** [comment] 2019-06-27 20:10
@brettsam I also ran into this problem today, despite the updated documentation.

I'm using the typed client approach you mentioned above, configuring 3 separate clients at startup. (simplified below)
```
builder.Services.AddHttpClient<ApiOne>(x => x.BaseAddress = new Uri(uriOneFromConfig));
builder.Services.AddHttpClient<ApiTwo>(x => x.BaseAddress = new Uri(uriTwoFromConfig));
```

My typed clients each get a `HttpClient` injected in the constructor, however on the second invocation the injected instances are **disposed**. Is this method not supported either?

I see the documentation now only shows the factory approach, but would rather use a typed approach than this `httpClientFactory.CreateClient("MagicString");`

Is it worth the documentation _explicitly_ mentioning that the other methods are not supported?
I read the first paragraph and assumed I could use either method (before ending up here)
> Azure Functions builds on top of the ASP.NET Core Dependency Injection features.

**Comment by brettsam** [comment] 2019-06-28 01:58
I just tried this and it all worked for me over many requests... can you share the full registration of your service? 

FYI -- I'm doing exactly what I've got in the [comment above](https://github.com/Azure/azure-functions-host/issues/4520#issuecomment-498770795).

**Comment by joanna1010** [comment] 2019-08-28 09:45
Hi there, can you confirm that [documented usage ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#use-injected-dependencies) is updated or still out-of-date? I am running the same issue, and have been stuck on getting this HttpClient /  IHttpClientFactory working with DI in Functions app for a stupid amount of time

**Comment by PureKrome** [comment] 2019-10-30 23:57
Just a question on this issue, still.

If we use the `Typed Clients` way of consuming `HttpClients`, I'm also getting the `httpClient` is disposed of. I've always prefered using `Typed Clients` by passing in an `HttpClient` instance into the constructor, vs `Named Clients` or `Basic Usage`.

Reference: [MS Docs : Making HTTP requests](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests).

You've said a few times that you recommend injecting into your service an `IHttpClientFactory` which is like a really simple basic usage and not the more recommended way of using `TypedClients`. 

- Why is this?
- Can we used the `TypedClients` pattern and inject our strongly typed `HttpClient` into a service? 

When I try using `TypedClients` _with a pre-set Polly rule_, the client doesn't work with the rule (i.e. the rule is not associated to the client _instance_ that is injected. If I fall back to using `NamedClients` with the same pre-set Polly rule, it all works hunky-dory.

e.g. in `Startup.cs`

Works:
```
builder.Services.AddHttpClient(nameof(SitemapGenerationService)) // <-- Named Client.
                .AddPolicyHandler((services, request) => GetRetryPolicy(services));
```

Fails:
```
builder.Services.AddHttpClient<SitemapGenerationService>() // <-- Typed Client
                .AddPolicyHandler((services, request) => GetRetryPolicy(services));
```

So how can we use `TypedClients` in an Azure Function, please?

**Comment by oising** [comment] 2019-11-13 15:26
I'm having a similar issue -- I'm using AddHttpClient<TFunctionType> and it's injecting a dead HttpClient. This is nuts.

**Comment by brettsam** [comment] 2019-11-13 15:46
@PureKrome -- I'm not sure how the Polly policy is applied, but let me try it out and I'll get back. I assume you have `SitemapGenerationService` in your Function class constructor?

@oising -- How are you consuming this in your Function? See my example above: https://github.com/Azure/azure-functions-host/issues/4520#issuecomment-498770795. Note that you *cannot* inject an `HttpClient` directly into your Function. But you *can* inject it into a separate service, which is then injected into your Function.

**Comment by brettsam** [comment] 2019-11-13 17:50
@PureKrome -- I just tried your sample and my `GetRetryPolicy()` was called, but only after I had made my first request with my typed client. I suspect that Polly (or the underlying call to `AddHttpMessageHandler()` that it makes) register this lazily and only construct the policy handler upon first request. Are you seeing the typed client injected and never see the policy created?

**Comment by PureKrome** [comment] 2019-11-14 03:40
Thanks heaps @brettsam for having a look at my question. I'll have to review my code again later on (question was asked a while back and I've moved on right now as I couldn't wait too long). I'll add an item to my calendar to review my code again.

once more Brett - thanks for looking into this. appreciate it!

**Comment by akki-s** [comment] 2019-12-01 14:31
I think this is still an issue. I'm using typed client, and not injecting `HttpClient` directly into the function but in another service, and this service class is injected in the `HttpClient`.

It works fine locally, but once deployed to Azure it gives exception saying, "Cannot access a disposed object".

For example here is code:

**Startup.cs**
```
builder.Services.AddHttpClient<IValidationService, ValidationService>();
```

**Function class**
```
 public class ValidationFunctionTriggers
    {
        private readonly IValidationService _validationService;

        public ValidationFunctionTriggers(IValidationService validationService)
        {
            _validationService = validationService;
        }

        [FunctionName(nameof(ValidateEvent))]
        public Task<HttpResponseMessage> ValidateEvent(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "events")] HttpRequestMessage requestMessage,
            ILogger functionsLogger,
            ExecutionContext executionContext)
        {
            return _validationService.Validate(requestMessage);
        }
}
```

**ValidationService.cs**

```
public class ValidationService : IValidationService
    {
        private readonly HttpClient _httpClient;

        public ValidationService(
            HttpClient httpClient)
        {
            _httpClient = httpClient.;
        }
```

**Comment by brettsam** [comment] 2019-12-03 03:07
@akki-s -- How easy is this to reproduce? I just took your code and deployed it and have been running it manually for a while with no issues. Can you put a project up on github somewhere that I can pull and try to reproduce? That'd make it easier for me to figure out what's going on.

**Comment by akki-s** [comment] 2019-12-04 07:00
@brettsam Sure will do and update the repo url here.

**Comment by brettsam** [comment] 2019-12-04 14:37
Thanks @akki-s! If you're able to get a solid repro -- can you try to add this to your DI setup also and see if it changes anything?

```
builder.Services.Configure<HttpClientFactoryOptions>(options => options.SuppressHandlerScope = true);
```
