### ISSUE TITLE
Why is a scaling warning displayed when using identity based connections for AzureWebJobsStorage?

### ISSUE THREAD

**Issue by tmeadon** [Azure/azure-functions-host#7442] opened 2021-06-08 08:29 UTC
#### Is your question related to a specific version? If so, please specify:
3.0.15733.0

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
PowerShell

#### Question
When testing deploying a Function App using the new identity based connection capability, the Azure Portal is displaying the following warning:

![image](https://user-images.githubusercontent.com/39049630/121150792-bc237c80-c83b-11eb-9687-01251fa4a024.png)

I've been able to reproduce the issue using the following bicep template:

```bicep
var baseName = uniqueString('identityRepro', subscription().id)
var location = 'uksouth'

resource stg 'Microsoft.Storage/storageAccounts@2019-06-01' = {
  name: baseName
  location: location 
  sku: {
    name: 'Standard_LRS'
  }
  kind: 'StorageV2'
}

resource asp 'Microsoft.Web/serverfarms@2019-08-01' = {
  name: baseName
  location: location
  sku: {
    name: 'Y1'
    tier: 'Dynamic'
  }
}

resource ai 'Microsoft.Insights/components@2015-05-01' = {
  name: baseName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
  }
}

resource fa 'Microsoft.Web/sites@2019-08-01' = {
  name: baseName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    serverFarmId: asp.id
  }
  kind: 'functionapp'

  resource appSettings 'config@2018-11-01' = {
    name: 'appsettings'
    properties: {
      'AzureWebJobsStorage__accountName': stg.name
      'FUNCTIONS_WORKER_RUNTIME': 'powershell'
      'FUNCTIONS_WORKER_RUNTIME_VERSION': '~7'
      'APPINSIGHTS_INSTRUMENTATIONKEY': ai.properties.InstrumentationKey
    }
  }
}

resource blobContrib 'Microsoft.Authorization/roleAssignments@2020-04-01-preview' = {
  name: guid(fa.name, stg.name, 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')
  properties: {
    principalId: fa.identity.principalId
    roleDefinitionId: resourceId('Microsoft.Authorization/roleDefinitions', 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')
    principalType: 'ServicePrincipal'
  }
  scope: stg
}
```

Am I missing something in the config?

Thanks!

**Comment by v-anvari** [comment] 2021-06-10 14:43
Hi @tommagumma , Thank you for your feedback! We will investigate and update as appropriate. While I check with the team if this is by design, can you provide me the steps to repro this scenario, how are you incorporating the template, and can you provide me links to the related sources of the identity based connections that you are using. This would help us understand more about your Function App. 

Thank you

**Comment by tmeadon** [comment] 2021-06-10 16:12
Hi @v-anvari - this can be reproduced simply by deploying that bicep template into a new resource group.  I'm not sure what you mean by the 'related sources of the identity based connection' - could you help me understand how I can get you the information you need please?  I've not currently got a repro deployed anywhere, but I can do if that would help.

**Comment by v-anvari** [comment] 2021-06-10 16:39
Thank you for the information, I was trying to understand what is the identity based connection you were talking about. Is it this - [how-to-identity-based-data-access](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-identity-based-data-access#:~:text=When%20you%20use%20identity-based%20data%20access%2C%20Azure%20Machine,at%20the%20storage%20level%20and%20keeps%20credentials%20confidential.)

**Comment by tmeadon** [comment] 2021-06-10 17:52
Yep - that's exactly it. I was testing out the new preview feature and was concerned by the warning and thought I should raise it.  Is this the correct repo for that?

**Comment by v-anvari** [comment] 2021-06-11 11:25
Hi @tommagumma , Once I repro it, I will check with the concerned team if this is an expected behavior, Thank you for the details.

**Comment by tmeadon** [comment] 2021-06-11 11:26
Thanks @v-anvari!

**Comment by v-anvari** [comment] 2021-06-15 14:10
Hi @tommagumma , Thank you for the patience, I tried to reproduce the issue and I am getting errors within the Bicep template, but,  I checked with the bicep team and they don't think its coming from the template. I am trying to fix those issues, I shall update you shortly

https://github.com/azure/bicep

**Comment by tmeadon** [comment] 2021-06-15 14:12
Thanks for the update.  What errors are you getting?

**Comment by v-anvari** [comment] 2021-06-15 14:15
Apologies, as I din't keep the error trace, I am working on resolving them, shall update you as appropriate

**Comment by v-anvari** [comment] 2021-06-25 12:36
Hi @tommagumma , I am unable to deploy the template from the visual studio code. I get the below error

Error: Code=InvalidTemplateDeployment; Message=The template deployment 'bicepeg' is not valid 
according to the validation procedure.

The bicep team is trying to reproduce this issue as well, meanwhile can you tell us how did you manage to deploy it without errors

**Comment by v-anvari** [comment] 2021-06-25 12:38
They are sure that the warning you see is coming from "Microsoft.Web/sites@2019-08-01". We are investigating on why the warning is being seen 

Thank you for your patience

**Comment by tmeadon** [comment] 2021-06-25 12:42
No problem - here's the compiled JSON equivalent of the template, perhaps you'll have more luck deploying this.

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "metadata": {
    "_generator": {
      "name": "bicep",
      "version": "0.4.1.14562",
      "templateHash": "2433187752857564681"
    }
  },
  "functions": [],
  "variables": {
    "baseName": "[uniqueString('identityRepro', subscription().id)]",
    "location": "uksouth"
  },
  "resources": [
    {
      "type": "Microsoft.Web/sites/config",
      "apiVersion": "2018-11-01",
      "name": "[format('{0}/{1}', variables('baseName'), 'appsettings')]",
      "properties": {
        "AzureWebJobsStorage__accountName": "[variables('baseName')]",
        "FUNCTIONS_WORKER_RUNTIME": "powershell",
        "FUNCTIONS_WORKER_RUNTIME_VERSION": "~7",
        "APPINSIGHTS_INSTRUMENTATIONKEY": "[reference(resourceId('Microsoft.Insights/components', variables('baseName'))).InstrumentationKey]"
      },
      "dependsOn": [
        "[resourceId('Microsoft.Insights/components', variables('baseName'))]",
        "[resourceId('Microsoft.Web/sites', variables('baseName'))]",
        "[resourceId('Microsoft.Storage/storageAccounts', variables('baseName'))]"
      ]
    },
    {
      "type": "Microsoft.Storage/storageAccounts",
      "apiVersion": "2019-06-01",
      "name": "[variables('baseName')]",
      "location": "[variables('location')]",
      "sku": {
        "name": "Standard_LRS"
      },
      "kind": "StorageV2"
    },
    {
      "type": "Microsoft.Web/serverfarms",
      "apiVersion": "2019-08-01",
      "name": "[variables('baseName')]",
      "location": "[variables('location')]",
      "sku": {
        "name": "Y1",
        "tier": "Dynamic"
      }
    },
    {
      "type": "Microsoft.Insights/components",
      "apiVersion": "2015-05-01",
      "name": "[variables('baseName')]",
      "location": "[variables('location')]",
      "kind": "web",
      "properties": {
        "Application_Type": "web"
      }
    },
    {
      "type": "Microsoft.Web/sites",
      "apiVersion": "2019-08-01",
      "name": "[variables('baseName')]",
      "location": "[variables('location')]",
      "identity": {
        "type": "SystemAssigned"
      },
      "properties": {
        "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('baseName'))]"
      },
      "kind": "functionapp",
      "dependsOn": [
        "[resourceId('Microsoft.Web/serverfarms', variables('baseName'))]"
      ]
    },
    {
      "type": "Microsoft.Authorization/roleAssignments",
      "apiVersion": "2020-04-01-preview",
      "scope": "[format('Microsoft.Storage/storageAccounts/{0}', variables('baseName'))]",
      "name": "[guid(variables('baseName'), variables('baseName'), 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')]",
      "properties": {
        "principalId": "[reference(resourceId('Microsoft.Web/sites', variables('baseName')), '2019-08-01', 'full').identity.principalId]",
        "roleDefinitionId": "[resourceId('Microsoft.Authorization/roleDefinitions', 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')]",
        "principalType": "ServicePrincipal"
      },
      "dependsOn": [
        "[resourceId('Microsoft.Web/sites', variables('baseName'))]",
        "[resourceId('Microsoft.Storage/storageAccounts', variables('baseName'))]"
      ]
    }
  ]
}
```

**Comment by v-anvari** [comment] 2021-06-25 13:24
Hi @tommagumma , Thank you for the json file. Can you tell us the steps and commands on how you are deploying the bicep. Are you deploying the json file
I used the commands shown in the deploy segment here - https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/quickstart-create-bicep-use-visual-studio-code?tabs=PowerShell

**Comment by tmeadon** [comment] 2021-06-25 13:28
@v-anvari I'm using the following commands which I just ran successfully:

```pwsh
New-AzResourceGroup -ResourceGroupName 'bicep-test' -Location uksouth
New-AzResourceGroupDeployment -ResourceGroupName 'bicep-test' -TemplateFile .\repro.bicep -Verbose
```

I have the following installed:
- bicep version `0.4.1`
- PowerShell module Az.Resources version `3.4.0`

**Comment by v-anvari** [comment] 2021-06-25 13:31
yes, I have been trying the same commands, Thank you for the confirmation.

**Comment by v-anvari** [comment] 2021-06-28 12:27
Hi @tommagumma , I was able to deploy it successfully and I could reproduce the warning you have mentioned. When I checked the app settings for the function app, I saw that the AzureWebJobsStorage or WEBSITE_CONTENTAZUREFILECONNECTIONSTRING were not present, which is shown as the reason for the warning. We are checking if the schema or template is missing these settings

**Comment by tmeadon** [comment] 2021-06-28 12:34
That's right - according to [this](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#connecting-to-host-storage-with-an-identity), the new identity based access feature needs you to replace the `AzureWebJobsStorage` setting with `AzureWebJobsStorage__accountName`.

**Comment by v-anvari** [comment] 2021-06-29 10:43
Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by v-anvari** [comment] 2021-07-06 09:20
Triaging this issue for further investigation. The identity based access requires storage blob owner access. I have added the required roles in the storage, but the Function still throws "Unauthorized access" error while running the function. 

Requires further investigation on adding the roles 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#connecting-to-host-storage-with-an-identity

**Comment by tmeadon** [comment] 2021-07-06 09:24
FWIW I don't see unauthorized access exceptions when I deploy the template.

**Comment by v-anvari** [comment] 2021-07-06 09:29
Yes, I wanted to check if the warning was just an UI issue, so I added the required access and tested the function. But, as a result/ output, I receive the below
![image](https://user-images.githubusercontent.com/66122429/124577348-cc467000-de6a-11eb-99b0-6bb00381ee7b.png)

**Comment by v-anvari** [comment] 2021-07-15 11:44
Hi @tommagumma , Apologies, took sometime to investigate the issue. 
As mentioned the previous comment, according to the following document, to use the setting, the storage account requires a storage blob owner role - https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#connecting-to-host-storage-with-an-identity

You need to grant the required permissions as mentioned here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#grant-permission-to-the-identity
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#connection-properties
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#local-development-with-identity-based-connections

I added the storage blob owner role in the azure role permission section to the storage account
![image](https://user-images.githubusercontent.com/66122429/125769774-07727705-0a10-42e6-8573-5b19941a28b3.png)
![image](https://user-images.githubusercontent.com/66122429/125770268-821e971f-8513-4ebc-a500-5aa592dc5275.png)

The following document is regarding the identity based access configuration. 
https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=dotnet#add-a-system-assigned-identity

Once you add the role and try to run the function (Timer trigger and Http trigger in my case), worked successfully fine. 
![image](https://user-images.githubusercontent.com/66122429/125770145-6dd328d3-e6e9-40f2-b03f-e741382264e7.png)

The warning may still be present, but this could be an UI issue. As the UI must be set in a way to check for certain App settings, since there is neither AzureWebJobsStorage nor WEBSITE_CONTENTAZUREFILECONNECTIONSTRING is present.

Can you recheck the configurations again and tell us if this works for you

**Comment by tmeadon** [comment] 2021-07-15 13:40
Hi @v-anvari - thanks for investigating.  So in my testing the functions run successfully, I only raised this because I was concerned by the warning message.  I suspected it might be a UI issue, so if you believe that to be the case too I think we can go with it.

**Comment by v-anvari** [comment] 2021-07-15 14:07
Hi @tommagumma , Thank you for the update, You can let me know if you see any issues with the functions runtime. Closing this issue, please feel free to re-open the case if any further queries.

**Closed as completed by v-anvari** 2021-07-15 14:07 UTC
