### ISSUE TITLE
node.js function not parsing JSON content from EventHubTrigger

### ISSUE THREAD

**Issue by ahmedspiir** [Azure/azure-functions-host#4982] opened 2019-09-26 12:40 UTC
I have Azure function to trigger eventhub events.
After deploying my function i got many errors about parsing JSON content.
#### Investigative information

Please provide the following:

- Timestamp: 2019-09-23 07:29:16.932 

- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: 247803a0-1252-4c9a-bba4-b6bd9ef7e425
- Region: NE

#### Repro steps

Provide the steps required to reproduce the problem:

```json
{
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "eventHubMessages",
      "direction": "in",
      "eventHubName": "myeventhubName",
      "connection": "EVENTHUB_CONNECTION_STRING",
      "cardinality": "many",
      "consumerGroup": "consumer_group"
    }
  ],
  "scriptFile": "../dist/XXEventHubTrigger/index.js"
}

```
```ts
const eventHubTrigger: AzureFunction = async function (context: Context, eventHubMessages: any[]): Promise<void> {
    context.log(`Eventhub trigger function called for message array ${eventHubMessages.length}`);
}
```
#### Expected behavior
It should work!
Provide a description of the expected behavior.

#### Actual behavior
I got exception
```
Binding parameters to complex objects (such as 'Object') uses Json.NET serialization. 
1. Bind the parameter type as 'string' instead of 'Object' to get the raw values and avoid JSON deserialization, or
2. Change the queue payload to be valid json. The JSON parser failed: After parsing a value an unexpected character was encountered: t. Path 'records[0].properties.requestbody', line 1, position 22397.

```

#### Known workarounds
I have seen in other issues that it may be caused because of `"cardinality": "many",` but this is how i want it!

#### Related information 

Provide any related information 

* Programming language used
TS (Node.js)
* Links to source
* Bindings used

**Comment by fabiocav** [comment] 2019-10-11 21:01
Closing as duplicate of https://github.com/Azure/azure-functions-nodejs-worker/issues/247

Please follow the linked issue for updates.

**Closed by fabiocav** 2019-10-11 21:01 UTC
Labels: Needs: Triage (Functions)
