### ISSUE TITLE
Memory working set grows each function invocation

### ISSUE THREAD

**Issue by ADH-LukeBollam** [Azure/azure-functions-host#7525] opened 2021-07-06 07:37 UTC
Function memory isn't fully released after each function invocation

![image](https://user-images.githubusercontent.com/24449147/124560377-51cc1f00-de6f-11eb-88f1-e96592d8e8f7.png)

Sometimes this causes the host to OOM and restart

#### Investigative information

Please provide the following:

- Timestamp: 2021-07-06 07:26:10.680 UTC
- Function App version: 3
- Operation ID: 94bd9537e2d1a949aaa4665d55263eb3
- Invocation ID: 13a2b4c4-18e3-4023-b32e-05442b730214
- Region: Australia East

#### Repro steps
Run the same job (in our case a queue trigger) multiple times in a row

#### Expected behavior
Memory should be released at the end of an invocation

#### Actual behavior
Memory usage grows

#### Known workarounds
Unknown

**Comment by v-anvari** [comment] 2021-07-09 16:05
Hi @LukeBolly , I have checked the logs for the Timestamp - 2021-07-06 07:00 to 2021-07-06 15:13 

Overall instance memory is below 80% however the current app is consuming high private bytes. The highest memory consumption within this duration for the current process is 5.0 GB. If this is unexpected, If your app is performing slow or not responding at all, or if it consuming high memory, you can collect a memory dump to identify the root cause of the issue. The tool will collect a memory dump for your app and generate an analysis report.

Issues with your application may be mitigated by performing a site restart. For further investigation, please follow these instructions to collect a memory dump.

1. Go to [App Service Diagnostics](https://portal.azure.com/?websitesextension_ext=asd.featurePath%3Ddetectors%2FMemoryusage#@microsoft.onmicrosoft.com/resource/subscriptions/73e4ae94-a3fb-431f-9e78-452a733ee425/resourceGroups/AtrioDashboard/providers/Microsoft.Web/sites/func-atrioimport-stage/troubleshoot) 
2. Choose **Diagnostic Tools** .
3. Click on **Collect Memory Dump** tile and follow the instructions.

_(Memory dumps incur overhead to your app so ensure you collect a memory dump only on the instances that are facing the issue.)_

**Comment by ADH-LukeBollam** [comment] 2021-07-14 00:58
The app using 5GB while running isn't unexpected, but the fact it isn't all released at the end is. I should have been a bit clearer, the picture above is from 6 separate invocations. 

If there is memory still locked up after the invocation completes, is that a memory leak in my function or in the function host?

Restarting the site is not a solution if it is going to keep growing.

**Comment by v-anvari** [comment] 2021-07-19 16:43
Hi @LukeBolly , I have checked the logs and  also checked this behavior with the team, this behavior is expected in Functions if an App is consuming memory. Multiple functions are taking up the memory, so after every execution, they do not get released. A single host can run multiple instances. Also, There were no memory leaks that we were able to see in your App. The recommendation here is to check the memory dump and understand the reason of the memory consumption and mitigate them. 

If the issue is not reproducible or intermittent, you can configure AutoHealing's custom action to collect some data (like profiler trace or memory dump) that will help you debug the issue further. The triggers and actions allow you to define various conditions based on request count, slow requests, memory limit on which you can take specific actions like restarting the process, logging an event, or starting another executable.

**Comment by ADH-LukeBollam** [comment] 2021-07-20 01:24
"Multiple functions are taking up the memory, so after every execution, they do not get released"

I don't understand what you mean here. Are you saying that every time a function completes, it is expected that some memory is going to be locked up forever?

If we run too many memory-heavy jobs in a row (ie. letting one finish before starting the next one), it crashes both our staging and live slot.

**Comment by v-anvari** [comment] 2021-07-20 08:46
Hi @LukeBolly , The Memory usage is per instance and not per invocation. During the Timestamp: 2021-07-06 07:26:10.680 UTC, Your Function App's committed memory was over 90% of the maximum limit (1536 MB). We saw a peak value of 6281.15 MB. 

Your app is a part of App Service plan which may contain other apps too. Your App will be recycled if it is consuming high memory, to prevent crashing or impacting other apps running in your App service plan. The only solution here is to find out the cause of the high memory usage and prevent this from happening or you can scale up the App to the higher tier. Function App restart will only be a temporary solution. 

Also, High CPU Usage has been detected on multiple instances serving the app however the CPU usage is not contributed by a single app or process. Multiple apps and system processes running on the instance are responsible for high CPU usage of the instance. We identified 2 data points in this time duration when CPU was high across any of the instances serving the app and the below table shows you the average CPU percentage for the top apps consuming high CPU during periods of high CPU across all instances. Scale up the App Service instance to increase available CPU, RAM, and disk space.

Here is a video which explains how to diagnose and resolve the high Memory usage
https://www.youtube.com/watch?v=ahrdqbrHw68

By collecting and doing the Analysis of the Memory dump, you will be able to diagnose and mitigate the high memory usage.

**Comment by v-anvari** [comment] 2021-07-20 08:55
`Are you saying that every time a function completes, it is expected that some memory is going to be locked up forever?`

If you see that there are two many objects from a class which is taking high memory bytes in the memory dump. Then there could be a possible memory leak. For example, If all these objects are part of a single array, which is rooted in the Application state then these objects will not be cleared by the garbage collector. Memory will not be locked up or consumed forever, unless they are in a state for the garbage collector to clear them.

**Comment by ADH-LukeBollam** [comment] 2021-07-20 09:05
The behavior I'm seeing is every time a job completes and the function app returns to idle, the memory is still a little bit higher than before. If I do this enough times, the whole app appears to crash because logs stop and any running jobs don't complete. It sounds like a leak to me, I'll investigate if it's on our end and get back to you.

**Comment by v-anvari** [comment] 2021-07-20 09:12
Thank you for the update

**Comment by ADH-LukeBollam** [comment] 2021-08-16 04:26
hi @v-anvari , our app has crashed again from what I appears to be OOM (logs stopped, followed by a restart with no errors) and I was hoping I could get some more information to help me to try and fix this. This occurred over a few days, over many executions.

![image](https://user-images.githubusercontent.com/24449147/129510712-8df13c39-3253-4205-a240-82e65ec8dff2.png)

Our function is parsing large files (a range of formats) into even larger arrays, sometimes up to 500MB of data will be in a single array. It is expected to see large peaks in memory usage. We also do some calculations on these arrays which can allocate additional space but everything is done within the managed memory of dotnet. I don't use any unsafe contexts.

I've checked my code multiple times for any lingering references to these arrays during an invocation and have tried to set any to null to really tell the GC I'm done with them, but even then I don't understand how memory can persist across different invocations, because surely any references must be gone once a job completes?

The only other thing I can think of is data is being left in our Dependency Injection service container, as some of these may be persistent?

**Comment by ADH-LukeBollam** [comment] 2021-08-24 06:26
I also cannot take a memory dump from azure because I get this message
![image](https://user-images.githubusercontent.com/24449147/130566884-c3b78449-68ce-4a38-83d4-066147cf69b6.png)
We are using a premium function so this option is on by default, and I do not see the option to change under general settings.

**Comment by ADH-LukeBollam** [comment] 2021-08-25 06:54
I've downloaded a dump from Kudu, which is not ideal because it times out trying to retrieve a memory dump of anything over 2GB. The biggest memory usage seems to be coming from WebJobs.Diagnostics

![image](https://user-images.githubusercontent.com/24449147/130740657-3e03de56-41cd-4c58-a7fb-f26c35fa8119.png)

If you could help me fix the issue so I can collect a dump from Azure Portal, I'm sure that will be more useful information.

**Comment by v-anvari** [comment] 2021-08-26 17:25
Hi @LukeBolly , Apologies, The recommended and legacy  way of getting the memory dump has always been kudu. But, the easier way is App diagnostics. You can turn on the "Always on" property if its present, if it is not. Then this is probably a limitation, for which the support team can raise a CRI or bug. They can also help you solve or understand how to mitigate the memory spike.

**Comment by v-anvari** [comment] 2021-09-27 12:03
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue

**Closed as completed by v-anvari** 2021-09-27 12:03 UTC
