### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by piotrzbyszynski** [Azure/azure-functions-host#7326] opened 2021-04-28 11:53 UTC
Sometimes, for no apparent reason, one of instances of my function (consumption plan, service bus triggered) starts to constantly throw `NullReferenceException`. It seems like an exception is thrown on function entry point.
 Usually restarting function helps. Here is a stack trace

```
System.NullReferenceException:
   at PerfectGym.GoApi.Infrastructure.Synchronization.Functions.SynchronizeFunction+<Run>d__4.MoveNext (PerfectGym.GoApi.Infrastructure.Synchronization.Functions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullPerfectGym.GoApi.Infrastructure.Synchronization.Functions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: c:\perfectgymdevops_build_agent\_work\1\s\PerfectGym.GoApi.Infrastructure.Synchronization.Functions\SynchronizeFunction.csPerfectGym.GoApi.Infrastructure.Synchronization.Functions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 62)
```

- Timestamp:
- Function App version: 3
- Invocation ID: 2324d41f-0cb6-4e6b-a082-475efacae9be
- Host instance: a8eb7c1c-1cf5-49d4-95ac-06c177237fdf
- Region: Europe West

#### Expected behavior

I would expect function to run without errors not related to business code

#### Actual behavior

Function throws NRE exception, message that triggers function goes to Dead Letter Queue. After function restart, messages are resubmitted and function runs properly

#### Known workarounds

Restart function app

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source
* Bindings used: service bus

<summary>Function signature</summary>

```csharp
[FunctionName("SynchronizeFunction")]
        public async Task Run([ServiceBusTrigger("%GoApiToSyncQueueName%", Connection = "BusConnectionString", IsSessionsEnabled = true)]
            Message message,
            [ServiceBus("%SyncToCacheQueueName%", Connection = "BusConnectionString")]
            IAsyncCollector<Message> outputCollector)
        {
            ...
        }
```

**Comment by balag0** [comment] 2021-04-29 02:09
@pzbyszynski Looks like the exception might be coming from the function code. Is it possible Line 62 might lead to NRE under some scenario?

Exception while executing function: SynchronizeFunction ---> System.NullReferenceException : Object reference not set to an instance of an object.
   at async PerfectGym.GoApi.Infrastructure.Synchronization.Functions.SynchronizeFunction.Run(Message message,IAsyncCollector`1 outputCollector) at c:\perfectgymdevops_build_agent\_work\1\s\PerfectGym.GoApi.Infrastructure.Synchronization.Functions\SynchronizeFunction.cs : 62

**Comment by piotrzbyszynski** [comment] 2021-04-29 12:33
@balag0  I don't thing it is code specyfic. In line 62 I see nothing that could result in NRE. 

Also, I usually have over 50 instances of this function (consumption plan). And it is only one random instance that suddenly starts to throw exceptions. After restart the same messages that were causing NRE earlier are handled just fine

**Comment by piotrzbyszynski** [comment] 2021-05-01 07:49
Another example, 2021-05-01 from around 02:51 AM till 05:10 AM. Cloud role instance: `e4fa83a8dadb36112a7cb1072f3cc29b0050959a0f88da9f5e3b081ec94133d3`

All unprocessed messages ended up in Dead Letter Queue. After resubmitting they were processed just fine

**Comment by v-bbalaiagar** [comment] 2021-06-28 11:24
Hi @balag0, Can you kindly look into this.

**Comment by balag0** [comment] 2021-06-28 19:31
@pzbyszynski Sorry, I missed this earlier. Is this still failing. Could you share a more recent failure instance. We have had couple of functions releases in the meantime, so want to check if this got resolved by some of the fixes there.

**Comment by piotrzbyszynski** [comment] 2021-06-29 11:31
@balag0  Unfortunately it is still failing. Example from today:
- Instance id: `1f601700fd1ad28d5724213ac5dac91af698fb7206a1c2cdc23446426bef84f6`
- Invocation id: `617d0e36-14b8-42db-a8c3-cc338d5d972a`
- SDK version: `azurefunctions: 3.0.15733.0`

**Comment by v-bbalaiagar** [comment] 2021-09-14 09:33
Hi @pzbyszynski, Apologies for the delayed response, can we know if you are still seeing this issue so that we can follow up with the team.

**Comment by piotrzbyszynski** [comment] 2021-09-20 20:26
@v-bbalaiagar Yes, the issue is still present

**Comment by v-bbalaiagar** [comment] 2021-09-21 10:33
Hi @pzbyszynski, Thank you for your feedback! Kindly can you provide us the latest invocation id of the error to check further.

**Comment by piotrzbyszynski** [comment] 2021-09-22 09:45
@v-bbalaiagar Here you go: `0b5e71a6-8d10-4689-b744-e50b74580e7f`

**Comment by v-bbalaiagar** [comment] 2021-09-28 14:28
Hi @pzbyszynski, I went through the logs with the given invocation id. I see the error- Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: SynchronizeFunction ---> System.NullReferenceException : Object reference not set to an instance of an object.
   at async PerfectGym.GoApi.Infrastructure.Synchronization.Functions.SynchronizeFunction.Run(ServiceBusReceivedMessage message,IAsyncCollector`1 outputCollector) at c:\perfectgymdevops_build_agent\_work\1\s\PerfectGym.GoApi.Infrastructure.Synchronization.Functions\SynchronizeFunction.cs : 65

Looking at the stack, the null reference exception is coming from the code. Can you try to add additional logging to the code to understand what is null or we need access to the code to check the cause.

**Comment by piotrzbyszynski** [comment] 2021-09-29 16:09
@v-bbalaiagar Line specified in the stack trace can not throw NRE. But I will add extensive logging to check what throws this NRE. But please keep in mind that messages that ended up in Dead Letter Queueu due to NRE after function restart are processed just fine

WIll add logging and will let you know

**Closed as completed** 2021-11-06 04:01 UTC
Labels: Needs: Author Feedback, no-recent-activity
