### ISSUE TITLE
Can't update function anymore

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-host#4148] opened 2019-02-27 12:40 UTC
I'm trying to update my function code with the core tools:

![image](https://user-images.githubusercontent.com/57396/53490752-c8350700-3a94-11e9-87cf-8bd0757ddd0a.png)

everything seems to be fine. Except the host is still running the old code. I know because for testing I'm now throwing an exception as very first thing - but it's not raised. Instead the old code runs as before.

#### Investigative information

Please provide the following:

- Function App version (1.0 or 2.0): 2
- Function App name: ecarcache
- Function name(s) (as appropriate): MasterDataCache
- Invocation ID:
- Region: Europe West

/cc @tforkmann

**Comment by tforkmann** [comment] 2019-02-27 12:57
I can approve that issue!

**Comment by valdisiljuconoks** [comment] 2019-02-27 13:10
do you have swap?

**Comment by forki** [comment] 2019-02-27 13:10
More details:

- azure-functions-core-tools@2.4.401
- Runtime version: 2.0.12309.0 (~2)

**Comment by forki** [comment] 2019-02-27 13:11
@valdisiljuconoks what swap?

**Comment by valdisiljuconoks** [comment] 2019-02-27 13:12
slot swap

**Comment by forki** [comment] 2019-02-27 13:12
we did not activate slots

**Comment by fabiocav** [comment] 2019-02-28 05:45
Took a look at the site and looks like there are two settings for the run from package feature, one using the legacy `RUN_FROM_ZIP` setting and another using the `RUN_FROM_PACKAGE` one. Looks like `RUN_FROM_ZIP` is taking precedence here, since it points to an older blob (which should be the code you see running). Deleting that should address the issue, but I'm raising this with the team responsible for the feature to make sure we have a proper warning there if this condition is met.

I'm assuming this has been this way on your site for a while (please correct me if not), so I'll follow up with them to see if there was a regression, as I believe `RUN_FROM_PACKAGE` was supposed to take precedence.

**Comment by fabiocav** [comment] 2019-02-28 06:03
Just delete the setting, that will trigger a site restart. The one you want to delete is the `RUN_FROM_ZIP` one.

**Comment by forki** [comment] 2019-02-28 07:35
@fabiocav thanks a lot!!! This fixed it.

But all my function apps have both settings. So I removed `RUN_FROM_ZIP` everywhere and now I'm redeploying everything.
I assume some migration went wrong on the host side?

**Comment by tforkmann** [comment] 2019-02-28 08:18
For me creating a complete new Function App solved that issue. The new Function App had  
`RUN_FROM_PACKAGE` as default.

**Comment by mhoeger** [comment] 2019-03-15 18:59
@fabiocav - can we automatically remove the RUN_FROM_ZIP property if we see it on func cli deployment?

**Comment by alrod** [comment] 2019-07-15 21:56
the issue is fixed by deleting `RUN_FROM_ZIP`

**Closed by alrod** 2019-07-15 21:56 UTC
