### ISSUE TITLE
dotnet get user folder return wrong value

### ISSUE THREAD

**Issue by iron9light** [Azure/azure-functions-host#6452] opened 2020-08-04 01:59 UTC
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

windows, dotnet core host.

#### Repro steps

I use code below to get the user folder and try to write some cache there,
```csharp
Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)
```

#### Expected behavior

The value should be the user folder, like `D:\local\username\`

#### Actual behavior

It returned a path like this: `D:\Program Files (x86)\SiteExtensions\Functions\3.0.14191\32bit`

#### Known workarounds

Now I use `Path.GetTempPath()` and it returns `D:\local\Temp`.

**Comment by iron9light** [comment] 2020-08-04 02:02
Checked my log again.
It seems it will return the correct value sometimes.
like this: `D:\Users\mawsFnPlaceholder699_f_v3_x86\`

**Comment by v-anvari** [comment] 2021-03-11 11:48
Hi @iron9light , Let us know if you are still seeing this issue.

**Comment by iron9light** [comment] 2021-03-12 13:13
@v-anvari Have you guys fixed this issue? Which version should I try?

**Comment by v-anvari** [comment] 2021-03-12 15:09
Hi @iron9light , Please check the document below: 
Syntax: public static string GetFolderPath (Environment.SpecialFolder folder);
[https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath?view=net-5.0#overloads](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath?view=net-5.0#overloads)

Returns
String
The path to the specified system special folder, if that folder physically exists on your computer; otherwise, an empty string ("").

You are getting a null value because the system is unable to find the folder. where the special folders are mentioned in this document. [https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-5.0#remarks](https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-5.0#remarks)


Applies to : 

![image](https://user-images.githubusercontent.com/66122429/110958665-f4b5d600-8372-11eb-8576-ae640e348a70.png)

**Comment by v-anvari** [comment] 2021-03-16 12:36
Closing this issue   as the required information is provided, please feel free to reach back to us   in case of any further queries related to this issue

**Comment by iron9light** [comment] 2021-03-18 15:40
@v-anvari Please read my post again:
Repro steps

I use code below to get the user folder and try to write some cache there,
```csharp
Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)
```
Expected behavior

The value should be the user folder, like `D:\local\username\`

Actual behavior

It returned a path like this: `D:\Program Files (x86)\SiteExtensions\Functions\3.0.14191\32bit`

It's not return `null` but a wrong place.

**Comment by v-anvari** [comment] 2021-03-18 16:38
Hi @iron9light , Thankyou for reaching back to us. This is an expected behavior, but we would like to know what you are trying to achieve here in order to provide the right guidance.

**Closed as completed** 2021-03-25 22:00 UTC
Labels: Needs: Author Feedback, no-recent-activity
