### ISSUE TITLE
Side by side configuration is incorrect and sxtrace cannot be run

### ISSUE THREAD

**Issue by leidegre** [Azure/azure-functions-host#2417] opened 2018-02-13 06:20 UTC
#### Investigative information

Please provide the following:

- Timestamp: 2018-02-17
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function App name: puppeteer, puppeteer2
- Function name(s) (as appropriate):
- Invocation ID:
- Region: West Europe

#### Repro steps

- Create a new Azure function host (consumption plan)
- Use the 2.0-beta runtime
- Use Node 8.5.0
- Open debug console from within Kudu
- Run `npm install puppeteer`
- Run the below script

~~~
const puppeteer = require("puppeteer")

puppeteer.launch().then((browser) => browser.close(), (err) => console.error(err))
~~~

#### Expected behavior

I expect this to work, as it does work with Windows Server Core 2016, for example.

#### Actual behavior

The node script will fail with error  `spawn UNKNOWN`. This is due to the "side by side configuration is incorrect" error, it will ask you to run sxtrace to investigate further but trying to do so within the Azure Function runtime will result in an access denied error. I cannot debug this issue due to insufficent access permission in the Azure Function runtime environment.

#### Known workarounds

None that I know of, it would require running AWS lambda or Linux in Azure, something which I think shouldn't be needed here.

**Comment by christopheranderson** [comment] 2018-02-15 19:57
We do not support headless chrome in Azure Functions on Windows today. You can try this on Azure Functions on Linux (which is unfortunately still preview, for now), or as you said use ACI/etc. We had to block some of the APIs that headless browsers rely on in our Windows environments (https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#win32ksys-user32gdi32-restrictions). Sorry for the trouble.

Closing as "by design"

**Closed by christopheranderson** 2018-02-15 19:57 UTC

**Comment by rajyraman** [comment] 2018-02-28 02:46
I had the path to Chrome, but I get different error.

```javascript
puppeteer.launch({
        executablePath: './node_modules/puppeteer/.local-chromium/win32-497674/chrome-win32/chrome.exe'
    }).then((browser) => browser.close(), (err) => console.error(err));
```

but I am getting HTTP 502 all the time. I will try this in Linux and see if this works.

**Comment by rajyraman** [comment] 2018-03-01 18:42
I tried this on Functions host on Linux as well. It does not work. Tried with _createBrowserFetcher_ and the latest version of Chromium on Linux, but no launch. I can see the version downloaded into node_modules, but launch promise does not resolve at all.

**Comment by Jehoel** [comment] 2019-09-27 11:02
@christopheranderson 

To my knowledge, Chrome's Headless mode doesn't use the GDI libraries (it's all OpenGL) so it should work. All of the postings about Chrome (and other WebKit-based HTML-to-PDF generators) not working in Azure Websites / Azure App Services predate the 2016 change to Chrome to prefer OpenGL to GDI. This is why `wkhtmltopdf.exe` runs on Azure App Services fine today (but I can't use `wkhtmtopdf.exe` myself because it has bugs when rendering SVG graphics in addition to issues with its build of `openssl`).

I was able to get `chrome.exe` to run by working-around the side-by-side error by running from the `HOME_EXPANDED` directory - I do get some assortment of errors written out of `stderr` and `stdout` but at least it does run.
