### ISSUE TITLE
Microsoft.NET.Sdk.Functions 3.0.4 breaks Dependency Injection

### ISSUE THREAD

**Issue by thdotnet** [Azure/azure-functions-host#5749] opened 2020-03-05 18:01 UTC
Hi Friends,

seems that there's a problem with the dependency injection feature in the latest sdk (3.0.4) .

Steps to reproduce:

```
namespace FunctionApp1
{
    public class FooService : IFooService
    {
        public string Greeting(string name)
        {
            return $"Hi {name}";
        }
    }

    public interface IFooService
    {
        string Greeting(string name);
    }
}

using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;

[assembly: FunctionsStartup(typeof(FunctionApp1.Startup))]

namespace FunctionApp1
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddScoped<IFooService, FooService>();
        }
    }
}

using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace FunctionApp1
{
    public class Function1
    {
        private readonly IFooService _fooService;
        public Function1(IFooService fooService)
        {
            _fooService = fooService;
        }

        [FunctionName("Function1")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            string responseMessage = string.IsNullOrEmpty(name)
                ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
                : _fooService.Greeting(name);

            return new OkObjectResult(responseMessage);
        }
    }
}

```

Installed packages:

    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.4" />

output when running the function:

[3/5/2020 6:00:35 PM] Executing HTTP request: {
[3/5/2020 6:00:35 PM]   "requestId": "3edd8745-5e39-4bdd-b36d-2fa1add5ae4b",
[3/5/2020 6:00:35 PM]   "method": "GET",
[3/5/2020 6:00:35 PM]   "uri": "/api/Function1"
[3/5/2020 6:00:35 PM] }
**[3/5/2020 6:00:35 PM] Executed 'Function1' (Failed, Id=3db0f356-ac59-4fff-b8c9-15631bc28114)
[3/5/2020 6:00:35 PM] Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'FunctionApp1.IFooService' while attempting to activate 'FunctionApp1.Function1'.
[3/5/2020 6:00:35 PM] An unhandled host error has occurred.
[3/5/2020 6:00:35 PM] Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'FunctionApp1.IFooService' while attempting to activate 'FunctionApp1.Function1'.**
[3/5/2020 6:00:35 PM] Executed HTTP request: {
[3/5/2020 6:00:35 PM]   "requestId": "3edd8745-5e39-4bdd-b36d-2fa1add5ae4b",
[3/5/2020 6:00:35 PM]   "method": "GET",
[3/5/2020 6:00:35 PM]   "uri": "/api/Function1",
[3/5/2020 6:00:35 PM]   "identities": [
[3/5/2020 6:00:35 PM]     {
[3/5/2020 6:00:35 PM]       "type": "WebJobsAuthLevel",
[3/5/2020 6:00:35 PM]       "level": "Admin"
[3/5/2020 6:00:35 PM]     }
[3/5/2020 6:00:35 PM]   ],
[3/5/2020 6:00:35 PM]   "status": 500,
[3/5/2020 6:00:35 PM]   "duration": 812
[3/5/2020 6:00:35 PM] }
[3/5/2020 6:00:37 PM] Host lock lease acquired by instance ID '00000000000000000000000015289094'.

**Comment by thdotnet** [comment] 2020-03-05 18:04
More people facing the same problem:

https://stackoverflow.com/questions/60509972/durable-azure-function-binding-types-not-registered-when-using-dependency-inject/60511472#60511472

https://stackoverflow.com/questions/60549618/azure-function-with-entityframework-di

**Comment by brettsam** [comment] 2020-03-05 18:19
Closing this as dupe of #5747

**Closed as completed by brettsam** 2020-03-05 18:19 UTC
