### ISSUE TITLE
Support Service Bus queues and topics which use sessions

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#563] opened 2016-08-08 17:40 UTC
From uservoice - https://feedback.azure.com/forums/355860-azure-functions/suggestions/13882992-support-for-session-enabled-azure-service-bus-queu

> Currently the queue/subscription trigger only works with queues and subscriptions that does not use sessions (RequiresSession = false). It would be very useful if the runtime would detect that sessions are enabled and adapt accordingly. As far as I can see, the actual function code would not even have to be aware.

**Comment by mathewc** [comment] 2016-08-09 00:00
FYI: This support would have to be added to the core WebJobs SDK, and we have several existing backlog items in that repo (e.g. https://github.com/Azure/azure-webjobs-sdk/issues/529) tracking this.

**Comment by ReadifySamSiu** [comment] 2016-11-13 23:32
any update on this? any ETA? it's kind of a blocker for us now. many thanks!

**Comment by AranVinkItility** [comment] 2016-12-01 10:08
Blocker for me as well, I cannot implement some of our core functionality in Functions if this is missing.

**Comment by danbueno20** [comment] 2017-06-01 16:34
Same here.  We are using Functions to handle EventSourced-object events.  There are a few occasions where an action creates multiple events for the same object and they are all put in the queue in quick succession.  I want to handle messages in parallel and we've had multiple cases of race conditions causing issues.  I was looking for a way to only handle multiple messages for various objects but only one message per object.  Looking at sessions, the hope is that using our SourceId (unique identifier) as the SessionId would solve our problem.  If my understanding is correct, then we need this functionality.  This is a huge drawback right now.

**Comment by mikhailshilkov** [comment] 2017-06-09 15:06
Blocker for us too. We use session'ed queues / topics and would like to migrate away from custom service bus handling code towards Function App. Please prioritize.

**Comment by Vossekop** [comment] 2017-07-24 09:57
Same here, it is the only blocking issue from migrating our worker roles to function apps.

**Comment by DaanWasscher** [comment] 2017-08-02 08:16
This feature is a real must have for many scenarios and is blocking me from using Azure Functions at this point. 

@christopheranderson is there any ETA on this top 10 user voice feature?

**Comment by JasonBSteele** [comment] 2018-01-03 09:29
Must have for me too. Is there a good workaround?

**Comment by syedhassaanahmed** [comment] 2018-02-09 09:45
+1 A blocker for us

**Comment by mcupito** [comment] 2018-03-27 12:40
It's been on the backlog for (over) a year and a half - should we stop asking? haha

**Comment by mikhailshilkov** [comment] 2018-03-27 12:42
Nah, it's almost 3 years if you consider https://github.com/Azure/azure-webjobs-sdk/issues/529

**Comment by rfolkes** [comment] 2018-04-12 06:40
This would be a blocker for us as well, really unfortunate for event handling scenarios

**Comment by stevenlivz** [comment] 2018-04-13 19:30
I'd even like the ability for it just to work even if it ignore the sessions rather than error - that way we can share the queue with some other consumers that do support session (some amqp clients).

**Comment by brettsam** [comment] 2018-04-26 16:48
This has been getting more requests -- I'm going to clear the milestone so we can discuss it further.

**Comment by rfolkes** [comment] 2018-04-27 09:06
ok, thanks for the transparency, hoping for you to be able to prioritize this in the future then

**Comment by martinfletcher** [comment] 2018-06-22 14:03
This really is a massive blocker for us, as we require FIFO of messages with topics using functions....

What is the release date for functions v2 runtime - Is there a finger in the air date that this may get addressed by  after the v2 release?

**Comment by JasonBSteele** [comment] 2018-07-13 10:05
This has hit me again today. Can we get some feedback from MS that this is at least being worked on?

**Comment by paulbatum** [comment] 2018-07-25 23:38
@JasonBSteele At this time, I have no further updates beyond my last comment above.

**Comment by JasonBSteele** [comment] 2018-10-08 10:39
We are currently working around it by using a Logic App but it is costing us £800 a month to run it due to the volume of messages and the 30 second polling.

**Comment by vhe1** [comment] 2018-10-13 15:37
This is your friendly nagging post :-)

We just couldn't use azure functions in quite a big project because of that, so how are things?

For message based architectures, sessioned queues with their ability to

- guarantee exclusive access to the session during function invocation, removing the need for locks in many scenarios
- their state store allowing to accumulate and process session state via GetState and SetState,

using Azure funcions for both would really be a big enabler for serverless architectures.

Right now I feel sessions are mostly limited to old style processors and call/return. I think ServiceBus is really the most powerful and flexible composing mechanism you have. Pity that the only a subset can be used in a serverless environment.

**Comment by konrad-powazka** [comment] 2018-10-17 11:52
We need it badly as well. Any plans to implement it?

**Comment by davidrevoledo** [comment] 2018-11-05 14:47
This is a limitation, any ETA for this to be implemented  ?

**Comment by JasonBSteele** [comment] 2018-11-07 08:59
There is some hope as the user voce https://feedback.azure.com/forums/355860-azure-functions/suggestions/13882992-support-for-session-enabled-azure-service-bus-queu for this feature was updated on Oct 18 2018 to say that the work has been planned.

**Comment by delradie** [comment] 2018-11-13 00:02
The uservoice item just says planned. Given the comments about backlogged work (trust me, I understand, I'm currently on refactoring work that's been on our critical list for 2 years) I'm guessing this isn't going to be in the next couple of weeks?

It's unfortunately a huge blocker for us moving away from legacy features. How have other people worked around it?

**Comment by davidrevoledo** [comment] 2018-11-13 01:28
@delradie Currently I'm using a webjob and pooling manually from the session as for me ordering is a requirement to process the queue, the problem is that I need to run the code in a serverless fashion with an autoscaling a quite more aggresive than a webjob `scaling out rules` `Consumption plan` would be perfect for me.

**Comment by AlmuqrinBF** [comment] 2018-12-30 14:33
أيات القرآن الكريم مقياس المسلم وعقله وفائدته من 
 رابط الحاسوب

**Comment by AlmuqrinBF** [comment] 2018-12-30 14:43
الكمبيوتر رابط محسوب لخصوصية جهاز محميي 
و
2019net/رابط/رابط

**Comment by moueldi** [comment] 2019-01-10 15:22
@davidrevoledo  You can try this fork: [https://github.com/moueldi/azure-webjobs-sdk](url)
I had a new project called Microsoft.Azure.WebJobs.Extensions.ServiceBusSessions.
It could be published as a new nuget package.
Original version of servicebus extensions and this new package can be used together

**Comment by davidrevoledo** [comment] 2019-01-10 15:54
@moueldi awesome I was trying to do something similar but you are much more advanced, please Humbly with my limitations I offer you all the help you need.  💯

**Comment by moueldi** [comment] 2019-01-14 00:49
@davidrevoledo  thanks!
At the moment i'm wating some feedbacks of my implementation.
Webjob ServiceBus feature is coupled with WebJobSdk core project.
It's difficult to add new feature without refactoring.

So, i tried another approach by adding new project without changing common code.
May be is not the best solution for a Pull request, but the feature works for me.
I could provide a public nuget package as extension of Microsoft.Azure.WebJobs package

**Comment by koenveevee** [comment] 2019-02-08 09:04
Any update on foreseen availability of this feature?
We could really use this in order to partition messages by having an affinity based on a number of fields in the message.

**Comment by bartdk-be** [comment] 2019-02-15 18:55
*bump
For a special case we need ordered delivery as well.
Any update on when we can epxect sessionId support in functions ? (or when it will be added to the documentation :-/ )

**Comment by juchom** [comment] 2019-03-08 14:27
just it the issue too... any chance to have some info?

**Comment by brettsam** [comment] 2019-03-08 14:53
I'm going to close this issue as we have another one tracking the work, which will happen in the WebJobs SDK repo. See the latest comment here: https://github.com/Azure/azure-webjobs-sdk/issues/529#issuecomment-469821143

> Assigning this to sprint 45 for initial design and scoping

**Closed by brettsam** 2019-03-08 14:53 UTC
Labels: improvement, user voice
