### ISSUE TITLE
InvalidOperationException: No service for type 'Microsoft.Azure.WebJobs.Script.IScriptJobHost' has been registered.

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#3743] opened 2018-11-06 15:39 UTC
It looks like we have a race condition in HTTP requests where a request will sneak into the FunctionInvocationMiddleware when there is no job host running. My theory is that the host  shuts down shutting down immediately after the IsHostReady check is performed. Will need some investigation.

**Comment by mathewc** [comment] 2018-11-10 00:05
Funny - I was just logging an issue for this and this existing issue popped up. Here's the details I was adding to my incident:

Seeing null being returned on startup for system services that should be present. Likely we have a startup ordering issue with service registration. 

FunctionsLogs
| where AppName  =~ "netisomeas-prd-eastus-diag"
| where PreciseTimeStamp > datetime(2018-11-08 19:07:08.664) and PreciseTimeStamp < datetime(2018-11-08 19:07:11.557)
| project PreciseTimeStamp, Source, Level, FunctionName, Summary, Details 


System.InvalidOperationException : No service for type 'Microsoft.Azure.WebJobs.Script.IScriptJobHost' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider,Type serviceType)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at async Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<CreateBinderDelegate>g__Bind|0(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next,Scope& scope,Object& state,Boolean& isCompleted)
   at async Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by fabiocav** [comment] 2019-03-20 23:43
@mathewc moving this to the triaged milestone as I don't believe you'd be able to  look at this in 46.

**Comment by mathewc** [comment] 2020-01-15 19:27
Related to https://github.com/Azure/azure-functions-host/issues/5161 I believe

**Comment by LegacyChris** [comment] 2020-02-07 14:59
I am getting this same issue with my function app.

System.InvalidOperationException : No service for type 'Microsoft.Azure.WebJobs.Script.IScriptJobHost' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider,Type serviceType)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at async Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<CreateBinderDelegate>g__Bind|0(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next,Scope& scope,Object& state,Boolean& isCompleted)
   at async Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Can you please advice?

**Comment by LegacyChris** [comment] 2020-02-07 15:00
@brettsam @mathewc @fabiocav

**Comment by mathewc** [comment] 2020-02-07 17:38
Closing this issue as a dupe of https://github.com/Azure/azure-functions-host/issues/5161 which is assigned to @fabiocav . Last time we spoke on it he had a plan on how to fix.

**Closed by mathewc** 2020-02-07 17:38 UTC
