### ISSUE TITLE
StandbyMode WarmUp function being returned when Offline

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#5631] opened 2020-02-11 23:55 UTC
When transitioning from Online to Offline, it's possible to get the host into a situation where its ListFunctions API is returning the standby mode WarmUp function. This should never happen. Likely we're messing up the state transition from online to offline, and using the standby mode temp directory as the functions root.

If the following repro steps don't work the first time, rename/copy the offline file back and forth a few times. You'll see it. Repro might require that the app was specialized from placeholder.

Repro steps:

- start with a v2 function app with an HttpTrigger function. My app was 2.0.12961.0
- create an `xapp_offline.htm` file in your `D:\home\site\wwwroot` directory
- verify that the app is online by hitting the root of your site
- verify your correct function list is shown in the portal. hit refresh on the list a few times
- verify your functions are correct by hitting the admin endpoint directly `https://<yourapp>.azurewebsites.net/admin/functions?code=<masterKey>`
- now in Kudu copy the file to go offline, by running `copy xapp_offline.htm app_offline.htm`
- hit the root of the site. app should now be offline (offline page is shown). This may take a bit to refresh
- hit the admin endpoint to list functions again. WarmUp will be incorrectly returned. Might need to query this a few times to see it.
- in the portal, if you refresh the function list a few times, you'll see WarmUp there as well

**Comment by alrod** [comment] 2020-12-04 21:06
related [incident](https://portal.microsofticm.com/imp/v3/incidents/details/216923431/home)

**Comment by alrod** [comment] 2020-12-04 21:42
https://github.com/Azure/azure-functions-host/issues/5631

**Comment by fabiocav** [comment] 2021-01-06 21:38
@mathewc are you planning on addressing this or should we have it assigned to someone?

**Comment by fabiocav** [comment] 2021-01-20 21:22
Recent CRI handled by @alrod

**Comment by alrod** [comment] 2021-02-03 20:52
The issue is not reproducible in current runtime 3.0.15193

**Closed by alrod** 2021-02-03 20:52 UTC
