### ISSUE TITLE
Host Error with OpenTelemetry.Extensions.Hosting

### ISSUE THREAD

**Issue by kolanos** [Azure/azure-functions-host#7007] opened 2020-12-22 14:31 UTC
When running `func start --csharp` when using `OpenTelemetry.Extensions.Hosting` in a function-app it gives the following error:

```bash
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  DoNothingApp -> /Users/kolanos/Web/newrelic/DoNothingApp/DoNothingApp/bin/output/DoNothingApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.69


Azure Functions Core Tools
Core Tools Version:       3.0.3160 Commit hash: 00aa7f43cc5c5f15241b5e6e5363256f19ceb990
Function Runtime Version: 3.0.14916.0

[2020-12-22T14:13:36.225Z] A host error has occurred during startup operation '8ad1dca7-4289-4911-ac9e-ac29c0d56a6f'.
[2020-12-22T14:13:36.225Z] func: Invalid host services. Microsoft.Azure.WebJobs.Script.WebHost: The following service registrations did not match the expected services:
[2020-12-22T14:13:36.225Z]   [Invalid] ServiceType: Microsoft.Extensions.Hosting.IHostedService, Lifetime: Singleton, ImplementationType: OpenTelemetry.Extensions.Hosting.Implementation.TelemetryHostedService, OpenTelemetry.Extensions.Hosting, Version=1.0.0.1, Culture=neutral, PublicKeyToken=7bd6737fe5b67e3c.
```

See [here](https://github.com/nintexvictor/DoNothingApp) for an example function app using `OpenTelemetry.Extensions.Hosting`.

cc @fabiocav

**Comment by v-anvari** [comment] 2020-12-23 17:19
Hi @kolanos , I was able to reproduce the issue. " builder.Services.AddOpenTelemetryTracing( )" throws the exception. The error should be because Azure Functions doesn't allow to register any IHostedService as a part of your Startup operation.  

Explained in https://github.com/Azure/azure-functions-host/issues/5447#issuecomment-575368316

**Error:**

**_Line_**:  builder.Services.AddOpenTelemetryTracing((serviceProvider, tracerBuilder) ----Startup file 
**_Results:_**
◢ | ServiceType | {Name = "IHostedService" FullName = "Microsoft.Extensions.Hosting.IHostedService"} | System.Type {System.RuntimeType}
**_Exception:_**
| DeclaringMethod | '((System.RuntimeType)(new System.Linq.SystemCore_EnumerableDebugView<Microsoft.Extensions.DependencyInjection.ServiceDescriptor>(builder.Services).Items[60]).ServiceType).DeclaringMethod' threw an exception of type 'System.InvalidOperationException' | System.Reflection.MethodBase {System.InvalidOperationException}

I could get rid of the error and thus gaining a successful deployment by commenting out "[assembly: FunctionsStartup(typeof(FunctionApp1.Startup))]" from the startup file

@brettsam or @fabiocav, would you have any inputs on this

**Comment by fabiocav** [comment] 2021-02-17 21:59
Moving this to sprint 97, but we might be able to spend some time investigating in sprint 96.

**Comment by fabiocav** [comment] 2021-03-17 20:19
Similar change here: https://github.com/Azure/azure-functions-host/pull/6729

**Closed as completed** 2021-04-06 17:22 UTC
