### ISSUE TITLE
Custom properties are not logged using Application Insights 

### ISSUE THREAD

**Issue by jsacapdev** [Azure/azure-functions-host#8114] opened 2022-02-02 10:10 UTC
Using the guidance from the [Application Insights logging with .NET](https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#logging-scopes) an Azure Function (`net6.0` and `FUNCTIONS_WORKER_RUNTIME` of `dotnet-isolated`) does not log custom properties.

## Steps to reproduce

The function trigger looks as follows:

``` C#
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;
using Performance.AuthTokenConfigGenerator.FunctionApp.Error_Responses;
using System;
using System.Collections.Generic;

namespace TokenGenerator.Function
{
    public class TokenGeneratorHttpTrigger
    {
        private readonly ILogger _logger;

        public TokenGeneratorHttpTrigger(ILogger<TokenGeneratorHttpTrigger> logger)
        {
            _logger = logger;
        }

        [Function(Constants.TokenGeneratorHttpTrigger)]
        public IActionResult Run([HttpTrigger(AuthorizationLevel.Function, "get",
            Route="TokenGeneratorHttpTrigger/{emailId}")] HttpRequestData req, string emailId, FunctionContext executionContext)
        {
            try
            {
                using (_logger.BeginScope(new Dictionary<string, object> { ["MyKey"] = "MyValue" }))
                {
                    _logger.LogError("An example of an Error level message");
                }

                return new OkObjectResult(emailId);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "");

                return new InternalServerError(ex.Message);
            }
        }
    }
}
```

## Expected results

I should see a custom property logged in application insights associated with the error message `An example of an Error level message`

## Actual results

The custom properties section does not have the custom property I am trying to log:

![image](https://user-images.githubusercontent.com/10151920/151566161-dab36dbe-6baf-4f77-951a-a0c7847f3861.png)

#### csproj

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

#### Program.cs

``` C#
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace Performance.AuthTokenConfigGenerator.FunctionApp
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            var host = new HostBuilder()
               .ConfigureFunctionsWorkerDefaults()
               .Build();

            host.Run();
        }
    }
}
```

**Comment by v-bbalaiagar** [comment] 2022-02-08 11:46
Hi @jsacapdev , Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by timmkrause** [comment] 2022-03-02 10:31
Any updates about the findings? Considering to go back to .NET 6 with in-process hosting otherwise.

**Comment by timmkrause** [comment] 2022-03-03 07:36
Related: #7452

**Comment by Postlagerkarte** [comment] 2022-03-15 14:06
This is a blocker for many. @v-bbalaiagar can you throw us an update please?

**Comment by v-bbalaiagar** [comment] 2022-03-15 14:45
Hi @brettsam / @liliankasem , Could you please look into this issue

**Comment by andersson09** [comment] 2022-04-30 16:29
Just ran into the same issue.

**Comment by liliankasem** [comment] 2022-05-04 20:14
Was able to repro; I'll follow up with the team on next steps and provide an update

**Comment by fabiocav** [comment] 2022-05-04 20:37
Duplicate of #7452

**Closed as completed by fabiocav** 2022-05-04 20:37 UTC
