### ISSUE TITLE
Optional routing parameters not returning empty object, not type specific or undefined if not present

### ISSUE THREAD

**Issue by dustensalinas** [Azure/azure-functions-host#3577] opened 2018-10-08 23:29 UTC
Could have swore I logged this but cannot find.

Azure Functions - Runtime 2+ - HttpTrigger

function.json
  "bindings": [
    {
...
      "route": "whatever/{id:alpha?}/{action:alpha?}"
    },

Expectation if id and action not provided in route:
id is undefined or empty string as it is an optional alpha.  Could even be null.  Current behavior is it returns an empty object which is not alpha, is truthy and requires a type check that is not in line with its definition.

**Comment by mhoeger** [comment] 2018-10-10 15:38
Thanks for re-opening, I think this is a dupe of https://github.com/Azure/azure-functions-host/issues/3517? I'll close this issue in favor of your previous one.

**Closed by mhoeger** 2018-10-10 15:38 UTC
