### ISSUE TITLE
Trigger change detection and automatic synchronization

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#4033] opened 2019-01-30 17:32 UTC
The runtime should be enhanced to:

- Detect trigger configuration changes
- When changes are detected, automatically trigger a synchronization with the scale controller to ensure trigger information is up to date

This work will address a class of issues where the scale controller doesn't get notified of trigger changes, leading to activation failures.

**Comment by TechWatching** [comment] 2019-01-31 08:42
Does this mean that for now updates to timer trigger configuration are not correctly taken into account ? It could explain some strange behaviors I have.

If I change a timertrigger cron expression in the app settings of my function app (I am using the attribute TimerTrigger like this in my code : `TimerTrigger("%TimerInterval%")`), it seems that the function triggers at the previous times configured not at the one I just set.

**Comment by alrod** [comment] 2019-02-08 00:32
duplicate of #3565

**Closed by alrod** 2019-02-08 00:32 UTC
