### ISSUE TITLE
Queue triggered Azure function displays 'Critical availability error'.

### ISSUE THREAD

**Issue by spmanjunath** [Azure/azure-functions-host#8554] opened 2022-07-18 18:31 UTC
The 'Diagnose and solve problems' blade of an queue triggered Azure function displays 'Missing Application Settings detected' error.  It appears that the function is triggered as expected when an item is added to the queue, however, the error is concerning.  What could be the possible reasons of this error? (I couldn't find any relevant information in **Troubleshooting categories** section).

![image](https://user-images.githubusercontent.com/7764072/179577223-74794de4-195c-4df4-823a-8a2468dea8fe.png)
  
#### Investigative information

- Function App version: v4
- Function App name: spm-dev-func
- Region: Central US

#### Related information 
**Queue triggered function code:**
 ```
[Function("Function2")]
public void Run([QueueTrigger("%StorageSettings:queueName%", Connection = "StorageSettings")] QueueMessage queueMessage)
{
    _logger.LogInformation($"C# Queue trigger function processed: {queueMessage.Body}");
    Console.Write(queueMessage);
}
```
**Function app configuration:**
![image](https://user-images.githubusercontent.com/7764072/179577909-e4737f29-3879-4248-87c9-5e61f99248e4.png)

**Note**:  The Azure function uses Managed identity to connect to storage account (has Storage contributor access).

**Comment by Ved2806** [comment] 2022-07-19 07:09
Hi @spmanjunath, Please verify if you have configured the storage account connection string while adding queue message input or output bindings. Please go through this [document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings?tabs=csharp) and let us know if it helps. Thanks.

**Comment by spmanjunath** [comment] 2022-07-19 08:39
Hi @Ved2806, the host storage account connection string is configured properly, the Function app has a HttpTriggered function and Queue triggered function, both of them are triggered and working as expected.  However, the concern is related to the 'Critical error' alert seen in 'Diagnose and solve problems" blade.  FYI below are other relevant configurations,

![image](https://user-images.githubusercontent.com/7764072/179705815-f995fbde-3c0f-4d34-9d96-b7c9b8d0627b.png)
![image](https://user-images.githubusercontent.com/7764072/179705883-118c4dd7-1cc2-4a7f-92d4-3a8454302818.png)

I have removed AzureWebJobsStorage entry and replaced with MI based AzureWebJobsStorage_accountName.  Since the Function app is running on Consumption model i have retained `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` and `WEBSITE_CONTENTSHARE` as-is.

**Comment by spmanjunath** [comment] 2022-07-27 09:04
@Ved2806 Any update on this issue?

**Comment by mathewc** [comment] 2022-07-27 17:33
@spmanjunath so you're saying your function has managed identity configured correctly and is running fine? Might be a problem with the detector then, giving a false positive error. Looks like the detector isn't taking the managed identity setting naming pattern into consideration.

**Comment by spmanjunath** [comment] 2022-07-27 18:00
@mathewc - It could be the detector error, if so, it is good to get this resolved - not sure which team handles this.  It is difficult to ignore such errors.  Any suggestion on what should be the next steps?

**Comment by mathewc** [comment] 2022-07-27 18:20
I've started an internal discussion on this issue with @sidkri @FinVamp1 to determine the owner of the detector logic and if changes need to be made, thanks.

**Comment by snicro** [comment] 2023-01-18 09:42
any updates on this?
Seems related to https://github.com/Azure/azure-functions-host/issues/8520

**Comment by sidkri** [comment] 2023-01-24 00:24
Confirmed that this is caused due to lack of support for managed identity based access by the detector.  I'm looking into how to enhance the logic to account for this.

**Comment by sidkri** [comment] 2023-01-25 21:41
I have modified the risk alert logic so it should not report an issue when using managed identity anymore.  @spmanjunath If possible, please verify that the issue is no longer present and report back (and feel free to close the issue as well). Thanks.

**Comment by snicro** [comment] 2023-01-26 07:52
For me it is fixed. Thank you!

**Comment by spmanjunath** [comment] 2023-01-26 07:57
@sidkri I no longer see the incorrect error report.  So this seems to be fixed.  Thanks.

**Comment by sidkri** [comment] 2023-01-26 19:19
Great, thanks for confirming @snicro and @spmanjunath - I will close this issue now.

**Closed as completed by sidkri** 2023-01-26 19:19 UTC
Labels: needs-discussion, needs-investigation
