### ISSUE TITLE
Cannot bind parameter 'log' to type ILogger

### ISSUE THREAD

**Issue by vatsan-madhavan** [Azure/azure-functions-host#7528] opened 2021-07-07 01:21 UTC
#### Project configuration

- TFM: netcoreapp3.1 
  - Actual runtime: 5.0.202+ latestFeature
  - `AzureFunctionsVersion`: `v3`
- NuGet Packages (relevant)
  - Microsoft.NET.Sdk.Functions: 3.0.13
  - Microsoft.Azure.Functions.Extensions: 1.1.0
  - Microsoft.Extensions.Configuration.AzureAppConfiguration: 4.4.0
  - Microsoft.Extensions.Http
    - 5.0.0: **Problem** (see details below)
    - 3.1.16: **Ok**

#### `Startup.cs`

```C#
    internal class Startup : FunctionsStartup
    {
        /// <inheritdoc/>
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddHttpClient();
        }
    }
```

#### Function `Run` method (typical)

```C#
        [FunctionName(nameof(GetStuff))]
        [HttpPost]
        public async Task<IActionResult> RunPost(
            [HttpTrigger(AuthorizationLevel.Function, "POST", Route = null)] HttpRequest req,
            ILogger log,
            ExecutionContext context)
        {
            return await this.Run(req, log, context);
        }
```

#### Actual behavior

```
[2021-07-07T01:18:46.782Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'GetStuff'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'log' to type ILogger. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[2021-07-07T01:18:46.926Z] Error indexing method 'GetStuff'
[2021-07-07T01:18:46.928Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'GetStuff'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'log' to type ILogger. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[2021-07-07T01:18:46.929Z] Function 'GetStuff' failed indexing and will be disabled.
```

#### Known workarounds

Downgrade `Microsoft.Extensions.Http` to 3.1.16

#### Related information 

This issue seems nearly identical to #3854

**Comment by v-anvari** [comment] 2021-07-20 12:26
Hi @vatsan-madhavan , Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by v-anvari** [comment] 2021-07-23 11:05
Hi @vatsan-madhavan , I am trying to reproduce this scenario,  can I know what are you passing in the host.json file.

**Comment by vatsan-madhavan** [comment] 2021-07-27 16:38
That's what I have in host.json:

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      }
    }
  },
  "functionTimeout": "00:10:00"
}
```

**Comment by v-anvari** [comment] 2021-07-27 16:43
Thank you for the information, I shall try to repro with these details

**Comment by v-anvari** [comment] 2021-07-28 13:33
Hi @vatsan-madhavan , I am able to reproduce the issue, can we know what are you passing through get stuff, because I am also getting runtime error. Probably because of the startup file.

**Comment by vatsan-madhavan** [comment] 2021-07-28 23:50
My startup file is very basic. 

```c#
    internal class Startup : FunctionsStartup
    {
        /// <inheritdoc/>
        public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
        {
            // Initialize a KeyVaultClient instance
            // builder.ConfigurationBuilder.AddAzureKeyVault(/*key vault uri*/, keyVaultClient, new DefaultKeyVaultSecretManager());
        }

        /// <inheritdoc/>
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddHttpClient();
        }
    }
```

Realistically, `ConfigureAppConfiguration` is specific to my deployment and you shouldn't need it for repro.

**Comment by v-anvari** [comment] 2021-07-29 16:29
Hi @vatsan-madhavan , I confirmed with the team, and 5.X.X versions are supported only on .Net 5.0 which is a breaking change. So for .Net 3 please roll back to 3.X.X versions.

**Comment by vatsan-madhavan** [comment] 2021-07-29 16:32
Thanks for the note. 

Given that .NET Core 3.1 is an LTS release, does that mean that Microsoft.Extensions.Http 3.x.x will continue to be supported - notably with security updates - in the same manner as 5.x.x?

**Comment by v-anvari** [comment] 2021-07-30 09:16
Hi @vatsan-madhavan , Yes it will be supported in the future as well.

**Comment by v-anvari** [comment] 2021-07-30 09:47
Closing this issue as the required information is provided, please feel free to reach back to us or re-open this issue in case of any queries.

**Closed as completed by v-anvari** 2021-07-30 09:47 UTC
