### ISSUE TITLE
[RPC] Shutdown functions host if there are no language worker processes that can handle invocation request

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7462] opened 2021-06-15 18:26 UTC
This is a follow up from a CRI - short-term fix

As of now, if there are no initialized language worker processes to handle invocations, host throws - `Did not find any initialized language workers` error from:

https://github.com/Azure/azure-functions-host/blob/852eed9ceef6ef56b431428a8eb31f1bd9c97f3b/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcherLoadBalancer.cs#L27

Host should shutdown instead. This is similar to what happens here if starting language process fails

https://github.com/Azure/azure-functions-host/blob/852eed9ceef6ef56b431428a8eb31f1bd9c97f3b/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs#L117-L122

cc @AnatoliB @alrod

**Comment by pragnagopa** [comment] 2021-06-15 18:28
cc @fabiocav @brettsam @ankitkumarr fyi incase they see similar issue for dotnet-isolated functions

**Comment by pragnagopa** [comment] 2021-06-15 18:49
cc @ConnorMcMahon

**Comment by fabiocav** [comment] 2022-03-09 21:53
@pragnagopa I think we need to have a discussion on this to better understand the desired behavior. Can we block some time to walk through this proposal?

**Comment by pragnagopa** [comment] 2022-03-09 22:00
Reached out offline to @liliankasem - please setup sometime with me to go through issues that need my input. Thanks!

**Comment by fabiocav** [comment] 2022-03-23 20:36
I think this item needs additional discussion.

@pragnagopa are we expecting this issue to be transient, and a shutdown would help trigger a process restart to reinitialize the worker and host, hoping that would address the issue? If not, what is the expected behavior/experience from a user perspective

**Comment by liliankasem** [comment] 2022-03-24 19:59
I think all of these issues are made to address the same problem:

- #5233
- #5774
- #7463

I think the gist of all these conversations is that we shouldn't get to this error message in the first place as we shouldn't allow invocations when there isn't a worker process ready to use, meaning we should be dealing with this issue before we get to an invocation, not when a function is invoked, @pragnagopa is this understanding correct?

Technically, we only see this message during invocation since `InvokeAsync` is the only place I see us using `GetLanguageWorkerChannel`. But usually this is a symptom of something else going wrong further upstream, and that could be for many different issues (most common is the worker process not starting properly). For example:

- It could be a customer code issue e.g. `when referencing an environment variable in Program.cs that wasn't present in the Function app configuration settings.`, which leads the worker process to fail
- It could be a condition where the worker process does not reply to the host / doesn't initialize properly
    - The Function App is allocated a new instance
    - The Functions Runtime is initialized
    - It detects that this is a Function app and starts to Initialize the Java Language worker
    - This process starts but never completes initialization / replies back to the Functions host and so the process start request times out
    - The Functions Runtime detects that the worker channel has not started and logs the error message on further invocations

Some ideas for next steps:

1) We can further investigate how we get into this state in the first place and try and fix this at a higher level
    - Like in the process start timeout event, we should probably restart here to avoid getting to invocations?
1) We can update `InvokeAsync` or `GetLanguageWorkerChannel` to restart hoping it will solve the issue
    - Which is what this issue is suggesting we do?
    
In the case of customer code/project issues - restarting isn't going to help us. We just need to surface the problems to customers better so they can address those issues.

It might help to write out the valid situations/use cases where logging "Did not find any initialized language workers" is acceptable; however I remember @pragnagopa mentioning one time that this should never happen, and if it does there is a bug somewhere :)

**Comment by liliankasem** [comment] 2022-03-24 23:07
Here's an example of an [issue](https://github.com/Azure/azure-functions-host/issues/8167) that leads to the `Did not find any initialized language workers` error. Looking at the logs for this, we see the process worker exit (without details on why), but the function was still invoked before we restarted (a restart was signaled due to the worker process exit). In this scenario, it makes sense to output this error message, but I don't think restarting will help as the worker process will probably fail to start again (+ we are already requesting a restarting somewhere else in the code).

I guess the question is, can we identify the scenarios where restarting on an invocation would help?

```sql
// Central US Region
let st = datetime(2022-02-12T01:33:04.1202521Z)-2m;
let et =  datetime(2022-02-12T01:33:04.1202521Z)+1m;
FunctionsLogs
| where PreciseTimeStamp between (st .. et)
| where FunctionInvocationId == "f0bcf73d-0a3e-443b-bca4-bfd67024bb4c"
| project-reorder PreciseTimeStamp, AppName, Summary, Details, FunctionInvocationId, EventName
```

**Comment by pragnagopa** [comment] 2022-03-25 16:47
> I think the gist of all these conversations is that we shouldn't get to this error message in the first place as we shouldn't allow invocations when there isn't a worker process ready to use, meaning we should be dealing with this issue before we get to an invocation, not when a function is invoked, @pragnagopa is this understanding correct?

Yes, that would be the ideal state we should get to. In cases where initial process start fails or restarting worker fails - both scenarios should have predictable behavior - shutdown functions host to avoid invocations failing due to worker process not starting up

> It could be a customer code issue e.g. when referencing an environment variable in Program.cs that wasn't present in the Function app configuration settings., which leads the worker process to fail

Are you referring to Dotnet worker specifically? Ideally for rest of the workers process start up should not be affected by user's code. Good to distinguish scenarios here as we need to come up different fixes for user code vs host unable to start up worker process.

> It might help to write out the valid situations/use cases where logging "Did not find any initialized language workers" is acceptable; however I remember @pragnagopa mentioning one time that this should never happen, and if it does there is a bug somewhere :)

Yes, confirming my input here again :) Host should detect there are no worker channels that can handle invocation and continue to buffer the invocations 

Buffering during initial start up - https://github.com/Azure/azure-functions-host/blob/f315e6439d7ffb1214f585a3a8332c0771307cde/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs#L63

During worker process restarts  state is reset here https://github.com/Azure/azure-functions-host/blob/f315e6439d7ffb1214f585a3a8332c0771307cde/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L516

Function Dispatcher should be set to initialized again only after atleast one worker channel is ready to accept invocations here - https://github.com/Azure/azure-functions-host/blob/f315e6439d7ffb1214f585a3a8332c0771307cde/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L133

Please take a look if we are still missing a flow where the state is not being set / reset as expected - as long as the state is not initialized host should should not dispatch invocations.

**Comment by fabiocav** [comment] 2022-03-30 20:42
Adding @soninaren to help drive this forward. Additional investigation/design is required here so we can clearly identify the work we need to track.

**Comment by fabiocav** [comment] 2022-06-08 20:19
Investigation on this issue has been completed by @soninaren and different issues/tasks have been identified. This issue will be closed in favor of more granular issues with those details.

**Closed as completed** 2023-02-21 23:30 UTC
Labels: bug, feature:language-extensibility, pending-design
