### ISSUE TITLE
GenerateFunctionsExtensionsMetadata Revisited

### ISSUE THREAD

**Issue by Varada** [Azure/azure-functions-host#7317] opened 2021-04-26 07:14 UTC
1. My Azure function carries some native dlls along with it - this is legacy code, we don't trigger usage of these native functions, but unfortunately, I need to carry them along with the package.
2. My build system treats warning as errors - this is corporate policy 

On build, we get these warnings 

Could not evaluate 'concrt140.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid.
...

I suspect the role of this task is to create functions.json - is there a way I can tell it to ignore a set of dll's?

**Comment by v-anvari** [comment] 2021-04-27 10:18
Hi @Varada , Can we get more details about your project to understand the scenario better. It would be helpful if you could provide the repro steps

**Comment by v-anvari** [comment] 2021-04-29 16:40
Hi @Varada , I have confirmed this scenario internally and, unfortunately the only workaround is to ignore these build warnings. You may have to modify the project not to consider warnings as errors. This is also a duplicate of the issue - [https://github.com/Azure/azure-functions-host/issues/6899](https://github.com/Azure/azure-functions-host/issues/6899). This issue is already considered for a fix and the updates will be given in the mentioned issue.

We will be closing this as a duplicate if you do not have any further queries.

**Comment by v-anvari** [comment] 2021-05-04 13:02
Closing this issue as it is by-design, feel free to reach back to us in case of any issue

**Closed as completed by v-anvari** 2021-05-04 13:02 UTC
