### ISSUE TITLE
Function host shuts down during deployment and does not restart

### ISSUE THREAD

**Issue by MrGlenThomas** [Azure/azure-functions-host#2618] opened 2018-04-03 11:11 UTC
I deployed a new version of my function app (with timer triggered function) to Azure and the function host shut down and did not restart.

The deployment was performed by uploading a zip file via Kudu REST API to https://<myfunctionapp>.azurewebsites.net/api/zip/site/wwwroot

Before the deployment I am updating the application settings using an ARM template deployment that only specifies application settings. I have tried disabling this and problem still persists on each deployment.

#### Investigative information

Please provide the following:

- Timestamp: 2018-03-29T15:44:17.442
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: 
- Region: North Europe

Host InstanceId=4c6a93e5-27bd-4be3-99b6-c9f2410c961a

#### Repro steps

I deployed a new version of my function app from automated deployment system (Octopus), the log from this time is as follows:

2018-03-29T15:44:16.646 | Host configuration has changed. Signaling restart
2018-03-29T15:44:16.646 | File change of type 'Changed' detected for 'D:\home\site\wwwroot\host.json'
2018-03-29T15:44:16.646 | File change of type 'Changed' detected for 'D:\home\site\wwwroot\host.json'
2018-03-29T15:44:16.646 | File change of type 'Changed' detected for 'D:\home\site\wwwroot\host.json'
2018-03-29T15:44:16.646 | Host configuration has changed. Signaling restart
2018-03-29T15:44:16.646 | Host configuration has changed. Signaling restart
2018-03-29T15:44:17.163 | Stopping Host
2018-03-29T15:44:17.196 | Job host stopped
2018-03-29T15:44:17.196 | Singleton lock released (<myfunc>.Run.Listener)
2018-03-29T15:44:17.244 | Host 'c2b68e61c534c3f52578fc3f74540bc0' released lock lease.
2018-03-29T15:44:17.442 | Starting Host (HostId=<myfunctionapp>, Version=1.0.11612.0, InstanceId=4c6a93e5-27bd-4be3-99b6-c9f2410c961a, ProcessId=2488, AppDomainId=2, Debug=False, ConsecutiveErrors=0, StartupCount=2, FunctionsExtensionVersion=~1)
2018-03-29T15:44:17.442 | Reading host configuration file 'D:\home\site\wwwroot\host.json'
2018-03-29T15:44:17.442 | Host configuration file read: { "functionTimeout": "00:05:00", "functions": [], "tracing": { "consoleLevel": "verbose", "fileLoggingMode": "always" }, "logger": { "categoryFilter": { "defaultLevel": "Debug", "categoryLevels": { "Host": "Debug", "Function": "Debug", "Host.Aggregator": "Debug" } } }, "applicationInsights": { "sampling": { "isEnabled": true, "maxTelemetryItemsPerSecond": 5 } }, "healthMonitor": { "enabled": true, "healthCheckInterval": "00:00:10", "healthCheckWindow": "00:02:00", "healthCheckThreshold": 6, "counterThreshold": 0.8 } }
2018-03-29T15:44:17.462 | Environment shutdown has been triggered. Stopping host and signaling shutdown.

There are no further logs after that until 2018-04-03T10:03:19.788 when the function host started running again. The function host appears to have started running again when I interacted with the portal website and woken it up by accessing URI "/admin/host/status".

The startup log:

HOST LOG
2018-04-03T10:03:20.258 [Info] Executed HTTP request: {
  "requestId": "dcf922e3-4ebb-47f4-a5e5-133fb79022a5",
  "method": "GET",
  "uri": "/admin/host/status",
  "authorizationLevel": "Admin",
  "status": "OK"
}
2018-04-03T10:03:19.710 [Info] Starting Host (HostId=<myfunctionapp>, Version=1.0.11612.0, InstanceId=02d9996e-0485-4f1c-ae99-ed5a57abe816, ProcessId=2488, AppDomainId=3, Debug=True, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=~1)

FUNCTION LOG
2018-04-03T10:03:19.788 | Starting Host (HostId=<myfunctionapp>, Version=1.0.11612.0, InstanceId=02d9996e-0485-4f1c-ae99-ed5a57abe816, ProcessId=2488, AppDomainId=3, Debug=True, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=~1)
2018-04-03T10:03:19.849 | Reading host configuration file 'D:\home\site\wwwroot\host.json'
2018-04-03T10:03:19.849 | Host configuration file read: { "functionTimeout": "00:05:00", "functions": [], "tracing": { "consoleLevel": "verbose", "fileLoggingMode": "always" }, "logger": { "categoryFilter": { "defaultLevel": "Debug", "categoryLevels": { "Host": "Debug", "Function": "Debug", "Host.Aggregator": "Debug" } } }, "applicationInsights": { "sampling": { "isEnabled": true, "maxTelemetryItemsPerSecond": 5 } }, "healthMonitor": { "enabled": true, "healthCheckInterval": "00:00:10", "healthCheckWindow": "00:02:00", "healthCheckThreshold": 6, "counterThreshold": 0.8 } }
2018-04-03T10:03:20.145 | Host Status: { "id": "<myfunctionapp>", "state": "Default", "version": "1.0.11612.0" }
2018-04-03T10:03:22.416 | Loaded custom extension 'SendGridConfiguration'
2018-04-03T10:03:22.416 | Loaded custom extension 'BotFrameworkConfiguration'
2018-04-03T10:03:22.434 | Loaded custom extension 'EventGridExtensionConfig'
2018-04-03T10:03:24.641 | Host lock lease acquired by instance ID 'c2b68e61c534c3f52578fc3f74540bc0'.
2018-04-03T10:03:24.736 | Generating 1 job function(s)
2018-04-03T10:03:26.478 | Found the following functions: <myfunc>
2018-04-03T10:03:26.601 | Singleton lock acquired (<myfunc>.Run.Listener)
2018-04-03T10:03:26.945 | Job host started
2018-04-03T10:38:40.946 | Host Status: { "id": "<myfunctionapp>", "state": "Running", "version": "1.0.11612.0" }
2018-04-03T10:42:14.467 | Host Status: { "id": "<myfunctionapp>", "state": "Running", "version": "1.0.11612.0" }
2018-04-03T11:00:00.071 | Function started (Id=51852ce6-6397-4abf-af23-ac7faf69544c)

#### Expected behavior

After deploying a new version of my function app I expect the function host to restart and begin scheduling the timer trigger for my function.

#### Actual behavior

The log indicates that the host stopped and started, but then says "Environment shutdown has been triggered. Stopping host and signaling shutdown".

#### Known workarounds

None

#### Related information 

C# precompiled function app with timer triggered function.

**Comment by MrGlenThomas** [comment] 2018-04-03 14:03
This _**MAY**_ have been related to the "Always On" setting being Off. It did still happen once with the setting On, I am still testing...
The function host knows that I have timer triggered function, it has scheduled triggers, it would be great if I didn't have to configure the function app to not die...

**Comment by paulbatum** [comment] 2018-04-03 22:05
I looked at the logs for the timeframe you originally reported. In our logs, the last entry I see before the gap is:
```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.CreateStaticServices(JobHostConfiguration config)
   at Microsoft.Azure.WebJobs.JobHost.InitializeServices()
   at Microsoft.Azure.WebJobs.Script.Utility.CreateMetadataProvider(JobHost host) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 362
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 490
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHostManager.cs : 184
```

This looks like a bug on our side. However, the system should have recovered and your function should still have run **assuming that Always On was enabled**. It looks like during the window you reported, it was not enabled and that is a likely explanation for why your function did not run.

Now most recently you commented "still happening with Always On set to On". Can you give me the time range where you know you had it enabled but the timer was still not running as scheduled?

**Comment by MrGlenThomas** [comment] 2018-04-03 22:29
When I said it's still happening I was referring to seeing the log message "Environment shutdown has been triggered. Stopping host and signaling shutdown." I'm not sure if it would have triggered the function as I was using an hour interval and the next scheduled trigger was a while off. I will do some more testing and see if it triggers with "Always On" and the shutdown message being logged.

Is it recommended to stop the function app before deployment or using an alternative to kudu, like Azure CLI?

**Comment by paulbatum** [comment] 2018-04-03 22:46
That message appearing is fine. What should happen shortly after is a restart. 

Here are our recommended deployment options:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment
https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push

I want to call out that recommended REST API `https://<app_name>.scm.azurewebsites.net/api/zipdeploy` discussed here:
https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push#rest

This is **different** from the API you noted you're using above. You should switch. Also, stopping the app before deployment should not be necessary, in general (although it can help in obscure cases where there is some sort of file locking issue).

I reopened this issue since it tracks the error that put you in a bad state to begin with:
https://github.com/Azure/azure-functions-host/issues/1690

I'm going to close this issue since we have a root cause.

**Closed by paulbatum** 2018-04-03 22:46 UTC
