### ISSUE TITLE
Functions without a body will still consume queue messages

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-host#824] opened 2016-10-26 18:18 UTC
We got customer feedback that this was very confusing, because they created a new function by copying and pasting, but had not yet written any code. They then saw that the function had already started and was consuming the messages, so they had to manually add the items back to the queue.

I'll see if the customer can chime in to this thread and provide more context on the scenario.

**Comment by fabiocav** [comment] 2016-10-26 21:58
Had a few conversations with @paulbatum about this in the early days and the possibility of creating those functions in a disabled state.

**Comment by paulbatum** [comment] 2016-10-26 23:37
Yeah the problem is that defaulting to disabled is not very intuitive. Basically you'll have a bunch of cases where people forget to enable the function and are confused. Its possible that good UX could make this straightforward.

Plus its not clear how this would work when adding an integration to an existing function. e.g. Should the act of adding a queue trigger disable an existing function?

Other possibilities include:

- making the default template for a queue trigger throw an exception, but you'll end up with your messages being moved to a poison queue.
- add a feature that can require message consumption to be an explicit action and update the template to use this flag (perhaps with the code setting it to true commented out)

**Comment by mathewc** [comment] 2016-10-28 14:39
How about for consumption functions like this (queues, blobs, event hub, etc.) we could add UI when creating an integration that requires users to decide this - show a disable checkbox (disabled by default for these types of functions) with some descriptive help.

Then, we should also update the functions list left pane such that the icon shown indicates whether a function is enabled or disabled. I actually logged https://github.com/projectkudu/AzureFunctionsPortal/issues/482 for that a long time ago and it was backlogged :( I think it would help with this issue so maybe we should reconsider it.

**Comment by fabiocav** [comment] 2019-07-15 22:36
Closing this as it has not come up again as an issue in a while.

**Closed by fabiocav** 2019-07-15 22:36 UTC
Labels: needs-discussion
