### ISSUE TITLE
Remote host forcibly closing connection causing function timeout

### ISSUE THREAD

**Issue by yashrmaa** [Azure/azure-functions-host#6165] opened 2020-06-04 22:01 UTC
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

Host forcibly closing connection causing function timeout

#### Investigative information

Please provide the following:

- Timestamp: 2020-06-04T18:56:10.537Z
- Function App version: 2.0
- Function App name: debtmanagementfunction
- Function name(s) (as appropriate): ArtifactServiceSubscription
- Invocation ID: 1a4030de-680f-44b5-9637-dc303eccddff
- Region: West US

#### Repro steps

Provide the steps required to reproduce the problem:

1. You would need a valid subscription to Azure Artifact Service. Please contact me at yasharma@microsoft.com and I would create a new subscription.
2. Deploy function available at \\\yasharma-dev\Public_share\PortClosureRepro.zip to Azure.
3. Let the function run for about 12 hours.
4. Run this query in function app insights to find the invocation Id of the function.

FunctionAppLogs
| where ExceptionType == "Microsoft.Azure.WebJobs.Host.FunctionTimeoutException"
| distinct FunctionInvocationId
| join (FunctionAppLogs
| where Message contains "SocketException"
| distinct FunctionInvocationId)
on FunctionInvocationId

#### Expected behavior

Provide a description of the expected behavior.
Host shouldn't close network connection when the function is still executing.

#### Actual behavior

Provide a description of the actual behavior observed.
Host closing network connection.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source 
* Bindings used: Service Bus

**Comment by kashimiz** [comment] 2020-07-16 21:41
Hi @yashvardhan90, my apologies for the late reply. It looks like your function app is running on the consumption plan, which enforces an upper limit of 10 minutes on any function invocation's execution time. This is because function executions are (usually) intended to be very short.

For scenarios where you have a process that needs to run for longer periods of time, there are other hosting options, such as the premium and dedicated App Service plans ([see docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#consumption-plan)). For long-running stateful workflows, there's also the [Durable Functions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp) extension.

Closing this now as it appears this behavior is by design, but please open a new issue if you observe premature execution timeouts on a non-consumption plan.

**Closed as completed by kashimiz** 2020-07-16 21:41 UTC
