### ISSUE TITLE
Azure Function App Unable to decode JWT Headers

### ISSUE THREAD

**Issue by jcaineccp** [Azure/azure-functions-host#5595] opened 2020-02-05 06:17 UTC
I'm starting to automate more and more items on a schedule, so I thought I would make use of Azure and deploy my Powershell scripts in Azure Function Apps.  This took some modification to adapt to the slight change in scenery; however, I feel like my scripts should be running successfully at this point.  

I keep getting stuck when I issue commands to connect to Office 365 from azure using the secure model framework.  Apparently, something is missing or the wrong version and I can't get it to connect.  Please help me track down the issue so I can get past this.

First, I modified the requirements.psd1 file to include the MSOnline and PartnerCenter modules.  After restarting the app, it downloaded them successfully, 1.1.183.57 for MSOnline and 3.0.6 for PartnerCenter

Here is my Powershell Script:

Import-module -Name MSOnline
Import-module -Name PartnerCenter

$ApplicationId = 'REDACTED'
$ApplicationSecret = 'REDACTED' | Convertto-SecureString -AsPlainText -Force
$TenantID = 'REDACTED'
$RefreshToken = 'REDACTED'
$credential = New-Object System.Management.Automation.PSCredential($ApplicationId, $ApplicationSecret)

$aadGraphToken = New-PartnerAccessToken -ApplicationId $ApplicationId -Credential $credential -RefreshToken $refreshToken -Scopes 'https://graph.windows.net/.default' -ServicePrincipal -Tenant $tenantID 
$graphToken = New-PartnerAccessToken -ApplicationId $ApplicationId -Credential $credential -RefreshToken $refreshToken -Scopes 'https://graph.microsoft.com/.default' -ServicePrincipal -Tenant $tenantID 

Connect-MsolService -AdGraphAccessToken $aadGraphToken.AccessToken -MsGraphAccessToken $graphToken.AccessToken

$LastDay = (Get-Date).addhours(-24)

$customers = Get-msolpartnercontract -All
$ChangedUsers = @()
foreach($customer in $customers){
    write-host "getting users for $($Customer.Name)" -ForegroundColorGreen
    $adminemails = Get-MsolRoleMember -TenantId $customer.tenantid -RoleObjectId(Get-MsolRole-RoleName"CompanyAdministrator").ObjectId
    $Users = $adminemails | get-msoluser-TenantId$customer.TenantId
    foreach($User in $Users){
        if($User.LastPasswordChangeTimestamp -gt $LastDay){$ChangedUsers += "$($User.UserPrincipalName)has changed his password in the last 24 hours.Please update documentation to reflect.`n"}
    }
}

Running the script immediately returns this error block:
[Error] ERROR: Connect-MsolService : IDX10703: Unable to decode the 'header': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkhsQzBSMTJza3hOWjFXUXdtak9GXzZ0X3RERSIsImtpZCI6IkhsQzBSMTJza3hOWjFXUXdtak9GXzZ0X3RERSJ9' as Base64url encoded string. jwtEncodedString: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkhsQzBSMTJza3hOWjFXUXdtak9GXzZ0X3RERSIsImtpZCI6IkhsQzBSMTJza3hOWjFXUXdtak9GXzZ0X3RERSJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLndpbmRvd3MubmV0IiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNGM2ZjliYzMtYzQzMy00YTZmLTllNWUtZDlmZDgzMGQyMjZhLyIsImlhdCI6MTU4MDg4MzA0NywibmJmIjoxNTgwODgzMDQ3LCJleHAiOjE1ODA4ODY5NDcsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84T0FBQUE4WEl3N1I2bksvanNqbnAvUFZLOUtja1pGSFF1ekl6NVh5QVZYdmVkT3BKdnV4MGN0MTRGb1hnVjY5a3pNT2RIaTNDUkh3dXpCYWtCWTRRRjdSbjhoOEE0V2xLK0c2bm5FanRxQk9aMzI1cz0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiZDI5ZmFiNDQtNDAwOC00NjgzLWI2OWItODcyMWY3ODczNmRhIiwiYXBwaWRhY3IiOiIxIiwiZmFtaWx5X25hbWUiOiJDYWluZSIsImdpdmVuX25hbWUiOiJKYXNvbiIsImlwYWRkciI6IjEwNC4wLjM0LjgxIiwibmFtZSI6Ikphc29uIENhaW5lIiwib2lkIjoiZDYzNWIwOWItYzcyYS00NzZiLThhYTEtMWRmMjc5MzVmYzdiIiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTMzODI0MDE0NjEtMzAzMTMzMDE5Ni0zMjg4OTkwNTk4LTExMzMiLCJwdWlkIjoiMTAwMzNGRkY4NkJEQkJEMiIsInNjcCI6IkRpcmVjdG9yeS5BY2Nlc3NBc1VzZXIuQWxsIFVzZXIuUmVhZCIsInN1YiI6IjBqR0Z0bWUxT3pOUEotbmRfUlg4WG1zNjg2U295MGk4cEFxQWNzblQyT2ciLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiTkEiLCJ0aWQiOiI0YzZmOWJjMy1jNDMzLTRhNmYtOWU1ZS1kOWZkODMwZDIyNmEiLCJ1bmlxdWVfbmFtZSI6ImpjYWluZUBjY3B0ZWFtLmNvbSIsInVwbiI6ImpjYWluZUBjY3B0ZWFtLmNvbSIsInV0aSI6ImxjSkNzX3VjeDBpY3dlQkd1bFFtQUEiLCJ2ZXIiOiIxLjAifQ.IM_ueC0Ud6AiH62bcm2zGCCbwvKcxGyHJxKEHfoBrJDDEB6Cr2umiJXpraZK-Fw5UeDOB4aislWPegzKu1eDC4STXlPqdTjdKYRGMt6gJ9UYb20gT92f9IdUCMidU9AWx8p_ohYyrrmFz7o-7q_YQY6Hw6MfgY6W6rYA9yD4zWsMINJzdObfCXC76Fu13emmGdxGuoOxT59g-efrn-4bukayGzHWc-U3zS-NPdgY8YdsKrftTr2r7UZUTjP77D_dcbkMzFwzM0Mvj-rSpLUyDN8vOyFYH07aUBwWQcCbeP4kPMNoMv4RG95D3tByg1yXn-azvR-KTpG4kBPkg5-vsw'.
At D:\home\site\wwwroot\MonGlobalAdminPwd\run.ps1:27 char:1
+ Connect-MsolService -AdGraphAccessToken $aadGraphToken.AccessToken #- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [Connect-MsolService], ArgumentException
+ FullyQualifiedErrorId : System.ArgumentException,Microsoft.Online.Administration.Automation.ConnectMsolService
 
Script stack trace:
   at <ScriptBlock>, D:\home\site\wwwroot\MonGlobalAdminPwd\run.ps1: line 27

System.ArgumentException: IDX10703: Unable to decode the 'header': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkhsQzBSMTJza3hOWjFXUXdtak9GXzZ0X3RERSIsImtpZCI6IkhsQzBSMTJza3hOWjFXUXdtak9GXzZ0X3RERSJ9' as Base64url encoded string. jwtEncodedString: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkhsQzBSMTJza3hOWjFXUXdtak9GXzZ0X3RERSIsImtpZCI6IkhsQzBSMTJza3hOWjFXUXdtak9GXzZ0X3RERSJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLndpbmRvd3MubmV0IiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNGM2ZjliYzMtYzQzMy00YTZmLTllNWUtZDlmZDgzMGQyMjZhLyIsImlhdCI6MTU4MDg4MzA0NywibmJmIjoxNTgwODgzMDQ3LCJleHAiOjE1ODA4ODY5NDcsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84T0FBQUE4WEl3N1I2bksvanNqbnAvUFZLOUtja1pGSFF1ekl6NVh5QVZYdmVkT3BKdnV4MGN0MTRGb1hnVjY5a3pNT2RIaTNDUkh3dXpCYWtCWTRRRjdSbjhoOEE0V2xLK0c2bm5FanRxQk9aMzI1cz0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiZDI5ZmFiNDQtNDAwOC00NjgzLWI2OWItODcyMWY3ODczNmRhIiwiYXBwaWRhY3IiOiIxIiwiZmFtaWx5X25hbWUiOiJDYWluZSIsImdpdmVuX25hbWUiOiJKYXNvbiIsImlwYWRkciI6IjEwNC4wLjM0LjgxIiwibmFtZSI6Ikphc29uIENhaW5lIiwib2lkIjoiZDYzNWIwOWItYzcyYS00NzZiLThhYTEtMWRmMjc5MzVmYzdiIiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTMzODI0MDE0NjEtMzAzMTMzMDE5Ni0zMjg4OTkwNTk4LTExMzMiLCJwdWlkIjoiMTAwMzNGRkY4NkJEQkJEMiIsInNjcCI6IkRpcmVjdG9yeS5BY2Nlc3NBc1VzZXIuQWxsIFVzZXIuUmVhZCIsInN1YiI6IjBqR0Z0bWUxT3pOUEotbmRfUlg4WG1zNjg2U295MGk4cEFxQWNzblQyT2ciLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiTkEiLCJ0aWQiOiI0YzZmOWJjMy1jNDMzLTRhNmYtOWU1ZS1kOWZkODMwZDIyNmEiLCJ1bmlxdWVfbmFtZSI6ImpjYWluZUBjY3B0ZWFtLmNvbSIsInVwbiI6ImpjYWluZUBjY3B0ZWFtLmNvbSIsInV0aSI6ImxjSkNzX3VjeDBpY3dlQkd1bFFtQUEiLCJ2ZXIiOiIxLjAifQ.IM_ueC0Ud6AiH62bcm2zGCCbwvKcxGyHJxKEHfoBrJDDEB6Cr2umiJXpraZK-Fw5UeDOB4aislWPegzKu1eDC4STXlPqdTjdKYRGMt6gJ9UYb20gT92f9IdUCMidU9AWx8p_ohYyrrmFz7o-7q_YQY6Hw6MfgY6W6rYA9yD4zWsMINJzdObfCXC76Fu13emmGdxGuoOxT59g-efrn-4bukayGzHWc-U3zS-NPdgY8YdsKrftTr2r7UZUTjP77D_dcbkMzFwzM0Mvj-rSpLUyDN8vOyFYH07aUBwWQcCbeP4kPMNoMv4RG95D3tByg1yXn-azvR-KTpG4kBPkg5-vsw'.
   at System.IdentityModel.Tokens.JwtSecurityToken.Decode(String jwtEncodedString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityToken.cs:line 376
   at System.IdentityModel.Tokens.JwtSecurityToken..ctor(String jwtEncodedString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityToken.cs:line 72
   at Microsoft.Online.Administration.Automation.ConnectMsolService.MsolCmdletProcessRecord() in X:\bt\1067178\repo\src\dev\PowerShell.V1\modules\psmodule\Cmdlets\Connect-Service.cs:line 225

Inner exception: System.TypeLoadException: Could not load type 'System.Web.Util.Utf16StringValidator' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeString()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeMemberName()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(String input, Type targetType)
   at System.IdentityModel.Tokens.JsonExtensions.DeserializeJwtHeader(String jsonString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JsonExtensions.cs:line 123
   at System.IdentityModel.Tokens.JwtHeader.Base64UrlDeserialize(String base64UrlEncodedJsonString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtHeader.cs:line 251
   at System.IdentityModel.Tokens.JwtSecurityToken.Decode(String jwtEncodedString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityToken.cs:line 384

Any thoughts?

**Comment by fabiocav** [comment] 2020-02-07 01:02
@jcaineccp what version of Functions are you using?

**Comment by jcaineccp** [comment] 2020-02-07 02:10
Runtime version: 3.0.13107 (~3)

**Comment by fabiocav** [comment] 2020-02-07 23:59
@jcaineccp are you able to use the code above outside of the context of Functions with the same PS version?

@AnatoliB / @Francisco-Gamino looks like this module has a full framework dependency, is it expected to work?

**Comment by AnatoliB** [comment] 2020-02-08 00:36
> looks like this module has a full framework dependency, is it expected to work?

In general case, the answer is "no", as Functions run this code on PowerShell Core (specifically, PowerShell 6.2.3 now, and we'll be migrating to 6.2.4 soon).

However:
- There is a workaround: https://github.com/Azure/azure-functions-powershell-worker/issues/232#issuecomment-536744760. The workaround mentions the AzureAD module, but I know that some users applied it to MSOnline as well.
- PowerShell 7 is going to improve compatibility with modules relying on the full framework, and Functions are expected to support PowerShell 7 within the next few weeks. In the meantime, you can try running this code on PowerShell 7.rc2 locally, just to see if this will resolve the problem in the future.

**Comment by fabiocav** [comment] 2020-02-08 01:12
Thank you. @jcaineccp can you please follow the workaround provided.

Closing this as answered, but let us know if you have any problems.

**Closed by fabiocav** 2020-02-08 01:12 UTC
Labels: Needs: Author Feedback

**Comment by jcaineccp** [comment] 2020-02-08 05:11
@fabiocav I can run the exact same script from my Windows 10 PC without any issue.  I only have the issue when using Azure Functions to run the script.  
@AnatoliB I don't think that workaround applies here.  I did modify my script to include the proposed workaround; however, the exact same issue persists.  Do you know if the next version will support these modules properly?  We'd really like to automate a fair portion of our workload using Azure functions, but aren't able to like this.

I suppose I could use the task scheduler on my local system to schedule these tasks instead, but i'd rather use Azure.

**Comment by AnatoliB** [comment] 2020-02-08 06:47
@jcaineccp What version of PowerShell are you using to run this on your local PC? (You can retrieve the version from the `$PSVersionTable` variable.)

**Comment by jcaineccp** [comment] 2020-02-08 14:09
Sorry, I forgot you asked for that earlier.  Here's my local table:
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by AnatoliB** [comment] 2020-02-09 07:35
@jcaineccp So, you are actually running this code on **Windows** PowerShell locally. Azure Functons use PowerShell **Core** 6.2.3. You can install it from here: [32-bit](https://github.com/PowerShell/PowerShell/releases/download/v6.2.3/PowerShell-6.2.3-win-x86.msi)/[64-bit](https://github.com/PowerShell/PowerShell/releases/download/v6.2.3/PowerShell-6.2.3-win-x64.msi). If you get the same error locally, the problem is caused by the differences between the full .NET Framework and .NET Core. If your code keeps working on PowerShell Core, the problem is somewhere else.

**Comment by jcaineccp** [comment] 2020-02-10 16:40
Ah, it seems using Powershell Core locally gives the same error.  So we should wait for the latest version of Powershell Core and it hopefully supports these modules?

**Comment by fabiocav** [comment] 2020-02-10 18:53
@jcaineccp yes. This is an issue with the module and not specific to Azure Functions.

**Comment by jcaineccp** [comment] 2020-02-10 18:56
Sadness!

**Comment by AnatoliB** [comment] 2020-02-11 22:43
@jcaineccp You can find out if PowerShell 7 will solve this problem by installing the latest preview version from here: [32-bit](https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-rc.2/PowerShell-7.0.0-rc.2-win-x86.msi)/[64-bit](https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-rc.2/PowerShell-7.0.0-rc.2-win-x64.msi).

I'm a bit surprised that you are getting the same error with the workaround I mentioned earlier, though. It normally resolves issues of this kind. At the very least, I would expect a different exception or a different call stack. Do you mind sharing the code, just to make sure the workaround is applied properly? If the workaround is applied properly but you are still running into this issue, something else is going on.

**Comment by jcaineccp** [comment] 2020-02-12 14:24
Yeah, me too.  Thanks for the link to 7 preview.  Seems I get an entirely different issue in version 7.  It doesn't think I've called the Connect-MsolService cmdlet even though I have.  Yes, I switched the function bitness to 64-bit.  Here is the full code, it's very simplistic.

$PowerShell64bitPath = Get-ChildItem -Path $Env:Windir\WinSxS | Where-Object {$_.FullName -match "amd64_microsoft-windows-powershell-exe"}
$PowerShell64bitPath = Get-ChildItem -Path $PowerShell64bitPath.FullName -Filter PowerShell.exe | Select-Object -ExpandProperty FullName

Invoke-Command -ScriptBlock $script
& $PowerShell64bitPath -NoLogo -NoProfile -WindowStyle Hidden -NonInteractive -Command $Script

Import-module -Name MSOnline
Import-module -Name PartnerCenter

$ApplicationId = 'd29fab44-4008-4683-b69b-8721f78736da'
$ApplicationSecret = '5qzR3wPqaGlzjjzQ4/+AOv1N4DTLyak0759j35GC62c=' | Convertto-SecureString -AsPlainText -Force
$TenantID = '4c6f9bc3-c433-4a6f-9e5e-d9fd830d226a'
$RefreshToken = 'OAQABAAAAAABeAFzDwllzTYGDLh_qYbH8F1SSZdjuBdWNWLQouw-YZxR8Lh3G3YJlzAP-ZKC7CScBXKxpUDFzvNYM_ecQqg7ILEV3kMe_b1FTl9t1yOiNBCseJMus-cSDJy6bH4fgSWTKHU_D3jMNsvbtZ2Gk2EXJt0vigLasaM7tBg7ukSt3lVLhsjcyhkdxoV6FPurMBs-ovzyWqwAnuLTX2P7oh1PzNahmUTlYkfiUx81aEceYqNgZkh5661_YEsMhyXg7mHbQOzacIkoUKWtD6Hcu-v0jllHeshQZkdFM8-bIs7tuWtJcTS0TO9yf-Aia8mJuakfhXFf_eUxnmY1VTXoJhJ7SO3B9HbblyFvUHF_oMg1IyCgo7uUXjTWW1NHOSlz0WjFLcuRelyxBjtKbHEJ7_bBwc_eZdqUcVBJyFYQHRSVTuxrIeHo0e-FlgNOH0bs0EzTnGgsq9YxMNL3fYO3ujVFREIoczARYQLca6zapd6amNZT3xNK-QIEqPpnRn_D7JHmc49vMBFAsoTRRGH2wduu1Mid-57zsciQUOOK30EjXJ2oMg-VTU2QfAyITf_LhnSzrm_sL2Au2gQVH7_krrZDaEE45j2sQOCwb-iRmwrJ07K6vT_FHyjFkiQaJNAPdpKr5GBoXwuI7-RjlxPwhxju9Z7IXHEdhDRiSbzMl_BCXne15XMUtGs7y1fCYjKKWK9Qga_LB6WhyYqbrIWVVaMXu0gHYMpCm0Pjk4YjBfad1B7LT_HOLVacgC1lDrGcgy7UMH53aIyyzEG_AAp8eWvI44j1ULrQklPJJxoKMEcqOavID9OCk_rLGw42sIuQHQx7d7DR-jMQ0OvNEBjLqkDWVZWC30mbLzbkiFNa_AafEkyawvokeHwxdl563e1dBEwoYo7Jgz7fgQgSse0KfIQLa97texrGBAK33p_Hv95xFdlY-CrH4A7TtXHj7L_1eH45YgqHIFYEhKauAfZHTn5GM66yeRvYw61Y7YHUcN7lsIyAA'
$credential = New-Object System.Management.Automation.PSCredential($ApplicationId, $ApplicationSecret)

$aadGraphToken = New-PartnerAccessToken -ApplicationId $ApplicationId -Credential $credential -RefreshToken $refreshToken -Scopes 'https://graph.windows.net/.default' -ServicePrincipal -Tenant $tenantID 
$graphToken = New-PartnerAccessToken -ApplicationId $ApplicationId -Credential $credential -RefreshToken $refreshToken -Scopes 'https://graph.microsoft.com/.default' -ServicePrincipal -Tenant $tenantID 

Connect-MsolService -AdGraphAccessToken $aadGraphToken.AccessToken -MsGraphAccessToken $graphToken.AccessToken

$LastDay = (Get-Date).addhours(-24)

$customers = Get-msolpartnercontract -All
$ChangedUsers = @()
foreach($customer in $customers){
    write-host "getting users for $($Customer.Name)" -ForegroundColorGreen
    $adminemails = Get-MsolRoleMember -TenantId $customer.tenantid -RoleObjectId(Get-MsolRole-RoleName"CompanyAdministrator").ObjectId
    $Users = $adminemails | get-msoluser-TenantId$customer.TenantId
    foreach($User in $Users){
        if($User.LastPasswordChangeTimestamp -gt $LastDay){$ChangedUsers += "$($User.UserPrincipalName)has changed his password in the last 24 hours.Please update documentation to reflect.`n"}
    }
}

**Comment by jcaineccp** [comment] 2020-02-12 14:26
I didn't comment out the sensitive data; instead, I just modified it.

**Comment by AnatoliB** [comment] 2020-02-12 22:04
@jcaineccp The workaround does not seem to be applied correctly. I would expect the following code structure:

**profile.ps1** file:
``` PowerShell
$64bitPowerShellPath = Get-ChildItem -Path $Env:Windir\WinSxS -Filter PowerShell.exe -Recurse -ErrorAction SilentlyContinue | Where-Object {$_.FullName -match "amd64"}
$env:64bitPowerShellPath=$64bitPowerShellPath.VersionInfo.FileName
```

**run.ps1** file:
``` PowerShell
$Script={
    param ()
    
    # This is where the code using the MSOnline module is supposed to go
    # ...
}

&$env:64bitPowerShellPath -WindowStyle Hidden -NonInteractive -Command $Script
```

The idea of the workaround is to pass your script to Windows PowerShell (powershell.exe) for execution. Instead, your code just invokes powershell.exe with an empty scripblock, and then proceeds executing your original code on PowerShell Core the same way as before, running into the original issue as I would expect.

**Comment by jcaineccp** [comment] 2020-02-12 23:44
I completely misunderstood the workaround.  Ok, I think i'm on the right track, now I have a new error.  I saved the required commands into profile.ps1 and built my script to run inside the script box of the run.ps1 file.  

Here's the error now:

2020-02-12T23:43:01.062 [Error] ERROR: The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.

At D:\home\site\wwwroot\MonGlobalAdminPwd\run.ps1:45 char:2

+ &$env:64bitPowerShellPath -WindowStyle Hidden -NonInteractive -Comman ...

+  ~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException

+ FullyQualifiedErrorId : BadExpression

 

Script stack trace:

   at <ScriptBlock>, D:\home\site\wwwroot\MonGlobalAdminPwd\run.ps1: line 45

**Comment by AnatoliB** [comment] 2020-02-13 20:46
@jcaineccp You would get this error if `$env:64bitPowerShellPath` is empty. Try to print out its value from the function code, and please double-check the code that is supposed to initialize it in profile.ps1.
