### ISSUE TITLE
V2: Better error message when using invalid JavaScript

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-functions-host#2351] opened 2018-01-24 19:54 UTC
#### Investigative information

Please provide the following:

- Timestamp: `2018-01-24T19:31:17.546545401Z`
- Function App version (1.0 or 2.0-beta): 2.0-beta (linux, guess it is the beta)
- Invocation ID: 7607ee73-9b89-4e49-b62c-203d5a3cd6cc
- Region: East US
#### Repro steps

Provide the steps required to reproduce the problem:

Example: 

1. Create a function with HTTP input, type GitHub webhook.
2. Add blob output
3. Run the app.

#### Expected behavior

Provide a description of the expected behavior.

Blob created with the request body.

#### Actual behavior

Provide a description of the actual behavior observed.

An exception thrown, the logs are in this [gist](https://gist.github.com/omerlh/374e68ca0c6359f3e1d457397983cf19#file-logs-txt).

#### Related information 

Provide any related information 

* Programming language used Javascript
* Links to source
* Bindings used
<details>
<summary>Source</summary>

```javascript
module.exports = function (context, req, outputBlob) {
    context.log('JavaScript HTTP trigger function processed a request.');
    var event-id = "7";

    console.log(req);
    outputBlob = req.body;
    
    context.done();
};
```
</details><details>
<summary>function.json:</summary>
```json
{
  "bindings": [
    {
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "webHookType": "github"
    },
    {
      "type": "blob",
      "name": "outputBlob",
      "path": "outcontainer/{event-id}",
      "connection": "<>_STORAGE",
      "direction": "out"
    }
  ]
}
```
</details>

**Comment by omerlh** [comment] 2018-01-25 10:32
The issue was bug in the code:
```
var event-id = "7";
```
This is not a valid JS...
But I think the exception could be clearer...

**Comment by brettsam** [comment] 2018-01-26 19:30
Thanks, I'll update the title to reflect that we need a better error in this scenario.

**Comment by paulbatum** [comment] 2018-03-01 19:40
@christopheranderson Do you know if this is a dupe of one of the existing error handling bugs we have around out-of-proc?

**Comment by mhoeger** [comment] 2018-07-10 21:51
Closing as fixed, this is what the error message there looks like in V2.

```
Exception: Worker was unable to load function HttpTriggerJS1: 'SyntaxError: Unexpected token -'
Stack: D:\home\site\wwwroot\HttpTriggerJS1\index.js:5
    var event-id = "7";
             ^

SyntaxError: Unexpected token -
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18).
```

**Closed by mhoeger** 2018-07-10 21:51 UTC
Labels: 2.0, functions-v2-GA-musthave, lang-js, out-of-proc
