### ISSUE TITLE
Function App Fails with Local Storage Emulator on Mac

### ISSUE THREAD

**Issue by chrisrymer** [Azure/azure-functions-host#5214] opened 2019-11-07 17:27 UTC
#### Check for a solution in the Azure portal
I am trying to create a local dev environment on mac to write with Durable Functions. This requires a storage Emulator to be a self contained dev environment. I have been using Azurite but it doesn't seem to be able to connect to the emulator and fails.

#### Investigative information

Please provide the following:

- Timestamp: N/A
- Function App version (2.0): V2
- Function App name: https://github.com/chrisrymer/durable-function-azurite
- Function name(s) (as appropriate): DurableFunctionsOrchestratorJS
- Invocation ID: N/A
- Region: N/A

#### Repro steps

Provide the steps required to reproduce the problem:

1. Import the Repo
2. `npm install`
3. Install Azurite Extension for Mac (VS Code)
4. Start Azurite
5. `func start`
6. Got to `http://localhost:7071/api/orchestrators/DurableFunctionsOrchestratorJS` in browser

#### Expected behavior

Provide a description of the expected behavior.

Outputs test text to screen once page is loaded

'Hello Tokyo'
'Hello Seattle'
'Hello London'

#### Actual behavior

Function app fails
```
[06/11/2019 10:42:59] A host error has occurred during startup operation 'e18a940b-4851-4c6a-a832-10b08eb53352'.
[06/11/2019 10:42:59] Microsoft.WindowsAzure.Storage: cannotconnect.
```

#### Known workarounds

Use storage in Azure Portal

#### Related information 

Provide any related information 
* nodejs 8.11.x
* https://github.com/chrisrymer/durable-function-azurite
* More detailed info in the repo README
* Active ticket with Azurite https://github.com/chrisrymer/durable-function-azurite

**Comment by mhoeger** [comment] 2019-12-31 22:56
Hi @chrisrymer - the work is on the azure-functions-core-tools issue. I'm going to close this as a duplicate of https://github.com/Azure/azure-functions-core-tools/issues/1247.

**Closed by mhoeger** 2019-12-31 22:56 UTC
Labels: Needs: Triage (Functions)
