### ISSUE TITLE
Host thresholds exceeded: [Connections]

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-host#3781] opened 2018-11-15 08:33 UTC
Since a couple of days my function app is crashing after a while. 

Error:

The function runtime is unable to start. Microsoft.Azure.WebJobs.Script.WebHost: Host thresholds exceeded: [Connections]. For more information, see https://aka.ms/functions-thresholds.
Session Id: 6db3b79aa6f24b22aa73895db2f87c04

Timestamp: 2018-11-15T08:26:33.200Z

I don't see that I have too many connections anywhere in the code. How can I troubleshoot this?

#### Investigative information

Please provide the following:

- Function App version (1.0 or 2.0): 2
- Function App name: ecarcache
- Function name(s) (as appropriate): MasterDataCache
- Region: Europe West

**Comment by forki** [comment] 2018-11-15 08:48
all functions in that app look like the following:

![image](https://user-images.githubusercontent.com/57396/48540822-75f02180-e8bb-11e8-97d4-81db3a600dcf.png)

so we have one connection to Redis and one connection to Azure Storage

**Comment by forki** [comment] 2018-11-15 10:29
I moved some of the functions in that app to new functionapp ecarstats in order to see which half of the functions has that problem

**Comment by forki** [comment] 2018-11-30 06:15
@dallancarr believe me I'd love to remove that .wait but the runtime can't deal with `Task<unit>`yet. It's a reported bug and the azure-functions Team promised to look into that

**Comment by dallancarr** [comment] 2018-12-01 02:09
I've seen examples in the docs using Async. Is this a recent bug or regression because they recommend this pattern.

`let someFunc(...) =
async 
{
 let! result = PerformIOAsyncTask |> Async.AwaitTask
} |> Async.StartAsTask`

**Comment by forki** [comment] 2018-12-01 08:42
It's a regression in v2 runtime. It worked before. But AFAIK it's unrelated to this issue here.

**Comment by dallancarr** [comment] 2018-12-01 21:48
Yeah you are totally right but you could try returning `Task.CompletedTask` out of the function instead of `Wait` as the stats  have been cached already at that point.

**Comment by dallancarr** [comment] 2018-12-01 22:17
Ignore me this must be the regression. :-)

**Comment by brettsam** [comment] 2018-12-04 15:51
Could you give this a try with the latest Functions release [2.0.12210.0](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12210)? We added a workaround that should help here.

**Comment by forki** [comment] 2018-12-04 16:03
What would that workaround do?

Am Di., 4. Dez. 2018, 16:51 hat Brett Samblanet <notifications@github.com>
geschrieben:

**Comment by brettsam** [comment] 2018-12-04 16:12
A little background -- .NET Core made the `ServicePointManager` a no-op when it comes to HttpClient usage. We used this in Functions v1 to keep a constraint on the number of connections a single HttpClient could create to a single host (using `ServicePointManager.DefaultConnectionLimit`). This now does nothing in .NET Core. This means that the various SDKs now need to give us a way to control this by passing an `HttpClientHandler` into them (or exposing some other means of controlling [MaxConnectionsPerServer](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.maxconnectionsperserver?view=netcore-2.1)).

For Storage, specifically, we implemented a private-reflection workaround to change this setting back to 50, which is what it was in Functions v1: https://github.com/Azure/azure-functions-host/pull/3749. Our testing has shown this to work, but I'm trying to find all issues filed that look like this is the cause and see if we're missing any scenarios.

I don't see this error in your app for 2.0.12210, but that may not be related (you may be running with lower load, etc). Let me know if you're still seeing it, and I can take a deeper look.

**Comment by forki** [comment] 2018-12-04 16:16
Well I changed a lot of code to do better caching myself, so that's
probably the cause why it works right now...

Am Di., 4. Dez. 2018, 17:12 hat Brett Samblanet <notifications@github.com>
geschrieben:

**Comment by jeffhollan** [comment] 2019-02-27 07:37
Closing as we both increased the connection limit (600 active, 1200 total. Up from 300 total), in addition to the fixes Brett mentioned.  Ping if this should be reopened

**Closed by jeffhollan** 2019-02-27 07:37 UTC

**Comment by Mortana89** [comment] 2019-10-24 18:32
Hi @jeffhollan ,

We're noticing similar behavior on our azure functions triggered from Data Factory.
Under high load we get the same message, using .NET core functions.
Do we need to increase the limit of max connections somewhere, or is this a platform limit?

**Comment by jeffhollan** [comment] 2019-10-24 18:57
The most COMMON reason people hit this is because they are using improper connection instantiation.  So if you have like a SqlClient, don't create a new SqlClient per execution or you'll consume a ton of threads or connections.  Instead create a singleton shared SqlClient (either using like dependency injection or just `private static SqlClient` so that it can be re-used and pooled across executions.

Other than that and assuming you've done that, for now option would be moving to a higher plan type (Premium) where you get many more connections and threads available.

**Comment by tbasallo** [comment] 2019-11-21 12:43
I am running into the same issue inserting records into table storage using the Azure SDK. I currently use Task.WaitAll(tasks); for ~30K entries. Is this not supported since there's no supported way of queuing connections?

Running in a foreach, per item runs without issue.  However, the difference is 20 minutes vs 2 minutes (locally). And at 20 minutes, it doesn't finish in time before Functions throws a timeout error.

I don't need more powerful machines. Do I need to somehow be clever (keeping some kind of counter or delay), use orchestrated functions or is there something else?

**Comment by forki** [comment] 2019-11-21 12:47
A) do you batch insert? B) why don't you partionate in multiple function calls? Basically the idea is to fan out so that the infrastructure can scale for you, right?

**Comment by tbasallo** [comment] 2019-11-21 13:57
@forki ,

I can't batch because it's different partitions.
Partitioning is the orchestration I mentioned. I wonder if it would work or run into similar issues. If this works, I think this might be the best way.

**Comment by forki** [comment] 2019-11-21 13:59
Yes try to fan out into multiple azure function invocations.
