### ISSUE TITLE
Non-determenistic Extension loading with Custom Handler and Eventhub Output Binding

### ISSUE THREAD

**Issue by cldmstr** [Azure/azure-functions-host#6227] opened 2020-06-15 12:54 UTC
Since last week I've been having some strange behavior when deploying a function with an eventhub output binding.
Every time the function job is started on the host there is an about 50/50 chance that the the function can not be loaded with the following error:
```
2020-06-15T12:21:48.151 [Error] The 'hook' function is in error: The binding type(s) 'eventHub' were not found in the configured extension bundle. Please ensure the type is correct and the correct version of extension bundle is configured.
```

#### Investigative information

- Function App version: 2
- Function App name: -
- Region: West Europe
- Function name(s) (as appropriate): hook
Successful Startup
- Instance ID: 1b9eaf4714aeaa48fbb67cd0ceca0084
- Timestamp: 2020-06-15T11:27:17.201
Failed Startup
- Instance ID: 2a0213747367f547396a4721b13d6c25
- Timestamp: 2020-06-15T12:21:53.409

#### Repro steps

Deploy a basic go http handler service to a basic app service plan.
Create an eventhub and configure connection string on deployment of function.
Sample binding:
```
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "POST"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "type": "eventHub",
      "name": "$return",
      "eventHubName": "events",
      "connection": "eventhub_connection",
      "direction": "out"
    }
  ]
}
```

#### Expected behavior
Functions starts and answers calls reproducibly. 

#### Actual behavior
Function is not always started with an error, calls are answered with a 404 HTTP Code.

#### Known workarounds
None

#### Additional Information
host.json
```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
  "httpWorker": {
    "description": {
      "defaultExecutablePath": "my-func.exe"
    }
  },
  "logging": {
    "fileLoggingMode": "always",
    "logLevel": {
      "Function.hook": "Debug",
      "default": "Information"
    },
    "console": {
      "isEnabled": "true"
    }
  }
}
```

When successful the ApplicationInsightsLoggerOptions has an Eventhub block when printing to the log and not when the startup fails.
**Successful**
```
2020-06-15T11:27:10.233 [Information] ApplicationInsightsLoggerOptions
{
  "SamplingSettings": {
    "EvaluationInterval": "00:00:15",
    "InitialSamplingPercentage": 100.0,
    "MaxSamplingPercentage": 100.0,
    "MaxTelemetryItemsPerSecond": 20.0,
    "MinSamplingPercentage": 0.1,
    "MovingAverageRatio": 0.25,
    "SamplingPercentageDecreaseTimeout": "00:02:00",
    "SamplingPercentageIncreaseTimeout": "00:15:00"
  },
  "SamplingExcludedTypes": null,
  "SamplingIncludedTypes": null,
  "SnapshotConfiguration": null,
  "EnablePerformanceCountersCollection": true,
  "HttpAutoCollectionOptions": {
    "EnableHttpTriggerExtendedInfoCollection": true,
    "EnableW3CDistributedTracing": true,
    "EnableResponseHeaderInjection": true
  },
  "LiveMetricsInitializationDelay": "00:00:15",
  "EnableLiveMetrics": true,
  "EnableDependencyTracking": true
}
2020-06-15T11:27:10.235 [Information] LoggerFilterOptions
{
  "MinLevel": "None",
  "Rules": [
    {
      "ProviderName": null,
      "CategoryName": null,
      "LogLevel": null,
      "Filter": "<AddFilter>b__0"
    },
    {
      "ProviderName": null,
      "CategoryName": "Function.hook",
      "LogLevel": "Debug",
      "Filter": null
    },
    {
      "ProviderName": null,
      "CategoryName": null,
      "LogLevel": "Information",
      "Filter": null
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
      "CategoryName": null,
      "LogLevel": "None",
      "Filter": null
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
      "CategoryName": null,
      "LogLevel": null,
      "Filter": "<AddFilter>b__0"
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",
      "CategoryName": null,
      "LogLevel": "Trace",
      "Filter": null
    }
  ]
}
2020-06-15T11:27:10.262 [Information] LoggerFilterOptions
{
  "MinLevel": "None",
  "Rules": [
    {
      "ProviderName": null,
      "CategoryName": null,
      "LogLevel": null,
      "Filter": "<AddFilter>b__0"
    },
    {
      "ProviderName": null,
      "CategoryName": "Function.hook",
      "LogLevel": "Debug",
      "Filter": null
    },
    {
      "ProviderName": null,
      "CategoryName": null,
      "LogLevel": "Information",
      "Filter": null
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
      "CategoryName": null,
      "LogLevel": "None",
      "Filter": null
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
      "CategoryName": null,
      "LogLevel": null,
      "Filter": "<AddFilter>b__0"
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",
      "CategoryName": null,
      "LogLevel": "Trace",
      "Filter": null
    }
  ]
}
2020-06-15T11:27:10.262 [Information] FunctionResultAggregatorOptions
{
  "BatchSize": 1000,
  "FlushTimeout": "00:00:30",
  "IsEnabled": true
}
2020-06-15T11:27:10.262 [Information] SingletonOptions
{
  "LockPeriod": "00:00:15",
  "ListenerLockPeriod": "00:01:00",
  "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
  "LockAcquisitionPollingInterval": "00:00:05",
  "ListenerLockRecoveryPollingInterval": "00:01:00"
}
2020-06-15T11:27:10.263 [Information] HttpOptions
{
  "DynamicThrottlesEnabled": true,
  "MaxConcurrentRequests": 100,
  "MaxOutstandingRequests": 200,
  "RoutePrefix": "api"
}
2020-06-15T11:27:10.263 [Information] EventHubOptions
{
  "BatchCheckpointFrequency": 1,
  "EventProcessorOptions": {
    "EnableReceiverRuntimeMetric": false,
    "InvokeProcessorAfterReceiveTimeout": false,
    "MaxBatchSize": 10,
    "PrefetchCount": 300,
    "ReceiveTimeout": "00:01:00"
  },
  "PartitionManagerOptions": {
    "LeaseDuration": "00:00:30",
    "RenewInterval": "00:00:10"
  }
}
```

**Failed**
```
2020-06-15T12:21:47.724 [Information] ApplicationInsightsLoggerOptions
{
  "SamplingSettings": {
    "EvaluationInterval": "00:00:15",
    "InitialSamplingPercentage": 100.0,
    "MaxSamplingPercentage": 100.0,
    "MaxTelemetryItemsPerSecond": 20.0,
    "MinSamplingPercentage": 0.1,
    "MovingAverageRatio": 0.25,
    "SamplingPercentageDecreaseTimeout": "00:02:00",
    "SamplingPercentageIncreaseTimeout": "00:15:00"
  },
  "SamplingExcludedTypes": null,
  "SamplingIncludedTypes": null,
  "SnapshotConfiguration": null,
  "EnablePerformanceCountersCollection": true,
  "HttpAutoCollectionOptions": {
    "EnableHttpTriggerExtendedInfoCollection": true,
    "EnableW3CDistributedTracing": true,
    "EnableResponseHeaderInjection": true
  },
  "LiveMetricsInitializationDelay": "00:00:15",
  "EnableLiveMetrics": true,
  "EnableDependencyTracking": true
}
2020-06-15T12:21:47.725 [Information] LoggerFilterOptions
{
  "MinLevel": "None",
  "Rules": [
    {
      "ProviderName": null,
      "CategoryName": null,
      "LogLevel": null,
      "Filter": "<AddFilter>b__0"
    },
    {
      "ProviderName": null,
      "CategoryName": "Function.hook",
      "LogLevel": "Debug",
      "Filter": null
    },
    {
      "ProviderName": null,
      "CategoryName": null,
      "LogLevel": "Information",
      "Filter": null
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
      "CategoryName": null,
      "LogLevel": "None",
      "Filter": null
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
      "CategoryName": null,
      "LogLevel": null,
      "Filter": "<AddFilter>b__0"
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",
      "CategoryName": null,
      "LogLevel": "Trace",
      "Filter": null
    }
  ]
}
2020-06-15T12:21:47.725 [Information] LoggerFilterOptions
{
  "MinLevel": "None",
  "Rules": [
    {
      "ProviderName": null,
      "CategoryName": null,
      "LogLevel": null,
      "Filter": "<AddFilter>b__0"
    },
    {
      "ProviderName": null,
      "CategoryName": "Function.hook",
      "LogLevel": "Debug",
      "Filter": null
    },
    {
      "ProviderName": null,
      "CategoryName": null,
      "LogLevel": "Information",
      "Filter": null
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
      "CategoryName": null,
      "LogLevel": "None",
      "Filter": null
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
      "CategoryName": null,
      "LogLevel": null,
      "Filter": "<AddFilter>b__0"
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",
      "CategoryName": null,
      "LogLevel": "Trace",
      "Filter": null
    }
  ]
}
2020-06-15T12:21:47.726 [Information] FunctionResultAggregatorOptions
{
  "BatchSize": 1000,
  "FlushTimeout": "00:00:30",
  "IsEnabled": true
}
2020-06-15T12:21:47.732 [Information] SingletonOptions
{
  "LockPeriod": "00:00:15",
  "ListenerLockPeriod": "00:01:00",
  "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
  "LockAcquisitionPollingInterval": "00:00:05",
  "ListenerLockRecoveryPollingInterval": "00:01:00"
}
2020-06-15T12:21:47.732 [Information] HttpOptions
{
  "DynamicThrottlesEnabled": true,
  "MaxConcurrentRequests": 100,
  "MaxOutstandingRequests": 200,
  "RoutePrefix": "api"
}
```

**Comment by pragnagopa** [comment] 2020-06-15 17:22
cc @yojagad 
@jackharbinger - Can you please share `host.json`?

**Comment by cldmstr** [comment] 2020-06-15 17:45
Updated main issue with my host.json. This is the same configuration that I have used since the beginning based on the examples and it worked fine until I started redeploying some updates last week: https://github.com/Azure-Samples/functions-custom-handlers

I also tried using "customHandler" instead of "httpWorker" as I found in this issue, but that didn't work at all as it couldn't find the executable any more:
https://github.com/Azure/azure-functions-host/issues/6080

**Comment by pragnagopa** [comment] 2020-06-15 17:49
thanks. We will investigate. Please continue using `httpWorker` for now. Changes that support `customHandler` section are not rolled out to production yet.

**Comment by yojagad** [comment] 2020-06-15 19:00
@jackharbinger Can you try to downgrade extensionBundle by updating host.json as below and let us know if you still face the same issue?

```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 1.2.0)"
  },
  "httpWorker": {
    "description": {
      "defaultExecutablePath": "my-func.exe"
    }
  },
  "logging": {
    "fileLoggingMode": "always",
    "logLevel": {
      "Function.hook": "Debug",
      "default": "Information"
    },
    "console": {
      "isEnabled": "true"
    }
  }
}
```

**Comment by cldmstr** [comment] 2020-06-16 08:28
Thanks for the suggestions.
I'm afraid that the downgrade didn't solve the problem. I'm still seeing the same pattern of sometimes working and sometimes failing with the same error as before.

**Comment by cldmstr** [comment] 2020-06-16 08:36
Looking through the host logs it seems that if on `Host Initialization` the StartupCount is > 1 the extension bundle isn't picked up and when it is =1 the function works:

**Successful**
```
2020-06-15T11:27:10.027 [Information] Initializing Warmup Extension.
2020-06-15T11:27:10.143 [Information] Initializing Host. OperationId: 'cdc65bff-6531-496b-9ff8-993dd5c4f4fe'.
2020-06-15T11:27:10.163 [Information] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=cdc65bff-6531-496b-9ff8-993dd5c4f4fe
```
**Failed**
```
2020-06-15T12:21:47.670 [Information] Initializing Warmup Extension.
2020-06-15T12:21:47.713 [Information] Initializing Host. OperationId: '37d55f22-e71b-4c4a-beeb-9b7675b042b7'.
2020-06-15T12:21:47.714 [Information] Host initialization: ConsecutiveErrors=0, StartupCount=3, OperationId=37d55f22-e71b-4c4a-beeb-9b7675b042b7
```
Not sure what that means, but it seems to consistently predict success or failure.

**Comment by yojagad** [comment] 2020-06-19 23:47
W're still investigating this. Can you pin your runtime version to 3.0.13353 while we continue investigating and let us know if you still encounter it ?

**Comment by ZachTB123** [comment] 2020-06-20 01:09
Seeing a similar issue. I recently recreated a function that was working last week but now I am frequently seeing the following errors in App Insights:

- The 'diagnostic_logs' function is in error: The binding type(s) 'eventHubTrigger' were not found in the configured extension bundle. Please ensure the type is correct and the correct version of extension bundle is configured.
- No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

`host.json` is:

```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
  "extensions": {
    "eventHubs": {
      "batchCheckpointFrequency": 1,
      "eventProcessorOptions": {
        "maxBatchSize": 512,
        "prefetchCount": 1024
      }
    }
  },
  "httpWorker": {
    "description": {
      "defaultExecutablePath": "function"
    }
  }
}

```

`function.json` is:

```
{
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "events",
      "direction": "in",
      "eventHubName": "diagnostic-logs",
      "consumerGroup": "lp-cl-consumer-group",
      "cardinality": "many",
      "dataType": "string",
      "connection": "DIAGNOSTIC_LOGS_EVENT_HUB_CONNECTION_STRING"
    }
  ]
}
```

Runtime version is 3.0.13901.0 (~3).

**Comment by yojagad** [comment] 2020-06-20 01:31
@ZachTB123 As I mentioned above, can you pin the runtime to 3.0.13353 and let us know if you still encounter it?

**Comment by cldmstr** [comment] 2020-06-22 13:59
> W're still investigating this. Can you pin your runtime version to 3.0.13353 while we continue investigating and let us know if you still encounter it ?

Sorry if I'm being a bit dense, but where do I pin that specific version? Is that a setting in the host.json or do I set that when configuring the function itself? I just see that I'm running on 3.0.13901 at the moment.

**Comment by pragnagopa** [comment] 2020-06-22 15:22
@jackharbinger / @ZachTB123 - Please see intructions [here](https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version#automatic-and-manual-version-updates) on how to pin to functions runtime version.

**Comment by ZachTB123** [comment] 2020-06-22 16:05
@pragnagopa I can't seem to pin my runtime version to `3.0.13353.0`. I created a brand new Function App and made sure `FUNCTIONS_EXTENSION_VERSION` is set to `3.0.13353.0`, but the portal shows that my runtime version is `2.0.13907.0`. After further investigation under `Function app settings` in the portal I see:

"Runtime version loaded from Application Settings: 3.0.13353.0" and "Unsupported Runtime Version, Your custom runtime version is not supported. As a result 2.0.13907.0 runtime is being used."

**Comment by pragnagopa** [comment] 2020-06-22 16:52
@ZachTB123  - Not sure why pinning is not working. I just tried and cannot repro the issue you mentioned.

cc @soninaren - fyi

Another workaround for this issue is not use extension bundles and install bundles using core tools
On your local machine
- [Install azure function core tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash)
- cd to your function app folder ( folder with `host.json`)
- Remove  `extensionBundle` element from `host.json`
- Run command `func extensions install` . This will generate extensions needed for your function app `bin` directory. 
- Deploy the function.

**Comment by yojagad** [comment] 2020-06-23 04:46
We were able to reproduce and identify the cause of the issue. We're working on figuring out what the right fix is and get it out.

**Comment by pragnagopa** [comment] 2020-06-23 14:21
@fabiocav  - this is a regression. Moved to current sprint as we should get the fix in for the next release.

**Comment by yojagad** [comment] 2020-06-24 02:16
@ZachTB123 @jackharbinger The fix is checked in and will go out with the next function release.

**Closed as completed** 2020-06-24 02:15 UTC
Labels: bug, httpWorker

**Comment by cldmstr** [comment] 2020-06-25 06:28
Thanks a lot for the quick fix!
