### ISSUE TITLE
Unhandled exception: access to disposed logger factory 

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#1690] opened 2017-07-19 16:33 UTC
With app insights enabled, I've seen the following failures when executing HTTP triggered functions from the portal:

```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager.HandleRequestAsync(FunctionDescriptor function,HttpRequestMessage request,CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebScriptHostManager.cs : 183
   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.ProcessRequestAsync(HttpRequestMessage request,FunctionDescriptor function,CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Controllers\FunctionsController.cs : 110
   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.<>c__DisplayClass3_0.<ExecuteAsync>b__0(??) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Controllers\FunctionsController.cs : 57
   at async Microsoft.Azure.WebJobs.Extensions.Http.HttpRequestManager.ProcessRequestAsync(HttpRequestMessage request,Func`3 processRequestHandler,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.ExecuteAsync(HttpControllerContext controllerContext,CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Controllers\FunctionsController.cs : 59
   at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)
   at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.SystemTraceHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Handlers\SystemTraceHandler.cs : 50
   at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.WebScriptHostHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Handlers\WebScriptHostHandler.cs : 63
   at async System.Web.Http.HttpServer.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)
```

Unfortunately I don't have a reliable repro - I suspect there is a race. I'm also not sure yet if this is a script level bug or a SDK bug.

**Comment by fabiocav** [comment] 2017-07-20 19:11
@cgillum had this issue reported in the context of Durable Functions as well.

Took a quick look at this and the issue seems to be caused by the fact that our config is reused across different host instances, and the ILoggerFactory is associated with that config, but when the host restarts (for any reason), it's dispose logic ultimately disposes of the factory (by disposing of the context, which in turn disposes of the factory here https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Executors/JobHostContext.cs#L99), leaving it in a disposed state.
Once the config is passed into the next instance of the host, we'll start seeing these failures.

**Comment by fabiocav** [comment] 2017-07-20 19:14
@brettsam / @mathewc / @MikeStall , this is another example of our mutating config object reuse/DI issues biting us.

**Comment by brettsam** [comment] 2017-07-24 22:03
Thanks for looking @fabiocav -- I'm taking a look at this now.

While we do reuse the ScriptHostConfiguration, we create a new JobHostConfiguration with every new ScriptHost. That should mean that we get a new LoggerFactory with each new ScriptHost. I also can't seem to figure out why it wouldn't happen every time if we're re-using disposed LoggerFactories. I'm trying to repro this in the portal now but I've not been able to hit it yet.

@paulbatum -- how often were you seeing the issue? Did you have incoming requests at the same time, or were you only issuing requests via the portal?

**Comment by cgillum** [comment] 2017-07-24 22:11
FWIW, in the case of Durable Functions the issue goes away if we set the `FUNCTIONS_EXTENSION_VERSION` app setting to `1.0.11015` and restart the function app.

**Comment by brettsam** [comment] 2017-07-24 22:29
@cgillum -- that's b/c I just (re-)added the LoggerFactory disposal with this latest release. We thought we'd fixed the issue with PR #1575, but it's obviously not fully fixed. This HttpTrigger path looks just like the bug we were trying to fix; the Orchestrator one looks completely different.

The common thread is that these seem to be coming via the Portal. 

The easy temp fix is to remove the disposal until we can iron this out. I'll do this if I can't get a real fix in place before our next release.

**Comment by brettsam** [comment] 2017-07-24 23:26
I see a couple of problems with our fix for #1575 that could cause races -- I'm going to remove the LoggerFactory disposal until we can figure out a solid way to prevent running functions on disposed hosts.

**Comment by brettsam** [comment] 2017-07-25 16:32
@cgillum -- so it looks like PR https://github.com/Azure/azure-webjobs-sdk/pull/1192 was actually included in 11015 (it went in a couple days before the release). So I'd guess that you're still exposed to the bug being pinned to this build. The errors that @paulbatum was seeing were run on 11015 as well, which confirms it. It makes me think that the restart of the function app was the important piece in your scenario and you were somehow hitting a race. If you move back to ~1, do you see the bug?

For the issue that @paulbatum is seeing -- the fix for #1537 watches the `CanInvoke` property of the `ScriptHostManager` and makes sure we don't run any HTTP functions while it is false. However, in his logs, I can clearly see a `Job host stopped`, followed a couple seconds later by a wave of HttpTrigger functions being executed and hitting the disposed object exception. Then, shortly after, the host starts back up. Somehow that `CanInvoke` check must not be protecting us. 

It may be b/c we're not setting the Host state to `Default` quick enough. It feels like we should be setting it before we stop the current host, to make sure that no new requests come in after we call Dispose -- [here ](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Host/ScriptHostManager.cs#L122)you can see we don't set it until the loop continues. On a single-core machine, this may be more problematic than on our dev machines. We may want to make sure to set it before the call to `Orphan`, [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Host/ScriptHostManager.cs#L178).

There's another problem, too. [Our usage of the LoggerFactory in Autofac](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script.WebHost/App_Start/AutofacBootstrap.cs#L33) means that it's possible for us to grab the LoggerFactory from a disposed host and pass it to a controller, which also throws. I'll need to address that before re-enabling the LoggerFactory disposal as well.

None of this explains https://github.com/Azure/azure-functions-durable-extension/issues/10. I'm going to start digging into that to see if it is related to either of the issues I've identified here.

**Comment by cgillum** [comment] 2017-07-25 17:19
Strangely, I haven't been able to repro it this morning on ~1.  A few days ago it was a 100% repro, which supports the idea that this could be a race condition (I'm wondering if noisy neighbors could also have a potential impact - making it even less predictable).

**Comment by fabiocav** [comment] 2017-07-26 17:11
@brettsam I'm hoping this issue will be resolved by the DI work we're planning on doing. That factory shouldn't be disposed by the context, and with the plans we have, the lifetime of that object should be properly managed outside of it.

**Comment by brettsam** [comment] 2017-07-26 18:06
@fabiocav -- we'll need to chat about the DI lifecycle of the LoggerFactory. Any changes to host.json mean we need to recreate it, for example. So it can't really live with the full lifecycle of the ScriptHostManager. And disposing it forces a flush, which works well for WebJobs scenarios (that's why it's disposed when the host stops).

But -- more related to this issue -- my bigger concern was that we're still running functions on stopped, disposed hosts. It looks like the HttpTrigger still isn't fully prevented from dispatching jobs to the old host during a restart. Even if the LoggerFactory wasn't disposed, any other disposed objects could be in play. It just so happens that we access the LoggerFactory with every invocation, hence the obvious exception.

**Comment by brettsam** [comment] 2017-09-06 22:34
I've re-added LoggerFactory disposal and (once again) gotten a reliable repro here. It seems to happen consistently in Consumption plans; I'm assuming due to the fact that you're running in the sandbox on a single core.

Writing this up for future reference.

My setup is an app with 2 functions and a custom site extension that disposes of the LoggerFactory and also adds some logging so we can see when the state of the ScriptHostManager changes and also when we start to dispose the host. The HTTP triggers watch the ScriptHostManager state to know if they can dispatch functions to it, so I wanted to see if the timing was off.

I have one simple HttpTrigger that just returns after a short 250ms delay. And another TimerTrigger that touches host.json every 10 seconds to force the host to restart. I then issue ~10 RPS to that Http function from my local machine.

I can see that we get logs like:
- Stopping Host
- Job host stopped
- Disposing ScriptHost
- *lots of errors about disposed LoggerFactory*
- Changed state from 'Running' to 'Default'

Because we fire-and-forget the disposal, we expect that we'll be changing the ScriptHostManager state from 'Running' to 'Default' very quickly. But in reality, it's a race. We should be able to change the ScriptHostManager state *before* we fire-and-forget, which should lock this down. I'm going to be doing some longer-term testing with and without the fix to compare.

**Comment by simonness** [comment] 2018-03-09 09:57
Hi @brettsam,

Sorry to drag up an old issue.  I'm still seeing this exception from time to time:

```
Microsoft.Azure.WebJobs.JobHost.StartAsync, Microsoft.Azure.WebJobs.Host, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock, Microsoft.Azure.WebJobs.Script, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, line: 182, fileName: C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHostManager.cs
```

The exception in Application Insights says `sdkVersion | azurefunctions: 1.0.11559.0`.  An invocation id from my function running in WestEurope `54b0990b-794e-481c-9f86-f01aad037ced (2018-03-09T09:53:37.836 UTC)`.

The Function App in question is made up of C# HTTP triggered functions all injecting `ILogger` in their `Run` method.  Are there any other gotchas or updates to be aware of?

**Comment by paulbatum** [comment] 2018-04-03 22:40
Reopening as we saw a recent occurrence of this in the logs for `1.0.11612.0`:

```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.CreateStaticServices(JobHostConfiguration config)
   at Microsoft.Azure.WebJobs.JobHost.InitializeServices()
   at Microsoft.Azure.WebJobs.Script.Utility.CreateMetadataProvider(JobHost host) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 362
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 490
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHostManager.cs : 184
```

For context see:
https://github.com/Azure/azure-functions-host/issues/2618

**Comment by brettsam** [comment] 2018-04-05 15:35
@paulbatum -- from what I see in your example, it seems like we've got lifecycle issues that are more obvious during deployments (more reason for the DI changes that @fabiocav is prepping for v2):

1. We see an assembly changed so we initiate a host restart.
2. We immediately get an Environment shutdown request -- I'm assuming this is coming from Kudu? Or something outside of our control. We're being told that the process is shutting down so we try to do some cleanup.
3. But we're still in the middle of initializing a new host (due to step 1). But nothing is stopping us from calling Stop/Dispose on that same instance mid- (or even pre-) initialization. We ignore errors here so there's nothing logged.

So, we're starting up and shutting down at the exact same time. This disposes some services before they can be initialized and we blow up inside `InitializeServices`. However, I see the host restart pretty quickly with a new process id, so I don't believe this is really an issue causing any problems (the process is recycling anyway).

It looks like this behavior was subtly changed in commit https://github.com/Azure/azure-functions-host/commit/88360e7d1db3e75361bf93b424a076c043346d40#diff-62f03af2f495fb19b4e6de748d6f21f8 (cc @mathewc). In that commit, `newInstance` is added to our `_liveInstances` collection **before** it is initialized. When we go to shutdown, we dispose of all instances in that collection. Previously, we didn't add to that collection until **after** it was initialized. That would allow initialization to continue, even if a stop was requested. Then, we'd see that the `stopEvent` was set, and we'd orphan that specific host.

I'll see what changes we can add to nip them a bit for v1.

**Comment by brettsam** [comment] 2018-04-05 15:38
@simonness (sorry for not seeing your comment previously) -- your scenario is very similar but I see something odd that requires some more investigation. Your site is logging "Environment shutdown requested" during a restart as well -- except I see in one case the process didn't recycle for almost an hour, when the next environment shutdown was requested. I'm going to see if there's some bug that could be preventing us from calling `HostingEnvironment.InitiateShutdown()' in some cases.

**Comment by simonness** [comment] 2018-04-05 15:52
@brettsam thanks for taking a look!  I've noticed this error trace only occurs intermittently around deployments, so that sounds like the problem I'm having.

One of the App's Functions is effectively a "version" method, a http trigger function, that returns the assembly version of the underlying DLLs.  I've recently noticed that after a deployment, an unexpected previous version was being returned, even though the DLL was updated (I use VSTS to do deployments and downloaded the DLL using Kudu to double check).  I had to manually stop and start the App to get the version method to return the expected version.  It seems that some how the old assemblies are still in use, even though the new ones are in the App's storage account - so perhaps tallying with your second observation?  Please let me know if you'd like me to raise a separate issue for this.

**Comment by brettsam** [comment] 2018-04-05 16:04
@simonness -- yes, that would be the effect. We notice there's a new assembly, then force the process to recycle so we can load it. If that recycle never happens, we'll never see your new assembly. I'm looking into that issue now.

**Comment by simonness** [comment] 2018-04-05 17:04
Great, thanks very much @brettsam :)

**Comment by brettsam** [comment] 2018-04-18 23:44
Reopening as the issue was regressed.

**Comment by sergsalo** [comment] 2018-05-08 18:11
we were just hit with this issue: 

Exception while executing function: Functions.send_to_router One or more errors occurred. Exception binding parameter '_log' Cannot access a disposed object.  Object name: 'LoggerFactory'. Exception binding parameter '_logger' Cannot access a disposed object.  Object name: 'LoggerFactory'.

2018-05-08T18:09:25.071 [Info] Function started (Id=9f6f0395-cbac-4c38-8baf-c230e22c107b)
2018-05-08T18:09:25.086 [Error] Function completed (Failure, Id=9f6f0395-cbac-4c38-8baf-c230e22c107b, Duration=3ms)

**Comment by brettsam** [comment] 2018-05-09 14:00
@sergsalo -- is `send_to_router` an Event Hub trigger?

The error you're seeing is a symptom of another problem, but not the cause. I'm seeing that your host was stopped, yet continued to run functions for **several hours**. That meant it was attempting to access services in a disposed host, which is what you're seeing.

I've opened a separate issue to track this: https://github.com/Azure/azure-webjobs-sdk/issues/1691

**Comment by sergsalo** [comment] 2018-05-09 17:56
@brettsam yes, it is an Event Hub trigger

**Comment by andrew-vandenbrink** [comment] 2018-10-11 14:08
I still get this exception..

**Comment by andrew-vandenbrink** [comment] 2018-10-13 03:39
Azure function v2
This exception kill my durable activity function randomly

```
Unhandled exception while executing task: System.ObjectDisposedException: Cannot access a disposed object.Object name: 'LoggerFactory'.   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)   at Microsoft.Azure.WebJobs.Script.WebHost.ScriptLoggerFactory.CreateLogger(String categoryName) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\ScriptLoggerFactory.cs:line 26   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.Log(LogLevel level, FunctionDescriptor descriptor, Guid functionId, String message, Exception exception) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 49   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.LogFunctionCompletedAsync(FunctionCompletedMessage message, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 36   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 136   at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 54   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.RunAsync(TaskContext context, String rawInput)   at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass12_1.<<OnProcessWorkItemAsync>b__1>d.MoveNext()	   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)   at Microsoft.Azure.WebJobs.Script.WebHost.ScriptLoggerFactory.CreateLogger(String categoryName) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\ScriptLoggerFactory.cs:line 26   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.Log(LogLevel level, FunctionDescriptor descriptor, Guid functionId, String message, Exception exception) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 49   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.LogFunctionCompletedAsync(FunctionCompletedMessage message, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 36   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 136   at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 54   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.RunAsync(TaskContext context, String rawInput)   at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass12_1.<<OnProcessWorkItemAsync>b__1>d.MoveNext()
```

**Comment by andrew-vandenbrink** [comment] 2018-10-13 03:43
I dont think my function host recycle rapidly, but same exception, linking the issue

https://github.com/Azure/azure-functions-durable-extension/issues/472

**Comment by paulbatum** [comment] 2018-10-15 23:05
@andrew-vandenbrink thank you. Reopening.

**Comment by jeffhollan** [comment] 2019-02-27 07:32
@brettsam any updates or thoughts on this one? Could use some help in understanding severity (P0 / P1 / P2), likely based on how likely this is to pop up for users

**Comment by brettsam** [comment] 2019-02-27 17:25
I think we need to close this and treat any new instances of it as separate issues. I've mentioned it [above](https://github.com/Azure/azure-functions-host/issues/1690#issuecomment-387748378), but this error is almost always a symptom, rather than a cause, of another issue.

When you access a disposed JobHost, you will almost always get this exception as:
- Lots of services use the LoggerFactory.
- The LoggerFactory actually throws an ObjectDisposedException, which a lot of services do not.

So the real question would be "how did your JobHost get a disposed"? And we fix those issues whenever we find them. If it crops back up, it'll likely be a completely different investigation anyway.

So -- for anyone that comes across this exception and finds this issue, please open a new issue (and feel free to mention this issue so we can refer back).

**Closed by brettsam** 2019-02-27 17:25 UTC
Labels: bug, feature:application-insights
