### ISSUE TITLE
[CRITICAL] Azure AD token never refreshed

### ISSUE THREAD

**Issue by antonGritsenko** [Azure/azure-functions-host#5915] opened 2020-04-24 18:43 UTC
#### Investigative information

Please provide the following:

- Timestamp:  2020-04-24T18:20:52.3891996Z
- Invocation ID: 7bd1d4f8-a13e-4af8-8dde-a02d47340758
- Region: West Europe

#### Repro steps

1. Create Azure Function as usual, enable Azure AD authentication, action when not authenticated: log in with Active Directory.
2. Create new Visual Studio project, add Token extension.

3. Add code:
```
[FunctionName("GetToken")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            [Token(Identity = TokenIdentityMode.UserFromRequest, Resource = "https://graph.windows.net")] string graphToken,
            ILogger log)
        {
            return new OkObjectResult(new { graphToken = graphToken });
        }
```
Publish to Azure.

#### Expected behavior

You can open the url at any time and get valid token.

#### Actual behavior
When you first time open the page, it redirect to Azure AD login page. Everything works fine.
Now wait 1 hour to expire the token.
Refresh the page - you got the 500 error. Internal stack:
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__19.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 322)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsyncCore>d__16.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 117)
Inner exception System.AggregateException handled at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw:
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DelayedException.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 27)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__26.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 502)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__25.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 468)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__19.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 278)

```

The error occurred because token already expired, but Azure Functions do not check this and do not redirect to login page again. 
Same problem exists when you using MSAL library to access from front end.

#### Known workarounds

Do the full log out, restart browser. This is really a pain for customers who have account attached to they Windows Account.

**Comment by brettsam** [comment] 2020-05-27 18:00
@glennamanns / @ConnorMcMahon -- I can't tell if this is due to `[Token]` or due to EasyAuth -- can either of you help?

**Comment by brettsam** [comment] 2020-05-27 18:28
I consulted with @ConnorMcMahon and confirmed that the `[Token]` binding is in preview and not recommended for production use.

You can do this yourself, however, by using MSAL to get a valid graph token. Some details can be found here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of#how-to-call-obo

**Comment by antonGritsenko** [comment] 2020-05-27 19:24
@brettsam thanks for taking this. This issue is a bit more complex than written in this ticket. As you may know, we have support case opened on this.
As I wrote to support engineer, the issue is not about `[Token]` attribute, its buggy, so we use our own implementation in any case. The problem is in X-MS-TOKEN-AAD-ID-TOKEN header (used by the `[Token]` attribute as well here: https://github.com/Azure/azure-functions-microsoftgraph-extension/blob/265ede3da9ac3dbe61c3d3ff49178e808689f048/src/TokenBinding/TokenBaseAttribute.cs#L56).

To build on-behalf token, we must have access to user's bearer token (the assertion parameter of the `UserAssertion` ctor). Azure Functions puts this token to X-MS-TOKEN-AAD-ID-TOKEN header and do not refresh it as it should.

**Comment by ConnorMcMahon** [comment] 2020-06-02 16:22
@antonGritsenko,

How is the user authenticated in at this point? Did they do a browser log-in, or did you use an AAD access token as a bearer token to authenticate the API?

If it's the browser login scenario, make sure you have set up your AAD identity provider with a client secret. Then you should have access to an X-MS-TOKEN-AAD-ACCESS-TOKEN header. Access tokens DO refresh when the /.auth/refresh endpoint is hit. Just note that if the header already contains an expired token, you will have to hit /.auth/refresh, and then I recommend hitting the /.auth/me endpoint to get the newly refreshed token. Note that this token may not be a valid JWT. In that case, if you hit /.auth/refresh?resource=<resource-you-are getting-token-for>, the new access token that gets refreshed will already be an OBO token, and you won't have to use ADAL or MSAL to get the token.

If the user is authenticated with a bearer token already, just use that in your UserAssertion.

**Comment by antonGritsenko** [comment] 2020-06-02 16:55
@ConnorMcMahon Sorry, not sure if I get what you mean with 

> you will have to hit /.auth/refresh

Let's assume the simplest scenario: user open Azure Functions URL direct in the browser. He will be redirected to Azure AD log in screen where he must log in. The only things I can control here is client ID and client secret, that's all.

What's going on for me with this scenario:
1. Open Azure Functions URL -> page redirect to Azure AD log in screen. All works fine.
2. Now leave page open and wait for one hour.
3. Try to refresh the page -> you got 500 error, X-MS-TOKEN-AAD-ACCESS-TOKEN will contains token from step 1.
4. Close browser
5. Open again, open Azure Functions URL  -> redirected to log in screen, but then you got 500 still, X-MS-TOKEN-AAD-ACCESS-TOKEN contains old token (I saw the case when same token used after about 10 hours).

**Comment by ConnorMcMahon** [comment] 2020-06-02 17:28
@antonGritsenko 

I'm definitely confused by the results in step 5. That should not be the case. If you are prompted to relogin, your access token (and your id token for that matter), should be new. I would verify that you are having that issue, in which case that should definitely be investigated.

As for hitting /.auth/refresh, you can hit this from your functions code. The tricky part will be making sure you utilize the cookie that is attached to the HttpRequest of your HTTP triggered function, and make the request to /.auth/refresh from your function code. You can then hit the /.auth/me endpoint from your function code (with the cookie attached) to see the new tokens. Note that if your cookie has expired (i.e. it has been 8 hours), then you are out of luck in this scenario.

We are in the near future adding a configuration option to make the browser cookie last as long as the ID token does for an identity provider. This would prompt a relogin for AAD after one hour, so that would help with this scenario some what.

In general, I would caution about using HTTP Triggers as endpoints that you hit in the browser. HTTP triggers are more similar to APIs and backend code, as you have no control over any client side JavaScript to manipulate the browser experience. 

My general recommendation here would be to have some other client (like a CLI tool, or maybe some JS code hosted on some other web app) get a JWT access token for your function app using libraries like ADAL or MSAL. These libraries will more gracefully handle the refresh scenario for you. This client can then call your HTTP trigger with a bearer token, and your function app can do the OBO flow and handle the business logic from there.

**Comment by antonGritsenko** [comment] 2020-06-02 18:16
@ConnorMcMahon the problem is what I get the same result even with MSAL. But I will check your recommendation about 

> If the user is authenticated with a bearer token already, just use that in your UserAssertion.

I assume you mean get the token from the Authentication header itself and not from the X-MS-TOKEN-AAD-ACCESS-TOKEN header.

But, to be honest, the behalf-of scenario in Azure Functions looks broken. Too much effort required to make it work, from my point of view there is no any benefits of using AF in compare of regular web app.

**Comment by antonGritsenko** [comment] 2020-06-08 09:58
@ConnorMcMahon ok, I was able to manage this for client app. Is there any possibility that it will be fixed for Azure Functions http trigger when accessed from the browser?

**Comment by ConnorMcMahon** [comment] 2020-06-08 20:26
@antonGritsenko 

There are definitely improvements we are looking into making to improve authentication scenarios with Azure Functions HTTP trigger scenarios.

That being said, our priority for these improvements will mainly be on the API scenarios, rather than browser scenarios. In general, HTTP triggers don't play as nicely as web apps in a browser because you don't really control any JavaScript or HTML for interactivity. In general, my recommendation if you want a browser experience would be to use a web app instead of an HTTP trigger.

HTTP triggers really shine when you have an API that will be used infrequently by a client application, so you don't want to have dedicated compute just to service that API. With authentication scenarios, this puts a bit of extra work on the client application to get a valid bearer token for your API, but thankfully there are many libraries and resources that already support this.

That isn't to say that we won't have a OBO solution for browsers, but it will not be the focus of our improvement efforts.

**Comment by brettsam** [comment] 2020-08-06 16:11
@ConnorMcMahon -- is there any work item to track here or is it okay to close this?

**Comment by brettsam** [comment] 2020-08-17 21:13
Gonna go ahead and close. We can re-open if we need to track any specific work items.

**Closed as completed by brettsam** 2020-08-17 21:13 UTC
