### ISSUE TITLE
Investivate Sqlite assembly loading

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-host#5940] opened 2020-04-29 19:45 UTC
Following up on the issue here https://github.com/Azure/azure-functions-host/issues/5597 , SQLitePCL.raw uses their own mechanism for resolving assemblies rather than relying on CLR. 

We need to identify and document the requirements needed to collaborate with SQLitePCL.raw in order to make this happen.

cc: @fabiocav

**Comment by opolo** [comment] 2020-05-05 13:45
Facing same issue. Rollbar* no longer working with Azure Functions due to this. It seems to use SQLLite internally.

Rollbar: Our error-logging which ironically errors now

**Comment by yojagad** [comment] 2020-05-06 00:14
Opened an issue here https://github.com/ericsink/SQLitePCL.raw/issues/343 to see if we can work with SQLLite to come up with a solution.

**Comment by fabiocav** [comment] 2020-05-13 19:11
Closing this as we've completed investigation and identified the root cause. Work items will be opened here and in the SQLite repo.

**Closed as completed by fabiocav** 2020-05-13 19:11 UTC
