### ISSUE TITLE
Create a cancellation notification for OOP workers

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#6287] opened 2020-06-30 07:22 UTC
The function runtime should notify workers when a function cancellation token is signaled. The worker would have the ability to expose this information in a language specific way (e.g. `CancellationToken` for the .NET worker).

**Comment by nzthiago** [comment] 2021-11-29 20:23
Related to [#2152](https://github.com/Azure/azure-functions-host/issues/2152)

**Comment by fabiocav** [comment] 2022-03-09 21:27
Duplicate of #2152

**Closed as completed by fabiocav** 2022-03-09 21:27 UTC
Labels: design
