### ISSUE TITLE
Function job host stops after deployment and doesn't restart

### ISSUE THREAD

**Issue by fabio-muramatsu** [Azure/azure-functions-host#5539] opened 2020-01-25 03:12 UTC
I have an http function that uses .net core, and I've noticed that sometimes, after deploying the function using VS2019 (zip deploy), I start getting 503 Service Unavailable errors with this message: Function host is not running. I enabled application insights to collect some logs, and I see that the job host is stopped around that time and it never restarts:
![image](https://user-images.githubusercontent.com/14302074/73115184-906a5580-3ed7-11ea-81dc-3d0450070b08.png)

Restarting the function app through the portal restores the functionality. At this point, sending a request to the function makes the job host start.

#### Investigative information
- Timestamp: 2020-01-25 2:16:55 UTC
- Function App version (1.0 or 2.0): ~3
- Function App name: odspmetricplatform

#### Repro steps
1. Deploy the function app using Visual Studio using zip deploy;
2. Send a request to the function endpoint.

#### Expected behavior
The function gets deployed and is in a usable state (job host running). The request is handled by the function.

#### Actual behavior
The function gets deployed, but in a bad state. Sending a request to the function results in 503 - Function host is not running. It's worth emphasizing here that this doesn't always happen - I tried deploying 10 times or so, and I could repro it once. The problem is that if it gets in this state, the app is completely down until manual action is taken.

#### Known workarounds
Restarting the app resolves the issue. Sending a request after that makes the host restart

**Comment by fabio-muramatsu** [comment] 2020-01-25 03:42
Ok, tried a few more times and could repro it again. This is the timeline (UTC):
1/24 3:19: Deployed the app, logs show host stopping;
1/24 3:20 - 3:26: Sending many requests, always getting 503s with no signs of the job host restarting;
1/24 3:26: manually restarted the app from the portal and sent a request. Job host restarted and request was handled.

![image](https://user-images.githubusercontent.com/14302074/73115853-4c7c4e00-3ee1-11ea-909a-2e78003e83fc.png)

Unfortunately, I hit another error when sending the request after the manual restart (it was an OutOfMemoryException which I believe is a known issue that is being fixed). But this is unrelated to this topic (I guess)

**Comment by pragnagopa** [comment] 2020-01-28 23:01
Thank you for the details on function app name and timestamp. I can confirm for both instances there is OutOfMemoryExcetion stack trace when job host tried to start
```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.CreateLibrary(TargetLibrary targetLibrary, Boolean runtime, Dictionary`2 libraryStubs)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.<>c__DisplayClass20_0.<CreateLibraries>b__0(TargetLibrary property)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(JsonTextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadContext(IDependencyContextReader reader, String location)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.LoadDefault()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.DependencyModel.DependencyContext.get_Default()
   at Microsoft.Azure.WebJobs.Script.Description.DependencyHelper.GetRuntimeFallbacks(String rid) in D:\a\1\s\src\WebJobs.Script\Description\DotNet\DependencyHelper.cs:line 153
   at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoadContext..ctor(String basePath) in D:\a\1\s\src\WebJobs.Script\Description\DotNet\FunctionAssemblyLoadContext.cs:line 38
   at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoadContext.CreateSharedContext() in D:\a\1\s\src\WebJobs.Script\Description\DotNet\FunctionAssemblyLoadContext.cs:line 109
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.<>c__DisplayClass9_1.<GetExtensionsStartupTypesAsync>b__0(AssemblyName assemblyName) in D:\a\1\s\src\WebJobs.Script\DependencyInjection\ScriptStartupTypeLocator.cs:line 134
   at System.TypeNameParser.ResolveAssembly(String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase)
   at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetExtensionsStartupTypesAsync() in D:\a\1\s\src\WebJobs.Script\DependencyInjection\ScriptStartupTypeLocator.cs:line 113
   at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetStartupTypes() in D:\a\1\s\src\WebJobs.Script\DependencyInjection\ScriptStartupTypeLocator.cs:line 55
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseExternalStartup(IWebJobsBuilder builder, IWebJobsStartupTypeLocator startupTypeLocator, ILoggerFactory loggerFactory) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs:line 167
   at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.UseScriptExternalStartup(IWebJobsBuilder builder, ScriptApplicationHostOptions applicationHostOptions, ILoggerFactory loggerFactory, IExtensionBundleManager extensionBundleManager, IMetricsLogger metricsLogger) in D:\a\1\s\src\WebJobs.Script\ScriptHostBuilderExtensions.cs:line 242
   at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass3_0.<AddScriptHostCore>b__0(HostBuilderContext context, IWebJobsBuilder webJobsBuilder) in D:\a\1\s\src\WebJobs.Script\ScriptHostBuilderExtensions.cs:line 125
   at Microsoft.Extensions.Hosting.WebJobsHostBuilderExtensions.<>c__DisplayClass4_0.<ConfigureWebJobs>b__1(HostBuilderContext context, IServiceCollection services) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsHostBuilderExtensions.cs:line 49
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptHostBuilder.BuildHost(Boolean skipHostStartup, Boolean skipHostConfigurationParsing) in D:\a\1\s\src\WebJobs.Script.WebHost\DefaultScriptHostBuilder.cs:line 59
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation, Int32 attemptCount, JobHostStartupMode startupMode) in D:\a\1\s\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 205
```
Root Cause issue: https://github.com/Azure/azure-functions-host/issues/5430

Closing this issue as dup and updating the title.

**Closed by pragnagopa** 2020-01-28 23:01 UTC
Labels: Needs: Triage (Functions)
