### ISSUE TITLE
Function V2 - Queue Trigger suddenly stopped

### ISSUE THREAD

**Issue by TynThordin** [Azure/azure-functions-host#4126] opened 2019-02-22 08:12 UTC
Today at 2019-02-22T00:53:45.696 UTC, my Function (v2) stopped and did not Trigger any Queue Messages, until i restarted it 7 hours later. There were over 1000 messages stuck on the Queue.

#### Investigative information

Please provide the following:

- Timestamp: 2019-02-22T00:53:45.696
- Function App version (1.0 or 2.0): 2.0
- Function App name: 1b790a60-ce8a-4fb9-b196-a2a6338445f5 (AppID)
- Function name(s) (as appropriate): thordinforecastdbinserter
- Invocation ID: 586647cd-3637-11e9-8990-ddfbfa5adbc
- Region: West Europe

#### Known workarounds

Restarted the Function App, and it started triggering again.

#### Related information 

host.json file:

```javascript
{
  "version": "2.0",
  "extensions": {
    "serviceBus": {
      "prefetchCount": 1,
      "messageHandlerOptions": {
        "maxConcurrentCalls": 1,
        "maxAutoRenewDuration": "00:05:00"
      }
    }
  }
}
```

**Comment by ielcoro** [comment] 2019-03-08 22:42
Could be related to #4152 ?

**Comment by mhoeger** [comment] 2019-03-15 23:51
Thanks for linking this. Yes, the root cause of this is #4152. Closing this issue, very sorry about that!

**Closed by mhoeger** 2019-03-15 23:51 UTC
