### ISSUE TITLE
Host starting function execution after shut down

### ISSUE THREAD

**Issue by yashrmaa** [Azure/azure-functions-host#6202] opened 2020-06-10 14:03 UTC
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp: 2020-06-09T17:31:52.566Z
- Function App version: 2.0
- Function App name: debtmanagementfunction
- Function name(s) (as appropriate): ArtifactServiceSubscription
- Invocation ID: 466dcb64-0572-4b5e-8e00-912542d592a4
- Region: West US
- HostInstanceId: 71748a9d-b18a-4793-afb0-b6d3034821d3

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a service bus triggered Azure function.
2. Let a function timeout.
Function timeout will cause host to shut down but before it shuts down completely another function invocation will start.

#### Expected behavior

Host should not start execution when a shutdown is in process.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source
* Bindings used: Service bus

**Comment by MarioPrabowo** [comment] 2020-06-17 02:47
We also had similar issue but with time-triggered Azure function v3. The function got restarted again afterwards in a different host, but because the previous execution was stopped forcefully, the system was left in a corrupted state and we had to fix the data manually. Below is the response we got from Microsoft support:

> It is possible for dynamic function app to have new hosts on new instances. It would take some time for scale controller make the decision and remove the instance. Function host on a certain instance could still run and get the lock until hot shutdown and worker process stopped.

Unfortunately, this seems to imply that we are unable to use Azure function unless we're using app service plan with alwayson enabled (which prevents scaling out) or build resiliency in our system so it can handle multiple retries and will never left the system in a bad state (which is not always possible, especially when dealing with blob files creation/update or external API, which won't support transaction). Is it possible to bump up the priority of this issue as this is really concerning?

**Comment by v-anvari** [comment] 2020-10-28 15:40
Hi @yashvardhan90 , I have tried to repro the scenario, but didn't find any error. I tried to capture the logs of your app, but seems like it has been deleted. 

Lets us know if you are still facing the issues, if yes could you please give us the function app name and recent time stamp to get the logs and check the cause

**Comment by yashrmaa** [comment] 2020-11-04 23:39
@v-anvari Here's the information you asked for:
HostInstanceId: 980fa878-f9ed-4354-aa31-a0e2c9c5d8a9
FunctionName: ArtifactServiceSubscription
FunctionInvocationId: 6ab4ad4e-fc75-486f-9db7-65a20ad481cc
Timestamp: 2020-11-03T07:25:58.514Z

If you see logs for this host, the host posted a stop message at the above timestamp and at 2020-11-03T07:26:00.246Z a new execution started.

**Comment by v-anvari** [comment] 2020-11-09 18:24
Hi @yashvardhan90 , we checked the logs, we want to know a bit more about the issue that you are facing. Can you please elaborate the issue in detail. Also, are you talking about single instance or different instances.

**Comment by yashrmaa** [comment] 2020-11-09 18:51
Sure, so I have a service bus triggered Azure function that runs on multiple instances and what I have seen is when these hosts are recycled, Azure still schedules function execution to it and that execution abruptly ends because the host was already powering down. For instance, if my function F was running on a host H1 and after a while when Azure decided to stop host H1 and move execution to a new host H2. Let's say Azure sends a stop signal to H1 at time T, then a new execution of function F is scheduled at time T+1 on host H1. This should not happen because the host is already in the processing of shutting down. 
The consequence is I have these incomplete executions. No failures on my end, just that the host stopped.

**Comment by v-anvari** [comment] 2020-11-10 14:56
Hi @yashvardhan90, Events are happening all the time. As we scale in and scale out, some instances will be shutting down while other ones will be starting up and continue. Or the ones that are still running will continue to process events. Execution of different instances are independent from each other and execution of different instances in the same time frame is an expected behavior. I see in the logs that the host took its time to shut down but didn't cause any visible errors on the new instance. 

We would like to understand if you are facing any error here.

**Comment by yashrmaa** [comment] 2020-11-10 15:11
Problems don't always come from an explicit field marked error. This is an incomplete execution. My function started and it's supposed to do 5 things. It stopped at thing #3 without any error. Now this is a bigger problem for me as there are no alerts for such a problem. My question is why did Azure schedule a function execution on a host that is in the process of shutting down?

This is what I have been trying to explain for so long.

**Comment by v-anvari** [comment] 2020-11-11 18:34
Thankyou @yashvardhan90 for explaining the issue in detail

Hi @pragnagopa, kindly look into this issue.

For invocation id- **6ab4ad4e-fc75-486f-9db7-65a20ad481cc,** function started but it did not stop or complete, and another instance id started as shown below, within the same role instance

**2020-11-03 07:26:00.2465124 - MediumDedicatedWebWorkerRole_IN_18 - function started- 6ab4ad4e-fc75-486f-9db7-65a20ad481cc
2020-11-03 07:26:03.4561486 - MediumDedicatedWebWorkerRole_IN_18 - DidNotShutDown - 6ab4ad4e-fc75-486f-9db7-65a20ad481cc**

Different events took place before next instance started and completed

**2020-11-03 07:28:20.737 - MediumDedicatedWebWorkerRole_IN_18 -  function started - e50cb644-b5ac-4a70-b78b-2ce48bebd9ee**

**Comment by yashvardhan90** [comment] 2020-11-13 01:12
I don't see how my issue is related to the one mentioned above and the reasoning for closing it. Am I missing something?

**Comment by yashvardhan90** [comment] 2020-11-13 01:31
I am a Microsoft employee facing this problem in a Microsoft product. If I can't get answers on this portal, I wonder what kind of service are you guys providing to other customers. 
@cgillum @soninaren 
Can I get your attention here? I have been trying to get a clear answer to this problem since June 10 and all I can see here are efforts to misguide or fend off responsibility.

**Comment by v-anvari** [comment] 2021-10-19 11:37
Hi @yashvardhan90 , Please let us know if the issue still persists, because a lot of fixes were made to the host versions in this period.

**Comment by yashrmaa** [comment] 2021-10-20 20:58
Hi @v-anvari, thanks for checking in. I am still seeing the issue and in fact it has got worse. Earlier I was only seeing this happen to durable activity functions or stand alone functions but now it is happening to Durable Orchestrator functions. I have retries to functions so that helps me get around this but there are no retries for Durable Orchestrations. 
Do you have any temporary workaround for the issue?

Here's the exception message for issues in Durable Orchestrations:
```
Container is disposed and should not be used: Container is disposed.
You may include Dispose stack-trace into the message via:
container.With(rules => rules.WithCaptureContainerDisposeStackTrace())
```

You can look up logs for this failure at 
HostInstanceId : 8c794b92-c760-4e1d-9c75-b9eadd326eed
TimeGenerated [UTC]: 2021-10-20T06:34:28.237Z

**Comment by v-anvari** [comment] 2021-10-21 15:44
Hi @yashvardhan90 , I'm unable to find the App, can you provide the invocation ID and the region

**Comment by v-anvari** [comment] 2021-10-21 16:26
Hi @yashvardhan90 , Looking at the earlier logs vs the present. This could be by design if this is because of a timeout, and the host is not gracefully shut down. Usage of cancellation token would give a grace time to gracefully shut down. https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#cancellation-tokens

A second option would be using drain mode - https://docs.microsoft.com/en-us/azure/virtual-desktop/drain-mode#:~:text=%20To%20turn%20on%20drain%20mode%20in%20the,then%20select%20Turn%20drain%20mode%20off.%20More%20, as this issue is explained here - https://github.com/Azure/azure-functions-host/issues/6894#issuecomment-738417120

Let us know if this helps reduce the lost ID's

**Closed as completed** 2021-11-06 04:01 UTC
Labels: Needs: Author Feedback, no-recent-activity
