### ISSUE TITLE
Function still triggers despite being disabled 

### ISSUE THREAD

**Issue by jameshowe** [Azure/azure-functions-host#3889] opened 2018-12-13 18:55 UTC
Cosmos DB trigger function seems to trigger despite being disabled from the portal.

#### Investigative information

- Timestamp: 2018-12-13 18:38:10.222 (Function was disabled well before this time)
- Function App version (1.0 or 2.0): 2.0
- Function App name: -
- Function name(s) (as appropriate): -
- Invocation ID: d6f8ea19-a0d4-408e-9075-1765af8049a2
- Region: North Europe

#### Repro steps

1. Setup Cosmos DB container
2. Configure Cosmos DB triggered function
3. Create/update document in Cosmos (verify Function is triggered)
4. Disable Cosmos DB function in Portal
5. Create/update document in Cosmos (verify Function is still triggered)

#### Expected behavior

After step 4, the function should not be triggered.

#### Actual behavior

After step 4, function still triggers.

#### Known workarounds

N/A

#### Related information 

* Language: Node.js

**Comment by alrod** [comment] 2018-12-14 21:54
@jameshowe, it looks like the issue is related to Linux(Preview). You can use windows azure functions as workaround.

**Comment by jameshowe** [comment] 2018-12-14 23:35
@alrod didn't even think to mention the platform I was on, sorry! Any idea of how likely it is to be fixed? If the ETA isn't all that long I could probably live with it in the meantime.

**Comment by alrod** [comment] 2018-12-14 23:47
@jameshowe, it should be fixed in the GA version of Linux azure functions.

**Comment by alrod** [comment] 2018-12-21 00:02
https://github.com/Azure/azure-webjobs-sdk/commit/1bfb2c34be6f5d87fa9e65797f5d6d4fe2bda8b8

**Closed by alrod** 2018-12-21 00:02 UTC
Labels: needs-investigation, platform:linux
