### ISSUE TITLE
Update table client behind scale metrics

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-host#9287] opened 2023-05-23 23:53 UTC
The scale metrics respoitory is using an old table client of its own:
https://github.com/Azure/azure-functions-host/blob/a9e69d28e22188db35ec4c2956e1363681da8db2/src/WebJobs.Script.WebHost/Scale/TableStorageScaleMetricsRepository.cs#L40

That need to be updated to use `Azure.Data.Tables` instead of the deprecated `Microsoft.Azure.Cosmos.Table`.

We also need to reassess the fact that this component is just creating its own client against a known connection without overrides. That pattern is not sustainable.

**Comment by fabiocav** [comment] 2024-07-17 21:01
Duplicate of #10166

**Closed as not planned** 2024-07-17 21:02 UTC
Labels: area: engineering, feature: identity
