### ISSUE TITLE
Support for HttpContext.RequestAborted in the HttpTrigger cancellation token

### ISSUE THREAD

**Issue by CasperWSchmidt** [Azure/azure-functions-host#8903] opened 2022-11-11 08:08 UTC
#### What problem would the feature you're requesting solve? Please describe.
Using Http triggers in Azure Functions is a common use case. Having longer running functions is also quite normal. Therefore I'm actually quite surprised that cancelling a request (fx. in Postman) affect the function running. IMHO that is what developers would expect (at least it's what I did, and what the author did [here](https://stackoverflow.com/questions/60202259/azure-functions-using-cancellation-token-with-http-trigger/))

#### Describe the solution you'd like
Something like what's described [here](https://stackoverflow.com/questions/60202259/azure-functions-using-cancellation-token-with-http-trigger/63439515#63439515) - when the client cancels the http request the Azure Function should be notified through the cancellation token by default

#### Describe alternatives you've considered
Manually handling the linking of the host cancellation token and HttpContext.RequestAborted as described [here](https://stackoverflow.com/questions/60202259/azure-functions-using-cancellation-token-with-http-trigger/63439515#63439515)

#### Additional context
None

**Comment by miqm** [comment] 2023-02-23 12:01
Subscribing to topic - this is also a problem with python worker - cancelled http requests can wait for a quite long time and execute long after client drops the connection which can lead ineffectiveness in utilising resources.

**Comment by esimkowitz** [comment] 2023-03-17 23:58
It is super exciting to see this issue being addressed and getting this regression closed! Do you have an ETA for when this will get rolled out to the SDK?

I am also throwing my support behind the idea of linking this to the existing FunctionContext.CancellationToken (from what I gathered from the draft PR, that is the current proposal?). That is the most intuitive approach from a developer standpoint, especially since I imagine a lot of developers already assume that is how this works (I know I did until today!).

**Comment by liliankasem** [comment] 2023-03-20 16:48
> It is super exciting to see this issue being addressed and getting this regression closed! Do you have an ETA for when this will get rolled out to the SDK?
> 
> I am also throwing my support behind the idea of linking this to the existing FunctionContext.CancellationToken (from what I gathered from the draft PR, that is the current proposal?). That is the most intuitive approach from a developer standpoint, especially since I imagine a lot of developers already assume that is how this works (I know I did until today!).

I think you're commenting about CancellationToken support in the dotnet worker? This is already supported today, that feature went out last year ([code](https://github.com/Azure/azure-functions-dotnet-worker/blob/37070d860af9fc89cbd14ffa550b49b655b57816/src/DotNetWorker.Core/Context/FunctionContext.cs#L67)). You should be able to bind to the CancellationToken directly or use it via FunctionContext. 

The focus of this issue/PR is to also take into account the the `RequestAborted` cancellation token with the host/platform CancellationToken that we use/handle today. I wouldn't consider it a regression as support for `RequestAborted` did not exist with in-proc dotnet either.

For `RequestAborted` support, ETA would be maybe some time next month. PR needs to go through review & testing and when that is merged it could take 3-4 weeks for the release to roll out.

**Comment by esimkowitz** [comment] 2023-03-20 18:37
Got it, that clears things up thank you! Very much looking forward to this going in!

**Closed as completed** 2023-03-22 00:05 UTC
Labels: bug, supportability

**Comment by CasperWSchmidt** [comment] 2023-04-12 07:27
@liliankasem Do you know when this will be out?

**Comment by liliankasem** [comment] 2023-04-12 15:51
> @liliankasem Do you know when this will be out?

Not 100% sure but probably end of April, or whenever `4.20.0` is out.

**Comment by esimkowitz** [comment] 2023-05-04 18:14
@liliankasem Do you know what the status of the rollout here is? What SDK versions do I need to take advantage of this if I'm using out-of-process mode?
