### ISSUE TITLE
Output bindings not registered

### ISSUE THREAD

**Issue by JamieMagee** [Azure/azure-functions-host#4335] opened 2019-04-19 20:01 UTC
I'm unable to get any output bindings to work when debugging locally using Azure Functions core tools. That includes using the example functions

#### Investigative information

n/a (Debugging locally)

#### Repro steps

Debug the function attached at the bottom of the bug report. `context.bindings` only contains 1 binding, but it should include 2: An input and an output. Both bindings are correctly defined in `context.bindingDefinitions`.

Trigger using `curl localhost:7071/api/HttpTrigger`

##### Environment
- Arch Linux
- Azure Functions core tools: 2.5.553

<details>
<summary>Source</summary>

```json
{
  "bindings": [
    {
      "name": "req",
      "type": "httpTrigger",
      "direction": "in"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

```ts
import { AzureFunction, Context } from '@azure/functions';

const index: AzureFunction = async function (context: Context): Promise<void> {
    
};

export default index;
```
</details>

**Comment by JamieMagee** [comment] 2019-04-28 21:02
Upgrading to Azure Functions core tools `2.6.1071` appears to have solved the issue.

**Comment by pragnagopa** [comment] 2019-04-29 20:12
@JamieMagee  - generated function.json looks right. Can you please explain what do you mean by

>  unable to get any output bindings to work 

cc @mhoeger  for follow up

**Comment by mhoeger** [comment] 2019-04-29 20:50
@JamieMagee - I think what you're referring to is that the "bindings" object only contains the names and values of input / trigger type bindings. This is expected behavior as we've documented it (in [our docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#contextbindings-property) and in our [TypeScript type definitions](https://github.com/Azure/azure-functions-nodejs-worker/blob/dev/types/public/Interfaces.d.ts#L27-L33)). 

We do also say to set output through `context.bindings` (more info [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#outputs)), you can do it as follows:
```
import { AzureFunction, Context } from '@azure/functions';

const index: AzureFunction = async function (context: Context): Promise<void> {
    context.log('res' in context.bindings); // logs "false"
    context.log(context.bindings.res); // logs "undefined"
    context.bindings.res = {
        body: "hello, world",
        status: 200
    }
};

export default index;
```

Is the ask to change it so that the output binding key name is there with a starting value of "undefined"? So when you inspect the context object, you see that output bindings should be assigned to?

Another thing to note is that on context, there is a special http response object, "res", that sets http output in a way that is different from any other output binding type. If you look at the `context.res` object, you'll see it's already defined and has a few methods on it. This is to allow users to do "express-like" calls like `context.res.send("hello world!");` ([more here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#accessing-the-request-and-response)). Notice that it is scoped under "context" instead of "context.bindings", because it is treated as separate from the other dynamically generated output bindings (example of [blob output](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#output---javascript-example)).

Admittedly.... it is very confusing and not very intuitively organized.

Although we can't make a change in V2, can you tell us what your expectations were when you were trying to create an HTTP response? This is something we can improve in future major versions!

**Comment by ahmedelnably** [comment] 2019-04-30 18:13
Closing as resolved

**Closed by ahmedelnably** 2019-04-30 18:13 UTC
