### ISSUE TITLE
Function get triggered but take a very long time to finish

### ISSUE THREAD

**Issue by jdneo** [Azure/azure-functions-host#3238] opened 2018-08-09 06:21 UTC
#### Investigative information
- Timestamp:
2018-08-09T06:12:51.415 [Information] Executing 'Functions.QueueTriggerJava' (Reason='This function was programmatically called via the host APIs.', Id=8cbeac83-3e20-4d81-82c5-d63052d4ba4c)
- Function App version 2.0-beta:
- Function App name: demo-1533727931131
- Function name(s) (as appropriate): QueueTriggerJava
- Invocation ID:
- Region: West US

#### Repro steps

Not stable repro.

#### Expected behavior

Function body get executed.

#### Actual behavior

No further output after `Executing 'Functions.QueueTriggerJava' ....` for a long time (about 4 min).

#### Known workarounds

Stop and start the function app

#### Related information 

Provide any related information 

* Programming language used: Java
* Source:
```java
package com.function;

import com.microsoft.azure.functions.annotation.*;
import com.microsoft.azure.functions.*;

/**
 * Azure Functions with Azure Storage Queue trigger.
 */
public class QueueTriggerJava {
    /**
     * This function will be invoked when a new message is received at the specified path. The message contents are provided as input to this function.
     */
    @FunctionName("QueueTriggerJava")
    public void queueHandler(
        @QueueTrigger(name = "message", queueName = "myqueue", connection = "AzureWebJobsStorage") String message,
        final ExecutionContext context
    ) {
        context.getLogger().info("Java Queue trigger function processed a message: " + message);
    }
}

```

**Comment by tareksharbak** [comment] 2018-11-12 12:35
I had a similar issue, and in my case, the problem was caused by a memory leak when binding the ExecutionContext. The executions would just take longer and longer to run until they started throwing OutOfMemory exceptions.

My Solution:
Removing the ExecutionContext parameter (it wasn't critical in my solution) solved the memory leak and fixed my problem. I hope it works for you!

**Comment by fabiocav** [comment] 2019-03-20 18:35
Closing this as there were significant changes in this area for Java after this was reported. Please let us know if this is still impacting you.

**Closed by fabiocav** 2019-03-20 18:35 UTC
