### ISSUE TITLE
App Settings not available in some instances

### ISSUE THREAD

**Issue by davetse** [Azure/azure-functions-host#5115] opened 2019-10-18 18:42 UTC
@brettsam 

#### Description
Some of my azure function instances are missing environment variables

#### Details
- Timestamp: 2019-10-18T06:47:28.5473944Z
- Function App version (1.0 or 2.0): 2.0
- Function App name: -----
- Function name(s) (as appropriate): EventLogger
- Invocation ID: "3fbd6722-4605-41da-892c-0522026db996"
- Region: WestUS
- Language: NodeJs

Provide the steps required to reproduce the problem:
1. In portal detail app setting DOCUMENTDB_HOST = "https://cosmosplaceholderurl.com"
2. Write a service bus triggered function to log app setting value
`
context.log.info(`Creating cosmos client to host ${process.env["DOCUMENTDB_HOST"]}`);
`
3. Deploy function to consumption plan
4. Send a bunch of requests to function to cause function to scale

#### Expected behavior

All instances will log "Creating cosmos client to host https://cosmosplaceholderurl.com"

#### Actual behavior

Some instances will log "Creating cosmos client to host undefined" repeatedly for entire lifetime of instance.
Other instances will be fine and log "Creating cosmos client to host https://cosmosplaceholderurl.com"

#### Related information 

* Started appearing on our radar on Oct 16, 2019
* NodeJs
* Servicebus input trigger

**Comment by brettsam** [comment] 2019-10-18 19:01
@pragnagopa / @mhoeger -- @davetse reached out to me internally about this, but I'm not sure what could be happening. Is it possible to be missing environment variables immediately after specialization of a language worker? Have either of you seen this in the past? 

It may be related to #1577, but I had him create a new issue as we hadn't heard anything on that one in a while (and it may have been .NET-specific).

**Comment by julius-tieto** [comment] 2019-10-21 09:57
The same issue also occured with our Nodejs Azure functions which are using Storage Queue and Scheduled triggers (West Europe, Windows consumption plan). The problem started Oct 16th at night. Our function was missing some environment variables which are set from the app settings.

Using an older version 2.0.12742.0 also fixed the issue.

**Comment by pragnagopa** [comment] 2019-10-21 17:44
Investigating this issue.

**Comment by mhoeger** [comment] 2019-10-22 01:03
Thanks for the details all! The root cause appears to be: https://github.com/Azure/azure-functions-host/issues/4488. It is intermittent because the ordering of environment variables matters for this bug to appear, and the order of environment variables varies per instance.

We're working on a fix.

**Comment by mhoeger** [comment] 2019-10-22 20:20
A fix has been applied, and if you bring your functions runtime version back to ~2, environment variables will be read normally again.

**Closed by mhoeger** 2019-10-22 20:20 UTC
