### ISSUE TITLE
404 Error because of proxy with same name as function

### ISSUE THREAD

**Issue by petero-dk** [Azure/azure-functions-host#3239] opened 2018-08-09 13:23 UTC
When the proxy has the same descriptive name as the function, the function is never executed and will return a 404 error. This is tested with a c# project on dotnet core, deployed via VSTS.

#### Investigative information

- Function App version (1.0 or 2.0-beta): 2.0-beta
- The runtime version is: 1.0.11913.0 (~1)
- Function name(s) (as appropriate): CalendarList
- Invocation ID:
- Region: North-Europe

#### Repro steps

Create the following proxies.json file

```json
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
      "calendarList": {
        "matchCondition": {
          "methods": [ "GET", "POST" ],
          "route": "/Calendars/List/{personId}"
        },
        "backendUri": "https://localhost/api/CalendarList?personId={personId}"
      }
    }
}
```

Create the following function file:

```csharp
[FunctionName("CalendarList")]
        public static IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "CalendarList")]HttpRequest req, ILogger log)
        {

            log.LogInformation("C# HTTP trigger function processed a request.");

            string personId = req.Query["personId"];

            return personId != null
                ? (ActionResult)new OkObjectResult($"Hello, {personId}")
                : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
        }
```

#### Expected behavior

That the function will execute either through the direct link
https://appname.azurewebsites.net/api/CalendarList
or the proxy link
https://appname.azurewebsites.net/Calendars/List/{personId}

#### Actual behavior

Returns 404 error with no trace logs and no entries in the ApplicationInsights.

#### Known workarounds

Rename either the function or the proxy

**Comment by safihamid** [comment] 2018-08-10 19:44
We do throw and exception but we let the host start as we don't want to block initializing the entire host if few functions and/or proxies are in error. are you not seeing it in AppInsights?

https://github.com/Azure/azure-functions-host/blob/4d5a82c2a3c3f01253979557b4b18d476fade1b1/src/WebJobs.Script/Host/ScriptHost.cs#L797

**Comment by safihamid** [comment] 2018-08-10 20:14
I verified the error does gets logged into ApplicationInsights:

here is an example:

 traces
 | where timestamp > ago(1h) 
 | where severityLevel >= 3

The following 1 functions are in error:
Ping: The function or proxy name 'Ping' must be unique within the function app.


We also do not allow a duplicate name in the portal when creating a proxy.

The reason why we just log and continue starting the host is explained above. So marking this as 'by design'

**Closed by safihamid** 2018-08-10 20:14 UTC
Labels: feature:Proxies

**Comment by petero-dk** [comment] 2018-08-10 20:47
Ahh, I see. 

Could I make a feature suggestion of throwing a warning on CI deployment when deploying a project with thhis issue? That way if someone creates a function app without Insights it would somehow show up.

**Comment by safihamid** [comment] 2018-08-10 20:57
@paulbatum Do you know if we have a work item for the feature suggestion above? https://github.com/Azure/azure-functions-host/issues/3239#issuecomment-412201687 
Basically for any function errors during startup that we swallow and allow the host to start?

**Comment by paulbatum** [comment] 2018-08-10 22:42
Hmm I am not sure I follow.. we are already surfacing the error to App Insights, where else would we send it? Agree with the part about making sure that the docs explain the need for unique names...

**Comment by petero-dk** [comment] 2018-08-11 12:03
My point above is that the application insights is after the fact (the functions are not working) throwing an error or warning on deployment would be before the fact. I could halt the deployment and not have a faulty service. 

I am talking about the connection fra VSTS to Azure where we deploy WebApps and WebApp Functions in our CI.

**Comment by petero-dk** [comment] 2018-08-11 12:07
And just to make sure is it obvious. I reported it here mostly because I wanted other people to know: Don't have the same name for proxy and function! All the rest is just ideas to reduce chance of failure for other people. It is a simple error to stear away from if you know it. 

But we (developers) are getting so used to our tools (Visual Studio, VSTS, AppCenter, etc) and our languages (C# type safety) being clever enough to avoid simple errors by default, so this was a suggestion to enhance that behavior of our tools.
