### ISSUE TITLE
Address flaky CosmosDB test

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#2824] opened 2018-05-09 19:01 UTC
`Microsoft.Azure.WebJobs.Script.Tests.CosmosDB.CosmosDBNodeEndToEndTests.CosmosDB` is frequently failing and exceeding the timeout.

**Comment by brettsam** [comment] 2018-05-23 18:56
Dupe of #2837

**Closed by brettsam** 2018-05-23 18:56 UTC
