### ISSUE TITLE
[Rpc] Accept function invocations only when FunctionLoad is complete.

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-host#6821] opened 2020-10-20 21:50 UTC
Today, we buffer invocations until the point where a FunctionLoad is complete. This could be a problem if the FunctionLoad fails and customers will be forced to retry. We should probably wait, not only until FunctionsHost is up and running, but also until FunctionLoad is complate before accepting invocations.

**Comment by fabiocav** [comment] 2022-03-09 21:57
Duplicate of #4852

**Closed as completed by fabiocav** 2022-03-09 21:57 UTC
Labels: feature:language-extensibility
