### ISSUE TITLE
Getting trigger execution warnings with Logic App Standard on Azure Function Runtime

### ISSUE THREAD

**Issue by arggrande** [Azure/azure-functions-host#7644] opened 2021-09-02 07:12 UTC
I've got a Logic App (Standard) running on an Azure Function runtime, and I've noticed I'm getting spammed with warnings for my O365 `When a new email arrives in a shared mailbox (V2)` trigger.

`Trigger is meant to execute on cluster type 'Classic'. However, it is executing on cluster 'NotSpecified'`

#### Investigative information

Please provide the following:

- Timestamp: `2021-09-02 2:59:25.962 PM AWST`
- Function App version: `v3 (assuming this is function extensions version?)`
- Stack: `node`
- Node runtime version: `node 12 LTS`
- Workflow Bundle Extension Id: `Microsoft.Azure.Functions.ExtensionBundle.Workflows`
- Workflow Bundle Extension Version: `[1.*, 2.0.0)`
- Correlation ID of the message in AppInsights: `257fbe4ae0e05d49bd7e2da39a3372a8`
- Tracking ID of the Trigger Invocation: `08585710409195149842797416117CU00`
- Region: `Australia East`

#### Repro steps

1. Create a Logic App (Standard) and create an O365 trigger on a shared mailbox v2 trigger
2. Allow the trigger to fire

#### Expected behavior

Provide a description of the expected behavior.

- The trigger should fire with no warnings

#### Actual behavior

Provide a description of the actual behavior observed.

- Log Stream/AppInsights will show the warning about trigger execution: `Trigger is meant to execute on cluster type 'Classic'. However, it is executing on cluster 'NotSpecified'`

#### Known workarounds

Provide a description of any known workarounds.

None, that I'm aware of.

**Comment by v-bbalaiagar** [comment] 2021-09-02 17:07
Hi @arggrande, Thank you for your feedback! We would like to know how you are integrating the function app.

**Comment by arggrande** [comment] 2021-09-03 00:41
All I'm doing is listening to a shared mailbox for a particular subject line, and then getting the attachments and sending them to Azure Blob Storage :)

**Comment by v-bbalaiagar** [comment] 2021-09-03 17:10
Hi @arggrande, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment] 2021-09-20 17:25
Hi @arggrande,  Apologies for the delayed response, discussed this issue internally. As the issue is not necessarily a function trigger, the best course of action here is to report this issue with logic apps team.

Closing this issue, please feel free to reach back to us in case of any further queries related to this issue.

**Closed as completed by v-bbalaiagar** 2021-09-20 17:25 UTC
