### ISSUE TITLE
Where to find the actual error instead of "exception while executing function: ... System.Private.CoreLib: One or more errors occurred ...."

### ISSUE THREAD

**Issue by isualize** [Azure/azure-functions-host#2321] opened 2018-01-17 08:49 UTC
Hi everyone,

Im executing a nodejs function in Azure and im getting the following error:

Exception while executing function: Functions.getSheet. System.Private.CoreLib: One or more errors occurred. (Worker process with pid 393 exited with code 1) (Worker process with pid 407 exited with code 1) (Worker process with pid 420 exited with code 1). Worker process with pid 393 exited with code 1.

Ofcourse this doesnt help me at all to consider whats wrong with the following piece of code:

<details>
var http = require('http');

http.createServer(function (req, res) {
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('Hello World!');
}).listen(8080);
</details>

The above piece of code is a simple hello world example. Could anyone tell me whats wrong with this?

Im on the West-European server by the way. Running on 2.0.1 beta runtime version and node version 8.4.0.
By default it's sets to 6.5.0, even though the latest version has been updated to 8.4.0:

https://github.com/Azure/azure-webjobs-sdk-script/commit/7a310233b862138f9e1c2ae5511aa537171c651b

Are there more specific logs to be found somewhere?

**Comment by isualize** [comment] 2018-01-17 08:52
<details>
<summary>Source</summary>

```javascript
var http = require('http');
http.createServer(function (req, res) {
res.writeHead(200, {'Content-Type': 'text/plain'});
res.end('Hello World!');
}).listen(8080);
```
</details>

**Comment by christopheranderson** [comment] 2018-01-18 01:01
This is a known bug we plan on addressing soon in v2. Restarting the Function App mostly works to address this as a temporary work around. Your code is fine, it's a bug in our state machine for the node process on the worker.

**Comment by christopheranderson** [comment] 2018-01-18 01:02
Probably a dupe of https://github.com/Azure/azure-webjobs-sdk-script/issues/2244

@pragnagopa, could you confirm?

**Comment by isualize** [comment] 2018-01-18 10:37
@christopheranderson ah thats unfortunate. Any ETA on a fix?

**Comment by isualize** [comment] 2018-01-23 09:55
@paulbatum Since @christopheranderson isnt responding. Do you have an ETA when 2.0 goes live? We are kind of waiting for this to work properly.

**Comment by paulbatum** [comment] 2018-01-30 00:19
@isualize As neither @pragnagopa or @christopheranderson have picked this up for an upcoming sprint, I can't give you an ETA for this particular issue to be fixed. Functions 2.0 is already in preview, and we will make sure this is fixed prior to GA for v2 (but I don't have a GA date either).

**Comment by pragnagopa** [comment] 2018-04-03 20:16
Submitted PR with a fix for this.

**Closed** 2018-04-10 19:11 UTC
Labels: 2.0, bug, out-of-proc

**Comment by iredjee** [comment] 2018-04-15 21:09
Just got the same issue.

Region: East Asia
Azure Function version: 2.x (beta)
Nodejs version: 8.9.4

**Comment by brusMX** [comment] 2018-04-30 22:01
+1

Region EastUS 
 func --version
2.0.1-beta.26
Docker image:
microsoft/azure-functions-python3.6:v2.0.11651-alpha

**Comment by iredjee** [comment] 2018-05-09 21:12
@paulbatum @pragnagopa I insist to reopen this issue, I continuously getting this again and again. Even restart doesn't help...

**Comment by pragnagopa** [comment] 2018-05-09 21:35
Fix is not rolled out yet. Fix is part of 2.0.11737-alpha. We are currently working on this release. Should be out soon.

**Comment by pragnagopa** [comment] 2018-05-09 21:38
@brusMX - For python can you try using the latest docker image from sample repo: https://github.com/Azure/azure-functions-docker-python-sample/blob/master/Dockerfile

**Comment by iredjee** [comment] 2018-05-09 22:12
@pragnagopa Thank you for the fast response, hopefully waiting for the next build to be published very soon. Any workaround you can suggest for now until version 2.0.11737-alpha? Restart, full redeploy, full redeploy with different app service name - none of this helped me :(

**Comment by pragnagopa** [comment] 2018-05-09 22:37
@iredjee - Moved investigation to https://github.com/Azure/azure-functions-nodejs-worker/issues/68

**Comment by catcher-in-the-try** [comment] 2018-05-10 08:16
Yes please, any workaround currently until the issue is fixed?

**Comment by pragnagopa** [comment] 2018-05-10 16:51
Please check [Kudu diagnostic logs](https://github.com/projectkudu/kudu/wiki/Investigating-issues#getting-the-diagnostic-dump).
