### ISSUE TITLE
Build warnings introduced after upgrade 3.0.9 -> 3.0.11

### ISSUE THREAD

**Issue by NoahStahl** [Azure/azure-functions-host#6899] opened 2020-11-14 02:00 UTC
After upgrading Microsoft.NET.Sdk.Functions from 3.0.9 to 3.0.11, I'm seeing new warnings on build locally in Visual Studio:

```
>C:\Users\Noah\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning :     Could not evaluate 'Cosmos.CRTCompat.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid.
>C:\Users\Noah\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning :     Could not evaluate 'Magick.Native-Q8-x64.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid.
>C:\Users\Noah\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning :     Could not evaluate 'Microsoft.Azure.Cosmos.ServiceInterop.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid.
>C:\Users\Noah\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning :     Could not evaluate 'Microsoft.Azure.Documents.ServiceInterop.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid.
```

There were no such warnings with 3.0.9, which has worked perfectly. Here are my project settings:

```
<PropertyGroup>
  <TargetFramework>netcoreapp3.1</TargetFramework>
  <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
  <PlatformTarget>x64</PlatformTarget>
  <Nullable>enable</Nullable>
  <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  <AzureFunctionsVersion>v3</AzureFunctionsVersion>
</PropertyGroup>
```

I'm targeting x64 and Windows specifically to avoid generating Linux/macos runtime & native folders and DLLs in the build output, which doubles the publish size. It's not for a self-contained deployment, as CI publish uses `--self-contained false`.

Reverting to 3.0.9 resolves the warnings. Happy to provide additional info that can help.

A minimal repro, consisting of empty project with one dependency (Magick.NET x64) and `PlatformTarget` + `RuntimeIdentifier` configured for project:

https://github.com/NoahStahl/BuildWarningRepro

**Comment by DarinMacRae** [comment] 2020-11-16 20:49
I just ran into this as well.  {{slaps hand for choosing latest}}.

**Comment by ThejaChoudary** [comment] 2020-11-17 08:17
@madelinegordon Able to repro the Issue.Can you please look into this further.
```
1>BuildWarningRepro -> C:\BuildWarningRepro\BuildWarningRepro\bin\Debug\netcoreapp3.1\win10-x64\BuildWarningRepro.dll
1>C:\Users\v-thek\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning :     Could not evaluate 'Cosmos.CRTCompat.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid.
1>C:\Users\v-thek\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning :     Could not evaluate 'Magick.Native-Q8-x64.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid.
1>C:\Users\v-thek\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning :     Could not evaluate 'Microsoft.Azure.Cosmos.ServiceInterop.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid
```

**Comment by Mys73rion** [comment] 2020-11-20 13:29
We ran into this issue as well and had to downgrade to 3.0.9. (Warnings are bad and we don't want to have them :-)
In version 3.0.10 the issue exists too.
Would be nice if there would be a fix as soon as possible.

**Comment by v-anvari** [comment] 2020-12-10 17:11
Tagging @fabiocav , for more insights here.

1>BuildWarningRepro -> C:\BuildWarningRepro\BuildWarningRepro\bin\Debug\netcoreapp3.1\win10-x64\BuildWarningRepro.dll 1>C:\Users\v-thek\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning : Could not evaluate 'Cosmos.CRTCompat.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid. 1>C:\Users\v-thek\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning : Could not evaluate 'Magick.Native-Q8-x64.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid. 1>C:\Users\v-thek\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning : Could not evaluate 'Microsoft.Azure.Cosmos.ServiceInterop.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid

**Comment by fabiocav** [comment] 2020-12-11 01:29
Adding to sprint 91 so we can take a closer look. This looks like exceptions logged by the metadata generator.

**Comment by fabiocav** [comment] 2021-01-06 21:25
Apologies for the delay on this. Assigning to sprint 93 for investigation.

**Comment by timabell** [comment] 2021-01-20 09:32
We have warnings-as-errors so this breaks our build.

What is the impact of these warnings? Is something broken or is it okay to upgrade and supress them?

**Comment by mgwilliam** [comment] 2021-01-20 11:29
Also seeing these warnings in a .NET 5 functions app... ok to ignore?

**Comment by seancolonello** [comment] 2021-02-11 14:26
I created an issue for the same problem over here...
https://github.com/Azure/azure-functions-vs-build-sdk/issues/487

Not sure which repo it belongs in? Anyway, the same problem popped up in an earlier SDK version, and was fixed in v3.0.7. This appears to be a regression in v3.0.10. 

Earlier issue that resulted in v3.0.7 fix...
https://github.com/Azure/azure-functions-host/issues/5963

**Comment by piotrzbyszynski** [comment] 2021-03-05 10:26
@fabiocav Any news on that?

**Comment by ElvenSpellmaker** [comment] 2021-04-07 16:06
@fabiocav Any news on your Sprint 93? Maybe this is a very long sprint? 🙂

**Comment by abisleem** [comment] 2021-04-08 17:53
@fabiocav +1 for a fix to this

**Comment by sixeyes** [comment] 2021-04-12 15:01
+1 for fix to this

**Comment by FanBaoMS** [comment] 2021-04-24 00:41
I hit the same issue and after some investigation I think this change is the root cause
https://github.com/Azure/azure-functions-host/commit/8ee1fb5af64a7d9311e73d486385068e683805a0#diff-a11275288a9a75bece2473411c40dbffbd2dddb303e3b932d123995861752786L55

Before
```
                        catch (Exception ex) when (ex is FileNotFoundException || ex is BadImageFormatException)
                        {
                            // Don't log this as an error. This will almost always happen due to some publishing artifacts (i.e. Razor) existing in the
                            // functions bin folder without all of their dependencies present, or native package artifacts being copied to the bin folder
                            // These will almost never have Functions extensions, so we don't want to write out errors every time there is a build.
                            // This message can be seen with detailed logging enabled.
                            logger.LogMessage($"Could not evaluate '{Path.GetFileName(path)}' for extension metadata. If this assembly contains a Functions extension, ensure that all dependent assemblies exist in '{sourcePath}'. If this assembly does not contain any Functions extensions, this message can be ignored. Exception message: {ex.Message}");
                        }
```

After
```
                        catch (Exception ex)
                        {
                            logger.LogError($"Could not evaluate '{Path.GetFileName(path)}' for extension metadata. Exception message: {ex.Message}");
                        }
```

Probably the original reason of log message still stands?

**Comment by ElvenSpellmaker** [comment] 2021-04-24 00:47
If this is the root cause it'd be nice to know what we can do to remove the warnings... Noöne uses Razor (statistically speaking) and so it seems bad to include some kludge code that accepts Razor when one man and his dog uses it.

Seeing as we're now almost half a year away from when this issue was raised I feel some solution should be imminent but then I know Microsoft and the only solution would be to downgrade packages and ignore the newer ones.

**Comment by caviyacht** [comment] 2021-05-03 16:22
I feel like this is an easy fix to get rid of warnings. When can we expect to have this resolved? Our solution now has hundreds of warnings with no way of hiding them.

**Comment by fabiocav** [comment] 2021-05-14 18:01
Sorry for the delay on this item. This was unfortunately impacted by other priorities. 

I'm assigning this to the current sprint so we can pick this up.

/cc @brettsam

**Comment by ElvenSpellmaker** [comment] 2021-05-14 18:02
Thanks!

**Comment by labuscpi** [comment] 2021-06-10 09:24
"Microsoft.NET.Sdk.Functions" Version="3.0.13"

Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37, 5):     Could not evaluate 'Microsoft.Azure.Documents.ServiceInterop.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid.

  Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37, 5):     Could not evaluate 'Cosmos.CRTCompat.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid.

**Comment by matringer** [comment] 2021-06-22 19:26
> Sorry for the delay on this item. This was unfortunately impacted by other priorities.
> 
> I'm assigning this to the current sprint so we can pick this up.
> 
> /cc @brettsam

Any updates?

**Comment by azat-galiev** [comment] 2021-06-24 17:41
+1

**Closed as completed** 2021-06-25 17:42 UTC
Labels: needs-investigation

**Comment by ElvenSpellmaker** [comment] 2021-06-28 23:33
Is this in a release yet @fabiocav?

**Comment by brettsam** [comment] 2021-06-29 12:27
You can add a direct package reference to [Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator version 1.2.3](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator/1.2.3) which will pick up the new behavior.

This package is a typically pulled in as a dependency of the [Microsoft.NET.Sdk.Functions](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/), but that release will take a few more days before it's out. Adding the direct dependency lets you use this fix without having to wait.

**Comment by ElvenSpellmaker** [comment] 2021-06-29 12:28
@brettsam Thanks!

**Comment by caviyacht** [comment] 2021-07-19 15:49
@fabiocav , Any update when the new release will be out for this? I know we can add the package directly, but would like an update on when it will be in a full release.
