### ISSUE TITLE
Dependency on specific Newtonsoft.Json package version = 10.0.3 throws version conflict error

### ISSUE THREAD

**Issue by pramod-hegde** [Azure/azure-functions-host#2905] opened 2018-05-29 12:20 UTC
Microsoft.NET.Sdk.Functions version 1.0.13 has few dependencies where the required version is **>=** [dependent assembly version]. However, its not the case with Newtonsoft.Json. There is a dependency on a specific version 10.0.3. Because of this specific version dependency, the projects are not getting built and thrown version conflict error.

**Comment by brettsam** [comment] 2018-05-30 18:09
@fabiocav -- can you resolve this as a duplicate of the root issue?

**Comment by fabiocav** [comment] 2019-07-13 03:58
This is tracked by https://github.com/Azure/azure-functions-vs-build-sdk/issues/304. Closing as duplicate

**Closed by fabiocav** 2019-07-13 03:58 UTC
