### ISSUE TITLE
[Question] C# - Execute code on application startup

### ISSUE THREAD

**Issue by felpel** [Azure/azure-functions-host#2632] opened 2018-04-05 15:26 UTC
We're trying to find an equivalent mechanism to execute code when the function app is started. We already have our own `IExtensionConfigProvider` in which we setup the services to be injected inside our functions with our custom `InjectAttribute`, but I don't think it is the right place to execute anything else (example: create Azure Table Storages if they don't exist for custom entity repositories).

With Azure WebJobs, we could have a `Program` class with `Main` method in which we could setup multiple things for our job as shown [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Program.cs). Is there something similar for the Azure Functions runtime?

**Comment by paulbatum** [comment] 2018-04-06 23:00
Short answer - functions does not have an equivalent of Program.Main 
See:
https://github.com/Azure/azure-functions-host/issues/281
https://github.com/Azure/azure-functions-host/issues/586

(i suspect one should be closed as a dupe of the other)

**Closed by paulbatum** 2018-04-06 23:00 UTC
