### ISSUE TITLE
Improve worker retry logic

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#4231] opened 2019-03-22 17:52 UTC
Instead of a hard numerical limit on the worker retries, we should have smarter logic to avoid crash loops (especially on first startup) but allows for recovery in the case of uncaught exceptions (especially on uncaught exceptions from user code).

This is the code that stops the worker process from recycling after a certain number of retries ([link](https://github.com/Azure/azure-functions-host/blob/743089948f6d6212fa0374b40a1a9c323ec204c6/src/WebJobs.Script/Rpc/FunctionRegistration/FunctionDispatcher.cs#L151)). It is a well-known issue with Node.js in particular that uncaught exceptions happen, and they can happen fairly easily. The behavior around uncaught exceptions is to [exit the node process](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly).

 We need to be more resilient on uncaught exceptions, especially for App Service plan function apps.

**Comment by mhoeger** [comment] 2019-04-05 22:26
cc: @pragnagopa

**Comment by mhoeger** [comment] 2019-04-30 01:39
@fabiocav - issue related to discussion today

**Comment by pragnagopa** [comment] 2019-05-15 17:42
cc @mathewc 
Fix for #4392  will mitigate this issue. If restarting node process fails after exceeding threshold - 3 times, jobhost is shutdown. When a new request comes is, jobhost is restarted --> which restarts language worker process.

Moving this issue to Triaged as we need to discuss what is the right approach to restarting language worker 
- Should there be a limit on number of restarts?
- When does restarting jobhist help instead of just retrying language worker process restarts
- When should we give up trying to restart? i.e shutdown application?

**Comment by mhoeger** [comment] 2019-05-15 18:02
One example of a case where the language worker startup would "infinitely fail" is if the WEBSITE_NODE_DEFAULT_VERSION is not set, or is set to a non-exact match or old value.

**Comment by pragnagopa** [comment] 2019-07-15 20:28
Closing this as the issue is addressed. We will open separate issues if the restart code needs to be improved.

**Closed by pragnagopa** 2019-07-15 20:28 UTC
Labels: P1, Supportability, improvement, needs-discussion, out-of-proc
