### ISSUE TITLE
Reenable http throttles in v2

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#2945] opened 2018-06-05 16:55 UTC
This feature was disabled as part of the move to .NET Core. We need to reenable it.

Code is currently commented out: https://github.com/Azure/azure-functions-host/blob/ecd1b7a1f1878d455de6dd292d50dba71ef85aa1/src/WebJobs.Script.WebHost/WebScriptHostRequestManager.cs#L4

**Comment by paulbatum** [comment] 2018-06-08 23:11
Closing as duplicate of https://github.com/Azure/azure-functions-host/issues/2113

**Comment by paulbatum** [comment] 2018-06-08 23:12
Unless these are two different types of throttles? If I'm mistaken please reopen..

**Comment by mathewc** [comment] 2018-06-08 23:48
This issue is different from the other, which is about enabling throttles by default. That presupposes the existence of the http throttles feature which was removed in the v2 migration. This issue tracks reenabling the feature, and #2113 tracks changing the default.

**Closed** 2018-08-22 17:53 UTC
Labels: 2.0, breaking, functions-v2-GA-musthave
