### ISSUE TITLE
Why is EasyAuth returning a 401 Unauthorized status when a client post an access token on /.auth/login/aad endpoint?

### ISSUE THREAD

**Issue by kzryzstof** [Azure/azure-functions-host#4465] opened 2019-05-17 13:21 UTC
I started to migrate my Live SDK registered applications to the new Application Registration Portal as Microsoft is deprecating their support:

![Application Registration Portal](https://i.stack.imgur.com/SMRbq.png)

I went on the App Registrations (Preview) page in the Azure Portal and choose to create a new application.

Then, I went to my Function App's Authentication / Authorization page to put the information of the newly registered AAD application.

My client iOS application is getting the authorization code first:

`https://login.microsoftonline.com/common/oauth2/v2.0/authorize`

using the appropriate `client_id`, `response_type=code`, `redirect_uri=my_function_app_uri`, `response_mode=query`, `scope=https://graph.microsoft.com/User.Read%20open_id...`

The `redirect_url` points to one of my Azure Functions which uses the authorization code to get a token from this endpoint using the `client secret`:

`https://login.microsoftonline.com/common/oauth2/v2.0/token`

The Azure Function then redirect the caller to the iOS app:
 
`ca.company.app://oauthcallback?access_token=xxx&expires_in=xxx&id_token=xxx`

So far so good. My iOS application has an access token, expiration information and an id token.

___ 

Now, with a valid access token in hand, the iOS application is trying to POST the token on the AAD endpoint (`/.auth/login/aad`) but it fails. The response that I get is a `401 Unauthorized` with the following message:

`You do not have the permission to view this directory or page.`

I am following the exact same procedure as I am doing for Google accounts. I also made sure that my registered application allows user from my Azure Active Directory as well as personal account. Here is a screenshot of these settings:

![Application registration](https://i.stack.imgur.com/TvYvs.png)

**Question**

Why is EasyAuth returning a `401 Unauthorized `status after a client posts an access token to the `/.auth/login/aad` endpoint? Especially since it does work with posting an access token retrieved from a Google account to the `/.auth/login/google` endpoint. 

Either it is a bug or it seems to point to a permission settings that I may have missed but I am unable to pinpoint the problem. I have not found a way to get diagnostics information either in my function app or my aad...

______

#### Investigative information

- Timestamp: 
- Function App version (1.0 or 2.0): **~2**
- Invocation ID: **EasyAuth**
- Region: **CanadaEast**

**Comment by ConnorMcMahon** [comment] 2019-07-15 22:11
Sorry for the delay in addressing this.

Can you provide the name of the function application, as well as a timestamp when you attempt the login operation? That will help me investigate the issue.

**Comment by kzryzstof** [comment] 2019-07-16 00:09
The Function App name is `demotape-ca` and the timestamp is 2019-07-15 08:08 PM (UTC-04:00).

**Comment by kzryzstof** [comment] 2019-07-22 20:54
@ConnorMcMahon Have I provided you with enough information?

**Comment by ConnorMcMahon** [comment] 2019-07-22 20:59
Yes, thank you @KrzysiekKnigawka. I will investigate it this week.

**Comment by kzryzstof** [comment] 2019-07-29 21:37
@ConnorMcMahon Have you bee able to look into this issue? I hope I am not coming across too insistent… :)

**Comment by ConnorMcMahon** [comment] 2019-07-29 22:30
Not at all @kzryzstof. I actually found a similar internal issue last week and forgot to update with the results here, so thanks for the ping.

The crux of the issue is that multi-tenancy with AAD V2 app registrations isn't fully supported by EasyAuth yet. If you provide an open id issuer for your EasyAuth configuration, we will verify that the issuer of the tokens you provide match the issuer. This makes the multi-tenant scenario of combining personal microsoft account logins and AAD logins tricky. 

For AAD v1 applications, the way we supported multi-tenant applications was by having customers set the open id issuer to null. If you don't have an issuer set, we will treat your application as a multi-tenant application and we will do no validation of the issuers in our code. Note that this allows tokens from ANY tenant pass our validation, and you may want to add additional validation in your code if that is not acceptable. Note that this workflow also was designed with AAD v1 application in mind, and unfortunately if the site is set to redirect on login, navigating to the page via a browser will redirect to an AAD v1 login endpoint, which likely only works with AAD logins, not personal accounts.

We are working on improving our multi-tenancy story now that Application Registration Portal is being deprecated, and customers are being funneled into using a single AAD app registration to manage both AAD logins and personal account logins. Let us know if you have any feedback about what the experience should look like.

**Comment by kzryzstof** [comment] 2019-08-05 21:01
@ConnorMcMahon Thanks for the update!

**Comment by fabiocav** [comment] 2020-01-17 00:54
@ConnorMcMahon any follow up required here? Or can we close this?

**Comment by fabiocav** [comment] 2020-07-29 16:22
Closing as resolved. Please let us know if any additional information is needed.

**Closed by fabiocav** 2020-07-29 16:22 UTC
Labels: Needs: Attention :wave:
