### ISSUE TITLE
Dependency Injection suddenly fails

### ISSUE THREAD

**Issue by riezebosch** [Azure/azure-functions-host#4237] opened 2019-03-26 07:27 UTC
https://stackoverflow.com/a/55199041/129269

We updated our functions to have proper dependency injection like described here: https://devkimchi.com/2019/02/22/performing-constructor-injections-on-azure-functions-v2/

All was fine until last week when functions began to fail suddenly with the error that certain types could not be resolved anymore!

```
b265712484d445219447954b02c17b15: Function 'MonitorAgentsIdleFunction (Orchestrator)' failed with an error. Reason: Microsoft.Azure.WebJobs.FunctionFailedException: The activity function 'AgentPoolCheckActivity' failed: "Unable to resolve service for type 'SecurePipelineScan.VstsService.IVstsRestClient' while attempting to activate 'AgentStatusFunction.AgentPoolCheckActivity'.". See the function execution logs for additional details. ---> System.InvalidOperationException: Unable to resolve service for type 'SecurePipelineScan.VstsService.IVstsRestClient' while attempting to activate 'AgentStatusFunction.AgentPoolCheckActivity'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IServiceProvider serviceProvider) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 42
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 32
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.CreateInstance(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 44
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.Initialize() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 845
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 116
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, String instanceId, RetryOptions retryOptions, Object input) in C:\projects\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\DurableOrchestrationContext.cs:line 456
   at AgentStatusFunction.MonitorAgentsIdleFunction.Run(DurableOrchestrationContextBase context) in C:\agent1\_work\10\s\AgentStatusFunction\MonitorAgentsIdleFunction.cs:line 17
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput) in C:\projects\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 92. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: agentscantest. SlotName: Production. ExtensionVersion: 1.7.1. SequenceNumber: 8.
```

Looks like I'm not the only one experiencing this regression?

**Comment by nguyenquyhy** [comment] 2019-03-26 08:34
Yes this has been reported several times here. You can check for a workaround here https://github.com/Azure/azure-functions-host/issues/4187#issuecomment-476053609.

@pragnagopa has also mentioned a fix in that issue for the next runtime update.

**Comment by fabiocav** [comment] 2019-03-26 16:58
Duplicate of #4228 
Yes. this has been addressed and is rolling out with the next release.

**Closed by fabiocav** 2019-03-26 16:58 UTC
