### ISSUE TITLE
Improve non-.NET developer experience by removing .NET binding dependencies 

### ISSUE THREAD

**Issue by dariagrigoriu** [Azure/azure-functions-host#3670] opened 2018-10-23 20:53 UTC
This is based on a customer request especially relevant for Linux Functions where customers are more likely to work with a non-.NET stack.

**Comment by paulbatum** [comment] 2018-10-24 22:59
Dupe of https://github.com/Azure/azure-functions-host/issues/3562

**Closed by paulbatum** 2018-10-24 22:59 UTC
Labels: platform:linux
