### ISSUE TITLE
Content negotiation for javascript HTTP responses breaks in v2

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-host#2339] opened 2018-01-20 17:13 UTC
If I return a specific content type (non-JSON) in a javascript function in v1 it works as expected, returns the content, and succeeds:

```
context.res = {
                    body: someHTML,
                    headers: {
                        'Content-Type': 'text/html'
                    }
                }
```

but the same example fails in v2 with a "406" response.  If I remove the content-type header it works, but then returns of plain/text

**Comment by christopheranderson** [comment] 2018-01-23 18:34
This shouldn't happen. I've recently done some tests where this worked. @jeffhollan, could you update this with your full sample that didn't work + did work?

**Comment by fabiocav** [comment] 2018-01-23 18:41
@christopheranderson I'm pretty sure we had some test coverage for those scenarios, so if this is really happening, we either have a test gap or a regression in our test suite.

**Comment by christopheranderson** [comment] 2018-02-17 02:25
Doesn't break for "isRaw": true

```javascript
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    context.res = {
        body: "<h1>Hello world!</h1>",
        headers: {
            'Content-Type': 'text/html'
        },
        status:200,
        isRaw: true
    }
    context.done();
};
```

This looks to be an issue with ObjectResult (i.e. `isRaw` = false) being used with `text/html`. It works just fine when you set json

```javascript
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    context.res = {
        body: {text: "<h1>Hello world!</h1>"},
        headers: {
            'Content-Type': 'application/json'
        },
        status:200
    }
    context.done();
};
```

and xml

```javascript
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    context.res = {
        body: {text: "<h1>Hello world!</h1>"},
        headers: {
            'Content-Type': 'application/xml'
        },
        status:200
    }
    context.done();
};
```

I gotta think about the experience for this should work. 

@fabiocav, it seems like we should have a filtered list for what goes through ObjectResult, everything else is a raw result. Defaulting to isRaw=false is going to be hard to account for.

**Comment by pragnagopa** [comment] 2018-03-27 20:04
@mhoeger - This is probably dup of #2552 . Can you please take a look and close this one?

**Comment by mhoeger** [comment] 2018-03-27 20:21
Yep - dupe. Closing this issue as the other is more up to date 👍

**Closed by mhoeger** 2018-03-27 20:21 UTC
Labels: bug, lang-js
