### ISSUE TITLE
Azure portal cannot list my functions anymore

### ISSUE THREAD

**Issue by btardif** [Azure/azure-functions-host#3510] opened 2018-09-22 00:01 UTC
_From @asavaritayal on September 17, 2018 21:29_

_From @Tetradeus on September 9, 2018 15:6_

Hello,

Azure portal is not listing my functions anymore. May it comes from recent changes ?

When azure portal tries to list my functions in the interface, it tries to access /admin/functions and here is the result :

OPTIONS https://xxxxxxx.azurewebsites.net/admin/functions 404 ()
Failed to load https://xxxxxxx.azurewebsites.net/admin/functions: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://functions.azure.com' is therefore not allowed access.
POST https://functions.azure.com/api/passthrough 500 (Internal Server Error)

I am not sure if it may comes from the docker image.
I am using 2.0 tag. Does the image behind this tag change overtime ? If yes it would be great to have immutable docker image tag.

Docker image is from microsoft/azure-functions-base:2.0

_Copied from original issue: Azure/azure-functions-docker#25_

_Copied from original issue: Azure/azure-functions-ux#3166_

**Comment by btardif** [comment] 2018-09-22 00:01
_From @asavaritayal on September 17, 2018 21:29_

_From @Tetradeus on September 10, 2018 22:1_

After redeploying, the ui finally get to print my functions but it only works one time....
The problem looks to me more on the second call :
POST https://functions.azure.com/api/passthrough 500 (Internal Server Error)
POST /api/passthrough HTTP/1.1
Host: functions.azure.com
Connection: keep-alive
Content-Length: 447
Origin: https://functions.azure.com
content-type: application/json
Accept: application/json, text/plain, */*

{
  "method": "GET",
  "url": "https://xxxxxx.azurewebsites.net/admin/functions",
  "body": "null",
  "headers": {
    "Authorization": "Bearer xxxxx"
  }
}

HTTP/1.1 500 Internal Server Error
Server: Kestrel
Set-Cookie: ARRAffinity=xxxxx;Path=/;HttpOnly;Domain=functions.azure.com
request-context: appId=cid-v1:xxxx
X-Powered-By: Express
X-Powered-By: ASP.NET
Date: Mon, 10 Sep 2018 21:52:37 GMT
Content-Length: 0

**Comment by btardif** [comment] 2018-09-22 00:01
hey @asavaritayal why is this a UX issue, it looks like runtime APIs are throwing 500 errors

**Comment by btardif** [comment] 2018-09-22 00:01
@paulbatum talked to @asavaritayal and she agrees this is back-end and not UX item, please triage

**Comment by paulbatum** [comment] 2018-09-22 01:14
@btardif its hard to tell. The call is failing to hit the runtime directly and is getting an error going through the portal's passthrough API. 

@tetradeus  can you run one of your functions and share the region, UTC timestamp and invocation ID. We'll use this to look at the backend logs for your app. See the [wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

**Comment by Tetradeus** [comment] 2018-09-22 14:58
Hi @paulbatum,

I cannot follow the wiki and run my function from the portal because my function is not listed on azure portal. This is my issue.
In parallel, I also opened an Azure ticket : 118091819036026

This is the beginning of my dockerfile, not sure if it may help to resolve the issue : 

```
# Base the image on the built-in Azure Functions Linux image.
ARG NAMESPACE=microsoft
ARG HOST_TAG=2.0

FROM ${NAMESPACE}/azure-functions-base:${HOST_TAG}
```

**Comment by Tetradeus** [comment] 2018-09-24 22:08
After having check docker image page, I find that this image is deprecated so I moved to 
```
FROM mcr.microsoft.com/azure-functions/base:2.0
```
It now redisplay my functions, but is very slow. I continue to verify that everything is fine.
Then I will close this issue.

**Comment by paulbatum** [comment] 2018-09-25 00:56
@Tetradeus thanks for the update. Sorry for asking you to perform steps that were not possible!

**Comment by ankitkumarr** [comment] 2019-07-15 22:09
@Tetradeus, sorry for the late follow-up. Since then, we have made several updates to both the Functions runtime as well as our images. I was unable to reproduce this issue on our newest images, so I will assume that the issue has been fixed.
Here's the link to the most recently updated [official documentation](https://docs.microsoft.com/bs-cyrl-ba/azure/azure-functions/functions-create-function-linux-custom-image) on how to use our Docker images.
Please re-open the issue if you continue to see such errors on our latest Docker images.

**Closed by ankitkumarr** 2019-07-15 22:09 UTC
