### ISSUE TITLE
Analyze Cold start impact of AspNetCore Grpc implementation on Linux

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#8001] opened 2021-12-15 18:12 UTC
Across different out of proc languages, [this ](https://github.com/Azure/azure-functions-host/commit/8596a27c5a3cf1c26546418fe8ac6bcf132f808b)seems to be adding 300-400ms to P50 cold start on Linux.

**Comment by pragnagopa** [comment] 2021-12-15 19:03
Tagging @fabiocav @brettsam - please prioritize to bring back the feature flag to bring back the feature flag: FeatureFlagDisableAspNetCoreGrpc that was part of the original commit - adding AspNetCore Grpc implementation (#7543) · Azure/azure-functions-host@8596a27 (github.com) . Adding feature flag will give 
us more time to root cause issue on Linux.

FYI @safihamid

**Comment by pragnagopa** [comment] 2021-12-15 19:46
cc @Francisco-Gamino @AnatoliB as FYI - this issue could have been caught with E2E tests running on private stamp - with alerts on cold start.

**Comment by fabiocav** [comment] 2022-01-05 21:41
Investigation in progress. Assigning this to sprint 116

**Comment by fabiocav** [comment] 2022-01-20 21:17
Closing this as resolved by #8048

**Closed as completed by fabiocav** 2022-01-20 21:17 UTC
