### ISSUE TITLE
Host releasing timer function singleton lease when the function is still in progress causes multiple invocation of the same function

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2950] opened 2018-06-06 19:52 UTC
#### Investigative information

Please provide the following:

- **Timestamp:** `TIMESTAMP > datetime(2018-06-01 13:59:50)  and TIMESTAMP < datetime(2018-06-01 14:59:30)`
- **Function App version:** 1.0
- **Icm Incident:** 71833507

You can see the queries and investigations in the ICM incident above. 

To summarize: A once-a-month timer function was triggered. This is the sequence of events that happened

```
1- Executing 'MonthlyOverQuota' id=first-invocation
2- Host is unhealthy. Initiating a restart.
3- Singleton lock released (<app Name>/...MonthlyOverQuota.Run.Listener)
4- Host 'GUID' released lock lease.
5- Starting Host
6- A ScriptHost error has occurred
7- Stopping Host
8- Starting Host
9- A ScriptHost error has occurred
10- Stopping Host
11- Starting Host
12- A ScriptHost error has occurred
13- Stopping Host
14- Starting Host
15- Host initialized (797ms)
16- Singleton lock acquired (<app name>/...MonthlyOverQuota.Run.Listener)
17- Function 'MonthlyOverQuota.Run' initial status: Last='0001-01-01T00:00:00.0000000', Next='2018-06-01T14:00:00.0000000+00:00', LastUpdated='2018-05-03T21:39:39.3686502+00:00'
18- Function 'MonthlyOverQuota.Run' is past due on startup. Executing now.
19- Executing 'MonthlyOverQuota' Id=second-invocation
20- Executed 'MonthlyOverQuota' (Succeeded, Id=first-invocation)
21- Executed 'MonthlyOverQuota' (Succeeded, Id=second-invocation)
```

**Comment by paulbatum** [comment] 2018-06-08 17:07
Dupe of https://github.com/Azure/azure-functions-host/issues/2950

**Closed by paulbatum** 2018-06-08 17:07 UTC

**Comment by paulbatum** [comment] 2018-06-08 17:11
Dupe of https://github.com/Azure/azure-functions-host/issues/2968
