### ISSUE TITLE
Function retry policy setting of App level is not working.

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-host#6868] opened 2020-11-05 09:08 UTC
I added a configuration to host.json to retry at the application level, but it did not work as expected. I set it up as described in the following document.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#retry

#### Investigative information

- Function App version: 3.0.14916.0
- WebJobs SDK version: 3.0.23

#### Repro steps

I prepared a simple HttpTrigger and tried both Function and Application level retry settings. The implementation of Function and `host.json` is as follows.

```csharp
public class Function1
{
    //[FixedDelayRetry(10, "00:00:03")]
    [FunctionName("Function1")]
    public IActionResult Run(
        [HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequest req,
        ILogger log)
    {
        throw new System.Exception();
    }
}
```

```json
{
  "version": "2.0",
  "retry": {
    "strategy": "fixedDelay",
    "maxRetryCount": 10,
    "delayInterval": "00:00:03"
  }
}
```

This HttpTrigger did not trigger a retry. Uncommenting the FixedDelayRetry annotation on Function will make the retry work.

#### Expected behavior

As with the function level retry setting, retries are performed up to 10 times at 3 seconds intervals.

#### Known workarounds

Using the function level retry setting.

#### Related information 

Provide any related information 

* Programming language used : C#

**Comment by anielii** [comment] 2021-02-25 08:16
The same pertains to the Timmer trigger.

**Comment by v-anvari** [comment] 2021-02-25 14:17
Hi @shibayan , Apologies for the delayed response. What is the actual behavior that you are seeing. Is there a delay? or is the retry setting is not working at all. I see that you have mentioned in a line that the uncommenting  the FixedDelayRetry is working fine.

Hi @anielii , Kindly open a new issue for us to look into the details of your App.

**Comment by shibayan** [comment] 2021-02-25 14:20
@v-anvari 
The retry configuration using host.json doesn't seem to be working at all, as shown in the documentation. Retries using the `FixedDelayRetry` attribute work fine.

**Comment by v-anvari** [comment] 2021-02-25 14:22
Thank you for confirming, I shall try to repro it as mentioned and update you

**Comment by v-anvari** [comment] 2021-02-25 18:02
Hi @shibayan, As mentioned in the document here [csharp#fixed-delay-retry](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#fixed-delay-retry). For the C# file it is mandatory to write the attribute on top of the class or method as appropriate. For non c# sharp files, it is to be written only in the function.json file. This scenario is by-design

Let us know if you have any further queries regarding this issue

**Comment by shibayan** [comment] 2021-02-25 18:05
@v-anvari 
The following document describes the App level configuration and I point out that the App level configuration is not working correctly. The documentation doesn't seem to mention that the behavior is different for different languages.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#app-level-configuration
https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#retry

**Comment by v-anvari** [comment] 2021-03-02 09:38
Hi @shibayan , Yes, you are right, for App level configuration, you need to only update the Host.json as mentioned in the document. Did you check the [limitations of the retry policy](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#retry-limitations-during-preview)?

We are trying to understand the cause of the failure. Can you give us quick repro steps of your project which uses retry policy on app level, and how do you see the failure. We would like to have the details of your Function App which uses the retry policy in the App level, so that we can check the backend configuration, in case if something is missing

**Comment by malramsay** [comment] 2021-03-03 18:25
I will jump in here.  The repro steps are straightforward. Copying @shibayan's steps above will recreate the issue.

1. In VS 2019, create a new http trigger in a new azure function using the packages as per the original post.
2. Add [FixedDelayRetry(10, "00:00:03")]. Run the function and note that the retry policy is followed.
3. Comment out the FixedDelayRetry attribute but add the corresponding values in the host.json.
4. Run the function. The retry policy is ignored.
5. Comment back in the FixedDelayRetry attribute, this time changing the values to "(5, "00:00:05)".
6. Run the function. The retry policy from the host.json is ignored. The values from the C# file are used.

Deploy the function to Azure and note that the host.json is ignored just as it is locally.  I did so using an App Service plan, so the ["Retry limitations during preview"](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#retry-policies-preview) points concerning consumption plans are not relevant.

I have noted this behavior also happens in QueueTriggers.

This appears to run counter to the statement "A retry policy can be defined for all functions in an app using the host.json file." [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#retry-policies-preview).

**Comment by v-anvari** [comment] 2021-03-04 18:29
Hi @shibayan , @malramsay , I Reproduced the steps above and Its working completely fine. I believe the document is causing some confusion. C# Functions explicitly look for the attributes, hence its not necessary to mention it in host.json (Only for C#). But, defining the retry in host.json and not specifying the fixed delay attribute, will not allow your function to look for the retry. 

For other languages as specified in the document, you will need to specify the host.json and define the attributes as mentioned for each individual language in the function.json file.

But, for C#, you will can specify the attribute in your function.cs file itself. 

Language : C#

Writing the code like below where the **[FixedDelayRetry(2, "00:00:01")]** above the class, then it is applied to all the functions within the class. 

  [FixedDelayRetry(2, "00:00:01")]
  [FunctionName("EventHubTrigger")]
    public static class Function1
    {
      ....
    }

If the Attribute in within the function like below, then it is applicable only for that specific function. 

[FunctionName("EventHubTrigger")]
[FixedDelayRetry(5, "00:00:10")]
public static async Task Run([EventHubTrigger("myHub", Connection = "EventHubConnection")] EventData[] events, ILogger log)
{
// ...
}

Hope this clarifies the confusion. I shall open a document issue and it will be updated appropriately.

**Comment by malramsay** [comment] 2021-03-05 15:06
Thanks for replying @v-anvari,

Can you confirm, are you saying that the host.json retry variables will be read in the host.json for a C# function if the function contains a Retry attribute, but not if it does not, or are you saying that the host.json is not read for a C# function?

**Comment by v-anvari** [comment] 2021-03-05 15:57
Hi @malramsay , If you see the below is the function bin file and we have a configuration source which checks for attributes explicitly. The fact that, defining the retry in host.json and not defining the attribute of function delay retry or exponential retry, will not work as expected. The document issue is created and this shall be explained

{
  "generatedBy": "Microsoft.NET.Sdk.Functions-3.0.11",
  **"configurationSource": "attributes",**
  "bindings": [
    {
      "type": "httpTrigger",
      "methods": [
        "get",
        "post"
      ],
      "authLevel": "anonymous",
      "name": "req"
    }
  ],

**Comment by shibayan** [comment] 2021-03-06 16:08
I tried it with Node.js Function, the retry policy defined in host.json worked correctly.

If it is by design that definitions at the host.json level do not work in C# only, then the documentation needs to be revised.

**Comment by v-anvari** [comment] 2021-03-08 09:02
Hi @shibayan , Thank you for the confirmation, the document issue is raised and they are working on the update

**Comment by v-anvari** [comment] 2021-03-08 09:03
Closing this issue as resolved, the document updates will be available in [https://github.com/MicrosoftDocs/azure-docs/issues/71628](https://github.com/MicrosoftDocs/azure-docs/issues/71628)

**Closed as completed by v-anvari** 2021-03-08 09:03 UTC
