### ISSUE TITLE
Azure Functions stops processing - IoT Hub trigger

### ISSUE THREAD

**Issue by frnk01** [Azure/azure-functions-host#4424] opened 2019-05-14 09:25 UTC
Azure function with IoT Hub trigger stops running after a period of time.

![image](https://user-images.githubusercontent.com/2760702/57686636-3a4fcd80-763a-11e9-8283-23204df14b74.png)

#### Repro steps
Azure functions running with node.js on windows. Using node package pg-promise for inserting data to timescale db in Azure.

#### Actual behavior
Azure functions stops running with error Received RST_STREAM with error code 2 even if requests are being made to the function.

```
module.exports = async function (context, IoTHubMessages) {
    context.log(`JavaScript eventhub trigger function called for message array: ${IoTHubMessages}`);

    ......

    for (let message of IoTHubMessages) {
        await db.tx(t => {
            const queries = message.map(payload => {                
                    return t.none('INSERT ..............');                
            });
            return t.batch(queries);
        })
    }

    pgp.end();

    context.done();
};
```

**Comment by brettsam** [comment] 2019-05-14 21:05
@mhoeger / @pragnagopa any ideas here? Looks like we may be in the process of stopping the job host and something blows up?

**Comment by pragnagopa** [comment] 2019-05-14 21:32
Fix for #4392  should mitigate this issue. If starting node worker process fails, then jobhost is shutdown. This forces language worker process to restart. 

I will investigate why the app ended up in this state.
@frnk01 - Can you please share function app name and approximate time range you got the errors?

**Comment by frnk01** [comment] 2019-05-15 05:30
@pragnagopa I would prefer not to share the name of the function. If we can talk on email I can share this information, or are there any IDs og the app I can share with you?

Last time function stopped:
14/05/19 19:16:35

**Comment by pragnagopa** [comment] 2019-05-15 09:53
Please share any invocationid during that time frame.

**Comment by frnk01** [comment] 2019-05-15 10:13
@pragnagopa 5f9489fe-b10a-499b-8b1d-341809cb5bbd

**Comment by pragnagopa** [comment] 2019-05-15 10:37
Apologies. I missed this earlier. I also need region your app is running in.

**Comment by frnk01** [comment] 2019-05-15 10:40
@pragnagopa West Europe

**Comment by pragnagopa** [comment] 2019-05-15 10:42
Thanks. I will investigate

**Comment by frnk01** [comment] 2019-05-15 18:02
@pragnagopa Is it possible to get any ETA on this issue? I can see several of the referenced issues are in the 49 sprint which ends today. Is it likely that a fix will be pushed anytime soon? This functionality is critical to our solution as it´s the only reasonable way to get data from an IoT Hub and into a postgre database as Stream Analytics does not support this.

**Comment by pragnagopa** [comment] 2019-05-15 18:24
As I mentioned earlier, fix for #4392 will help mitigate this issue. And we will be pushing that fix as part Sprint 49.
I still have investigate this issue to understand why restarting the node process was failing.

**Comment by pragnagopa** [comment] 2019-05-16 17:41
Error you are seeing in the logs: `Received RST_STREAM with error code 2` is same as the issue #4190 which is a noise in the logs due to ungraceful shutdown of the resources and does not cause any issues with function executions. Your application insights logs should have following information as well:
```
Shuttingdown Rpc Channels Manager
[error] Worker ee92a484-431a-425c-b630-f1dc29230ad0 encountered event stream error:  { Error: 13 INTERNAL: Received RST_STREAM with error code 2
Worker ee92a484-431a-425c-b630-f1dc29230ad0 exited with code 1
[error] Worker ee92a484-431a-425c-b630-f1dc29230ad0 uncaught exception:  { Error: 13 INTERNAL: Received RST_STREAM with error code 2
Stopping host...
Language Worker Process exited.
Handling WorkerErrorEvent for runtime:node
Disposing errored channel for workerId: ee92a484-431a-425c-b630-f1dc29230ad0, for runtime:node
Stopping JobHost
```

which indicates that process is shuttindown (which is part of the normal execution) but disposing child processes is not going through graceful shutdown.

I looked through logs for your app, it does seem to be running as expected. You can check app lens for your application: https://azure.microsoft.com/en-us/updates/introducing-applens-for-azure-app-service-web-apps/ for the overall status on function executions. 

Will update the title of the issue to reflect the issue of investigation. 

If you still think function app is not processing triggers as expected, please do share other invocationIds and approximate time range. I will continue looking into it.

**Comment by frnk01** [comment] 2019-05-16 20:18
@pragnagopa The IoT hub is receiving multiple events and normally no less than one event per 15 seconds. After the RST_STREAM error is shown in the log the function never fires again. It will be stuck in "shutdown mode" for several hours, an as soon I visit the function page in the portal it triggers for all of the "missed" events.

I´m not sure what invocation ID you want me to share. I shared the last ID before the app crashed.

**Comment by pragnagopa** [comment] 2019-05-17 15:44
I do not have a root cause yet. Will post an update once I have more info.

**Comment by pragnagopa** [comment] 2019-05-21 19:53
cc: @mathewc 
@frnk01  - We have looked through the backend logs.  `Function IoTHub_Trigger is disabled`.  This resulted in function app not being scaled as expected even when there were incoming messages on the IOT Hub.
Please remove `  "disabled": true` from function.json. 

Closing this issue. Please reopen if needed.

**Closed by pragnagopa** 2019-05-21 19:53 UTC

**Comment by pragnagopa** [comment] 2019-05-21 21:20
Also, we have opened https://github.com/Azure/Azure-Functions/issues/1223 to improve detection of cases where disabled property interferes with function scaling.
