### ISSUE TITLE
EventhubTrigger may not work after deployment unless visit it in portal

### ISSUE THREAD

**Issue by Flanker32** [Azure/azure-functions-host#3899] opened 2018-12-17 06:05 UTC
#### Investigative information

Please provide the following:

- Timestamp: 2018-12-17T00:21:40Z
- Function App version (1.0 or 2.0): 2.0
- Function App name:  maven-functions-it-20181217000845413-3
- Function name(s) (as appropriate): EventHubTriggerJava
- Invocation ID:
- Region:West US

#### Repro steps

Provide the steps required to reproduce the problem:
(Unstable reproduce)
1. Create an Eventhub trigger
2. Create eventhub and set the connection string to Application settings
3. Write something to eventhub by eventhub java sdk to trigger the function

#### Expected behavior

Function should be triggered and output correspond result to aim eventhub

#### Actual behavior

The issue appears in a ci test project create by our daily ci job, and the function seems sleep after deployment, it didn't execute when we send trigger events and ci job failed. When i open the portal and show the log, eventhub trigger seems to be awaked and execute immediately.

#### Related information 

[CI job log](https://ci.appveyor.com/project/xscript/azure-maven-plugins-vvy0i/builds/21050642)
We could see the job was executed in 2018-12-17T00:21:40Z and function was triggerd in 2018-12-17T01:33:46.781

``` cmd
2018-12-17T01:33:34  Welcome, you are now connected to log-streaming service.
2018-12-17T01:33:46.781 [Information] Executing 'Functions.EventHubTriggerJava' (Reason='', Id=b2370d85-9ed8-436b-a6dd-9e0b3e202e78)
2018-12-17T01:33:46.860 [Information] Executing 'Functions.EventHubTriggerJava' (Reason='', Id=66c0a84f-9bff-4b32-ba1a-1fa34fcfd5be)
2018-12-17T01:33:46.860 [Information] Executing 'Functions.EventHubTriggerJava' (Reason='', Id=7a5f1b69-d80e-40d6-ab19-4f05ba076bfe)
2018-12-17T01:33:46.971 [Information] Executing 'Functions.EventHubTriggerJava' (Reason='', Id=b4b4dcdd-dc35-4e83-a055-e057d09913b9)
2018-12-17T01:33:48.442 [Information] Function "EventHubTriggerJava" (Id: b2370d85-9ed8-436b-a6dd-9e0b3e202e78) invoked by Java Worker
2018-12-17T01:33:48.638 [Information] Function "EventHubTriggerJava" (Id: 66c0a84f-9bff-4b32-ba1a-1fa34fcfd5be) invoked by Java Worker
2018-12-17T01:33:48.640 [Information] Function "EventHubTriggerJava" (Id: 7a5f1b69-d80e-40d6-ab19-4f05ba076bfe) invoked by Java Worker
2018-12-17T01:33:48.647 [Information] Function "EventHubTriggerJava" (Id: b4b4dcdd-dc35-4e83-a055-e057d09913b9) invoked by Java Worker
2018-12-17T01:33:48.679 [Information] Function "EventHubTriggerJava" (Id: e4d6cd37-5463-4399-bd5e-7591818e3ebc) invoked by Java Worker
2018-12-17T01:33:48.946 [Information] Executed 'Functions.EventHubTriggerJava' (Succeeded, Id=66c0a84f-9bff-4b32-ba1a-1fa34fcfd5be)
2018-12-17T01:33:48.947 [Information] Executed 'Functions.EventHubTriggerJava' (Succeeded, Id=b4b4dcdd-dc35-4e83-a055-e057d09913b9)
2018-12-17T01:33:49.044 [Information] Executed 'Functions.EventHubTriggerJava' (Succeeded, Id=b2370d85-9ed8-436b-a6dd-9e0b3e202e78)
2018-12-17T01:33:49.060 [Information] Executed 'Functions.EventHubTriggerJava' (Succeeded, Id=7a5f1b69-d80e-40d6-ab19-4f05ba076bfe)
2018-12-17T01:33:49.061 [Information] Executed 'Functions.EventHubTriggerJava' (Succeeded, Id=e4d6cd37-5463-4399-bd5e-7591818e3ebc)
```

[AzureWebJobsHostLogs201812.typed.xlsx](https://github.com/Azure/azure-functions-host/files/2684636/AzureWebJobsHostLogs201812.typed.xlsx)

**Comment by Flanker32** [comment] 2018-12-17 06:06
@pragnagopa  Please have a view about this issue.

**Comment by pragnagopa** [comment] 2019-01-03 20:05
@Flanker32 - does this repro standalone?

**Comment by Flanker32** [comment] 2019-01-04 07:30
@pragnagopa  Yes, i could repro this issue by creating a new function project, the project has been uploaded to [here](https://github.com/Flanker32/AzureEventhubTriggerTest), it use zip deploy and eventhub java sdk. You may repro this issue by package and deploy the project and run the cleanup.groovy script to create eventhub and trigger it.(You need to set CLIENT_ID,TENANT_ID and KEY environment values as credentials)

**Comment by pragnagopa** [comment] 2019-02-19 01:34
@Flanker32 - Apologies for the late response. Is this still an issue? If yes, please share app name from the most recent run. As of now, we do not have any active CRIs indicating issue with the trigger.

**Comment by Flanker32** [comment] 2019-02-19 04:44
@pragnagopa  We found it may related to the test script, we used to deploy the trigger first and then create the eventhub and set eventhub connection string by azure cli,  and it may lead to this issue, is it behaves by design? If so we plan to update the test case , create and save eventhub connection string to pom in pre build script and then deploy and trigger the test.

**Comment by pragnagopa** [comment] 2019-02-19 19:23
Yes. When a function app starts up, it sets up listeners for various triggers. For E2E tests, a better flow would be to setup azure resources once and run tests against existing azure resources. 

Closing this as by design.

**Closed by pragnagopa** 2019-02-19 19:23 UTC
