### ISSUE TITLE
Function host cannot find an executable file specified  as custom handler in host.json.

### ISSUE THREAD

**Issue by horihiro** [Azure/azure-functions-host#5812] opened 2020-03-20 11:00 UTC
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp: 2020-03-20T00:03:59.456Z
- Function App version: 2.0.13017.0
- Function App name: denofunc-win
- Function name(s) (as appropriate): n/a (because it happened while host was starting up)
- Invocation ID: n/a
- Region: Japan West

#### Repro steps

Provide the steps required to reproduce the problem:

I deployed following files to use [deno](https://deno.land) as a [custom handler](https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-custom-handlers).

```
D:\home\site\wwwroot
  ├── deno.exe (<- `deno` runtime)
  ├── host.json
  ├── HttpTrigger1
  │   └── function.json
  ├── proxies.json
  └── server.ts
```

And host.json deployed is following
```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
  "httpWorker": {
    "description": {
      "defaultExecutablePath": "deno.exe",
      "defaultWorkerPath": "server.ts",
      "arguments": [ "run", "--allow-env", "--allow-net", "--allow-read"]
    }
  }
}
```

Then the function host could not find `deno.exe`.
![image](https://user-images.githubusercontent.com/4566555/77157085-ffcd8180-6ae3-11ea-8537-6dd8312237b6.png)

#### Expected behavior

Provide a description of the expected behavior.

I expected that the host worked file even if `httpWorker` in host.json is such as following

```
  "httpWorker": {
    "description": {
      "defaultExecutablePath": "deno.exe",
      "defaultWorkerPath": "server.ts",
      "arguments": [ "run", "--allow-env", "--allow-net", "--allow-read"]
    }
  }
```

#### Actual behavior

The host cannot find executable file specified in `defaultExecutablePath`.

#### Known workarounds
A workaround is to edit host.json as following.

  1. remove `defaultWorkerPath` property
  1. append `server.ts` to `arguments`

```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
  "httpWorker": {
    "description": {
      "defaultExecutablePath": "deno.exe",
      "arguments": [ "run", "--allow-env", "--allow-net", "--allow-read", "server.ts"]
    }
  }
}
```

#### Related information 

n/a

Could you please let me know if this is expected behavior?

Best Regard,

**Comment by alrod** [comment] 2020-04-03 00:52
cc: @pragnagopa

**Comment by pragnagopa** [comment] 2020-04-03 01:57
This behavior is by design when you are brining in your runtime. 
Setting `defaultExecutablePath`  and 'defaultWorkerPath` allows users to take advantage of the runtimes that are already part of the environment such as node, dotnet etc.

Workaround mentioned is the right way to describe httpWorker section.

FYI, here is the code that parses httpworker section:
https://github.com/Azure/azure-functions-host/blob/c65155a166b39298fa73d611465fe3f92d68de65/src/WebJobs.Script/Workers/Http/HttpWorkerDescription.cs#L24-L34

Closing this as by design.

**Closed as completed by pragnagopa** 2020-04-03 01:57 UTC
Labels: question, httpWorker
