### ISSUE TITLE
Azure Function (linux java EP2) unable to scale out with "Did not find any initialized language workers" & timeout errors

### ISSUE THREAD

**Issue by rahulroy1** [Azure/azure-functions-host#6931] opened 2020-11-24 03:37 UTC
We have 3 Azure Functions with JAVA 8 runtime in single Linux EP2 plan, handling around 500 messages per hour.
1st function is a Cosmos DB Trigger, 2nd one is a Storage Queue trigger function with Cosmos db reads and writes and 3rd one is also a Storage Queue trigger function.

In a one hour window where we putting 500 messages to DB, we can see, instead of plan scaling out (max burst set to 20), the 2nd function is encountering lots of errors:

**Message	Exception: while executing function: Functions.QueueTriggerFunction Did not find any initialized language workers	
Exception type: System.InvalidOperationException	
Failed method: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel
Message | Exception while executing function: Functions.QueueTriggerFunction Did not find any initialized language workers |**  

#### Investigative information

Please provide the following:

- Timestamp: 11/24/2020, 1:50:34 AM IST
- Function App version: 3.0.15065.0
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID: 61cc5701-f964-4dbd-9e17-cffad3a07d20
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:
1. Putting 500 messages into Cosmos DB through a web app
2. Cosmos db trigger kicks the function 1 and puts messages in Storage Queue
3. Function 2 (the impacted one) gets triggered from the queue and reads and writes to CosmosDB
4. Out of 500 messages, we can see 379 got processed by Function (2) but 121 was not processed by Function (2)
5. Application Map shows only 2 instances of Function (2).

#### Expected behavior
Function (2) should scale out more than 2 instances and process all messages without this exception/

#### Related information 
**This same load worked fine on Friday 20/11 and Saturday 21/11 with Function (2) scaling up to 8 instances. (see last image below)**
* Programming language used: Java 8
* Bindings used: Queue Trigger

![Exception](https://user-images.githubusercontent.com/39401248/100057400-5e09eb80-2e4d-11eb-960f-e0c859bc5908.png)
![app-map](https://user-images.githubusercontent.com/39401248/100044100-d0220680-2e34-11eb-9ffc-544fedf23307.jpg)
![Good-example-run](https://user-images.githubusercontent.com/39401248/100044149-f778d380-2e34-11eb-9da5-1ba0091d2dbe.jpg)

**Comment by rahulroy1** [comment] 2020-11-24 03:44
@mhoeger @pragnagopa please help on this.

**Comment by pragnagopa** [comment] 2020-11-24 21:20
@rahulroy1 - can you please confirm information you provided - region and invocation id? I cannot find logs for the invocationid you provided.

**Comment by rahulroy1** [comment] 2020-11-25 03:59
@pragnagopa Here are the details:
Invocation ID: 61cc5701-f964-4dbd-9e17-cffad3a07d20
Region: West Europe

**Comment by rahulroy1** [comment] 2020-11-25 09:45
Hi @pragnagopa 
We tried the following things in parallel.

1. Setting `linuxFxVersion = java|8` in the TF code for function app and it reflects in the config.
2. Reran the load with 500 messages per hour, 1000 messages per hour - all ran successfully without any "language worker" error.

Now at this point, we assumed that it got fixed. 
Now we ran running a load of 5000 messages per hour and all got processed successfully, functionality-wise. 
However I can see 2 occurrences of the following exceptions:

Event time | 11/25/2020, 2:52:01 PM (IST) |  -- | -- | --
Message | Exception while executing function: Functions.<QueueTriggerFunction> Did not find any initialized language workers |  
Exception type | System.InvalidOperationException |  
Failed method | Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel


Event time | 11/25/2020, 2:52:01 PM (IST) |  -- | -- | --
Message | Exception while executing function: Functions.<QueueTriggerFunction> The operation has timed out. |  
Exception type | System.TimeoutException |  
Failed method | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw

**HostInstanceId: 2a501b0c-0a6f-45e0-b5a8-9f404230d839
Invocation ID: c6439d00-ac6b-4270-a814-694028fde5dc
Region: West Europe**

The failure count is only (2) unlike earlier when it ran into hundreds (before linuxFxVersion fix), still we don't have any idea why this is coming only for one of the functions.

**Comment by pragnagopa** [comment] 2020-11-25 16:31
@rahulroy1  - Thanks for reporting and sharing the details. I looked up the logs. This is due to a recent regression https://github.com/Azure/azure-functions-host/issues/6936 and we are in the process for deploying a hotfix 

Until the deployment completes, please use one of following mitigations:

Option 1:  Increase functiontimeout to a large value: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout . Please note that this will require you to re-deploy your app

Option 2: Pin your app to previous runtime version by updating `linuxFxVersion` site config property to `DOCKER|mcr.microsoft.com/azure-functions/java:3.0.14916-java8-appservice`

**Comment by pragnagopa** [comment] 2020-11-26 02:02
Hotfix deployment completed to Linux platform. Closing as addressed.

**Closed as completed by pragnagopa** 2020-11-26 02:02 UTC
Labels: Needs: Attention :wave:

**Comment by rahulroy1** [comment] 2020-11-26 03:21
@pragnagopa Thanks a lot for helping.

One clarification: yesterday we ran continuous load between 10.30pm IST 25th Nov and 8.30 am 26th Nov - around 65k messages in that period.
I can see:
- 0 errors of Language worker
- 8 timeout exceptions although the execution time of the function was in milliseconds (so less then the actual timeout value).

Event time | 11/26/2020, 1:08:28 AM (Local time) |  -- | -- | --
Message | Exception while executing function: Functions.QueueTriggerFunction The operation has timed out. |  
Exception type | System.TimeoutException |  
Failed method | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw

**HostInstanceId	a39937f6-b220-4cbe-92bc-5c1cc8c194f1
InvocationId	5dc45124-7bf5-4494-afda-1dbf6b33407c
Region West Europe**

Can you please share if:
1. this timeout exception is related to the above issue mentioned by you.
2. we are already using `linuxFxVersion = java|8`. Is the correct value which we should continue using it or change to `DOCKER|mcr.microsoft.com/azure-functions/java:3.0.14916-java8-appservice`

Thanks again for the help.

**Comment by rahulroy1** [comment] 2020-11-28 12:45
Can confirm that after the hotfix apply, we ran two load patterns with:
1. 65k messages in 10 hours
2. 2.5k messages in 24 hours.

We found no timeout errors or language worker not found issues.
So this can be closed.

**Comment by pragnagopa** [comment] 2020-11-28 18:26
Thanks for confirming. 

Regarding 

> we are already using linuxFxVersion = java|8. Is the correct value which we should continue using it or change to DOCKER|mcr.microsoft.com/azure-functions/java:3.0.14916-java8-appservice

`linuxFxVersion` set to  `java|8` is the correct value
