### ISSUE TITLE
[.Net] HttpTrigger Model Binding - Collections not desearilized in v2.0.12050.0

### ISSUE THREAD

**Issue by andyroschy** [Azure/azure-functions-host#3370] opened 2018-08-31 23:12 UTC
I have an HTTP trigger function. The binding attribute is set to a custom POCO model. When sending a POST request with JSON content, array properties are not being deserialized in the model (they are left as null). This was working before the update.

#### Investigative information
- Function App version: 2.0.1-beta.36
- Function App name: Localy hosted function with Azure SDK. (Also happens on hosted functions)

#### Repro steps

1. Create a simple Azure function with HttpTrigger bound to a POCO model. The model should have at least one collection property (Array<>, ICollection<>, IEnuerable<>, etc)
2. Send a POST request to the function with correctly formed payload.

#### Expected behavior
The deserialized model should have collection properties correctly deserialized.

#### Actual behavior
All collection properties are null instead. Non collection properties deserialize as expected, including complex objects.

#### Related information 

You can test the issue with the following:
Function code:
```
       [FunctionName("Test")]
        public static async Task<IActionResult> Test(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "test")] TestPayload payload,
            HttpRequest req,
            TraceWriter log,
            ExecutionContext context)
        {

            return new OkObjectResult(true);
        }
```
TestPayload class (you can change the IEnumerable for any collection type, Nested[], ICollection<Nested>, IList<Netsed>, List<Nested>, etc): 
```
    public class TestPayload
    {
        public IEnumerable<Nested> Foo { get; set; }
    }

    public class Nested
    {
        public string Bar { get; set; }
    }
```
Example payloads (none of them work):
```
{
	"Foo": [{"Bar":'bar'}]
}
```
```
{
	"Foo": []
}
```
```
{
	"Foo": [{"Bar":"bar"}, {"Bar":"baz"}]
}
```

I also tried with camelCasing and with the property names without double quotes.

**Comment by ChristianWeyer** [comment] 2018-09-24 11:08
Same here for us - and is a major blocker, obviously 😅 @fabiocav 
Thanks!

**Comment by ChristianWeyer** [comment] 2018-09-26 07:36
Maybe someone can confirm this? @tohling @fabiocav @paulbatum ?
Thank you!

**Comment by andyroschy** [comment] 2018-09-26 16:19
I ended up creating an extension method over HttpRequest to workaround this, maybe it helps someone:

```
        public static T DeserializeModel<T>(this HttpRequest request)
        {
            using (var reader = new StreamReader(request.Body))
            using(var textReader = new JsonTextReader(reader))
            {
                var text = reader.ReadToEnd();
                request.Body.Seek(0, SeekOrigin.Begin);
                var serializer = JsonSerializer.Create(new JsonSerializerSettings()
                {
                    ContractResolver = new CamelCasePropertyNamesContractResolver()
                });
                return serializer.Deserialize<T>(textReader);
            }
        }
```

**Comment by ChristianWeyer** [comment] 2018-10-03 05:48
👌🏼 This is a working workaround (hence the name ;-) )

Would be great to see it fixed in the product, though.
Maybe @fabiocav could look at it?

Thanks!

**Comment by damoodamoo** [comment] 2018-11-02 13:17
I'm seeing the same, currently just having to accept a string and manually use JsonConvert.DeserializeObject<> to properly deserialise to my POCO.

**Comment by joshdcar** [comment] 2018-11-06 02:11
Running into this issue as well. Manual workaround with JsonConvert is less then elegant but does work.  I was about to create a new issue until I found this one so just in case you needed another repository to reproduce this issue you can find mine over here - https://github.com/joshdcar/azure-func-v2-httptrigger-model-binding-bug . It's probably not worth mentioning but this works as expected under Azure Function 1.x.  

Hopefully this will get addressed soon :)

Thanks!

**Comment by joshdcar** [comment] 2018-11-06 03:05
So I did some digging and I believe I potentially candidate for the guilty line of code within a binding utility class used by the HttpTriggerAttributeBindingProvider of the HttpTrigger. 

[https://github.com/Azure/azure-webjobs-sdk-extensions/blob/cdeb65faacf04c53845fb76c4b513c9998fc97de/src/WebJobs.Extensions.Http/Utility.cs#L29](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/cdeb65faacf04c53845fb76c4b513c9998fc97de/src/WebJobs.Extensions.Http/Utility.cs#L29)

It appears that the binding logic is explicitly excluding arrays for some reason (**p.Value.Type != JTokenType.Array**) while deserializing. 

```
JObject parsed = JObject.Parse(json);
 var additionalBindingData = parsed.Children<JProperty>()
         .Where(p => p.Value != null && (p.Value.Type != JTokenType.Array))
         .ToDictionary(p => p.Name, p => ConvertPropertyValue(p));
```

Please advice if I should create a new issue over on that Repo since it looks like the issue is actually out of that code base (azure-webjobs-sdk-extensions). Also feel free to tell me I'm going down the wrong rabbit hole :)  

Thanks!

**Comment by ChristianWeyer** [comment] 2019-02-07 14:39
Any idea when this will (finally) be merged @fabiocav ? Thanks!

**Comment by ChristianWeyer** [comment] 2019-02-27 09:21
Hi guys - just wanted to check about the status of this.
It has been open since September 2018 - and it really is a very basic and essential feature of a Web API-like facade framework.

Some customers talked to me at conferences, and they really have a hard time in building faith and trust into Azure Functions when even such a basic thing is not working - or is not being fixed for such a long time.

@jeffhollan @fabiocav 

Thanks!

**Comment by jeffhollan** [comment] 2019-02-28 05:34
Thanks for the ping. Been working through and triaging some things.  Not sure how this fell off but will move it to the top of the backlog and make sure we pick up in an upcoming sprint (or at least circle back if the fix is non-trivial for some reason)

**Comment by ChristianWeyer** [comment] 2019-02-28 05:50
Thanks @jeffhollan !

**Comment by jeffhollan** [comment] 2019-03-01 00:50
Has a workaroud so bumping to P1

**Comment by lukasvosyka** [comment] 2019-04-27 13:49
This is still open! Just ran into the same issue. Using an ordinary custom model for HttpTrigger binding won't deserialize arrays, collections, etc. Instead need to go via HttpRequestMessage or similar and deserialize on it own.

**Comment by jason-system1** [comment] 2019-05-07 11:18
Chop, chop!

**Comment by nmfisher** [comment] 2019-05-20 02:18
Just ran into this one myself - any indication of when this will be merged? Workaround is fine but a touch messy for such a core feature.

**Comment by ChristianWeyer** [comment] 2019-07-18 06:23
... I keep knocking for the upcoming years ... 😇 @fabiocav @jeffhollan

**Comment by fabiocav** [comment] 2019-07-18 17:14
@ChristianWeyer and others, let me share a way to address this that requires a bit of code, but it's relatively clean...

You can use the DI support (add a reference to `Microsoft.Azure.Functions.Extensions`) to configure some of this behavior. The following should address your issue:

``` csharp
using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters.Json.Internal;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Options;

[assembly:FunctionsStartup(typeof(MyFunctionApp.Startup))]

namespace MyFunctionApp
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddTransient<IConfigureOptions<MvcOptions>, MvcJsonMvcOptionsSetup>();
        }
    }
}

```

We're looking into options to do this out of the box with an opt-in model (as some of the behavior differences introduced by this could break other customers). But this should give you what you need for now.

**Comment by galvesribeiro** [comment] 2019-07-20 07:44
@ChristianWeyer make sure the attribute and the base class are as on his example.

**Comment by ChristianWeyer** [comment] 2019-07-20 08:26
They are, thanks for the idea @galvesribeiro

**Comment by macux** [comment] 2019-08-22 06:55
@fabiocav - I've added the suggested code to my function's startup but I'm still seeing the issue described here: https://github.com/Azure/azure-webjobs-sdk-extensions/issues/511 - (array input binding broken in v2) should your code fix this as well? My startup is fine generally as I was already successfully using DI with the function in question.

**Comment by zpittmansf** [comment] 2019-10-23 16:09
Is there an update on a fix for this or a pull request that is in progress at least?

**Comment by CasperWSchmidt** [comment] 2020-02-11 12:21
1½ years later and still not fixed? Reports say this worked in V1 so it is clearly a regression and should be fixed ASAP (no opt-in this should just work)

**Comment by galvesribeiro** [comment] 2020-02-11 14:18
@CasperWSchmidt yeah... Look at the age of other issues/PRs. There is one for AI, and many others. Sometimes I wonder if Functions is something that will be long term supported since it takes ages to something get fixed, event the simple ones...

**Comment by fabiocav** [comment] 2020-02-11 15:45
@CasperWSchmidt are you experiencing this in 3.0? The workaround for 2.0 was provided as there were potential issues with changes to the default serialization behavior there.

@galvesribeiro  I’m sorry if that is the impression you’re getting. I can assure you the team is committed to the service and the product. Following our sprints is the best way to see what the team is actively working on. We try to make sure issues are correctly prioritized for assignment, and I’m sorry if some of the ones you’ve been following have sat for a while. We’re working to address that.

**Comment by galvesribeiro** [comment] 2020-02-11 16:56
@fabiocav thanks for getting back. You are the only one from the team I see around. This impression comes exactly because of what @CasperWSchmidt said... 

> 1½ years later and still not fixed?

Don't take me bad, this is not just me as you may see. There are multiple issues that are critical for many customers (like myself) like this one which makes things way harder...

**Comment by fabiocav** [comment] 2020-02-11 17:03
Understood. We recognize that a set of issues haven’t been prioritized (mostly because of competing priorities) and we’re working to address that.

Are you still experiencing this in 3.0? For this particular issue, given that we have a viable workaround that made this behavior configurable, the priority hasn’t been as high as others where users were completely blocked, but I do agree it is an inconvenience.

**Comment by galvesribeiro** [comment] 2020-02-11 17:20
@fabiocav I do have migrated all my functions to `System.Text.Json` to avoid those serialization issues:

```csharp
[FunctionName(nameof(TestFunc))]
public async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "/test")] HttpRequest request)
{
    var obj = await JsonSerializer.DeserializeAsync<TestBody>(request.Body, Constants.SerializerOptions);
    ....
}
```

That way I don't need any hacks.

**Comment by galvesribeiro** [comment] 2020-02-11 17:34
But it still, this issue should be addressed so people that still use JSON.Net can have it sorted.

I honestly think the best way to solve this is to let people register at the DI container their own serializer for the `HttpRequest.Body` on the `Startup.cs`. 

An abstraction like this with the a default implementations (i.e. JSON.Net or System.Text.Json) would work perfectly:

```csharp
public interface IBodySerializer
{
    string[] SupportedContentTypes { get; }
    ValueTask<TBody> Deserialize<TBody>(Stream body);
}
```

That would just work across the board. Multiple serializers could be registered for a set of content types and the appropriated one would be invoked based on the `Content-Type`.

**Comment by CasperWSchmidt** [comment] 2020-02-12 07:48
@fabiocav We are not running V3 as that gave us some other interesting issues. As mentioned in https://github.com/Azure/azure-webjobs-sdk-extensions/issues/486#issuecomment-584621155 I can't get the work-around to run.

**Comment by jeffhollan** [comment] 2020-03-02 22:34
@fabiocav  / others can we confirm if this is fixed in v3?  For others realize it's a bit more of a pain but since this was a breaking change the plan was to bring along with a major version.  Until then the [mitigation from fabio](https://github.com/Azure/azure-functions-host/issues/3370#issuecomment-512906790) is the best option.

**Comment by vitalybibikov** [comment] 2020-03-04 10:03
It is still reproducible in v3. (in 3.0.3), can't check in 3.0.4 as a Critical bug was introduced their and Startup is not being called.

**Comment by DenisBalan** [comment] 2020-03-16 17:43
Still not fixed in v3

**Comment by proton888** [comment] 2020-03-18 19:31
having errors with this in V_3.05 still

**Comment by CasperWSchmidt** [comment] 2020-03-18 20:43
It's truly amazing that such a basic feature (which goes back to before 2013 in newtonsoft.json) is still an open issue here. Especially since it is a clear regression between v1 and v2/3.
@jeffhollan how can a regression and only partial object deserialization ever be a breaking change? Who on earth would rely on this "feature"?

**Comment by fredrikdaveus** [comment] 2020-03-28 15:00
> @fabiocav I do have migrated all my functions to `System.Text.Json` to avoid those serialization issues:
> 
> ```cs
> [FunctionName(nameof(TestFunc))]
> public async Task<IActionResult> Run(
>     [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "/test")] HttpRequest request)
> {
>     var obj = await JsonSerializer.DeserializeAsync<TestBody>(request.Body, Constants.SerializerOptions);
>     ....
> }
> ```
> 
> That way I don't need any hacks.

There's one problem though. It doesn't seem to be possible to use the batching features, as you cannot have HttpRequest[] requests as a parameter.

Or, is there a workaround here as well using custom deserialisation? (which we do anyways for performance reasons)

**Comment by fabiocav** [comment] 2020-04-29 20:19
Work on this is currently in progress. Moving to sprint 75 to reflect the current status.

**Comment by alrod** [comment] 2020-05-12 20:55
The issue is fixed in the V3. 
Please reopen the issue if it's still reproducible in V3.

**Closed by alrod** 2020-05-12 20:55 UTC
Labels: P1, bug

**Comment by CasperWSchmidt** [comment] 2020-05-13 06:06
Where do I find the fix? And what about V2. This issue is raised against a 2.0.1 beta and according to https://github.com/Azure/azure-functions-host/issues/3370#issuecomment-436106870 it worked in V1.
I would expect this bug to be fixed in V2 as well unless it has publicly been deprecated?

**Comment by CasperWSchmidt** [comment] 2020-06-08 19:47
@alrod I'm trying to get this to work in V3. Brand new project with Azure Functions V3, host version 3.0.13353.0 (as reported when I start debugging the project).

I have a simple POCO:
```
public class PostCurrenciesCommand : ICommand
    {
        public List<CurrencyModel> Currencies { get; set; }
        
        public PostCurrenciesCommand()
        {
            Currencies = new List<CurrencyModel>();
        }
    }
```
(setting a temp object in constructor since I'm also testing C# 8 nullable reference types)

Using the following JSON:
```
[
	{
		"code": "DKK",
		"name": "Danske kroner",
		"location": "Danmark"
	},
	{
		"code": "USD",
		"name": "American dollar",
		"location": "United States of America"
	},
	{
		"code": "EUR",
		"name": "Euro",
		"location": "European Union"
	}
]
```
I have also tried wrapping the array:
```
{
    "currencies": [
	{
		"code": "DKK",
		"name": "Danske kroner",
		"location": "Danmark"
	},
	{
		"code": "USD",
		"name": "American dollar",
		"location": "United States of America"
	},
	{
		"code": "EUR",
		"name": "Euro",
		"location": "European Union"
	}
]
}
```

I can't get my Function to work:
```
public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "v1/currency")] PostCurrenciesCommand command, CancellationToken cancellationToken)
```
I have also tried a simple List:
```
public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "v1/currency")] List<CurrencyModel> currencies, CancellationToken cancellationToken)
```
Whatever I do I get an empty list. Please let me know what I need to do to use the model binding with lists

**Comment by feminho** [comment] 2020-06-18 08:30
I'm getting the same error with Azure Functions 3.1 when trying to deserealize a message from a queue using Newtonsoft.Json

```
    public class JsonMessageSerializer : ISerializer
    {
        public T Deserialize<T>(string message)
        {
            return JsonConvert.DeserializeObject<T>(message);
        }

        public string Serialize(object obj)
        {
            return JsonConvert.SerializeObject(obj);
        }
    }
```

I have log before and after call JsonMessageSerializer.Deserialize and log stream shows that code crashes at this point. 

> Error: One or more errors occurred. (Value cannot be null. (Parameter 'resource'))

The project where the serealization is running has .Net Core 3.0.
The Azure function has its SDK on 3.0.7 and target .Net Core 3.1
