### ISSUE TITLE
Exceptions "node exited with code -1" on function apps

### ISSUE THREAD

**Issue by zeeshan-aym** [Azure/azure-functions-host#3876] opened 2018-12-11 11:25 UTC
We are having "node exited with code -1" exceptions on our different function apps. There is no much details being logged against this exception. also worth mentioning that triggered functions also working fine. There is no such issue observed to test on local env.
Please be informed that these exceptions are on and off, sometimes it happen one time when function gets trigger and sometimes it happen more than 2 times in an half an hour.

#### Investigative information

Please provide the following:

- Timestamp: 2018-12-11T10:30:00.0051731+00:00
- Function App version (1.0 or 2.0): 2.0.12210.0 (~2)
- Function App name: 
- Function name(s) (as appropriate):
- Invocation ID: 2da8d2f2-2d57-41df-8b7d-08b1324e8f43
- Region:East US 2

#### Repro steps

Unfortunately we are unable to reproduce the problem because function itself triggered correctly but thrown exceptions so keen to know about this exception.

#### Expected behavior

Function triggered
Function completed successfully
No exceptions in application insights

#### Actual behavior

Function triggered
Function completed successfully
Exceptions thrown

#### Known workarounds

Function runtime version has been upgraded to latest one.

#### Related Information

Exception Type ->  Microsoft.Azure.WebJobs.Script.Rpc.LanguageWorkerProcessExitException

**Comment by mhoeger** [comment] 2018-12-14 07:43
You can safely ignore those exceptions as they are expected (root cause is this: https://github.com/Azure/azure-functions-host/issues/3415).

Those exceptions will go away after resolving #3415, but we should also look into seeing if we can get those logs out of the exceptions table in Application Insights too.

**Comment by pragnagopa** [comment] 2019-02-18 19:28
Closing this as host will log process exits with -1 as debug logs https://github.com/Azure/azure-functions-host/blob/b99edf799d532304ddcf4fd37328f0289594d512/src/WebJobs.Script/Rpc/LanguageWorkerChannel.cs#L461

**Closed by pragnagopa** 2019-02-18 19:28 UTC
