### ISSUE TITLE
Add new admin APIs to fetch aggregate status / error details persisted logs for function overview

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#6981] opened 2020-12-10 22:28 UTC
#### Describe the solution you'd like
- Pending

#### Additional context
- Pending

**Comment by fabiocav** [comment] 2021-01-20 21:47
@apawast FYI

**Comment by fabiocav** [comment] 2021-03-03 21:40
Duplicate of #7125

**Closed as completed by fabiocav** 2021-03-03 21:40 UTC
Labels: supportability
