### ISSUE TITLE
Huge number of "Host configuration has changed. Signaling restart" logs on functionapp publish

### ISSUE THREAD

**Issue by mattbierner** [Azure/azure-functions-host#2585] opened 2018-03-26 05:20 UTC
Similar to https://github.com/Azure/azure-functions-host/issues/2095

#### Investigative information

Please provide the following:

- Timestamp: NA
- Function App version (1.0 or 2.0-beta):  1.0.11612.0 (latest)
- Function App name: GifSliceApi
- Function name(s) (as appropriate): NA
- Invocation ID: NA
- Region: West US

#### Repro steps

Ran `$ func azure functionapp publish GifSliceApi`

This kicked off a huge number of these log events:

```
...
018-03-26T05:09:22.361 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\Tools\autorest.gen.cmd'
2018-03-26T05:09:22.361 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.470 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\Tools\autorest.gen.cmd'
2018-03-26T05:09:22.470 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.470 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\Tools\autorest.gen.cmd'
2018-03-26T05:09:22.470 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.595 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\jsdocs\jsdoc.conf.json'
2018-03-26T05:09:22.595 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.595 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\jsdocs\jsdoc.conf.json'
2018-03-26T05:09:22.595 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.612 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\jsdocs\jsdoc.conf.json'
2018-03-26T05:09:22.612 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.612 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\jsdocs\jsdoc.conf.json'
2018-03-26T05:09:22.612 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.658 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\runtime\NodeJSClientRuntime.sln'
2018-03-26T05:09:22.658 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.674 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\runtime\NodeJSClientRuntime.sln'
2018-03-26T05:09:22.674 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.674 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\runtime\NodeJSClientRuntime.sln'
2018-03-26T05:09:22.674 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.705 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\runtime\NodeJSClientRuntime.sln'
2018-03-26T05:09:22.705 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.720 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\runtime\.jshintrc'
2018-03-26T05:09:22.720 [Info] Host configuration has changed. Signaling restart
2018-03-26T05:09:22.720 [Info] Watched directory change of type 'Changed' detected for 'D:\home\site\wwwroot\node_modules\azure\runtime\.jshintrc'
2018-03-26T05:09:22.720 [Info] Host configuration has changed. Signaling restart
...
```

Which used up my entire AI quota in like five minutes

I actually don't even want to deploy `node_modules` at all as my functions are webpacked into single files. I have a `.funcignore` file with `node_modules`, but this did not seem to prevent `node_modules` files from being uploaded

**Comment by pragnagopa** [comment] 2018-03-26 17:08
@ahmelsayed - is it by design that funcignore does not exclude files under node_modules? Is there a work around?

**Comment by ahmelsayed** [comment] 2018-03-26 17:39
`.funcignore` support hasn't been released yet in the cli. adding `*/node_modules` to `.funcignore` should exclude all node_modules folder from deployment. We'll be releasing a new cli this week

**Comment by mattbierner** [comment] 2018-03-27 03:48
Thanks. Yes `.funcignore` node_modules should have prevented this from happening kin the first place

But triggering a restart for each file seems like a bug. What if my functions did actually need files from `node_modules`?

**Comment by pragnagopa** [comment] 2018-03-27 19:59
Yes, we need to figure out a way not to restart on every file when deploying via CLI

**Comment by paulbatum** [comment] 2018-03-27 20:50
So as far as I can tell we're not actually doing all those restarts. The restart operation is being signaled but its debounced, so only one restart should occur, at the end. We should probably change those messages to verbose level though.

**Comment by Robula** [comment] 2018-04-06 10:32
@ahmelsayed Has the support for `.funcignore` been released? I am still having `node_modules` uploaded.

Azure Functions Core Tools (220.0.0-beta.0)
Function Runtime Version: 2.0.11651.0

**Comment by ahmelsayed** [comment] 2018-04-09 16:47
Yes that version should have the `.funcignore` changes. 

Can you try adding `--list-ignored-files` or `--list-included-files`? 

I think the regex parsing I have currently is more strict that git. Try `*/node_modules` instead of `node_modules`

**Comment by Robula** [comment] 2018-04-10 08:26
Thank you @ahmelsayed, those switches helped me discover where I was going wrong. All working now!

**Comment by ahmelsayed** [comment] 2018-04-10 18:16
Thanks for confirming @Robula

**Comment by pragnagopa** [comment] 2018-05-01 16:49
closing as .funcignore option works.

**Closed by pragnagopa** 2018-05-01 16:49 UTC
Labels: improvement
