### ISSUE TITLE
Function Apps on Linux Consumption show WarmUp function

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-host#4038] opened 2019-02-01 03:40 UTC
Currently if you publish your functions to a Linux Function App running on the Consumption Plan, an additional function called `WarmUp` starts to surface in the project. This is a **known issue** and we're currently working on the fix.

## Where does this function show up?

The WarmUp function can surface in two ways: 

1. Core Tools 
    example -
    ![image](https://user-images.githubusercontent.com/8435148/52100864-2fdb5d80-258e-11e9-9aca-803637f962fb.png)

2. Portal 
    example -
    ![image](https://user-images.githubusercontent.com/8435148/52101279-af1d6100-258f-11e9-98a6-6878643647ba.png)

## How does it impact my Function App? 

The `WarmUp` function **does not** impact the functionality of the rest of your app. It's a harmless addition to the project and is expected to return a 404 for JavaScript and Python based apps. 

**We'll update this thread once the fix is available.**

**Comment by fabiocav** [comment] 2019-02-01 18:33
Duplicate of #4015

**Comment by mathewc** [comment] 2019-02-01 23:51
We've verified the fix in PR https://github.com/Azure/azure-functions-host/pull/4040 addresses the issue. We'll be deploying that fix soon.

**Closed** 2019-02-01 23:50 UTC
