### ISSUE TITLE
Custom Handler Function App with a timer triggered function occasionally receives invalid timestamps

### ISSUE THREAD

**Issue by ZachTB123** [Azure/azure-functions-host#7391] opened 2021-05-20 20:14 UTC
I have multiple Function Apps using Custom Handlers with Golang that are running timer triggered functions. Occasionally my code fails to parse the times provided in the [request payload](https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers#request-payload).

The normal/expected request payload looks like the following:

<img width="794" alt="Screen Shot 2021-05-20 at 3 01 35 PM" src="https://user-images.githubusercontent.com/17228033/119041537-5c445f00-b97c-11eb-8030-0b13e8db24b0.png">

An unexpected request payload that breaks my parsing is like the following:

<img width="798" alt="Screen Shot 2021-05-20 at 3 02 27 PM" src="https://user-images.githubusercontent.com/17228033/119041657-7da54b00-b97c-11eb-89e8-2e10118f63a0.png">

Here the problem is `Last` and `LastUpdated`. This only happens occasionally (not every invocation of my timer triggered function). 

#### Investigative information

Please provide the following:

- Timestamp: 2021-05-17T21:00:00.163207Z
- Function App version: 3.0.15584.0
- Function App name: 
- Function name(s) (as appropriate):
- Invocation ID: e1040a7f-b79d-4361-970b-3a55b9cad22c 
- Region: centralus

#### Repro steps

Create a custom handler function app with a timer trigger function. Let it run for a while.

#### Expected behavior

Correct timestamp values are provided to my functions in the request payload.

#### Actual behavior

`Last` is set to `0001-01-01T00:00:00` and `LastUpdated` is set to `0001-01-01T00:00:00`

#### Known workarounds

N/A

#### Related information 

function.json:

```
{
  "bindings": [
    {
      "name": "timer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */15 * * * *"
    }
  ]
}
```

**Comment by v-anvari** [comment] 2021-05-21 09:26
Hi @ZachTB123 , Thank you for your feedback! We will investigate this further and update as appropriate.

**Comment by v-anvari** [comment] 2021-05-21 17:19
Hi @ZachTB123 , Every time the function runs, I see there is a warning before the function completes:

![image](https://user-images.githubusercontent.com/66122429/119173076-5cc81d00-ba84-11eb-823f-f35bc4ff0c24.png)


But, as you mentioned, between the time stamp - 2021-05-17 00:30:00 to 2021-05-19 23:00:00 , there is only once the error occurred with the invocation id - e1040a7f-b79d-4361-970b-3a55b9cad22c, which is running successfully but with an exception as shown below, which looks a request error:

Can you tell me if the you see this kind off behavior with any other invocation id as well. Because I don't see any other exception.

Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.dynamic_app_settings ---> System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at async Microsoft.Azure.WebJobs.Script.Workers.Http.DefaultHttpWorkerService.ProcessDefaultInvocationRequest(ScriptInvocationContext scriptInvocationContext) at D:\a\1\s\src\WebJobs.Script\Workers\Http\DefaultHttpWorkerService.cs : 186
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at D:\a\1\s\src\WebJobs.Script\Description\Workers\WorkerFunctionInvoker.cs : 93
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at D:\a\1\s\src\WebJobs.Script\Description\FunctionInvokerBase.cs : 82
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs : 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 555
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 501
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 279
   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 326
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 94

**Comment by ZachTB123** [comment] 2021-05-21 19:23
@v-anvari Those warnings you posted aren't impacting our invocations at all. Issue #6717 talks about this and I've commented there in the past that I would like to see those messages go away since they are just noise since our function doesn't have any return values or outputs.

The `Response status code does not indicate success: 500 (Internal Server Error).` exception you see is expected because that is my application code complaining that it could not parse the timestamps given to us. I'm returning a non-200 status code to surface the error in application insights. Other invocations will not have this exception since they were able to parse the timestamp correctly.

I have other examples of this occurring. Here are just a few:

Invocation id = 75ff6370-b97b-4eae-84e2-76bd567ad5b6, Timestamp = 2021-05-21T06:30:00.317142Z

Invocation id = 4f5abeef-6422-4182-ad7c-0b66d9e150a4, Timestamp = 2021-05-20T22:00:00.527317Z

Invocation id = b101e5b3-86b1-40e4-949a-cb1ec715212d, Timestamp = 2021-05-20T18:15:00.252313Z

Invocation id = be5b99e3-5a32-458c-94de-a69eb563df35, Timestamp = 2021-05-20T17:45:00.236295Z

With all of these, I expect you'll see the same `Response status code does not indicate success: 500 (Internal Server Error).` exception because my code is failing to parse the timestamps.

**Comment by v-anvari** [comment] 2021-05-24 16:53
@ZachTB123 , Thank you for your feedback 

Tagging @pragnagopa / @yojagad for further investigation.

**Comment by yoichiozaki** [comment] 2022-11-17 03:34
Hi @kashimiz 

Has this issue been resolved?

I am currently working on an incident in a Java timer trigger function app where an error occurs when deserializing the timer object.

```
Exception: IllegalArgumentException: No time zone indicator
Stack: com.google.gson.JsonSyntaxException: Failed parsing '0001-01-01T00:00:00' as Date;
at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:90)
at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:75)
at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:46)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
... (omit below)
```

It seems like it is due to an incorrect timestamp being passed.
Please fix it so that the timestamp will be passed to the function code with an time zone indicator, such as +00:00 at the end of the timestamp.

**Comment by yoichiozaki** [comment] 2022-11-18 06:06
The value of the timer object given at the first execution after the function host started sometimes appears to be a value without a time zone indicator.

**Comment by fabiocav** [comment] 2022-11-18 17:01
Flagging this for triage and investigation

**Comment by yoichiozaki** [comment] 2023-02-09 11:21
Hi @fabiocav @kashimiz @liliankasem 
Do you know which version of the Function runtime causes this issue? and is there any workaround which the customer can implement?

**Comment by yoichiozaki** [comment] 2023-02-09 11:25
I am currently being contacted by a customer about an issue where this issue (timezone error) occurs on initial run and all subsequent scheduled runs timed out (30 min).
Do you think the situation is related to this issue?

**Comment by liliankasem** [comment] 2023-02-15 00:19
I was able to reproduce this pretty easily with a basic java timer trigger

```logs
[2023-02-15T00:10:00.069Z] Executing 'Functions.keepAlive' (Reason='Timer fired at 2023-02-14T16:10:00.0213950-08:00', Id=7203f2f4-c61c-4e82-b0a1-1883ca34bf83)
[2023-02-15T00:10:00.178Z] Timer is triggered:
 {
 	"Schedule": {
 		"AdjustForDST": true
 	},
 	"ScheduleStatus": {
 		"Last": "0001-01-01T00:00:00",
 		"Next": "2023-02-14T16:10:00-08:00",
 		"LastUpdated": "0001-01-01T00:00:00"
 	},
 	"IsPastDue": false
 }
[2023-02-15T00:10:00.179Z] Function "keepAlive" (Id: 7203f2f4-c61c-4e82-b0a1-1883ca34bf83) invoked by Java Worker
[2023-02-15T00:10:00.216Z] Executed 'Functions.keepAlive' (Succeeded, Id=7203f2f4-c61c-4e82-b0a1-1883ca34bf83, Duration=179ms)
```

We can see that Last and LastUpdated is set to `0001-01-01T00:00:00` without a timezone value. So if customers are trying to parse these two properties, it is likely to throw an exception i.e. 

```logs
Exception: IllegalArgumentException: No time zone indicator
Stack: com.google.gson.JsonSyntaxException: Failed parsing '0001-01-01T00:00:00' as Date; at path $.ScheduleStatus.
```

We can see where this is getting initialized in the [webjobs timer extension](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/23de1c1df9a6f089d295b5e52bdca5ae5fe037c8/src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs#L111-L119):

```csharp
if (ScheduleStatus == null)
{
    // no schedule status has been stored yet, so initialize
    ScheduleStatus = new ScheduleStatus
    {
        Last = default(DateTime),
        Next = _schedule.GetNextOccurrence(now)
    };
}
```

Will keep looking into this and see if we can fix it.

Edit:

Confirmed it's the same for a dotnet-isolated function:

```json
{
	"Schedule": {
		"AdjustForDST": true
	},
	"ScheduleStatus": {
		"Last": "0001-01-01T00:00:00",
		"Next": "2023-02-14T16:50:00-08:00",
		"LastUpdated": "0001-01-01T00:00:00"
	},
	"IsPastDue": false
}
```

However in c# we're able to deserialize this without any issues.

**Comment by liliankasem** [comment] 2023-02-16 00:38
On second thought, I'm not sure that this is a fix for the timer extension but potentially a fix in the workers. I was able to easily repro this with a java worker

```java
    @FunctionName("keepAliveTimer1")
    public void keepAliveTimer1(
        @TimerTrigger(name = "keepAlive1", schedule = "0 */1 * * * *") TimerInfo timerInfo,
        ExecutionContext context
    ) {
        context.getLogger().info("Last: " + timerInfo.ScheduleStatus.Last);
    }
```

Which gave me the following exception:

```log
[2023-02-16T00:31:00.253Z] Executed 'Functions.keepAliveTimer1' (Failed, Id=ac361ee7-1371-445e-91ba-eb04fd72994c, Duration=218ms)
[2023-02-16T00:31:00.253Z] System.Private.CoreLib: Exception while executing function: Functions.keepAliveTimer1. System.Private.CoreLib: Result: Failure
[2023-02-16T00:31:00.253Z] Exception: IllegalArgumentException: No time zone indicator
[2023-02-16T00:31:00.253Z] Stack: com.google.gson.JsonSyntaxException: Failed parsing '0001-01-01T00:00:00' as Date; at path $.ScheduleStatus.Last
[2023-02-16T00:31:00.253Z]      at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:90)
```

In the Java worker, this is parsed via `gson.fromJson(sourceValue, targetType);`

[code](https://github.com/Azure/azure-functions-java-worker/blob/385d93af4bd5727336e3e937064a49457616ea70/src/main/java/com/microsoft/azure/functions/worker/binding/RpcJsonDataSource.java#L26)

Which could be fixed by using Gson builder to include a DT format:

`new GsonBuilder().setDateFormat("yyyy-MM-dd'T'HH:mm:ss").create();`

I'll need to look at what's happening with the custom handler. @ZachTB123 what does your custom timer trigger look like?

cc: @kaibocai for more investigation on the Java side.

**Comment by kaibocai** [comment] 2023-02-16 23:36
> Hi @fabiocav @kashimiz @liliankasem Do you know which version of the Function runtime causes this issue? and is there any workaround which the customer can implement?

@zakimal a potentail workaround would be binding to `String` type and customize gson in the function to deserialize. 
example:
```java
    @FunctionName("keepAliveTimer1")
    public void keepAliveTimer1(
            @TimerTrigger(name = "keepAlive1", schedule = "0 */1 * * * *") String timerInfoData,
            ExecutionContext context
    ) {
        Gson gson = new GsonBuilder().setDateFormat("yyyy-MM-dd'T'HH:mm:ss").create();
        TimerInfo timerInfo = gson.fromJson(timerInfoData, TimerInfo.class);
        context.getLogger().info("Last: " + timerInfo.ScheduleStatus.Last);
    }
```

Meanwhile I am checking with the team on supporting [customize gson instance feature](https://github.com/Azure/azure-functions-java-worker/pull/704#issuecomment-1433873547). Will keep you updated. 

@liliankasem I do have one question on the default time zone indicator, based on my understanding, the very first timestamp of timer trigger is not meaningful, so can we add an default time zone indicator for it, is there any specific reason why we ignore the time zone indicator for the first timestamp? Thanks.

**Comment by liliankasem** [comment] 2023-02-16 23:40
> > Hi @fabiocav @kashimiz @liliankasem Do you know which version of the Function runtime causes this issue? and is there any workaround which the customer can implement?
> 
> @zakimal a potentail workaround would be binding to `String` type and customize gson in the function to deserialize. example:
> 
> ```java
>     @FunctionName("keepAliveTimer1")
>     public void keepAliveTimer1(
>             @TimerTrigger(name = "keepAlive1", schedule = "0 */1 * * * *") String timerInfoData,
>             ExecutionContext context
>     ) {
>         Gson gson = new GsonBuilder().setDateFormat("yyyy-MM-dd'T'HH:mm:ss").create();
>         TimerInfo timerInfo = gson.fromJson(timerInfoData, TimerInfo.class);
>         context.getLogger().info("Last: " + timerInfo.ScheduleStatus.Last);
>     }
> ```
> 
> Meanwhile I am checking with the team on supporting [customize gson instance feature](https://github.com/Azure/azure-functions-java-worker/pull/704#issuecomment-1433873547). Will keep you updated.
> 
> @liliankasem I do have one question on the default time zone indicator, based on my understanding, the very first timestamp of timer trigger is not meaningful, so can we add an default time zone indicator for it, is there any specific reason why we ignore the time zone indicator for the first timestamp? Thanks.

Yes, they are not meaningful. I have a PR that will add a timestamp indicator to the them but I don't know for sure that it will be a breaking change or not. Waiting for more reviews on it before going forward.

**Comment by liliankasem** [comment] 2023-02-24 20:05
The PR to update the default values to include a timezone indicator has been checked in. This will go out in the next stable release of the WebJobs Extension and Host (eta: ~1 month from now).  There's a workaround provided in the discussion above in the meantime.

**Closed as completed by liliankasem** 2023-02-24 20:05 UTC
Labels: needs-investigation
