### ISSUE TITLE
Adding a second extension via the ExtensionsController fails due to files in use

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#2100] opened 2017-11-03 16:10 UTC
The controller attempts to delete the /bin directory and copy the temp, but some files may be in use and this fails.

**Comment by paulbatum** [comment] 2018-05-03 20:39
Dupe of https://github.com/Azure/azure-functions-host/issues/2548

**Closed by paulbatum** 2018-05-03 20:39 UTC
Labels: 2.0, bug, feature:byob
