### ISSUE TITLE
Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### ISSUE THREAD

**Issue by JimiSmith** [Azure/azure-functions-host#2856] opened 2018-05-16 17:02 UTC
A different version of System.Runtime.CompilerServices.Unsafe appears to be present at runtime compared to what is referenced by the various function nuget packages. This seems to be causing problems for the ImageSharp library.

[I did report this in the ImageSharp repo as well](https://github.com/SixLabors/ImageSharp/issues/574)

#### Investigative information

Please provide the following:

- Timestamp: 2018-05-14T22:35:37.6560098+00:00
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function name(s) (as appropriate): BlobEventGridTrigger
- Invocation ID: db51b97f-61b8-4db2-b275-2941ef0bda2a
- Region: West Europe

#### Repro steps

Create a V2 function that references [ImageSharp](https://github.com/SixLabors/ImageSharp)
Attempt to resize an image

#### Expected behavior

System.Runtime.CompilerServices.Unsafe should be loaded correctly

#### Actual behavior

System.Runtime.CompilerServices.Unsafe will not be loaded by ImageSharp.

#### Known workarounds

None

#### Related information 

<summary>Exception</summary>

<details>

```
Exception while executing function: BlobEventGridTrigger
<--- Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
<--- Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

</details>

<summary>csproj</summary>

<details>

```xml

<Project Sdk="Microsoft.NET.Sdk;Microsoft.NET.Sdk.Publish">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0-beta1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.13" />
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-dev001335" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

```
</details>

<summary>Function Snippet</summary>

<details>

```csharp

using (var stream = new MemoryStream())
using (var outStream = new MemoryStream())
{
    await blob.DownloadToStreamAsync(stream);
    using (var image = Image.Load(stream))
    {
        image.Mutate(x => x.Resize(width, height));
        image.SaveAsJpeg(outStream);
    }
}

```

</details>

**Comment by fabiocav** [comment] 2018-05-16 18:12
@JimiSmith your function is currently on version `2.0.11651.0` or the rutime. This should be addressed on the latest preview update that is rolling out right now (2.0.11776.0).  The rollout should be completed by the end of the week

**Comment by fabiocav** [comment] 2018-05-16 18:18
You can subscribe to this repo and follow this issue to track the progress:
https://github.com/Azure/app-service-announcements/issues/106

**Comment by JimiSmith** [comment] 2018-05-19 07:46
Thanks @fabiocav . I also have this issue when running locally. Is there anyway to resolve/work around the error when running locally?

**Comment by fabiocav** [comment] 2018-05-21 17:02
The local development tools (Azure Functions Core Tools) will be updated shortly and will reflect what has been deployed. In the meantimg, you can install what is on npm here: https://www.npmjs.com/package/azure-functions-core-tools by running `npm i -g azure-functions-core-tools@core`

**Comment by JimiSmith** [comment] 2018-05-22 18:46
@fabiocav The initial issue is now resolved, however I'm now getting a different assembly load issue with System.Memory. 

```
System.Private.CoreLib: Exception while executing function: BlobEventGridTrigger. SixLabors.ImageSharp: 
Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 
The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file
```

**Comment by fabiocav** [comment] 2018-05-22 21:46
@JimiSmith that is a known and expected issue with this current release. Currently, we're explicitly blocking certain assemblies in the function load context and being overly aggressive. We'll relax those restrictions with the next release, but the fact that the original issue has been addressed is a good sign. 

We're planning a release with those updates soon! I'll keep this open to track.

**Comment by JimiSmith** [comment] 2018-05-23 05:03
Awesome. I'll test again then. Thanks for all the help.

**Comment by tmakin** [comment] 2018-06-10 21:08
@fabiocav Are you are able to share which assemblies are being explicitly blocked? 

I have run into the ImageSharp issue, and I have similar looking problem with `System.IO.Packaging` and I'm interested to know if the root cause is the same:
https://github.com/Azure/Azure-Functions/issues/816

**Comment by fabiocav** [comment] 2018-06-11 03:48
@tmakin this has been addressed with the update we’re rolling out. If you create a function app in West US 2, you should be able to test with those new bits (2.0.11857). CLI will be available soon.

**Comment by paulceli** [comment] 2018-07-05 16:03
Hey, I had the exact same problem as @JimiSmith with SixLabors.ImageSharp and System.Memory.
Saw your message and thus upgraded my CLI, I now have Version=2.0.11888.0.

I'm doing a FAN-OUT on the same method. About 80% of them work perfectly and the rest fails with what looks like the same issue as before.

`Method not found: '!0 System.ReadOnlySpan'1.get_Item(Int32)'`

Even if I don't get the following message anymore

`Could not load file or assembly 'System.Memory, Version=4.0.1.0'`


Any idea what could be happening ??


Thanks a lot

**Comment by fabiocav** [comment] 2018-07-17 17:37
Closing this as the original issue is resolved. 

@paulceli it looks like you're running into a version mismatch. Could you open a different issue with the repro so we can investigate? Thanks!

**Closed by fabiocav** 2018-07-17 17:37 UTC

**Comment by paulceli** [comment] 2018-07-17 17:59
It works when I deploy to azure. I guess it's a problem on the mac CLI. It seems way behind.
Thanks.
