### ISSUE TITLE
Filtering out logging in Application Insights

### ISSUE THREAD

**Issue by marshall76963** [Azure/azure-functions-host#4474] opened 2019-05-20 14:10 UTC
Hi,

I am writing a set of C# Azure functions, some timer triggered, others http triggered and am having difficulty restricting the information logged in Application insights.

A bit of background...

I have 2 timer triggers, one that runs every 5 seconds to check for specific database condition changes which, most of the time, will not have to do anything as changes are infrequent but the response to them has to be fairly prompt (hence the 5 seconds).  The other time runs every 5 minutes and does something similar but the response time is less critical.

The 2 http triggers access blob storage to manipulate images (resize/rotate/etc.) and are called by a web app also hosted on Azure.
 
All the functions are v2 and execute against .Net Core 2.2 using the latest (v1.0.28) Microsoft.NET.Sdk.Functions library.

The challenge

Because of the highly repetitive nature of the timer functions, I only want to capture in app insights user-level logging when logging is explicitly called (Info/Warn/Error) and not have the "Executing...", "Executed..." message show up.

My searching led me to stackoverflow (as it almost always does!) and to this post: https://stackoverflow.com/questions/53484337/stop-an-azure-function-from-logging-the-executing-and-executed-messages which suggests modifying the *host.json* to set logging levels specific for the different azure functions and stop other logs triggering.

I have tried many versions of this and currently have:

```json
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "Function.FastTimer.User": "Information",
      "Function.SlowTimer.User": "Information",
      "Function.ImageHttp1.User": "Information",
      "Function.ImageHttp2.User": "Information",
      "Function": "Error",
      "default": "Error"
    }
  }
}
```
This, I believe, should filter out everything except user-level logging for all 4 functions, however I am still getting every single verbose trace output in AI.

Is this an issue in my code/configuration or is there something else that is causing AI to pick up all logging output regardless of the host.json?

Thanks

Rich

**Update 2019-05-24**
It appears that the `host.json` values are being ignored/overridden when deployed to Azure but are working locally.  I have verified that the file has been deployed correctly but I can see the logging being triggered both in AI and to the Logging directory of the app service site.

**Comment by marshall76963** [comment] 2019-05-31 08:08
We have done some more investigating and have found the following:

- The `host.config` settings are working with respect to file and console logging.
- App Insights does not respect the logging settings in `host.config` and everything is displayed in the trace output.
- The behavior of the logging when executing both local and on Azure is the same.

We have worked around the issue for now by applying a startup class to explicitly filter logging to AI.  The filter does two things:

1. Filters out trace logs from the framework similar to that specified in the `host.config`
2. Filters out 404 dependency errors which are triggered when a request to `blob.CheckIfExists()` is called against Azure Blob Storage.

```C#
using Microsoft.ApplicationInsights.Channel;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.ApplicationInsights.Extensibility;
using Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System.Linq;

[assembly: WebJobsStartup(typeof(MyNamespace.AzureFunctions.Startup))]
namespace MyNamespace.AzureFunctions
{
    public class Startup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            var configDescriptor = builder.Services.SingleOrDefault(tc => tc.ServiceType == typeof(TelemetryConfiguration));
            if (configDescriptor?.ImplementationFactory != null)
            {
                var implFactory = configDescriptor.ImplementationFactory;
                builder.Services.Remove(configDescriptor);
                builder.Services.AddSingleton(provider =>
                {
                    if (implFactory.Invoke(provider) is TelemetryConfiguration config)
                    {
                        var newConfig = TelemetryConfiguration.Active;
                        newConfig.ApplicationIdProvider = config.ApplicationIdProvider;
                        newConfig.InstrumentationKey = config.InstrumentationKey;
                        newConfig.TelemetryProcessorChainBuilder.Use(next => new CustomTelemetryProcessor(next));
                        foreach (var processor in config.TelemetryProcessors)
                        {
                            newConfig.TelemetryProcessorChainBuilder.Use(next => processor);
                        }
                        var quickPulseProcessor = config.TelemetryProcessors.OfType<QuickPulseTelemetryProcessor>().FirstOrDefault();
                        if (quickPulseProcessor != null)
                        {
                            var quickPulseModule = new QuickPulseTelemetryModule();
                            quickPulseModule.RegisterTelemetryProcessor(quickPulseProcessor);
                            newConfig.TelemetryProcessorChainBuilder.Use(next => quickPulseProcessor);
                        }
                        newConfig.TelemetryProcessorChainBuilder.Build();
                        newConfig.TelemetryProcessors.OfType<ITelemetryModule>().ToList().ForEach(module => module.Initialize(newConfig));
                        return newConfig;
                    }
                    return null;
                });
                builder.Services.AddSingleton<ITelemetryInitializer, CustomTelemetryInitializer>();
            }
        }
    }


    public class CustomTelemetryInitializer : ITelemetryInitializer
    {
        public void Initialize(ITelemetry telemetry)
        {
            if (telemetry is DependencyTelemetry dependency && dependency != null && dependency.ResultCode.Equals("404"))
            {
                dependency.Success = true;
            }
        }
    }


    public class CustomTelemetryProcessor : ITelemetryProcessor
    {
        private readonly ITelemetryProcessor _next;
        public CustomTelemetryProcessor(ITelemetryProcessor next)
        {
            _next = next;
        }

        public void Process(ITelemetry item)
        {
            if (ShouldFilterTrace(item))
            {
                return;
            }
            _next.Process(item);
        }

        private bool ShouldFilterTrace(ITelemetry item)
        {
            var result = false;
            if (item is TraceTelemetry trace)
            {
                result = true;
                var category = trace.Properties["Category"];
                var logLevel = trace.Properties["LogLevel"];
                if (!string.IsNullOrWhiteSpace(category) && !string.IsNullOrWhiteSpace(logLevel))
                {
                    switch (logLevel)
                    {
                        case "Error":
                        case "Warning":
                            result = false;
                            break;
                        case "Information":
                            switch (category)
                            {
                                case "Function.FastTimer.User":
                                case "Function.SlowTimer.User":
                                case "Function.ImageHttp1.User":
                                case "Function.ImageHttp2.User":
                                    result = false;
                                    break;
                            }
                            break;
                    }
                }
            }
            return result;
        }

    }
}
```

This gives us way forward that works, but it would be great if App Insights respected and used the configuration specified in `host.config`.

**Comment by espray** [comment] 2019-06-01 12:56
@marshall76963 I have been trying to add custom ITelemetryInitializer/ITelemetryProcessor with no luck. `var configDescriptor = builder.Services.SingleOrDefault(tc => tc.ServiceType == typeof(TelemetryConfiguration));` is always null for me, any idea why? Any chance you have a sample proj I can compare with?

#4345

**Comment by espray** [comment] 2019-06-01 14:03
Resolved the issue I was having. The host references TelemetryConfiguration Version=2.9.1.0 and I was using Version=2.10.0.0

**Comment by gzuber** [comment] 2019-07-15 23:05
@marshall76963 have you tried setting the logLevel for "Host" (or anything you don't want to see) to "None" or "Error"?  Because the host sets these log levels, you would have to explicitly overwrite them.

**Comment by marshall76963** [comment] 2019-07-16 11:37
@gzuber - yes, I tried a bunch of different excludes in the `logLevel`, setting `Host`, `Default` and `Function` to Error or Warning, all of which worked on the file logging, but as far as I could tell did not affect what was sent to App Insights.

The work-around that we have applied appears stable for now, so I am not actively trying alternative options.

**Comment by gzuber** [comment] 2019-07-29 21:38
Ah I see. Unfortunately, I haven't been able to reproduce this issue so we'd have to dig deeper into your app to find a cause but I understand if you're happy with the workaround. Although this did prompt me to update some of our [documentation on logging](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#configure-categories-and-log-levels), so hopefully that will help the next person :) I'll close this for now

**Closed by gzuber** 2019-07-29 21:38 UTC
Labels: Needs: Attention :wave:
