### ISSUE TITLE
Could not load file or assembly 'System.Text.Encoding.CodePages, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-host#7061] opened 2021-01-15 07:03 UTC
#### Repro steps

Provide the steps required to reproduce the problem:

1. Create function app project
2. Install `System.Text.Encoding.CodePages` nuget package
3. Adding `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);` to function
4. Run function app

#### Expected behavior

Function app is executed without error

#### Actual behavior

The following error occurs and the function cannot be executed.

```
[2021-01-15T07:00:17.378Z] A host error has occurred during startup operation 'e356b46a-f0fb-44a1-8494-df0ad91f3d36'.
[2021-01-15T07:00:17.380Z] FunctionApp34: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 指定されたファイルが見つかりません。.
Value cannot be null. (Parameter 'provider')
```

#### Known workarounds

- Adding `_FunctionsSkipCleanOutput` setting
- Downgrade `System.Text.Encoding.CodePages` to v4.7.1

**Comment by lars-erik** [comment] 2021-01-18 16:17
I have the same problem. The publish targets remove a lot of stuff.  
The System.Text.Encoding.CodePages.dll is copied into bin/runtime/netstandard2.0.  
It seems like files under bin/runtime/** are not probed at all.  
I've tried this with both V2 and V3 runtime, including pretty much all framework targets since netstandard2.0.

I managed to get the file copied to the bin folder locally with an extra target in my .csproj, but I couldn't figure which target / filegroup / property to use in order to include the file in the .zip that is published.  
So for now I grudgingly copy the file into the function's bin folder using the kudu console.

Let me know if I can help by providing more details. Here's my targets:

```xml
  <Target Name="ForceCopyCodePages" AfterTargets="_FunctionsBuildCleanOutput">
    <Message Importance="High" Text="Copying messed up deps to $(OutputPath)" />
    <Copy SourceFiles="$(OutputPath)bin\runtimes\win\lib\netcoreapp2.0\System.Text.Encoding.CodePages.dll"
          DestinationFolder="$(OutputPath)bin"/>
  </Target>
  <Target Name="ForcePublishCodePages" AfterTargets="_FunctionsPostPublish">
    <Message Importance="High" Text="Copying messed up deps for publish to $(PublishDir)bin" />
    <Copy SourceFiles="$(OutputPath)bin\runtimes\win\lib\netcoreapp2.0\System.Text.Encoding.CodePages.dll"
          DestinationFolder="$(PublishDir)bin"/>
  </Target>
```

**Comment by v-bbalaiagar** [comment] 2021-03-02 10:00
Hi @shibayan, Apologies for the delayed response, please let us know if you were able to find a solution to this, if not, we would like to reproduce your project to understand the error better, could you give us the repro steps or test Zip file if possible which can repro the error.

**Comment by shibayan** [comment] 2021-03-06 15:54
@v-bbalaiagar The workaround is described in the first comment.
The root cause of this problem is that the Azure Functions SDK deletes any assembly with a matching name without considering the assembly version. It is necessary to delete the assembly only if it is the same or lower version than the assembly that Functions Runtime has, and not delete it if it is a larger version.

**Comment by SOFSPEEL** [comment] 2021-03-09 01:45
@shibayan, the workaround is **not** in the first comment, as per my understanding the author of those targets tried them out but it didn't work.

Note that I'm experiencing the same issue, and so far only workaround is to manually move the dll using kudo.

**Comment by shibayan** [comment] 2021-03-09 04:57
@SOFSPEEL I have confirmed that it works with the first workaround I wrote. It's not wrong.
>Known workarounds
>Adding _FunctionsSkipCleanOutput setting
>Downgrade System.Text.Encoding.CodePages to v4.7.1

**Comment by SOFSPEEL** [comment] 2021-03-09 15:54
@shibayan thanks for the feedback as I was unclear as to which workaround you were referring to. Ultimately what fixed it for me was just doing this, which seems to prevent the deletion of the runtime dlls that now deploy to the wwwroot/bin folder 
  `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
`

Wondering why the need to 'Downgrade System.Text.Encoding.CodePages to v4.7.1'?

I should add I'm targeting as follows:
  ` <TargetFramework>netcoreapp3.1</TargetFramework>
 `

Thanks

**Comment by rob4bertus** [comment] 2021-04-07 11:15
I have the same problem, except with System.IO.Pipelines, Version=5.0.0.0, while connecting to redis using the StackExchange.Redis 2.2.4 package.

Adding <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput> to the .csproj file resolves the issue of not being able to connect to Redis. BUT: it also causes the EventHubTrigger not to fire. When I remove it, the event hub trigger fires again, but connecting to redis throws the exception again.

And what I need unfortunatly is to react to an event hubtrigger and read some date from redis to decide what to do with the event.

Hope anybody can help mee, or at least that this scenario is considered while solving this issue.

Kind regards,
Rob.

ps. When I look at the verbose logging I notice that this part of the logging:
[2021-04-07T12:33:45.165Z] EventHubOptions
[2021-04-07T12:33:45.177Z] {
[2021-04-07T12:33:45.179Z]   "BatchCheckpointFrequency": 3,
[2021-04-07T12:33:45.180Z]   "EventProcessorOptions": {
[2021-04-07T12:33:45.184Z]     "EnableReceiverRuntimeMetric": false,
[2021-04-07T12:33:45.186Z]     "InvokeProcessorAfterReceiveTimeout": false,
[2021-04-07T12:33:45.191Z]     "MaxBatchSize": 400,
[2021-04-07T12:33:45.193Z]     "PrefetchCount": 512,
[2021-04-07T12:33:45.195Z]     "ReceiveTimeout": "00:01:00"
[2021-04-07T12:33:45.196Z]   },
[2021-04-07T12:33:45.200Z]   "PartitionManagerOptions": {
[2021-04-07T12:33:45.207Z]     "LeaseDuration": "00:00:30",
[2021-04-07T12:33:45.209Z]     "RenewInterval": "00:00:10"
[2021-04-07T12:33:45.210Z]   },
[2021-04-07T12:33:45.212Z]   "InitialOffsetOptions": {
[2021-04-07T12:33:45.215Z]     "Type": "",
[2021-04-07T12:33:45.221Z]     "EnqueuedTimeUTC": ""
[2021-04-07T12:33:45.225Z]   }
[2021-04-07T12:33:45.226Z] }
Is present only when skip clean output is true.

**Comment by v-bbalaiagar** [comment] 2021-04-20 15:48
Hi @shibayan, We would like to know if you can close this issue or if you are still looking for a solution

@rob4bertus ,Can you create a new issue by explaining your scenario as it looks like a different scenario and not duplicate

**Comment by aaronhudon** [comment] 2021-05-15 02:51
Why is this about to be closed?  I am seeing the issue myself running latest Functions SDK 3.0.12

**Comment by bryanknox** [comment] 2021-05-15 15:11
Please don't close this issue. A fix is needed so that the perpetual use of a workaround is not required.

@kashimiz, @v-bbalaiagar can some one investigate the root cause and develop a fix?

**Comment by v-bbalaiagar** [comment] 2021-05-17 10:58
@aaronhudon ,@bryanknox  The bot has closed the issue due to in-activity. We shall keep the issue open.

**Comment by MikeNicholls** [comment] 2021-05-19 04:55
[`FunctionsPreservedDependencies`](https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs#configure-your-build-output-settings) seems to be the documented way to deal with these issues, it can have fewer side-effects than `_FunctionsSkipCleanOutput` due to it being targeted at specific assemblies.

It requires [`Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator`](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator/) 1.2.1 or newer, version 1.2.2 is included by [`Microsoft.NET.Sdk.Functions`](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/) 3.0.12 (which was released a few days ago).

@shibayan This worked for me:
```xml
<ItemGroup>
  <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.12" />
  <PackageReference Include="System.Text.Encoding.CodePages" Version="5.0.0" />
</ItemGroup>
<ItemGroup>
  <FunctionsPreservedDependencies Include="System.Text.Encoding.CodePages.dll" />
</ItemGroup>
```

@rob4bertus For Redis we were able to successfully replace our use of `_FunctionsSkipCleanOutput` with `<FunctionsPreservedDependencies Include="System.IO.Pipelines.dll" />`, although I haven't tested with an Event Hubs trigger.

**Comment by rob4bertus** [comment] 2021-05-19 08:34
Thanks for the update. Currently (with some help :)) we have got it running with _FunctionsSkipCleanOutput. (We had to downgrade some dependencies to do that, but that's ok for us). When I have some time I will test this new option. 

Maybe version conflicts between dll's is one of the side effects you speak about?

**Closed as completed** 2021-05-26 13:00 UTC
Labels: Needs: Author Feedback, no-recent-activity
