### ISSUE TITLE
Azure Function with Event Hub binding - getting more events than set maxBatchSize 

### ISSUE THREAD

**Issue by bchrisb** [Azure/azure-functions-host#1649] opened 2017-06-30 14:56 UTC
I have a function with an Event Hub input binding. 
I have "event hub cardinality" set to "many" in the integrate window.
I have the following in my function host.json file:
`{
    "eventHub": {
      "maxBatchSize": 64,
      "prefetchCount": 256
    }
}`
I have my method declaration as:
`public static async Task Run(TraceWriter log, string[] eventHubMessages)`

When testing, I am sending tens of thousands of events to the event hub and I expect the function to receive a maximum of 64 events for one invocation. I am logging out eventHubMessages.Length to the TraceWriter and in most cases I see that the Length is 300.

I have tried altering the maxBatchSize to other values and I still see the Length at 300.

#### Investigative information

Please provide the following:

- Timestamp: 2017-06-30T14:42:05.091
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: aab1ef15-3423-481d-95cb-b6c2cd081a03
- Region: North Europe

**Comment by SnoyIatK** [comment] 2017-10-14 09:32
I'm facing the same issue, any updates on this ?

**Comment by paulbatum** [comment] 2017-10-16 18:31
Hi, its still in my work queue, its just taking a while to get to. I plan on having a fix done and released sometime in November.

**Comment by SnoyIatK** [comment] 2017-10-17 02:59
@paulbatum Thank you.
Before it get released, is there any workaround I can use to limit number of batchSize to less than 300, say ~30 or 60?
At the moment I must use batch trigger to improve performance for my application, but handling 300 events will cause timeout exception because it can't finish within 10mins (hard limit of azure functions).

**Comment by durgakhumbu** [comment] 2017-12-04 04:14
I am having same issue. Is the any workaround for this?

**Comment by patrickdet** [comment] 2018-05-08 09:30
same issue. any update on this?

**Comment by paulbatum** [comment] 2018-05-18 21:17
So I lost track of this issue, my apologies. However I did work on several similar event hubs issues over the past months and I'm not able to reproduce this issue with the current bits. 

@patrickdet I know you commented on this and some related issues.. do you have a current repro of the issue discussed here?

**Comment by paulbatum** [comment] 2018-05-24 18:41
OK I am closing this as I cannot repro and I think it was fixed as part of other bug fixes. Please comment if you are setting max batch size and are still getting more messages in an invocation than what you set.

**Closed by paulbatum** 2018-05-24 18:41 UTC
Labels: needs-investigation
