### ISSUE TITLE
"Server failed to authenticate the request" Trouble getting Azure Functions to work with Managed Identity and Key Vault

### ISSUE THREAD

**Issue by ahawes-clarity** [Azure/azure-functions-host#8412] opened 2022-05-23 21:51 UTC
I have a Functions App that I am migrating from v2 to v4. During the migration I wanted to change from secrets in App Settings to use Key Vault and Managed Identity.

I have followed the guidance that I found in these links as well as others:

- https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#connecting-to-host-storage-with-an-identity-preview
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial

However, the documentation is a bit confusing to me and while I think I set everything up as needed I am getting the following error.

```
2022-05-23T20:59:08.377 [Information] Request [846e8f6d-a332-4ff6-ba71-70127eab69d6] GET https://********.queue.core.windows.net/anova-controller-reading-to-process?comp=metadatax-ms-version:2018-11-09Accept:application/xmlx-ms-client-request-id:846e8f6d-a332-4ff6-ba71-70127eab69d6x-ms-return-client-request-id:trueUser-Agent:azsdk-net-Storage.Queues/12.10.0,(.NET 6.0.3; Microsoft Windows 10.0.14393)x-ms-date:Mon, 23 May 2022 20:59:08 GMTAuthorization:REDACTEDclient assembly: Azure.Storage.Queues
2022-05-23T20:59:08.862 [Warning] Error response [c523f72e-f6f2-48f3-b1da-9d3dfb48c575] 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. (01.0s)Server:Microsoft-HTTPAPI/2.0x-ms-request-id:8bcff400-8003-0046-28e7-6e5e1b000000x-ms-error-code:AuthenticationFailedDate:Mon, 23 May 2022 20:59:08 GMTContent-Length:787Content-Type:application/xml
2022-05-23T20:59:08.950 [Error] An unhandled exception has occurred. Host is shutting down.Azure.RequestFailedException : Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:8bcff400-8003-0046-28e7-6e5e1b000000Time:2022-05-23T20:59:08.8402781ZStatus: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)ErrorCode: AuthenticationFailedAdditional Information:AuthenticationErrorDetail: The MAC signature found in the HTTP request '4wyyc82uJ/Of1+kDsXMyakzuQ/ABrEDJwrODUVe+B1g=' is not the same as any computed signature. Server used following string to sign: 'GETx-ms-client-request-id:c523f72e-f6f2-48f3-b1da-9d3dfb48c575x-ms-date:Mon, 23 May 2022 20:59:07 GMTx-ms-return-client-request-id:truex-ms-version:2018-11-09/********/aquasolconnect-faults-to-processcomp:metadata'.Content:<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:8bcff400-8003-0046-28e7-6e5e1b000000Time:2022-05-23T20:59:08.8402781Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '4wyyc82uJ/Of1+kDsXMyakzuQ/ABrEDJwrODUVe+B1g=' is not the same as any computed signature. Server used following string to sign: 'GETx-ms-client-request-id:c523f72e-f6f2-48f3-b1da-9d3dfb48c575x-ms-date:Mon, 23 May 2022 20:59:07 GMTx-ms-return-client-request-id:truex-ms-version:2018-11-09/********/aquasolconnect-faults-to-processcomp:metadata'.</AuthenticationErrorDetail></Error>Headers:Server: Microsoft-HTTPAPI/2.0x-ms-request-id: 8bcff400-8003-0046-28e7-6e5e1b000000x-ms-error-code: AuthenticationFailedDate: Mon, 23 May 2022 20:59:08 GMTContent-Length: 787Content-Type: application/xmlat async Azure.Storage.Queues.QueueRestClient.GetPropertiesAsync(Nullable`1 timeout,CancellationToken cancellationToken)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Azure.Storage.Queues.QueueClient.GetPropertiesInternal(Boolean async,CancellationToken cancellationToken,String operationName)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Azure.Storage.Queues.QueueClient.ExistsInternal(Boolean async,CancellationToken cancellationToken)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Azure.Storage.Queues.QueueClient.ExistsAsync(CancellationToken cancellationToken)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Microsoft.Azure.WebJobs.Extensions.Storage.Common.Listeners.QueueListener.ExecuteAsync(CancellationToken cancellationToken)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Microsoft.Azure.WebJobs.Extensions.Storage.Common.Timers.TaskSeriesTimer.RunAsync(CancellationToken cancellationToken)

2022-05-23T21:17:59.416 [Information] Request [ad81b3c8-8e39-43be-b154-9f8f65986ea0] GET https://********.queue.core.windows.net/durable-functions-cleanup?comp=metadatax-ms-version:2018-11-09Accept:application/xmlx-ms-client-request-id:ad81b3c8-8e39-43be-b154-9f8f65986ea0x-ms-return-client-request-id:trueUser-Agent:azsdk-net-Storage.Queues/12.10.0,(.NET 6.0.3; Microsoft Windows 10.0.14393)Authorization:REDACTEDclient assembly: Azure.Storage.Queues
2022-05-23T21:18:00.760 [Warning] Error response [5ee6a228-094f-4658-adf5-119c0083f531] 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. (01.6s)Server:Microsoft-HTTPAPI/2.0x-ms-request-id:fcd53a08-7003-0020-12ea-6e113b000000x-ms-error-code:AuthenticationFailedDate:Mon, 23 May 2022 21:17:59 GMTContent-Length:790Content-Type:application/xml
2022-05-23T21:18:00.863 [Error] An unhandled exception has occurred. Host is shutting down.Azure.RequestFailedException : Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:fcd53a08-7003-0020-12ea-6e113b000000Time:2022-05-23T21:18:00.3561769ZStatus: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)ErrorCode: AuthenticationFailedAdditional Information:AuthenticationErrorDetail: The MAC signature found in the HTTP request '6c3hdJnIBhGSciUyDLkL4vmPFQjsnBkGtWgAV2CL9Lg=' is not the same as any computed signature. Server used following string to sign: 'GETx-ms-client-request-id:5ee6a228-094f-4658-adf5-119c0083f531x-ms-date:Mon, 23 May 2022 21:17:59 GMTx-ms-return-client-request-id:truex-ms-version:2018-11-09/********/anova-controller-reading-to-processcomp:metadata'.Content:<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:fcd53a08-7003-0020-12ea-6e113b000000Time:2022-05-23T21:18:00.3561769Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '6c3hdJnIBhGSciUyDLkL4vmPFQjsnBkGtWgAV2CL9Lg=' is not the same as any computed signature. Server used following string to sign: 'GETx-ms-client-request-id:5ee6a228-094f-4658-adf5-119c0083f531x-ms-date:Mon, 23 May 2022 21:17:59 GMTx-ms-return-client-request-id:truex-ms-version:2018-11-09/********/anova-controller-reading-to-processcomp:metadata'.</AuthenticationErrorDetail></Error>Headers:Server: Microsoft-HTTPAPI/2.0x-ms-request-id: fcd53a08-7003-0020-12ea-6e113b000000x-ms-error-code: AuthenticationFailedDate: Mon, 23 May 2022 21:17:59 GMTContent-Length: 790Content-Type: application/xmlat async Azure.Storage.Queues.QueueRestClient.GetPropertiesAsync(Nullable`1 timeout,CancellationToken cancellationToken)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Azure.Storage.Queues.QueueClient.GetPropertiesInternal(Boolean async,CancellationToken cancellationToken,String operationName)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Azure.Storage.Queues.QueueClient.ExistsInternal(Boolean async,CancellationToken cancellationToken)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Azure.Storage.Queues.QueueClient.ExistsAsync(CancellationToken cancellationToken)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Microsoft.Azure.WebJobs.Extensions.Storage.Common.Listeners.QueueListener.ExecuteAsync(CancellationToken cancellationToken)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Microsoft.Azure.WebJobs.Extensions.Storage.Common.Timers.TaskSeriesTimer.RunAsync(CancellationToken cancellationToken)x-ms-error-code:AuthenticationFailedDate:Mon, 23 May 2022 21:17:59 GMTContent-Length:790Content-Type:application/xml
```

I am confident that the issue is with configuration but like I said the docs are confusing.

Is having the AppSetting "AzureWebJobsStorage__accountName" sufficient or do you also need to have "AzureWebJobsStorage__blobServiceUri", "AzureWebJobsStorage__queueServiceUri", and "AzureWebJobsStorage__tableServiceUri"? I read the docs saying "If you are configuring "AzureWebJobsStorage" using a storage account that uses the default DNS suffix and service name for global Azure, following the https://<accountName>.blob/queue/file/table.core.windows.net format, you can instead set AzureWebJobsStorage__accountName to the name of your storage account. The endpoints for each storage service will be inferred for this account." to mean that I should be able to just set "AzureWebJobsStorage__accountName".

If I am using "AzureWebJobsStorage__accountName" do I still need to set "AzureWebJobsStorage" to support anything that can't use Managed Identity? I tried to add it but the Function App would not even start so I figured you had to use one or the other.

The identity I have has all the following roles Storage Blob Data Contributor, Storage Queue Data Contributor, Storage Table Data Contributor.

**Comment by ahawes-clarity** [comment] 2022-05-25 21:26
Still struggling with this. Can anyone help? Not sure how to get past this issue.

**Comment by Ved2806** [comment] 2022-05-31 10:50
Hi @mattchenderson Could you please look into this issue?

**Comment by ahawes-clarity** [comment] 2022-06-06 19:20
Still struggling with this. Can anyone help? Not sure how to get past this issue.

**Comment by ahawes-clarity** [comment] 2022-06-13 19:09
I guess no help is available. I will go back to putting my secrets directly into the Azure Functions settings.

**Comment by ahawes-clarity** [comment] 2022-06-13 21:35
Sadly, even when I put the Azure Storage settings directly into the Azure Functions Settings I am still getting the same error. I am at a loss. Not sure how to move forward.

**Comment by Ved2806** [comment] 2022-06-16 10:33
Hi @ahawes-clarity We are discussing this issue internally, we will get back to you soon with the findings!

**Comment by mattchenderson** [comment] 2022-06-17 18:05
Hi - apologies for missing the ping.

Are these errors you're hitting in local debugging or in a hosted service? Do you see the same error across both?

You're correct that it's not advisable to mix `AzureWebJobsStorage` and `AzureWebJobsStorage__accountName`. In these cases, the `AzureWebJobsStorage` key would win. The app not starting was a bit surprising to me there - that wouldn't be expected unless the connection string in that scenario was somehow invalid. If you have any specifics of that error, that might be interesting.

Because this error set is a MAC exception, it looks like the server is attempting to process this as a shared key request. I'm basing that on the error showing up in tests in the Azure SDK for .NET ([example](https://github.com/Azure/azure-sdk-for-net/blob/6a395c10a9a3126661bed9958a864f3c4487d39c/sdk/storage/Azure.Storage.Common/tests/SessionRecords/StorageSharedKeyCredentialsTests/RollCredentialsToChildrenAsync.json#L184)). CC @jaschrep-msft in case there are other scenarios where this might occur.

So, it looks like identity isn't even attempted. I assume the app does indeed have the identity assigned, and that it is able to request tokens directly. Is that correct? The roles you have assigned to the identity look like they should be fine for Durable, which it seems like you're using. Could you confirm the version of the Durable extension that you are using? Support for MI from that was only added recently. And are there other scenarios here where you would be leveraging an identity-based connection?

I think to help with this, we might need to get a bit more information out of logs. If you could please share some details we can correlate with per https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately, we can take a look. Feel free to open a support ticket if you haven't already as well, though I'm hoping we should be able to identify the cause here pretty quickly.

For your own logs, you can get more verbose information out of the underlying Azure SDKs by [changing log levels](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#log-levels-and-categories) (just be advised that these get noisy fast and should probably not be used in a production environment). This can sometimes be helpful for understanding configurations. I can't remember which level specifically ends up being needed. I think Debug works, but I recall needing Trace for my own apps in the past.

**Comment by ahawes-clarity** [comment] 2022-06-17 20:48
Thank you for your help.

I only see the error when it is hosted.
Yes, identity is assign in the function app.
![image](https://user-images.githubusercontent.com/6013584/174399111-ef488bd3-b9b0-4945-8d79-95164eb4d5ea.png)

Yes, I am using Durable Functions version 2.7.1
![image](https://user-images.githubusercontent.com/6013584/174399129-bde5c3d6-697a-4c3f-b11a-ecb6c00cff71.png)

I am new to Managed Identity with Azure Functions. As I understand if I setup my setting correctly it would be used anytime the Function App needs to access Storage Account resources. I do have different connections to multiple Azure Storage accounts by they are managed fully by my code outside of the connection Azure Functions provides to the main storage account.

Yes, please look into the logs. As noted the app does not fully start so I hope this line will be enough to find the function. If not, maybe I can share the app name another way.

2022-06-17T20:01:44.648 [Information] Request [4793511a-32a1-4b67-aedd-c7ea569225e9] in South Central US

I changed the logging to Debug and it didn’t add much. I tried changing to Trace and still didn’t see much difference in the Log Stream. I can’t get any of the usual startup logging to show like what functions are starting and things like that. I set the debug level in the host.json back to Information.

**Comment by mattchenderson** [comment] 2022-06-18 01:09
Interestingly, I don't see requests for managed identity tokens coming from your app after 5/25, though I do see it is configured to have the identity. That does align with what I was thinking given that the error seems to be attempting to do a non-shared key, but only since then. More on the original errors a bit later.

## Current error

The current error is happening at startup, and I see it as connected to the WebJobs secret storage repository, which is by default in the blob account for AzureWebJobsStorage under the azure-webjobs-secrets container. This reminded me that for Identity, your setup may be a permissions issue (though it would not explain the error you're seeing), in that I think you need Storage Blob Data Owner, not just Storage Blob Data Contributor. Both provide the permission to write, which probably should be sufficient, but the Storage Blob Data Owner is what we document for AzureWebJobsStorage in general, and there may be another operation occurring first (stack trace shows it's attempting to create the container). I do see a docs issue here where Durable in the context of AzureWebJobsStorage does not report needing Owner, so I'll make a note to get that fixed.

The only other thing I noticed is that right now, the system is expecting a well-formed connection string in the `AzureWebJobsStorage` application setting. That's the only thing I see for this connection - I don't see `AzureWebJobsStorage__accountName` existing. Perhaps you changed back to the connection string since it wasn't working? The error you sent from today then would probably have to be an issue with that connection string itself, then. It might be worth double-checking that the value is as expected from the storage account itself.

## Original errors

In your original report, the errors are actually connected to a queue, it seems, not the blob service. I believe this blob check is supposed to occur first, and if those were using the same connection, I'd expect to see the blob issue only, as that does take out the host. At the point of first incident, the blob is resolved correctly, but then errors occur in the context of Durable, as it tries to get things going for the queues. The app requested and received tokens from the token service (and it made multiple requests, which it didn't need to - a small optimization we can make). But after that, we get these HMAC signing issues that are for shared keys. Doc describing what Storage expects: https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key

## Summary

I'll ask around and discuss more with the team. It seems like it's relying on shared logic in our extensions and resolving down to the Azure SDK. On the Azure SDK for .NET repo, I see a few issues regarding whitespace and HMAC calculation. I do see whitespace coming back in the server's response for what it expects, so this could be related. Regardless, we'll get some folks to look into it.

Some additional actions I'm taking beyond that:
- Doc issue on permission requirement in the context of Durable+AzureWebJobsStorage
- Exploring possible reduction of token requests made during Durable startup.

**Comment by ahawes-clarity** [comment] 2022-06-20 15:02
Yes, I was trying different configuration settings to see if I could work around the issue while waiting for help. Yes, I had AzureWebJobsStorage__accountName and later changed it to putting the connection string in the AzureWebJobsStorage. I can set it back to AzureWebJobsStorage__accountName if that is the best course for troubleshooting.

I did/do have the Storage Blob Owner role permission assigned.
![image](https://user-images.githubusercontent.com/6013584/174626643-228eaa77-a1d7-4c60-bb98-5e2356005ecb.png)

I am confused by the HMAC signing issues and what if anything needs to be done on my end to account for the Shared Keys. As I understand everything that I have read, there should not be any code changes required to implement Managed Identity authentication/authorization with Azure Functions and Azure Storage. This is simply a change in configuration. When you said "But after that, we get these HMAC signing issues that are for shared keys. Doc describing what Storage expects: https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key" I referred to those docs and they seem to discuss how to implement shared key detail. But aren't those details handled by Azure Functions or the Azure Storage SDK/Libraries? If Managed Identity is going to be a hassle I would be fine with just using Key Vault, but at this point even that does not seem to be working.

Is there something that I can do to help resolve this issue?

Thank you very much for your help.

**Comment by mattchenderson** [comment] 2022-06-22 16:47
Apologies - yes, my assertion is that this looks like some bug that is happening lower in the stack outside of your control. It very well could be an issue with the preview support for idenitity-based in Durable (or even just the intersection with the preview for AzureWebJobsStorage). I left that doc primarily as a breadcrumb trail for ongoing investigation, and I did not mean to imply any action needed on your part there.

**Comment by ahawes-clarity** [comment] 2022-06-22 16:53
Thank you. I am anxious to get past this issue. I know there is time but I had hoped to get this resolved well before the December 3rd deadline to upgrade to Azure Functions 4 due to the retirement of .NET Core 3.1. Let me know how I can help.

**Comment by mattchenderson** [comment] 2022-06-24 18:11
The Storage team confirmed that the HMAC error is because the Storage SDK is being handed a key. This is evidenced by the computed signature value that Storage presents there. So, the theory is that somewhere in the system, a bad shared key value is being set, either because it was rotated out or tampered somehow.

Durable is not returning these errors after all. It has an equivalent, but the stack traces go through different assemblies. It looks like you have queue-triggered functions that use a separate connection (not AzureWebJobsStorage), which currently is a connection string. These are presenting the bulk of the errors.

This isn't fully explanatory yet, and we're still investigating. While the durable and queue behaviors can be reproduced by intentionally mangling a key in the connection string, I don't think the blob access for the secrets repository has manifested in the way we're seeing here. That said, I wanted to provide some steps you could try to rebuild from a stable starting state, and if an error comes up in the process, we can identify where that is.

I think the correct thing to do is to:
1. For each storage connection, start with a connection string and verify that it is a correct value for the storage account. In that state, there should be no errors. And you would still be able to have everything on the latest versions (runtime V4, latest extensions).
2. Then, for moving to identity, I would start with GA-only identity support, so you'd just change the queue connections only, meaning AzureWebJobsStorage remains a connection string. If the queues are using the connection named `queueConnection` (chosen for example - you can swap your actual value in), I expect you to have an app setting with that name whose value is the connection string, and that whole setting should be replaced with a trio of settings (since you're using a user-assigned identity):
    - One named `queueConnection__queueServiceUri` whose value is a URI of the form "https://<storage_account_name>.queue.core.windows.net". ([doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-trigger#identity-based-connections))
    - One named `queueConnection__credential` whose value is "managedidentity". ([doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#common-properties-for-identity-based-connections))
    - One named `queueConnection__clientId` whose value is the client ID that user-assigned identity. ([doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#common-properties-for-identity-based-connections))
  And again, replace the "queueConnection" part with whatever is the name of the connection that you have configured.
3. If you wanted to keep going, using the preview support, you could then move `AzureWebJobsStorage` over. I would recommend, just for issue isolation, that you [move Durable to a different connection](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-storage-providers#configuring-the-azure-storage-provider) beforehand, still with a connection string. If you do that, I think it's probably fine to replace `AzureWebJobsStorage` with `AzureWebJobsStorage__accountName`, `AzureWebJobsStorage__credential`, and `AzureWebJobsStorage__clientId`. However, if Durable is going to use the AzureWebJobsStorage connection, then I would suggest breaking the value up into the `AzureWebJobsStorage__blobServiceUri`, `AzureWebJobsStorage__queueServiceUri`, `AzureWebJobsStorage__tableServiceUri`, `AzureWebJobsStorage__credential`, and `AzureWebJobsStorage__clientId`. In both cases, again because this is a user-assigned identity, you need those two extra settings for credential and client ID, similar to the queueTrigger setup.
4. Whatever connection Durable has should start with that split form (5 settings total for that connection). You could experiment with the `__accountName` form if that connection is AzureWebJobsStorage, but I'd start with the more explicit configuration.

**Comment by ahawes-clarity** [comment] 2022-06-24 18:56
@mattchenderson  I will work on your suggestions on Monday. Thanks

**Comment by ahawes-clarity** [comment] 2022-06-27 16:15
@mattchenderson, I really appreciate all your help.

At first I put in the storage connection strings manually and I was still getting the MAC error.

I then double checked the connection strings and they were different. It turns out that unbeknownst to me the keys had changed to the storage connections (which is odd because the same connections are working in the current v3 production application). Once updated I stopped receiving that error.

After reading your instructions what it would take to get Managed Identity working and the preview nature of some of the current implementations I think I am going to hold off on trying to move this project to use Managed Identity. It just doesn't seem to be to the point where I feel comfortable switching. I will just move to using Key Vault for this iteration and kick the Managed Identity feature support down the road. Hopefully by then maybe configuration and support will be more straight forward and complete.

Thanks again.

**Comment by mattchenderson** [comment] 2022-06-27 17:24
Sounds good - thanks for the follow-up and the feedback!

**Closed as completed by mattchenderson** 2022-06-27 17:24 UTC
